project:
  type: book
  output-dir: docs/book

book:
  title: "Foundations of Data Science"
  reader-mode: true
  author: "Taylor Arnold"

  sidebar:
    search: true
    collapse-level: 1

  page-footer:
    left: |
      Taylor Arnold
    right: |
      A <a href="https://distantviewing.org/">Distant Viewing Lab</a> project

  cover-image: img/owl_explore.png
  favicon: img/owl_explore.png

  chapters:
    - index.qmd

    - part: "Part I: Core"
      chapters:
      - 01_intro.qmd
      - 02_organize.qmd
      - 03_types.qmd
      - 04_graphics.qmd
      - 05_group.qmd
      - 06_window.qmd
      - 07_graphics_ii.qmd
      - 08_combine.qmd
      - 09_restructure.qmd
      - 10_collect.qmd

    - part: "Part II: Applications"
      chapters:
      - 11_spatial_data.qmd
      - 12_apis.qmd
      - 13_temporal_data.qmd
      - 14_text_annotations.qmd
      - 15_text_vectors.qmd
      - 16_network_data.qmd
      - 17_image_data.qmd

bibliography: refs.bib
csl: journal-of-combinatorics.csl

format:
  html:
    theme:
      - cosmo
      - custom.scss

    link-external-newwindow: true

    author-meta: "Taylor Arnold"
    callout-appearance: simple
    lightbox: true
