<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Notebook14 – Foundations of Data Science: Notebooks</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-77a666a5542a07a54dbe0a7f6e3b86cd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-sidebar docked fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./notebook14.html">Notebook14</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Foundations of Data Science: Notebooks</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook01</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook02</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook03</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook04</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook05</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook06</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook07</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook08</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook09</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook10</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook11</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook12</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook13</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook14.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Notebook14</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook15</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook17</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook18</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook19</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook20.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook20</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Notebook14</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="setup" class="level3">
<h3 class="anchored" data-anchor-id="setup">Setup</h3>
<p>Run all of the following before starting the notebook.</p>
<div id="b812107b" class="cell" data-tags="[&quot;noclear&quot;]" data-execution_count="1">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span> wget <span class="op">-</span>q <span class="op">-</span>nc https:<span class="op">//</span>raw.githubusercontent.com<span class="op">/</span>taylor<span class="op">-</span>arnold<span class="op">/</span>fds2<span class="op">/</span>refs<span class="op">/</span>heads<span class="op">/</span>main<span class="op">/</span>funs.py</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="0367b58c" class="cell" data-tags="[&quot;noclear&quot;]" data-execution_count="2">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotnine <span class="im">import</span> ggplot, aes</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> polars <span class="im">import</span> col <span class="im">as</span> c</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> funs</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>ub <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/taylor-arnold/fds2/refs/heads/main/"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="5aa61fdd" class="cell" data-tags="[&quot;noclear&quot;]" data-execution_count="4">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>play <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/shakespeare_plays.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>char <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/shakespeare_characters.csv"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>line <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/shakespeare_lines.csv.gz"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>word <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/shakespeare_words.csv.gz"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="questions" class="level3">
<h3 class="anchored" data-anchor-id="questions">Questions</h3>
<p>Four tables this week, from the Folger Shakespeare Library’s editions of the plays. They are not four datasets. They are one corpus, recorded four times over at four levels of detail: the plays, the characters in them, the lines those characters speak, and the words in those lines. Nothing else changes between the tables.</p>
<p>That makes this the right corpus for the only question this chapter asks: what is a row? Every table has an answer, and getting it wrong does not raise an error. It gives you a number that looks fine.</p>
<p>There is no new Polars method in this notebook. Everything below is <code>filter</code>, <code>sort</code>, <code>group_by</code>, <code>agg</code>, <code>n_unique</code>, and <code>pl.len()</code>, which you already have. What is new is what you point them at.</p>
<p>Unless a question says otherwise, just print the result of each block; do not save it to a variable.</p>
<ol type="1">
<li>Look at all four tables and write down, in words, what a single row of each one is.</li>
</ol>
<div id="cd87afea" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(play.shape, char.shape, line.shape, word.shape)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>play.head(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(37, 4) (1126, 4) (80592, 8) (599864, 8)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (3, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">play_id</th>
<th data-quarto-table-cell-role="th">title</th>
<th data-quarto-table-cell-role="th">author</th>
<th data-quarto-table-cell-role="th">short_title</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>str</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"mnd"</td>
<td>"A Midsummer Night’s Dream"</td>
<td>"William Shakespeare"</td>
<td>"MND"</td>
</tr>
<tr class="even">
<td>"aww"</td>
<td>"All’s Well That Ends Well"</td>
<td>"William Shakespeare"</td>
<td>"AWW"</td>
</tr>
<tr class="odd">
<td>"ant"</td>
<td>"Antony and Cleopatra"</td>
<td>"William Shakespeare"</td>
<td>"Ant"</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="ab2c08f7" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>char.head(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="5">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (3, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">character_id</th>
<th data-quarto-table-cell-role="th">play_id</th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">role_description</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>str</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Hermia_MND"</td>
<td>"mnd"</td>
<td>"Hermia"</td>
<td>null</td>
</tr>
<tr class="even">
<td>"Lysander_MND"</td>
<td>"mnd"</td>
<td>"Lysander"</td>
<td>null</td>
</tr>
<tr class="odd">
<td>"Helena_MND"</td>
<td>"mnd"</td>
<td>"Helena"</td>
<td>null</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="531f0bb6" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>line.head(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="6">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (3, 8)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">line_id</th>
<th data-quarto-table-cell-role="th">play_id</th>
<th data-quarto-table-cell-role="th">character_id</th>
<th data-quarto-table-cell-role="th">act</th>
<th data-quarto-table-cell-role="th">scene</th>
<th data-quarto-table-cell-role="th">line_number</th>
<th data-quarto-table-cell-role="th">line_type</th>
<th data-quarto-table-cell-role="th">text</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>str</td>
<td>i64</td>
<td>i64</td>
<td>str</td>
<td>str</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"mnd_line_000001"</td>
<td>"mnd"</td>
<td>"Theseus_MND"</td>
<td>1</td>
<td>1</td>
<td>"1.1.1"</td>
<td>"verse"</td>
<td>"Now, fair Hippolyta, our nupti…</td>
</tr>
<tr class="even">
<td>"mnd_line_000002"</td>
<td>"mnd"</td>
<td>"Theseus_MND"</td>
<td>1</td>
<td>1</td>
<td>"1.1.2"</td>
<td>"verse"</td>
<td>"Draws on apace. Four happy day…</td>
</tr>
<tr class="odd">
<td>"mnd_line_000003"</td>
<td>"mnd"</td>
<td>"Theseus_MND"</td>
<td>1</td>
<td>1</td>
<td>"1.1.3"</td>
<td>"verse"</td>
<td>"Another moon. But, O, methinks…</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="e95d6991" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>word.head(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="7">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (3, 8)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">word_id</th>
<th data-quarto-table-cell-role="th">play_id</th>
<th data-quarto-table-cell-role="th">character_id</th>
<th data-quarto-table-cell-role="th">line_id</th>
<th data-quarto-table-cell-role="th">word</th>
<th data-quarto-table-cell-role="th">lemma</th>
<th data-quarto-table-cell-role="th">pos</th>
<th data-quarto-table-cell-role="th">location</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>str</td>
<td>str</td>
<td>str</td>
<td>str</td>
<td>str</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"mnd_word_00000001"</td>
<td>"mnd"</td>
<td>"Theseus_MND"</td>
<td>"mnd_line_000001"</td>
<td>"Now"</td>
<td>"now"</td>
<td>"av"</td>
<td>"1.1.1"</td>
</tr>
<tr class="even">
<td>"mnd_word_00000002"</td>
<td>"mnd"</td>
<td>"Theseus_MND"</td>
<td>"mnd_line_000001"</td>
<td>"fair"</td>
<td>"fair"</td>
<td>"j"</td>
<td>"1.1.1"</td>
</tr>
<tr class="odd">
<td>"mnd_word_00000003"</td>
<td>"mnd"</td>
<td>"Theseus_MND"</td>
<td>"mnd_line_000001"</td>
<td>"Hippolyta"</td>
<td>"Hippolyta"</td>
<td>"n1-nn"</td>
<td>"1.1.1"</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Answer</strong>: A row of <code>play</code> is a play (37 of them). A row of <code>line</code> is one line as it is printed on the page (80,592). A row of <code>word</code> is one word (599,864). A row of <code>char</code> is a character, or so it looks: 1,126 of them, each with an id, a play, and a name.</p>
<p>Hold on to that last one. It is wrong, and question 3 is where it breaks.</p>
<p>The chapter calls this the <em>unit of observation</em>: the “who” or “what” that each row stands for. Notice that the four units here are nested, each one a finer grain of the one above, and that the corpus keeps them in four separate tables rather than one enormous table with a column for everything. That is the third tidy rule in practice. One table, one unit.</p>
<ol start="2" type="1">
<li>A primary key is the column, or set of columns, that uniquely identifies the unit of observation. So a claim about the unit is a claim you can test: count the distinct values of the id and compare it to the number of rows. Do that for each table.</li>
</ol>
<div id="679ffb7d" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(play.select(rows <span class="op">=</span> pl.<span class="bu">len</span>(), ids <span class="op">=</span> c.play_id.n_unique()))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(char.select(rows <span class="op">=</span> pl.<span class="bu">len</span>(), ids <span class="op">=</span> c.character_id.n_unique()))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(line.select(rows <span class="op">=</span> pl.<span class="bu">len</span>(), ids <span class="op">=</span> c.line_id.n_unique()))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(word.select(rows <span class="op">=</span> pl.<span class="bu">len</span>(), ids <span class="op">=</span> c.word_id.n_unique()))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>shape: (1, 2)
┌──────┬─────┐
│ rows ┆ ids │
│ ---  ┆ --- │
│ u32  ┆ u32 │
╞══════╪═════╡
│ 37   ┆ 37  │
└──────┴─────┘
shape: (1, 2)
┌──────┬──────┐
│ rows ┆ ids  │
│ ---  ┆ ---  │
│ u32  ┆ u32  │
╞══════╪══════╡
│ 1126 ┆ 1066 │
└──────┴──────┘
shape: (1, 2)
┌───────┬───────┐
│ rows  ┆ ids   │
│ ---   ┆ ---   │
│ u32   ┆ u32   │
╞═══════╪═══════╡
│ 80592 ┆ 80592 │
└───────┴───────┘
shape: (1, 2)
┌────────┬────────┐
│ rows   ┆ ids    │
│ ---    ┆ ---    │
│ u32    ┆ u32    │
╞════════╪════════╡
│ 599864 ┆ 599864 │
└────────┴────────┘</code></pre>
</div>
</div>
<p><strong>Answer</strong>: Three of the four pass. <code>play_id</code>, <code>line_id</code>, and <code>word_id</code> each have exactly as many distinct values as their table has rows, so each one identifies a row and the unit of observation is what we said it was.</p>
<p><code>character_id</code> does not. There are 1,126 rows and only 1,066 distinct ids, so some ids are being used by more than one row. That makes <code>character_id</code> not a key, which means a row of this table is not a character. It is something else, and we do not know what yet.</p>
<ol start="3" type="1">
<li>Find the ids that repeat, then go look at the rows behind the worst offender.</li>
</ol>
<div id="0d62378c" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    char</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    .agg(n <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.n <span class="op">&gt;</span> <span class="dv">1</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    .sort(c.n, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">5</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="9">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (5, 2)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">character_id</th>
<th data-quarto-table-cell-role="th">n</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Bedford_H5"</td>
<td>4</td>
</tr>
<tr class="even">
<td>"MistressQuickly_1H4"</td>
<td>4</td>
</tr>
<tr class="odd">
<td>"Bardolph_1H4"</td>
<td>4</td>
</tr>
<tr class="even">
<td>"QueenMargaret_1H6"</td>
<td>4</td>
</tr>
<tr class="odd">
<td>"Gloucester_2H4"</td>
<td>4</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="031facdc" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    char</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.character_id <span class="op">==</span> <span class="st">"Bardolph_1H4"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="10">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (4, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">character_id</th>
<th data-quarto-table-cell-role="th">play_id</th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">role_description</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>str</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Bardolph_1H4"</td>
<td>"1h4"</td>
<td>"Bardolph"</td>
<td>null</td>
</tr>
<tr class="even">
<td>"Bardolph_1H4"</td>
<td>"2h4"</td>
<td>"Bardolph"</td>
<td>null</td>
</tr>
<tr class="odd">
<td>"Bardolph_1H4"</td>
<td>"h5"</td>
<td>"Bardolph"</td>
<td>null</td>
</tr>
<tr class="even">
<td>"Bardolph_1H4"</td>
<td>"wiv"</td>
<td>"Bardolph"</td>
<td>null</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Answer</strong>: Four rows, one id, four different plays. Bardolph drinks his way through <em>Henry IV Part 1</em>, <em>Part 2</em>, <em>Henry V</em>, and <em>The Merry Wives of Windsor</em>, and the Folger gives him one id in all four.</p>
<p>So the unit of observation of <code>char</code> is not a character. It is a <em>character × play</em>: one row for each appearance of a character in a play. Thirty-nine characters cross plays this way and account for the sixty extra rows. Thirty-six of them are in the English histories, where the same nobles fight the same wars across eight plays. The other three are Antony, Octavius, and Lepidus, who carve up the Roman world at the end of <em>Julius Caesar</em> and are still arguing about it in <em>Antony and Cleopatra</em>.</p>
<p>Look closely at the id itself. It is <code>Bardolph_1H4</code>, and one of those four rows has <code>play_id</code> equal to <code>2h4</code>. The id encodes the play where the character <em>first shows up</em>, not the play the row is about. A column that looks like a label for the row is really a label for something else, and the only way to find that out was to count.</p>
<ol start="4" type="1">
<li>If <code>character_id</code> is not the key, what is? Test the obvious candidate. Then test the one a human would have picked, the character’s name within their play.</li>
</ol>
<div id="b592eca9" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    char</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id, c.play_id)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    .agg(n <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.n <span class="op">&gt;</span> <span class="dv">1</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="11">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (0, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">character_id</th>
<th data-quarto-table-cell-role="th">play_id</th>
<th data-quarto-table-cell-role="th">n</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>u32</td>
</tr>
</thead>
<tbody>
</tbody>
</table>
</div>
</div>
</div>
<div id="e9387bf6" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    char</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    .group_by(c.name, c.play_id)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    .agg(n <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.n <span class="op">&gt;</span> <span class="dv">1</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    .sort(c.n, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">5</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="12">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (5, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">play_id</th>
<th data-quarto-table-cell-role="th">n</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Indeterminate member of the SE…</td>
<td>"wt"</td>
<td>3</td>
</tr>
<tr class="even">
<td>"Messenger"</td>
<td>"ado"</td>
<td>2</td>
</tr>
<tr class="odd">
<td>"Soldiers"</td>
<td>"cor"</td>
<td>2</td>
</tr>
<tr class="even">
<td>"First Lord"</td>
<td>"ayl"</td>
<td>2</td>
</tr>
<tr class="odd">
<td>"Sailor"</td>
<td>"per"</td>
<td>2</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Answer</strong>: The first returns nothing, which is the answer: no pair of <code>character_id</code> and <code>play_id</code> occurs twice, so together they are the key, and they name the unit exactly.</p>
<p>The second returns fourteen rows, so name-within-play is <em>not</em> a key. <em>Pericles</em> has two characters called Gentlemen, <em>Coriolanus</em> has two called Lieutenant, and <em>As You Like It</em> has two Second Lords. Shakespeare gives a great many people no name at all, and a table cannot tell two nameless gentlemen apart. Print the two Gentlemen if you want to see how the Folger solved it: their ids are <code>GENTLEMEN.EPHESUS_Per</code> and <code>GENTLEMEN.MYTILENE_Per</code>, which is a librarian doing by hand what the data could not do on its own.</p>
<ol start="5" type="1">
<li>Now watch what the broken key does to an ordinary question. Which characters have the most lines? Count the lines per character, first the obvious way, then at the grain you established in question 4.</li>
</ol>
<div id="80610946" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">8</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="13">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (8, 2)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">character_id</th>
<th data-quarto-table-cell-role="th">n_lines</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"RichardIII_R3"</td>
<td>1563</td>
</tr>
<tr class="even">
<td>"Antony_JC"</td>
<td>1148</td>
</tr>
<tr class="odd">
<td>"HenryV_H5"</td>
<td>1132</td>
</tr>
<tr class="even">
<td>"HenryIV_1H4"</td>
<td>1044</td>
</tr>
<tr class="odd">
<td>"Hamlet_Ham"</td>
<td>873</td>
</tr>
<tr class="even">
<td>"HenryVI_1H6"</td>
<td>860</td>
</tr>
<tr class="odd">
<td>"Coriolanus_Cor"</td>
<td>852</td>
</tr>
<tr class="even">
<td>"QueenMargaret_1H6"</td>
<td>843</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="07f8e547" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id, c.play_id)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">8</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="14">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (8, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">character_id</th>
<th data-quarto-table-cell-role="th">play_id</th>
<th data-quarto-table-cell-role="th">n_lines</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"RichardIII_R3"</td>
<td>"r3"</td>
<td>1148</td>
</tr>
<tr class="even">
<td>"Hamlet_Ham"</td>
<td>"ham"</td>
<td>873</td>
</tr>
<tr class="odd">
<td>"Coriolanus_Cor"</td>
<td>"cor"</td>
<td>852</td>
</tr>
<tr class="even">
<td>"Othello_Oth"</td>
<td>"oth"</td>
<td>827</td>
</tr>
<tr class="odd">
<td>"Antony_JC"</td>
<td>"ant"</td>
<td>823</td>
</tr>
<tr class="even">
<td>"Iago_Oth"</td>
<td>"oth"</td>
<td>800</td>
</tr>
<tr class="odd">
<td>"RichardII_R2"</td>
<td>"r2"</td>
<td>756</td>
</tr>
<tr class="even">
<td>"HenryV_H5"</td>
<td>"h5"</td>
<td>728</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Answer</strong>: Both tables are sorted, both look reasonable, and they disagree about almost everything. Hamlet is fifth in the first one and second in the second.</p>
<p>The first table pools each id across every play it appears in, because that is what grouping by a non-key does. So <code>Antony_JC</code> shows 1,148 lines, which is 823 lines in <em>Antony and Cleopatra</em> plus 325 in <em>Julius Caesar</em>, two plays and about fourteen years apart in the story. <code>HenryV_H5</code> shows 1,132, which is Prince Hal drinking in the taverns of the two <em>Henry IV</em> plays added to the king who gives the speech at Agincourt. Best of all, <code>HenryIV_1H4</code> shows 1,044 lines and the largest block of them, 411, is in <em>Richard II</em>, where he is Bolingbroke and not yet king, has not usurped anything, and is nobody’s Henry IV.</p>
<p>None of those three are parts. They are actors’ careers. A part is a character in a play, the second grouping asks for exactly that, and the numbers it returns are ones you could check against a script.</p>
<ol start="6" type="1">
<li>On to the first tidy rule: every variable gets its own column. Print the lines of <em>Hamlet</em>, Act 3 Scene 1, in order. Sort them by <code>line_number</code>, which is the column that appears to hold the order.</li>
</ol>
<div id="d6f9f4d0" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"ham"</span>, c.act <span class="op">==</span> <span class="dv">3</span>, c.scene <span class="op">==</span> <span class="dv">1</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    .sort(c.line_number)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    .select(c.line_number, c.character_id, c.text)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">6</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="15">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (6, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">line_number</th>
<th data-quarto-table-cell-role="th">character_id</th>
<th data-quarto-table-cell-role="th">text</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"3.1.1"</td>
<td>"Claudius_Ham"</td>
<td>"And can you by no drift of con…</td>
</tr>
<tr class="even">
<td>"3.1.10"</td>
<td>"Guildenstern_Ham"</td>
<td>"Of his true state."</td>
</tr>
<tr class="odd">
<td>"3.1.100"</td>
<td>"Ophelia_Ham"</td>
<td>"How does your Honor for this m…</td>
</tr>
<tr class="even">
<td>"3.1.101"</td>
<td>"Hamlet_Ham"</td>
<td>"I humbly thank you, well."</td>
</tr>
<tr class="odd">
<td>"3.1.102"</td>
<td>"Ophelia_Ham"</td>
<td>"My lord, I have remembrances o…</td>
</tr>
<tr class="even">
<td>"3.1.103"</td>
<td>"Ophelia_Ham"</td>
<td>"That I have longèd long to red…</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="536498db" class="cell" data-execution_count="17">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"ham"</span>, c.act <span class="op">==</span> <span class="dv">3</span>, c.scene <span class="op">==</span> <span class="dv">1</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    .sort(c.line_id)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    .select(c.line_number, c.character_id, c.text)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">6</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="16">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (6, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">line_number</th>
<th data-quarto-table-cell-role="th">character_id</th>
<th data-quarto-table-cell-role="th">text</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"3.1.1"</td>
<td>"Claudius_Ham"</td>
<td>"And can you by no drift of con…</td>
</tr>
<tr class="even">
<td>"3.1.2"</td>
<td>"Claudius_Ham"</td>
<td>"Get from him why he puts on th…</td>
</tr>
<tr class="odd">
<td>"3.1.3"</td>
<td>"Claudius_Ham"</td>
<td>"Grating so harshly all his day…</td>
</tr>
<tr class="even">
<td>"3.1.4"</td>
<td>"Claudius_Ham"</td>
<td>"With turbulent and dangerous l…</td>
</tr>
<tr class="odd">
<td>"3.1.5"</td>
<td>"Rosencrantz_Ham"</td>
<td>"He does confess he feels himse…</td>
</tr>
<tr class="even">
<td>"3.1.6"</td>
<td>"Rosencrantz_Ham"</td>
<td>"But from what cause he will by…</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Answer</strong>: The first sort gives you 3.1.1, then 3.1.10, then 3.1.100, then 3.1.101. It is alphabetical order, because <code>line_number</code> is a <code>str</code>, and as text “3.1.10” really does come before “3.1.2”.</p>
<p>It is text because it is not one variable. It is three, glued together with periods: act, scene, and the line’s position in the scene. Two of the three already have honest columns of their own, <code>act</code> and <code>scene</code>, both <code>i64</code>. The third one, the number that actually orders the speeches, exists only inside that string, and there is no column you can sort on to get it. The second block works around the problem by sorting on <code>line_id</code> instead, which happens to be zero-padded and so happens to sort correctly. That is luck, not design. It also tells you where the famous line lives: 3.1.64, “To be or not to be”.</p>
<p>We cannot fix this yet. Prying the three numbers out of one cell needs a method that splits a string into a list and another that gives each list element its own row, and both are in the second half of this chapter. Notice for now that a packed cell is not a cosmetic problem. It cost us the ability to sort a scene.</p>
<ol start="7" type="1">
<li>Same rule, worse violation. Count the speakers in <em>Macbeth</em> from the lines table, and compare that with the number of characters the dramatis personae lists for it.</li>
</ol>
<div id="152a0237" class="cell" data-execution_count="18">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(char.<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>).select(listed <span class="op">=</span> pl.<span class="bu">len</span>()))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(line.<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>).select(speakers <span class="op">=</span> c.character_id.n_unique()))</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">20</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">print</span>(<span class="dv">20</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>shape: (1, 1)
┌────────┐
│ listed │
│ ---    │
│ u32    │
╞════════╡
│ 28     │
└────────┘
shape: (1, 1)
┌──────────┐
│ speakers │
│ ---      │
│ u32      │
╞══════════╡
│ 49       │
└──────────┘</code></pre>
</div>
<div class="cell-output cell-output-display">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (20, 2)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">character_id</th>
<th data-quarto-table-cell-role="th">n_lines</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Macbeth_Mac"</td>
<td>711</td>
</tr>
<tr class="even">
<td>"LadyMacbeth_Mac"</td>
<td>230</td>
</tr>
<tr class="odd">
<td>"Malcolm_Mac"</td>
<td>209</td>
</tr>
<tr class="even">
<td>"Macduff_Mac"</td>
<td>175</td>
</tr>
<tr class="odd">
<td>"Ross_Mac"</td>
<td>134</td>
</tr>
<tr class="even">
<td>"Banquo_Mac"</td>
<td>111</td>
</tr>
<tr class="odd">
<td>"Lennox_Mac"</td>
<td>70</td>
</tr>
<tr class="even">
<td>"Duncan_Mac"</td>
<td>69</td>
</tr>
<tr class="odd">
<td>"WITCHES.1_Mac"</td>
<td>59</td>
</tr>
<tr class="even">
<td>"Hecate_Mac"</td>
<td>39</td>
</tr>
<tr class="odd">
<td>"SOLDIERS.Captain_Mac"</td>
<td>34</td>
</tr>
<tr class="even">
<td>"LadyMacduff_Mac"</td>
<td>33</td>
</tr>
<tr class="odd">
<td>"Siward_Mac"</td>
<td>30</td>
</tr>
<tr class="even">
<td>"WITCHES.3_Mac"</td>
<td>25</td>
</tr>
<tr class="odd">
<td>"MURDERERS.1_Mac"</td>
<td>24</td>
</tr>
<tr class="even">
<td>"WITCHES.2_Mac"</td>
<td>24</td>
</tr>
<tr class="odd">
<td>"Angus_Mac"</td>
<td>21</td>
</tr>
<tr class="even">
<td>"WITCHES.1_Mac #WITCHES.2_Mac #…</td>
<td>21</td>
</tr>
<tr class="odd">
<td>"Lord_Mac"</td>
<td>21</td>
</tr>
<tr class="even">
<td>"Doctor2_Mac"</td>
<td>18</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Answer</strong>: The personae lists 28 characters. The lines table has 49 distinct speakers. The two tables disagree by 21 about who is even in the play, and both are right.</p>
<p>Two things in that list explain it. The first is the Witches. <code>WITCHES.1_Mac</code>, <code>WITCHES.2_Mac</code>, and <code>WITCHES.3_Mac</code> speak 59, 25, and 24 lines, three separate speakers. In <code>char</code> they are a single row, <code>WITCHES_Mac</code>, named “Three Witches, the Weïrd Sisters”. A cast list can name the Witches once. A script has to know which of them is talking. Neither table is wrong, and whether the Weïrd Sisters are one character or three depends on what you are doing with them.</p>
<p>The second is the row near the bottom, the one Polars had to cut off to fit:</p>
<pre><code>WITCHES.1_Mac #WITCHES.2_Mac #WITCHES.3_Mac    21</code></pre>
<p>Go look at what it says.</p>
<div id="3d24d2a0" class="cell" data-execution_count="19">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.character_id <span class="op">==</span> <span class="st">"WITCHES.1_Mac #WITCHES.2_Mac #WITCHES.3_Mac"</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    .select(c.line_number, c.text)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">4</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="18">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (4, 2)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">line_number</th>
<th data-quarto-table-cell-role="th">text</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"1.1.12"</td>
<td>"Fair is foul, and foul is fair…</td>
</tr>
<tr class="even">
<td>"1.1.13"</td>
<td>"Hover through the fog and filt…</td>
</tr>
<tr class="odd">
<td>"1.3.33"</td>
<td>"The Weïrd Sisters, hand in han…</td>
</tr>
<tr class="even">
<td>"1.3.34"</td>
<td>"Posters of the sea and land,"</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>That is not a speaker. It is three speakers in a single cell, hashes and all, and it is how the Folger records the Witches chanting in unison: “Fair is foul, and foul is fair”, and the refrain of “Double, double toil and trouble” they say three times over the cauldron in 4.1. Every count in this question has been quietly treating that cell as a fourth witch.</p>
<p>There are 177 such lines in the corpus and 75 distinct combinations of speakers. The worst of them is in <em>Antony and Cleopatra</em> at 2.7.138, where ten characters, drunk on Pompey’s galley, sing “Cup us till the world go round” out of a single cell.</p>
<p>So <code>character_id</code> does not hold one value per row. It sometimes holds a set, which breaks the first tidy rule about as plainly as it can be broken, and it is why <code>n_unique</code> said 49. The honest count of Macbeth’s speaking parts is lower than that, and we cannot compute it today: separating those three names into three rows is the same missing method that would have unpacked <code>line_number</code> in question 6.</p>
<ol start="8" type="1">
<li>One more column to look at, and this one is a warning about the opposite mistake. Count the distinct values of <code>line_type</code>.</li>
</ol>
<div id="cd3005b1" class="cell" data-execution_count="20">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    .select(</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>        rows <span class="op">=</span> pl.<span class="bu">len</span>(),</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>        line_types <span class="op">=</span> c.line_type.n_unique(),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>        acts <span class="op">=</span> c.act.n_unique(),</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="19">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (1, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">rows</th>
<th data-quarto-table-cell-role="th">line_types</th>
<th data-quarto-table-cell-role="th">acts</th>
</tr>
<tr class="even">
<td>u32</td>
<td>u32</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>80592</td>
<td>1</td>
<td>5</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Answer</strong>: <code>line_type</code> has exactly one distinct value across all 80,592 rows. Every line in the table is labeled <code>verse</code>.</p>
<p>A column with one value is not a variable. It cannot vary. It tells you nothing about any row, it cannot be filtered on, grouped by, or plotted, and it would survive a tidy-data inspection untouched, because the rule is that every variable gets a column and says nothing about columns that are not variables. The tidy rules are about shape. They cannot tell you what a one-value column means, and no rule can. You have to look.</p>
<p>So look. A label that never changes is either a genuine constant or the fossil of a filter somebody already ran, and those are very different things. Here is a first clue about which one this is. The cast list of <em>Macbeth</em> includes a Porter. Ask the lines table how many lines he speaks.</p>
<div id="e705d575" class="cell" data-execution_count="21">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(char.<span class="bu">filter</span>(c.character_id <span class="op">==</span> <span class="st">"Porter_Mac"</span>).select(c.character_id, c.name))</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(line.<span class="bu">filter</span>(c.character_id <span class="op">==</span> <span class="st">"Porter_Mac"</span>).select(porter_lines <span class="op">=</span> pl.<span class="bu">len</span>()))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>shape: (1, 2)
┌──────────────┬──────────┐
│ character_id ┆ name     │
│ ---          ┆ ---      │
│ str          ┆ str      │
╞══════════════╪══════════╡
│ Porter_Mac   ┆ A Porter │
└──────────────┴──────────┘
shape: (1, 1)
┌──────────────┐
│ porter_lines │
│ ---          │
│ u32          │
╞══════════════╡
│ 0            │
└──────────────┘</code></pre>
</div>
</div>
<p>Zero. The Porter is one of the most famous speaking parts in the play, the drunk answering the knock at the gate, and there is not a single line of his in this table. What the Porter speaks is prose. We cannot prove the pattern yet, because pinning it down needs a column we have to build out of <code>line_number</code>, and that is the second half of this chapter. But keep the suspicion: <code>verse</code> may not be a broken label at all. It may be an honest record of a decision that was made before we ever got the data, which is that the prose was left out.</p>
<ol start="9" type="1">
<li>Draw the twelve biggest parts. Use the grain from question 5, and remember that a categorical axis takes its order from the rows of the table.</li>
</ol>
<div id="8f889679" class="cell" data-execution_count="22">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id, c.play_id)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">12</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(c.character_id, c.n_lines))</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    .geom_col(fill<span class="op">=</span><span class="st">"#F5276C"</span>)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    .coord_flip()</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    .labs(</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>        x<span class="op">=</span><span class="st">""</span>,</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>        y<span class="op">=</span><span class="st">"Lines spoken"</span>,</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>        title<span class="op">=</span><span class="st">"The twelve biggest parts in Shakespeare"</span>,</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>        caption<span class="op">=</span><span class="st">"Folger Shakespeare Library"</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>    .theme_tufte()</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="21">
<div>
<figure class="figure">
<p><a href="notebook14_files/figure-html/cell-23-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="notebook14_files/figure-html/cell-23-output-1.png" width="672" height="480" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p>Richard III is a runaway, with 1,148 lines to Hamlet’s 873, and the rest of the list is tragedy after tragedy. Note the double sort: descending to pick the top twelve, then ascending so the bars come out longest-first once <code>coord_flip</code> turns them sideways.</p>
<p>The title on that chart is a small overstatement, and question 8 is the reason. Every line in this table is verse, so what we have drawn is the twelve biggest <em>verse</em> parts. It happens to be all tragic leads, who speak in verse anyway, so the top of the list would look much the same either way. But a great comic role that lives in prose would count for far less here than it does on the stage, and one is missing from this list who might not belong off it. Hold that thought until we come back to this corpus.</p>
<p>Now read the axis labels, because one of them is lying to you. The fifth bar says <code>Antony_JC</code> and those 823 lines are from <em>Antony and Cleopatra</em>. The label is the id, the id was minted in <em>Julius Caesar</em>, and the <code>play_id</code> column sitting right next to it in the grouped table says <code>ant</code>. The bar is correct and its name is not.</p>
<p>The fix is to label each bar with the character’s <code>name</code>, which lives in <code>char</code>, one table over. Pulling a column from another table by matching on a key is a join, and it is the chapter after this one.</p>
<ol start="10" type="1">
<li>Last question, and it is a written one. This corpus is stored long, four tables deep, one unit of observation each. Suppose you wanted a table with one row per play and one column per act, holding the number of lines. Could you build it with what you know today?</li>
</ol>
<p><strong>Answer</strong>: Half of it. <code>group_by(c.play_id, c.act).agg(n_lines = pl.len())</code> gets you the numbers, but it gets them long: one row per play × act, 185 rows, an <code>act</code> column and an <code>n_lines</code> column. Turning that into five columns named <code>1</code> through <code>5</code>, one per act, is a <em>pivot</em>, and we do not have it yet.</p>
<p>Which is the honest place to end. Everything we did today was diagnosis. We counted rows and distinct ids until the tables confessed what a row was, and every time we found a table in the wrong shape, we worked around it or wrote an IOU. Next class on this chapter we get the three methods that actually change a table’s shape: <code>pivot</code> to go wide, <code>unpivot</code> to go long, and <code>explode</code> to give each element of a packed cell its own row.</p>
<p>Worth noticing before then: aggregation also changes the unit of observation, and we have had it since chapter 5. The difference is that aggregation only goes one way. When we counted lines per character in question 5, the lines themselves were gone, and no method brings them back. A pivot loses nothing and can be undone. That asymmetry is the argument for storing data long, the way the Folger did, and letting each analysis reshape it as needed.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script>
document.addEventListener('DOMContentLoaded', function() {
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details .sourceCode");
      for (let i = 0; i < detailsSrc.length; i++) {
        const details = detailsSrc[i].closest('details');
        if (details) {
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
      }
      return false;
    };
  }
  // Replace buttons to strip the broken listeners Quarto attached, then re-add fixed ones
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    const fresh = hideAllCode.cloneNode(true);
    hideAllCode.parentNode.replaceChild(fresh, hideAllCode);
    fresh.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    const fresh = showAllCode.cloneNode(true);
    showAllCode.parentNode.replaceChild(fresh, showAllCode);
    fresh.addEventListener("click", toggleCodeHandler(true));
  }
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Notebook14"</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="an">solutions-release-date:</span><span class="co"> "2026-10-21"</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">### Setup</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>Run all of the following before starting the notebook.</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [noclear]</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="op">!</span> wget <span class="op">-</span>q <span class="op">-</span>nc https:<span class="op">//</span>raw.githubusercontent.com<span class="op">/</span>taylor<span class="op">-</span>arnold<span class="op">/</span>fds2<span class="op">/</span>refs<span class="op">/</span>heads<span class="op">/</span>main<span class="op">/</span>funs.py</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [noclear]</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotnine <span class="im">import</span> ggplot, aes</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> polars <span class="im">import</span> col <span class="im">as</span> c</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> funs</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>ub <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/taylor-arnold/fds2/refs/heads/main/"</span></span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [remove]</span></span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb27-36"><a href="#cb27-36" aria-hidden="true" tabindex="-1"></a>ub <span class="op">=</span> <span class="st">""</span></span>
<span id="cb27-37"><a href="#cb27-37" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-38"><a href="#cb27-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-41"><a href="#cb27-41" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-42"><a href="#cb27-42" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [noclear]</span></span>
<span id="cb27-43"><a href="#cb27-43" aria-hidden="true" tabindex="-1"></a>play <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/shakespeare_plays.csv"</span>)</span>
<span id="cb27-44"><a href="#cb27-44" aria-hidden="true" tabindex="-1"></a>char <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/shakespeare_characters.csv"</span>)</span>
<span id="cb27-45"><a href="#cb27-45" aria-hidden="true" tabindex="-1"></a>line <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/shakespeare_lines.csv.gz"</span>)</span>
<span id="cb27-46"><a href="#cb27-46" aria-hidden="true" tabindex="-1"></a>word <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/shakespeare_words.csv.gz"</span>)</span>
<span id="cb27-47"><a href="#cb27-47" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-48"><a href="#cb27-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-49"><a href="#cb27-49" aria-hidden="true" tabindex="-1"></a><span class="fu">### Questions</span></span>
<span id="cb27-50"><a href="#cb27-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-51"><a href="#cb27-51" aria-hidden="true" tabindex="-1"></a>Four tables this week, from the Folger Shakespeare Library's editions of the plays. They</span>
<span id="cb27-52"><a href="#cb27-52" aria-hidden="true" tabindex="-1"></a>are not four datasets. They are one corpus, recorded four times over at four levels of</span>
<span id="cb27-53"><a href="#cb27-53" aria-hidden="true" tabindex="-1"></a>detail: the plays, the characters in them, the lines those characters speak, and the words</span>
<span id="cb27-54"><a href="#cb27-54" aria-hidden="true" tabindex="-1"></a>in those lines. Nothing else changes between the tables.</span>
<span id="cb27-55"><a href="#cb27-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-56"><a href="#cb27-56" aria-hidden="true" tabindex="-1"></a>That makes this the right corpus for the only question this chapter asks: what is a row?</span>
<span id="cb27-57"><a href="#cb27-57" aria-hidden="true" tabindex="-1"></a>Every table has an answer, and getting it wrong does not raise an error. It gives you a</span>
<span id="cb27-58"><a href="#cb27-58" aria-hidden="true" tabindex="-1"></a>number that looks fine.</span>
<span id="cb27-59"><a href="#cb27-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-60"><a href="#cb27-60" aria-hidden="true" tabindex="-1"></a>There is no new Polars method in this notebook. Everything below is <span class="in">`filter`</span>, <span class="in">`sort`</span>,</span>
<span id="cb27-61"><a href="#cb27-61" aria-hidden="true" tabindex="-1"></a><span class="in">`group_by`</span>, <span class="in">`agg`</span>, <span class="in">`n_unique`</span>, and <span class="in">`pl.len()`</span>, which you already have. What is new is what</span>
<span id="cb27-62"><a href="#cb27-62" aria-hidden="true" tabindex="-1"></a>you point them at.</span>
<span id="cb27-63"><a href="#cb27-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-64"><a href="#cb27-64" aria-hidden="true" tabindex="-1"></a>Unless a question says otherwise, just print the result of each block; do not save it to a</span>
<span id="cb27-65"><a href="#cb27-65" aria-hidden="true" tabindex="-1"></a>variable.</span>
<span id="cb27-66"><a href="#cb27-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-67"><a href="#cb27-67" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Look at all four tables and write down, in words, what a single row of each one is.</span>
<span id="cb27-68"><a href="#cb27-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-71"><a href="#cb27-71" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-72"><a href="#cb27-72" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(play.shape, char.shape, line.shape, word.shape)</span>
<span id="cb27-73"><a href="#cb27-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-74"><a href="#cb27-74" aria-hidden="true" tabindex="-1"></a>play.head(<span class="dv">3</span>)</span>
<span id="cb27-75"><a href="#cb27-75" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-76"><a href="#cb27-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-79"><a href="#cb27-79" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-80"><a href="#cb27-80" aria-hidden="true" tabindex="-1"></a>char.head(<span class="dv">3</span>)</span>
<span id="cb27-81"><a href="#cb27-81" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-82"><a href="#cb27-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-85"><a href="#cb27-85" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-86"><a href="#cb27-86" aria-hidden="true" tabindex="-1"></a>line.head(<span class="dv">3</span>)</span>
<span id="cb27-87"><a href="#cb27-87" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-88"><a href="#cb27-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-91"><a href="#cb27-91" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-92"><a href="#cb27-92" aria-hidden="true" tabindex="-1"></a>word.head(<span class="dv">3</span>)</span>
<span id="cb27-93"><a href="#cb27-93" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-94"><a href="#cb27-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-95"><a href="#cb27-95" aria-hidden="true" tabindex="-1"></a>**Answer**: A row of <span class="in">`play`</span> is a play (37 of them). A row of <span class="in">`line`</span> is one line as it is</span>
<span id="cb27-96"><a href="#cb27-96" aria-hidden="true" tabindex="-1"></a>printed on the page (80,592). A row of <span class="in">`word`</span> is one word (599,864). A row of <span class="in">`char`</span> is a</span>
<span id="cb27-97"><a href="#cb27-97" aria-hidden="true" tabindex="-1"></a>character, or so it looks: 1,126 of them, each with an id, a play, and a name.</span>
<span id="cb27-98"><a href="#cb27-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-99"><a href="#cb27-99" aria-hidden="true" tabindex="-1"></a>Hold on to that last one. It is wrong, and question 3 is where it breaks.</span>
<span id="cb27-100"><a href="#cb27-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-101"><a href="#cb27-101" aria-hidden="true" tabindex="-1"></a>The chapter calls this the *unit of observation*: the "who" or "what" that each row stands</span>
<span id="cb27-102"><a href="#cb27-102" aria-hidden="true" tabindex="-1"></a>for. Notice that the four units here are nested, each one a finer grain of the one above,</span>
<span id="cb27-103"><a href="#cb27-103" aria-hidden="true" tabindex="-1"></a>and that the corpus keeps them in four separate tables rather than one enormous table with</span>
<span id="cb27-104"><a href="#cb27-104" aria-hidden="true" tabindex="-1"></a>a column for everything. That is the third tidy rule in practice. One table, one unit.</span>
<span id="cb27-105"><a href="#cb27-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-106"><a href="#cb27-106" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>A primary key is the column, or set of columns, that uniquely identifies the unit of</span>
<span id="cb27-107"><a href="#cb27-107" aria-hidden="true" tabindex="-1"></a>observation. So a claim about the unit is a claim you can test: count the distinct values</span>
<span id="cb27-108"><a href="#cb27-108" aria-hidden="true" tabindex="-1"></a>of the id and compare it to the number of rows. Do that for each table.</span>
<span id="cb27-109"><a href="#cb27-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-112"><a href="#cb27-112" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-113"><a href="#cb27-113" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(play.select(rows <span class="op">=</span> pl.<span class="bu">len</span>(), ids <span class="op">=</span> c.play_id.n_unique()))</span>
<span id="cb27-114"><a href="#cb27-114" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(char.select(rows <span class="op">=</span> pl.<span class="bu">len</span>(), ids <span class="op">=</span> c.character_id.n_unique()))</span>
<span id="cb27-115"><a href="#cb27-115" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(line.select(rows <span class="op">=</span> pl.<span class="bu">len</span>(), ids <span class="op">=</span> c.line_id.n_unique()))</span>
<span id="cb27-116"><a href="#cb27-116" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(word.select(rows <span class="op">=</span> pl.<span class="bu">len</span>(), ids <span class="op">=</span> c.word_id.n_unique()))</span>
<span id="cb27-117"><a href="#cb27-117" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-118"><a href="#cb27-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-119"><a href="#cb27-119" aria-hidden="true" tabindex="-1"></a>**Answer**: Three of the four pass. <span class="in">`play_id`</span>, <span class="in">`line_id`</span>, and <span class="in">`word_id`</span> each have exactly</span>
<span id="cb27-120"><a href="#cb27-120" aria-hidden="true" tabindex="-1"></a>as many distinct values as their table has rows, so each one identifies a row and the unit</span>
<span id="cb27-121"><a href="#cb27-121" aria-hidden="true" tabindex="-1"></a>of observation is what we said it was.</span>
<span id="cb27-122"><a href="#cb27-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-123"><a href="#cb27-123" aria-hidden="true" tabindex="-1"></a><span class="in">`character_id`</span> does not. There are 1,126 rows and only 1,066 distinct ids, so some ids are</span>
<span id="cb27-124"><a href="#cb27-124" aria-hidden="true" tabindex="-1"></a>being used by more than one row. That makes <span class="in">`character_id`</span> not a key, which means a row of</span>
<span id="cb27-125"><a href="#cb27-125" aria-hidden="true" tabindex="-1"></a>this table is not a character. It is something else, and we do not know what yet.</span>
<span id="cb27-126"><a href="#cb27-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-127"><a href="#cb27-127" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Find the ids that repeat, then go look at the rows behind the worst offender.</span>
<span id="cb27-128"><a href="#cb27-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-131"><a href="#cb27-131" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-132"><a href="#cb27-132" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb27-133"><a href="#cb27-133" aria-hidden="true" tabindex="-1"></a>    char</span>
<span id="cb27-134"><a href="#cb27-134" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id)</span>
<span id="cb27-135"><a href="#cb27-135" aria-hidden="true" tabindex="-1"></a>    .agg(n <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb27-136"><a href="#cb27-136" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.n <span class="op">&gt;</span> <span class="dv">1</span>)</span>
<span id="cb27-137"><a href="#cb27-137" aria-hidden="true" tabindex="-1"></a>    .sort(c.n, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb27-138"><a href="#cb27-138" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">5</span>)</span>
<span id="cb27-139"><a href="#cb27-139" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-140"><a href="#cb27-140" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-141"><a href="#cb27-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-144"><a href="#cb27-144" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-145"><a href="#cb27-145" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb27-146"><a href="#cb27-146" aria-hidden="true" tabindex="-1"></a>    char</span>
<span id="cb27-147"><a href="#cb27-147" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.character_id <span class="op">==</span> <span class="st">"Bardolph_1H4"</span>)</span>
<span id="cb27-148"><a href="#cb27-148" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-149"><a href="#cb27-149" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-150"><a href="#cb27-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-151"><a href="#cb27-151" aria-hidden="true" tabindex="-1"></a>**Answer**: Four rows, one id, four different plays. Bardolph drinks his way through</span>
<span id="cb27-152"><a href="#cb27-152" aria-hidden="true" tabindex="-1"></a>*Henry IV Part 1*, *Part 2*, *Henry V*, and *The Merry Wives of Windsor*, and the Folger</span>
<span id="cb27-153"><a href="#cb27-153" aria-hidden="true" tabindex="-1"></a>gives him one id in all four.</span>
<span id="cb27-154"><a href="#cb27-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-155"><a href="#cb27-155" aria-hidden="true" tabindex="-1"></a>So the unit of observation of <span class="in">`char`</span> is not a character. It is a *character × play*: one row</span>
<span id="cb27-156"><a href="#cb27-156" aria-hidden="true" tabindex="-1"></a>for each appearance of a character in a play. Thirty-nine characters cross plays this way and</span>
<span id="cb27-157"><a href="#cb27-157" aria-hidden="true" tabindex="-1"></a>account for the sixty extra rows. Thirty-six of them are in the English histories, where the</span>
<span id="cb27-158"><a href="#cb27-158" aria-hidden="true" tabindex="-1"></a>same nobles fight the same wars across eight plays. The other three are Antony, Octavius, and</span>
<span id="cb27-159"><a href="#cb27-159" aria-hidden="true" tabindex="-1"></a>Lepidus, who carve up the Roman world at the end of *Julius Caesar* and are still arguing</span>
<span id="cb27-160"><a href="#cb27-160" aria-hidden="true" tabindex="-1"></a>about it in *Antony and Cleopatra*.</span>
<span id="cb27-161"><a href="#cb27-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-162"><a href="#cb27-162" aria-hidden="true" tabindex="-1"></a>Look closely at the id itself. It is <span class="in">`Bardolph_1H4`</span>, and one of those four rows has</span>
<span id="cb27-163"><a href="#cb27-163" aria-hidden="true" tabindex="-1"></a><span class="in">`play_id`</span> equal to <span class="in">`2h4`</span>. The id encodes the play where the character *first shows up*, not</span>
<span id="cb27-164"><a href="#cb27-164" aria-hidden="true" tabindex="-1"></a>the play the row is about. A column that looks like a label for the row is really a label</span>
<span id="cb27-165"><a href="#cb27-165" aria-hidden="true" tabindex="-1"></a>for something else, and the only way to find that out was to count.</span>
<span id="cb27-166"><a href="#cb27-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-167"><a href="#cb27-167" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>If <span class="in">`character_id`</span> is not the key, what is? Test the obvious candidate. Then test the one</span>
<span id="cb27-168"><a href="#cb27-168" aria-hidden="true" tabindex="-1"></a>a human would have picked, the character's name within their play.</span>
<span id="cb27-169"><a href="#cb27-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-172"><a href="#cb27-172" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-173"><a href="#cb27-173" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb27-174"><a href="#cb27-174" aria-hidden="true" tabindex="-1"></a>    char</span>
<span id="cb27-175"><a href="#cb27-175" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id, c.play_id)</span>
<span id="cb27-176"><a href="#cb27-176" aria-hidden="true" tabindex="-1"></a>    .agg(n <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb27-177"><a href="#cb27-177" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.n <span class="op">&gt;</span> <span class="dv">1</span>)</span>
<span id="cb27-178"><a href="#cb27-178" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-179"><a href="#cb27-179" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-180"><a href="#cb27-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-183"><a href="#cb27-183" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-184"><a href="#cb27-184" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb27-185"><a href="#cb27-185" aria-hidden="true" tabindex="-1"></a>    char</span>
<span id="cb27-186"><a href="#cb27-186" aria-hidden="true" tabindex="-1"></a>    .group_by(c.name, c.play_id)</span>
<span id="cb27-187"><a href="#cb27-187" aria-hidden="true" tabindex="-1"></a>    .agg(n <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb27-188"><a href="#cb27-188" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.n <span class="op">&gt;</span> <span class="dv">1</span>)</span>
<span id="cb27-189"><a href="#cb27-189" aria-hidden="true" tabindex="-1"></a>    .sort(c.n, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb27-190"><a href="#cb27-190" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">5</span>)</span>
<span id="cb27-191"><a href="#cb27-191" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-192"><a href="#cb27-192" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-193"><a href="#cb27-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-194"><a href="#cb27-194" aria-hidden="true" tabindex="-1"></a>**Answer**: The first returns nothing, which is the answer: no pair of <span class="in">`character_id`</span> and</span>
<span id="cb27-195"><a href="#cb27-195" aria-hidden="true" tabindex="-1"></a><span class="in">`play_id`</span> occurs twice, so together they are the key, and they name the unit exactly.</span>
<span id="cb27-196"><a href="#cb27-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-197"><a href="#cb27-197" aria-hidden="true" tabindex="-1"></a>The second returns fourteen rows, so name-within-play is *not* a key. *Pericles* has two</span>
<span id="cb27-198"><a href="#cb27-198" aria-hidden="true" tabindex="-1"></a>characters called Gentlemen, *Coriolanus* has two called Lieutenant, and *As You Like It*</span>
<span id="cb27-199"><a href="#cb27-199" aria-hidden="true" tabindex="-1"></a>has two Second Lords. Shakespeare gives a great many people no name at all, and a table</span>
<span id="cb27-200"><a href="#cb27-200" aria-hidden="true" tabindex="-1"></a>cannot tell two nameless gentlemen apart. Print the two Gentlemen if you want to see how</span>
<span id="cb27-201"><a href="#cb27-201" aria-hidden="true" tabindex="-1"></a>the Folger solved it: their ids are <span class="in">`GENTLEMEN.EPHESUS_Per`</span> and <span class="in">`GENTLEMEN.MYTILENE_Per`</span>,</span>
<span id="cb27-202"><a href="#cb27-202" aria-hidden="true" tabindex="-1"></a>which is a librarian doing by hand what the data could not do on its own.</span>
<span id="cb27-203"><a href="#cb27-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-204"><a href="#cb27-204" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Now watch what the broken key does to an ordinary question. Which characters have the</span>
<span id="cb27-205"><a href="#cb27-205" aria-hidden="true" tabindex="-1"></a>most lines? Count the lines per character, first the obvious way, then at the grain you</span>
<span id="cb27-206"><a href="#cb27-206" aria-hidden="true" tabindex="-1"></a>established in question 4.</span>
<span id="cb27-207"><a href="#cb27-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-210"><a href="#cb27-210" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-211"><a href="#cb27-211" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb27-212"><a href="#cb27-212" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb27-213"><a href="#cb27-213" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id)</span>
<span id="cb27-214"><a href="#cb27-214" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb27-215"><a href="#cb27-215" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb27-216"><a href="#cb27-216" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">8</span>)</span>
<span id="cb27-217"><a href="#cb27-217" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-218"><a href="#cb27-218" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-219"><a href="#cb27-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-222"><a href="#cb27-222" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-223"><a href="#cb27-223" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb27-224"><a href="#cb27-224" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb27-225"><a href="#cb27-225" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id, c.play_id)</span>
<span id="cb27-226"><a href="#cb27-226" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb27-227"><a href="#cb27-227" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb27-228"><a href="#cb27-228" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">8</span>)</span>
<span id="cb27-229"><a href="#cb27-229" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-230"><a href="#cb27-230" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-231"><a href="#cb27-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-232"><a href="#cb27-232" aria-hidden="true" tabindex="-1"></a>**Answer**: Both tables are sorted, both look reasonable, and they disagree about almost</span>
<span id="cb27-233"><a href="#cb27-233" aria-hidden="true" tabindex="-1"></a>everything. Hamlet is fifth in the first one and second in the second.</span>
<span id="cb27-234"><a href="#cb27-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-235"><a href="#cb27-235" aria-hidden="true" tabindex="-1"></a>The first table pools each id across every play it appears in, because that is what</span>
<span id="cb27-236"><a href="#cb27-236" aria-hidden="true" tabindex="-1"></a>grouping by a non-key does. So <span class="in">`Antony_JC`</span> shows 1,148 lines, which is 823 lines in *Antony</span>
<span id="cb27-237"><a href="#cb27-237" aria-hidden="true" tabindex="-1"></a>and Cleopatra* plus 325 in *Julius Caesar*, two plays and about fourteen years apart in the</span>
<span id="cb27-238"><a href="#cb27-238" aria-hidden="true" tabindex="-1"></a>story. <span class="in">`HenryV_H5`</span> shows 1,132, which is Prince Hal drinking in the taverns of the two</span>
<span id="cb27-239"><a href="#cb27-239" aria-hidden="true" tabindex="-1"></a>*Henry IV* plays added to the king who gives the speech at Agincourt. Best of all,</span>
<span id="cb27-240"><a href="#cb27-240" aria-hidden="true" tabindex="-1"></a><span class="in">`HenryIV_1H4`</span> shows 1,044 lines and the largest block of them, 411, is in *Richard II*,</span>
<span id="cb27-241"><a href="#cb27-241" aria-hidden="true" tabindex="-1"></a>where he is Bolingbroke and not yet king, has not usurped anything, and is nobody's Henry</span>
<span id="cb27-242"><a href="#cb27-242" aria-hidden="true" tabindex="-1"></a>IV.</span>
<span id="cb27-243"><a href="#cb27-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-244"><a href="#cb27-244" aria-hidden="true" tabindex="-1"></a>None of those three are parts. They are actors' careers. A part is a character in a play,</span>
<span id="cb27-245"><a href="#cb27-245" aria-hidden="true" tabindex="-1"></a>the second grouping asks for exactly that, and the numbers it returns are ones you could</span>
<span id="cb27-246"><a href="#cb27-246" aria-hidden="true" tabindex="-1"></a>check against a script.</span>
<span id="cb27-247"><a href="#cb27-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-248"><a href="#cb27-248" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>On to the first tidy rule: every variable gets its own column. Print the lines of</span>
<span id="cb27-249"><a href="#cb27-249" aria-hidden="true" tabindex="-1"></a>*Hamlet*, Act 3 Scene 1, in order. Sort them by <span class="in">`line_number`</span>, which is the column that</span>
<span id="cb27-250"><a href="#cb27-250" aria-hidden="true" tabindex="-1"></a>appears to hold the order.</span>
<span id="cb27-251"><a href="#cb27-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-254"><a href="#cb27-254" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-255"><a href="#cb27-255" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb27-256"><a href="#cb27-256" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb27-257"><a href="#cb27-257" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"ham"</span>, c.act <span class="op">==</span> <span class="dv">3</span>, c.scene <span class="op">==</span> <span class="dv">1</span>)</span>
<span id="cb27-258"><a href="#cb27-258" aria-hidden="true" tabindex="-1"></a>    .sort(c.line_number)</span>
<span id="cb27-259"><a href="#cb27-259" aria-hidden="true" tabindex="-1"></a>    .select(c.line_number, c.character_id, c.text)</span>
<span id="cb27-260"><a href="#cb27-260" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">6</span>)</span>
<span id="cb27-261"><a href="#cb27-261" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-262"><a href="#cb27-262" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-263"><a href="#cb27-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-266"><a href="#cb27-266" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-267"><a href="#cb27-267" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb27-268"><a href="#cb27-268" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb27-269"><a href="#cb27-269" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"ham"</span>, c.act <span class="op">==</span> <span class="dv">3</span>, c.scene <span class="op">==</span> <span class="dv">1</span>)</span>
<span id="cb27-270"><a href="#cb27-270" aria-hidden="true" tabindex="-1"></a>    .sort(c.line_id)</span>
<span id="cb27-271"><a href="#cb27-271" aria-hidden="true" tabindex="-1"></a>    .select(c.line_number, c.character_id, c.text)</span>
<span id="cb27-272"><a href="#cb27-272" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">6</span>)</span>
<span id="cb27-273"><a href="#cb27-273" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-274"><a href="#cb27-274" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-275"><a href="#cb27-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-276"><a href="#cb27-276" aria-hidden="true" tabindex="-1"></a>**Answer**: The first sort gives you 3.1.1, then 3.1.10, then 3.1.100, then 3.1.101. It is</span>
<span id="cb27-277"><a href="#cb27-277" aria-hidden="true" tabindex="-1"></a>alphabetical order, because <span class="in">`line_number`</span> is a <span class="in">`str`</span>, and as text "3.1.10" really does come</span>
<span id="cb27-278"><a href="#cb27-278" aria-hidden="true" tabindex="-1"></a>before "3.1.2".</span>
<span id="cb27-279"><a href="#cb27-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-280"><a href="#cb27-280" aria-hidden="true" tabindex="-1"></a>It is text because it is not one variable. It is three, glued together with periods: act,</span>
<span id="cb27-281"><a href="#cb27-281" aria-hidden="true" tabindex="-1"></a>scene, and the line's position in the scene. Two of the three already have honest columns</span>
<span id="cb27-282"><a href="#cb27-282" aria-hidden="true" tabindex="-1"></a>of their own, <span class="in">`act`</span> and <span class="in">`scene`</span>, both <span class="in">`i64`</span>. The third one, the number that actually orders</span>
<span id="cb27-283"><a href="#cb27-283" aria-hidden="true" tabindex="-1"></a>the speeches, exists only inside that string, and there is no column you can sort on to get</span>
<span id="cb27-284"><a href="#cb27-284" aria-hidden="true" tabindex="-1"></a>it. The second block works around the problem by sorting on <span class="in">`line_id`</span> instead, which</span>
<span id="cb27-285"><a href="#cb27-285" aria-hidden="true" tabindex="-1"></a>happens to be zero-padded and so happens to sort correctly. That is luck, not design. It</span>
<span id="cb27-286"><a href="#cb27-286" aria-hidden="true" tabindex="-1"></a>also tells you where the famous line lives: 3.1.64, "To be or not to be".</span>
<span id="cb27-287"><a href="#cb27-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-288"><a href="#cb27-288" aria-hidden="true" tabindex="-1"></a>We cannot fix this yet. Prying the three numbers out of one cell needs a method that splits</span>
<span id="cb27-289"><a href="#cb27-289" aria-hidden="true" tabindex="-1"></a>a string into a list and another that gives each list element its own row, and both are in</span>
<span id="cb27-290"><a href="#cb27-290" aria-hidden="true" tabindex="-1"></a>the second half of this chapter. Notice for now that a packed cell is not a cosmetic</span>
<span id="cb27-291"><a href="#cb27-291" aria-hidden="true" tabindex="-1"></a>problem. It cost us the ability to sort a scene.</span>
<span id="cb27-292"><a href="#cb27-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-293"><a href="#cb27-293" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>Same rule, worse violation. Count the speakers in *Macbeth* from the lines table, and</span>
<span id="cb27-294"><a href="#cb27-294" aria-hidden="true" tabindex="-1"></a>compare that with the number of characters the dramatis personae lists for it.</span>
<span id="cb27-295"><a href="#cb27-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-298"><a href="#cb27-298" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-299"><a href="#cb27-299" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(char.<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>).select(listed <span class="op">=</span> pl.<span class="bu">len</span>()))</span>
<span id="cb27-300"><a href="#cb27-300" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(line.<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>).select(speakers <span class="op">=</span> c.character_id.n_unique()))</span>
<span id="cb27-301"><a href="#cb27-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-302"><a href="#cb27-302" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb27-303"><a href="#cb27-303" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb27-304"><a href="#cb27-304" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>)</span>
<span id="cb27-305"><a href="#cb27-305" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id)</span>
<span id="cb27-306"><a href="#cb27-306" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb27-307"><a href="#cb27-307" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb27-308"><a href="#cb27-308" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">20</span>)</span>
<span id="cb27-309"><a href="#cb27-309" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">print</span>(<span class="dv">20</span>)</span>
<span id="cb27-310"><a href="#cb27-310" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-311"><a href="#cb27-311" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-312"><a href="#cb27-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-313"><a href="#cb27-313" aria-hidden="true" tabindex="-1"></a>**Answer**: The personae lists 28 characters. The lines table has 49 distinct speakers. The</span>
<span id="cb27-314"><a href="#cb27-314" aria-hidden="true" tabindex="-1"></a>two tables disagree by 21 about who is even in the play, and both are right.</span>
<span id="cb27-315"><a href="#cb27-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-316"><a href="#cb27-316" aria-hidden="true" tabindex="-1"></a>Two things in that list explain it. The first is the Witches. <span class="in">`WITCHES.1_Mac`</span>,</span>
<span id="cb27-317"><a href="#cb27-317" aria-hidden="true" tabindex="-1"></a><span class="in">`WITCHES.2_Mac`</span>, and <span class="in">`WITCHES.3_Mac`</span> speak 59, 25, and 24 lines, three separate speakers. In</span>
<span id="cb27-318"><a href="#cb27-318" aria-hidden="true" tabindex="-1"></a><span class="in">`char`</span> they are a single row, <span class="in">`WITCHES_Mac`</span>, named "Three Witches, the Weïrd Sisters". A</span>
<span id="cb27-319"><a href="#cb27-319" aria-hidden="true" tabindex="-1"></a>cast list can name the Witches once. A script has to know which of them is talking. Neither</span>
<span id="cb27-320"><a href="#cb27-320" aria-hidden="true" tabindex="-1"></a>table is wrong, and whether the Weïrd Sisters are one character or three depends on what</span>
<span id="cb27-321"><a href="#cb27-321" aria-hidden="true" tabindex="-1"></a>you are doing with them.</span>
<span id="cb27-322"><a href="#cb27-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-323"><a href="#cb27-323" aria-hidden="true" tabindex="-1"></a>The second is the row near the bottom, the one Polars had to cut off to fit:</span>
<span id="cb27-324"><a href="#cb27-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-325"><a href="#cb27-325" aria-hidden="true" tabindex="-1"></a><span class="in">    WITCHES.1_Mac #WITCHES.2_Mac #WITCHES.3_Mac    21</span></span>
<span id="cb27-326"><a href="#cb27-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-327"><a href="#cb27-327" aria-hidden="true" tabindex="-1"></a>Go look at what it says.</span>
<span id="cb27-328"><a href="#cb27-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-331"><a href="#cb27-331" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-332"><a href="#cb27-332" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb27-333"><a href="#cb27-333" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb27-334"><a href="#cb27-334" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.character_id <span class="op">==</span> <span class="st">"WITCHES.1_Mac #WITCHES.2_Mac #WITCHES.3_Mac"</span>)</span>
<span id="cb27-335"><a href="#cb27-335" aria-hidden="true" tabindex="-1"></a>    .select(c.line_number, c.text)</span>
<span id="cb27-336"><a href="#cb27-336" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">4</span>)</span>
<span id="cb27-337"><a href="#cb27-337" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-338"><a href="#cb27-338" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-339"><a href="#cb27-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-340"><a href="#cb27-340" aria-hidden="true" tabindex="-1"></a>That is not a speaker. It is three speakers in a single cell, hashes and all, and it is how</span>
<span id="cb27-341"><a href="#cb27-341" aria-hidden="true" tabindex="-1"></a>the Folger records the Witches chanting in unison: "Fair is foul, and foul is fair", and</span>
<span id="cb27-342"><a href="#cb27-342" aria-hidden="true" tabindex="-1"></a>the refrain of "Double, double toil and trouble" they say three times over the cauldron in</span>
<span id="cb27-343"><a href="#cb27-343" aria-hidden="true" tabindex="-1"></a>4.1. Every count in this question has been quietly treating that cell as a fourth witch.</span>
<span id="cb27-344"><a href="#cb27-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-345"><a href="#cb27-345" aria-hidden="true" tabindex="-1"></a>There are 177 such lines in the corpus and 75 distinct combinations of speakers. The worst</span>
<span id="cb27-346"><a href="#cb27-346" aria-hidden="true" tabindex="-1"></a>of them is in *Antony and Cleopatra* at 2.7.138, where ten characters, drunk on Pompey's</span>
<span id="cb27-347"><a href="#cb27-347" aria-hidden="true" tabindex="-1"></a>galley, sing "Cup us till the world go round" out of a single cell.</span>
<span id="cb27-348"><a href="#cb27-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-349"><a href="#cb27-349" aria-hidden="true" tabindex="-1"></a>So <span class="in">`character_id`</span> does not hold one value per row. It sometimes holds a set, which breaks</span>
<span id="cb27-350"><a href="#cb27-350" aria-hidden="true" tabindex="-1"></a>the first tidy rule about as plainly as it can be broken, and it is why <span class="in">`n_unique`</span> said 49.</span>
<span id="cb27-351"><a href="#cb27-351" aria-hidden="true" tabindex="-1"></a>The honest count of Macbeth's speaking parts is lower than that, and we cannot compute it</span>
<span id="cb27-352"><a href="#cb27-352" aria-hidden="true" tabindex="-1"></a>today: separating those three names into three rows is the same missing method that would</span>
<span id="cb27-353"><a href="#cb27-353" aria-hidden="true" tabindex="-1"></a>have unpacked <span class="in">`line_number`</span> in question 6.</span>
<span id="cb27-354"><a href="#cb27-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-355"><a href="#cb27-355" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>One more column to look at, and this one is a warning about the opposite mistake. Count</span>
<span id="cb27-356"><a href="#cb27-356" aria-hidden="true" tabindex="-1"></a>the distinct values of <span class="in">`line_type`</span>.</span>
<span id="cb27-357"><a href="#cb27-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-360"><a href="#cb27-360" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-361"><a href="#cb27-361" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb27-362"><a href="#cb27-362" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb27-363"><a href="#cb27-363" aria-hidden="true" tabindex="-1"></a>    .select(</span>
<span id="cb27-364"><a href="#cb27-364" aria-hidden="true" tabindex="-1"></a>        rows <span class="op">=</span> pl.<span class="bu">len</span>(),</span>
<span id="cb27-365"><a href="#cb27-365" aria-hidden="true" tabindex="-1"></a>        line_types <span class="op">=</span> c.line_type.n_unique(),</span>
<span id="cb27-366"><a href="#cb27-366" aria-hidden="true" tabindex="-1"></a>        acts <span class="op">=</span> c.act.n_unique(),</span>
<span id="cb27-367"><a href="#cb27-367" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb27-368"><a href="#cb27-368" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-369"><a href="#cb27-369" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-370"><a href="#cb27-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-371"><a href="#cb27-371" aria-hidden="true" tabindex="-1"></a>**Answer**: <span class="in">`line_type`</span> has exactly one distinct value across all 80,592 rows. Every line in</span>
<span id="cb27-372"><a href="#cb27-372" aria-hidden="true" tabindex="-1"></a>the table is labeled <span class="in">`verse`</span>.</span>
<span id="cb27-373"><a href="#cb27-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-374"><a href="#cb27-374" aria-hidden="true" tabindex="-1"></a>A column with one value is not a variable. It cannot vary. It tells you nothing about any</span>
<span id="cb27-375"><a href="#cb27-375" aria-hidden="true" tabindex="-1"></a>row, it cannot be filtered on, grouped by, or plotted, and it would survive a tidy-data</span>
<span id="cb27-376"><a href="#cb27-376" aria-hidden="true" tabindex="-1"></a>inspection untouched, because the rule is that every variable gets a column and says</span>
<span id="cb27-377"><a href="#cb27-377" aria-hidden="true" tabindex="-1"></a>nothing about columns that are not variables. The tidy rules are about shape. They cannot</span>
<span id="cb27-378"><a href="#cb27-378" aria-hidden="true" tabindex="-1"></a>tell you what a one-value column means, and no rule can. You have to look.</span>
<span id="cb27-379"><a href="#cb27-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-380"><a href="#cb27-380" aria-hidden="true" tabindex="-1"></a>So look. A label that never changes is either a genuine constant or the fossil of a filter</span>
<span id="cb27-381"><a href="#cb27-381" aria-hidden="true" tabindex="-1"></a>somebody already ran, and those are very different things. Here is a first clue about which</span>
<span id="cb27-382"><a href="#cb27-382" aria-hidden="true" tabindex="-1"></a>one this is. The cast list of *Macbeth* includes a Porter. Ask the lines table how many lines</span>
<span id="cb27-383"><a href="#cb27-383" aria-hidden="true" tabindex="-1"></a>he speaks.</span>
<span id="cb27-384"><a href="#cb27-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-387"><a href="#cb27-387" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-388"><a href="#cb27-388" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(char.<span class="bu">filter</span>(c.character_id <span class="op">==</span> <span class="st">"Porter_Mac"</span>).select(c.character_id, c.name))</span>
<span id="cb27-389"><a href="#cb27-389" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(line.<span class="bu">filter</span>(c.character_id <span class="op">==</span> <span class="st">"Porter_Mac"</span>).select(porter_lines <span class="op">=</span> pl.<span class="bu">len</span>()))</span>
<span id="cb27-390"><a href="#cb27-390" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-391"><a href="#cb27-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-392"><a href="#cb27-392" aria-hidden="true" tabindex="-1"></a>Zero. The Porter is one of the most famous speaking parts in the play, the drunk answering the</span>
<span id="cb27-393"><a href="#cb27-393" aria-hidden="true" tabindex="-1"></a>knock at the gate, and there is not a single line of his in this table. What the Porter speaks</span>
<span id="cb27-394"><a href="#cb27-394" aria-hidden="true" tabindex="-1"></a>is prose. We cannot prove the pattern yet, because pinning it down needs a column we have to</span>
<span id="cb27-395"><a href="#cb27-395" aria-hidden="true" tabindex="-1"></a>build out of <span class="in">`line_number`</span>, and that is the second half of this chapter. But keep the</span>
<span id="cb27-396"><a href="#cb27-396" aria-hidden="true" tabindex="-1"></a>suspicion: <span class="in">`verse`</span> may not be a broken label at all. It may be an honest record of a decision</span>
<span id="cb27-397"><a href="#cb27-397" aria-hidden="true" tabindex="-1"></a>that was made before we ever got the data, which is that the prose was left out.</span>
<span id="cb27-398"><a href="#cb27-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-399"><a href="#cb27-399" aria-hidden="true" tabindex="-1"></a><span class="ss">9. </span>Draw the twelve biggest parts. Use the grain from question 5, and remember that a</span>
<span id="cb27-400"><a href="#cb27-400" aria-hidden="true" tabindex="-1"></a>categorical axis takes its order from the rows of the table.</span>
<span id="cb27-401"><a href="#cb27-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-404"><a href="#cb27-404" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb27-405"><a href="#cb27-405" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb27-406"><a href="#cb27-406" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb27-407"><a href="#cb27-407" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id, c.play_id)</span>
<span id="cb27-408"><a href="#cb27-408" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb27-409"><a href="#cb27-409" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb27-410"><a href="#cb27-410" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">12</span>)</span>
<span id="cb27-411"><a href="#cb27-411" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines)</span>
<span id="cb27-412"><a href="#cb27-412" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(c.character_id, c.n_lines))</span>
<span id="cb27-413"><a href="#cb27-413" aria-hidden="true" tabindex="-1"></a>    .geom_col(fill<span class="op">=</span><span class="st">"#F5276C"</span>)</span>
<span id="cb27-414"><a href="#cb27-414" aria-hidden="true" tabindex="-1"></a>    .coord_flip()</span>
<span id="cb27-415"><a href="#cb27-415" aria-hidden="true" tabindex="-1"></a>    .labs(</span>
<span id="cb27-416"><a href="#cb27-416" aria-hidden="true" tabindex="-1"></a>        x<span class="op">=</span><span class="st">""</span>,</span>
<span id="cb27-417"><a href="#cb27-417" aria-hidden="true" tabindex="-1"></a>        y<span class="op">=</span><span class="st">"Lines spoken"</span>,</span>
<span id="cb27-418"><a href="#cb27-418" aria-hidden="true" tabindex="-1"></a>        title<span class="op">=</span><span class="st">"The twelve biggest parts in Shakespeare"</span>,</span>
<span id="cb27-419"><a href="#cb27-419" aria-hidden="true" tabindex="-1"></a>        caption<span class="op">=</span><span class="st">"Folger Shakespeare Library"</span></span>
<span id="cb27-420"><a href="#cb27-420" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb27-421"><a href="#cb27-421" aria-hidden="true" tabindex="-1"></a>    .theme_tufte()</span>
<span id="cb27-422"><a href="#cb27-422" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-423"><a href="#cb27-423" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-424"><a href="#cb27-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-425"><a href="#cb27-425" aria-hidden="true" tabindex="-1"></a>Richard III is a runaway, with 1,148 lines to Hamlet's 873, and the rest of the list is</span>
<span id="cb27-426"><a href="#cb27-426" aria-hidden="true" tabindex="-1"></a>tragedy after tragedy. Note the double sort: descending to pick the top twelve, then</span>
<span id="cb27-427"><a href="#cb27-427" aria-hidden="true" tabindex="-1"></a>ascending so the bars come out longest-first once <span class="in">`coord_flip`</span> turns them sideways.</span>
<span id="cb27-428"><a href="#cb27-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-429"><a href="#cb27-429" aria-hidden="true" tabindex="-1"></a>The title on that chart is a small overstatement, and question 8 is the reason. Every line in</span>
<span id="cb27-430"><a href="#cb27-430" aria-hidden="true" tabindex="-1"></a>this table is verse, so what we have drawn is the twelve biggest *verse* parts. It happens to</span>
<span id="cb27-431"><a href="#cb27-431" aria-hidden="true" tabindex="-1"></a>be all tragic leads, who speak in verse anyway, so the top of the list would look much the</span>
<span id="cb27-432"><a href="#cb27-432" aria-hidden="true" tabindex="-1"></a>same either way. But a great comic role that lives in prose would count for far less here than</span>
<span id="cb27-433"><a href="#cb27-433" aria-hidden="true" tabindex="-1"></a>it does on the stage, and one is missing from this list who might not belong off it. Hold that</span>
<span id="cb27-434"><a href="#cb27-434" aria-hidden="true" tabindex="-1"></a>thought until we come back to this corpus.</span>
<span id="cb27-435"><a href="#cb27-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-436"><a href="#cb27-436" aria-hidden="true" tabindex="-1"></a>Now read the axis labels, because one of them is lying to you. The fifth bar says</span>
<span id="cb27-437"><a href="#cb27-437" aria-hidden="true" tabindex="-1"></a><span class="in">`Antony_JC`</span> and those 823 lines are from *Antony and Cleopatra*. The label is the id, the id</span>
<span id="cb27-438"><a href="#cb27-438" aria-hidden="true" tabindex="-1"></a>was minted in *Julius Caesar*, and the <span class="in">`play_id`</span> column sitting right next to it in the</span>
<span id="cb27-439"><a href="#cb27-439" aria-hidden="true" tabindex="-1"></a>grouped table says <span class="in">`ant`</span>. The bar is correct and its name is not.</span>
<span id="cb27-440"><a href="#cb27-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-441"><a href="#cb27-441" aria-hidden="true" tabindex="-1"></a>The fix is to label each bar with the character's <span class="in">`name`</span>, which lives in <span class="in">`char`</span>, one table</span>
<span id="cb27-442"><a href="#cb27-442" aria-hidden="true" tabindex="-1"></a>over. Pulling a column from another table by matching on a key is a join, and it is the</span>
<span id="cb27-443"><a href="#cb27-443" aria-hidden="true" tabindex="-1"></a>chapter after this one.</span>
<span id="cb27-444"><a href="#cb27-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-445"><a href="#cb27-445" aria-hidden="true" tabindex="-1"></a><span class="ss">10. </span>Last question, and it is a written one. This corpus is stored long, four tables deep,</span>
<span id="cb27-446"><a href="#cb27-446" aria-hidden="true" tabindex="-1"></a>one unit of observation each. Suppose you wanted a table with one row per play and one</span>
<span id="cb27-447"><a href="#cb27-447" aria-hidden="true" tabindex="-1"></a>column per act, holding the number of lines. Could you build it with what you know today?</span>
<span id="cb27-448"><a href="#cb27-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-449"><a href="#cb27-449" aria-hidden="true" tabindex="-1"></a>**Answer**: Half of it. <span class="in">`group_by(c.play_id, c.act).agg(n_lines = pl.len())`</span> gets you the</span>
<span id="cb27-450"><a href="#cb27-450" aria-hidden="true" tabindex="-1"></a>numbers, but it gets them long: one row per play × act, 185 rows, an <span class="in">`act`</span> column and an</span>
<span id="cb27-451"><a href="#cb27-451" aria-hidden="true" tabindex="-1"></a><span class="in">`n_lines`</span> column. Turning that into five columns named <span class="in">`1`</span> through <span class="in">`5`</span>, one per act, is a</span>
<span id="cb27-452"><a href="#cb27-452" aria-hidden="true" tabindex="-1"></a>*pivot*, and we do not have it yet.</span>
<span id="cb27-453"><a href="#cb27-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-454"><a href="#cb27-454" aria-hidden="true" tabindex="-1"></a>Which is the honest place to end. Everything we did today was diagnosis. We counted rows</span>
<span id="cb27-455"><a href="#cb27-455" aria-hidden="true" tabindex="-1"></a>and distinct ids until the tables confessed what a row was, and every time we found a</span>
<span id="cb27-456"><a href="#cb27-456" aria-hidden="true" tabindex="-1"></a>table in the wrong shape, we worked around it or wrote an IOU. Next class on this chapter</span>
<span id="cb27-457"><a href="#cb27-457" aria-hidden="true" tabindex="-1"></a>we get the three methods that actually change a table's shape: <span class="in">`pivot`</span> to go wide,</span>
<span id="cb27-458"><a href="#cb27-458" aria-hidden="true" tabindex="-1"></a><span class="in">`unpivot`</span> to go long, and <span class="in">`explode`</span> to give each element of a packed cell its own row.</span>
<span id="cb27-459"><a href="#cb27-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-460"><a href="#cb27-460" aria-hidden="true" tabindex="-1"></a>Worth noticing before then: aggregation also changes the unit of observation, and we have</span>
<span id="cb27-461"><a href="#cb27-461" aria-hidden="true" tabindex="-1"></a>had it since chapter 5. The difference is that aggregation only goes one way. When we</span>
<span id="cb27-462"><a href="#cb27-462" aria-hidden="true" tabindex="-1"></a>counted lines per character in question 5, the lines themselves were gone, and no method</span>
<span id="cb27-463"><a href="#cb27-463" aria-hidden="true" tabindex="-1"></a>brings them back. A pivot loses nothing and can be undone. That asymmetry is the argument</span>
<span id="cb27-464"><a href="#cb27-464" aria-hidden="true" tabindex="-1"></a>for storing data long, the way the Folger did, and letting each analysis reshape it as</span>
<span id="cb27-465"><a href="#cb27-465" aria-hidden="true" tabindex="-1"></a>needed.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>