<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Notebook46 – Foundations of Data Science: Notebooks</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-77a666a5542a07a54dbe0a7f6e3b86cd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-sidebar docked fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./notebook46.html">Notebook46</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Foundations of Data Science: Notebooks</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook30.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook30</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook31.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook31</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook32.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook32</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook33.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook33</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook34.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook34</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook35.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook35</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook36.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook36</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook37.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook37</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook38.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook38</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook39.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook39</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook40.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook40</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook41.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook41</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook42.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook42</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook43.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook43</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook45.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook45</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook46.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Notebook46</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook47.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook47</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook48.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook48</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Notebook46</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="setup" class="level3">
<h3 class="anchored" data-anchor-id="setup">Setup</h3>
<p>Run all of the following before starting the notebook.</p>
<div id="7a90563e" class="cell" data-tags="[&quot;noclear&quot;]" data-execution_count="1">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span> wget <span class="op">-</span>q <span class="op">-</span>nc https:<span class="op">//</span>raw.githubusercontent.com<span class="op">/</span>taylor<span class="op">-</span>arnold<span class="op">/</span>fds2<span class="op">/</span>refs<span class="op">/</span>heads<span class="op">/</span>main<span class="op">/</span>funs.py</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="e9a5c1d5" class="cell" data-tags="[&quot;noclear&quot;]" data-execution_count="2">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotnine <span class="im">import</span> ggplot, aes, arrow</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> polars <span class="im">import</span> col <span class="im">as</span> c</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> funs</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> funs <span class="im">import</span> DSNetwork</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>ub <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/taylor-arnold/fds2/refs/heads/main/"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="7522aa69" class="cell" data-tags="[&quot;noclear&quot;]" data-execution_count="4">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>case <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/scotus_case.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>cite <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/scotus_citation.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="questions" class="level3">
<h3 class="anchored" data-anchor-id="questions">Questions</h3>
<p>This notebook continues with the U.S. Supreme Court citation network from the previous notebook. A row of <code>case</code> is one decided case, keyed by its reporter <code>citation</code> (<code>"384 U.S. 436"</code> is <em>Miranda v. Arizona</em>), with a <code>case_name</code>, the <code>term</code> it was argued, and the coded <code>issue_description</code> and <code>lean</code>. A row of <code>cite</code> is one precedent link: <code>citing_case</code> refers to the earlier <code>cited_case</code> somewhere in its opinion. Last time we built one network, the direct-citation network of the 80 most-cited cases, and measured its centrality. This time we build three <em>other</em> kinds of network from the same edge list — a co-citation network, a directed network, and a nearest-neighbor network — and see what each one shows that the direct network could not. The book’s own examples for these sections use a Wikipedia author corpus, which it warns is too small and too temporally scrambled to bring out the differences; a court is neither. Print your results unless a question says to save them.</p>
<p>We start, as before, by fixing the 80 most-cited cases so every network below is built on the same set of nodes.</p>
<div id="c797f056" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>top <span class="op">=</span> (</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    cite</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    .group_by(c.cited_case)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    .agg(n_in <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    .sort([c.n_in, c.cited_case], descending<span class="op">=</span>[<span class="va">True</span>, <span class="va">False</span>])</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">80</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    .get_column(<span class="st">"cited_case"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    .to_list()</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<ol type="1">
<li>The direct-citation network joins two cases when one cites the other. A <em>co-citation</em> network joins two cases when some third case cites <em>both</em> of them: the idea is that a later court reaching for two precedents in the same opinion is treating them as related. Build the co-citation edge list from <code>cite</code> by joining the citation table to itself on <code>citing_case</code>, keeping only the rows where both cited cases are in the top 80. Keep each unordered pair once with <code>c.cited_case &lt; c.cited_case_right</code>, count how many third cases cite both, and print the 10 pairs cited together most often. Join the names in so the pairs are readable.</li>
</ol>
<div id="9678d1d9" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>cc <span class="op">=</span> cite.<span class="bu">filter</span>(c.cited_case.is_in(top))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>cocite <span class="op">=</span> (</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    cc</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    .join(cc, on<span class="op">=</span><span class="st">"citing_case"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.cited_case <span class="op">&lt;</span> c.cited_case_right)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    .group_by([c.cited_case, c.cited_case_right])</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    .agg(count <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    .sort(c.count, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    cocite</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">10</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    .join(</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>        case.select(c.citation, name_a<span class="op">=</span>c.case_name),</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>        left_on<span class="op">=</span><span class="st">"cited_case"</span>,</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>        right_on<span class="op">=</span><span class="st">"citation"</span>,</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>        how<span class="op">=</span><span class="st">"left"</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    .join(</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>        case.select(c.citation, name_b<span class="op">=</span>c.case_name),</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>        left_on<span class="op">=</span><span class="st">"cited_case_right"</span>,</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>        right_on<span class="op">=</span><span class="st">"citation"</span>,</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>        how<span class="op">=</span><span class="st">"left"</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    .select(c.name_a, c.name_b, c.count)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="5">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (10, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">name_a</th>
<th data-quarto-table-cell-role="th">name_b</th>
<th data-quarto-table-cell-role="th">count</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"SCHNEIDER v. STATE (TOWN OF IR…</td>
<td>"CANTWELL et al. v. CONNECTICUT"</td>
<td>84</td>
</tr>
<tr class="even">
<td>"FURMAN v. GEORGIA"</td>
<td>"GREGG v. GEORGIA"</td>
<td>72</td>
</tr>
<tr class="odd">
<td>"LOVELL v. CITY OF GRIFFIN"</td>
<td>"SCHNEIDER v. STATE (TOWN OF IR…</td>
<td>71</td>
</tr>
<tr class="even">
<td>"MEYER v. STATE OF NEBRASKA"</td>
<td>"PIERCE, GOVERNOR OF OREGON, et…</td>
<td>64</td>
</tr>
<tr class="odd">
<td>"SCHNEIDER v. STATE (TOWN OF IR…</td>
<td>"THORNHILL v. ALABAMA"</td>
<td>63</td>
</tr>
<tr class="even">
<td>"LOVELL v. CITY OF GRIFFIN"</td>
<td>"CANTWELL et al. v. CONNECTICUT"</td>
<td>62</td>
</tr>
<tr class="odd">
<td>"BOYD v. UNITED STATES"</td>
<td>"WEEKS v. UNITED STATES"</td>
<td>59</td>
</tr>
<tr class="even">
<td>"NATIONAL ASSOCIATION FOR THE A…</td>
<td>"NATIONAL ASSOCIATION FOR THE A…</td>
<td>59</td>
</tr>
<tr class="odd">
<td>"HAGUE, MAYOR, et al. v. COMMIT…</td>
<td>"SCHNEIDER v. STATE (TOWN OF IR…</td>
<td>58</td>
</tr>
<tr class="even">
<td>"OZIE POWELL, WILLIE ROBERSON, …</td>
<td>"GIDEON v. WAINWRIGHT, CORRECTI…</td>
<td>57</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The top pair is <em>Schneider v. State</em> and <em>Cantwell v. Connecticut</em>, cited together 84 times, two 1939 decisions at the root of modern free-speech and free-exercise doctrine. The rest of the list is the same kind of thing: the leafleting and speech cases (<em>Lovell</em>, <em>Thornhill</em>) that later First Amendment opinions reach for as a block, and the death-penalty pair <em>Furman</em> and <em>Gregg</em>. This is a self-join on a shared value, the join-chapter pattern, used here to turn “who cites whom” into “who gets cited alongside whom.” The chapter notes that on Wikipedia the citation and co-citation networks look nearly the same, because its pages are edited continually and link freely in both directions; on a court record, where an opinion can only cite backward and never forward, the two are genuinely different objects.</p>
<ol start="2" type="1">
<li>Build an undirected network from the co-citation edges. As with any weighted edge list, weak links are mostly noise, so first keep only the pairs cited together at least 15 times, and rename the columns to the <code>doc_id</code>/<code>doc_id2</code> names <code>DSNetwork.process</code> expects. Build the network, join the case names onto the nodes, and then count the nodes in each component before trusting the drawing.</li>
</ol>
<div id="ad7dd6a9" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>cocite_edges <span class="op">=</span> (</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    cocite</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.count <span class="op">&gt;=</span> <span class="dv">15</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    .rename({<span class="st">"cited_case"</span>: <span class="st">"doc_id"</span>, <span class="st">"cited_case_right"</span>: <span class="st">"doc_id2"</span>})</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>co_node, co_edge, co_G <span class="op">=</span> DSNetwork.process(cocite_edges, directed<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>co_node <span class="op">=</span> co_node.join(</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    case.select(c.citation, c.case_name, c.term, c.issue_description),</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    left_on<span class="op">=</span><span class="st">"id"</span>,</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    right_on<span class="op">=</span><span class="st">"citation"</span>,</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    how<span class="op">=</span><span class="st">"left"</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    co_node</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    .group_by(c.component)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    .agg(n <span class="op">=</span> pl.<span class="bu">len</span>(), size <span class="op">=</span> c.component_size.first())</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    .sort(c.component)</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="6">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (3, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">component</th>
<th data-quarto-table-cell-role="th">n</th>
<th data-quarto-table-cell-role="th">size</th>
</tr>
<tr class="even">
<td>i64</td>
<td>u32</td>
<td>i64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>68</td>
<td>68</td>
</tr>
<tr class="even">
<td>2</td>
<td>2</td>
<td>2</td>
</tr>
<tr class="odd">
<td>3</td>
<td>2</td>
<td>2</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Unlike the direct-citation network, which came back as one connected piece, the co-citation network splits into three components: a core of 68 cases and two tiny islands of two cases each. Filtering to <code>count &gt;= 15</code> is what separates them — a pair of cases only reaches the core if it shares a citer with the rest of the set that often. The two islands are worth reading: one is <em>Furman v. Georgia</em> and <em>Gregg v. Georgia</em>, the pair that struck down and then restored the death penalty, and the other is <em>Standard Oil</em> and <em>Socony-Vacuum</em>, two antitrust decisions. Both pairs are heavily co-cited <em>with each other</em> and almost never co-cited with the constitutional-rights core, so they float off on their own. The component check is the same discipline from last notebook: a network can quietly fall apart, and you want to know that before you read a centrality score off it.</p>
<ol start="3" type="1">
<li>Compute eigenvalue centrality on the core. Because centrality is only defined within a component, filter to <code>component == 1</code> first, then print the 10 cases with the highest <code>eigen</code>, showing <code>degree</code> alongside. Compare the top of this list to what the direct-citation network ranked highest last notebook (degree crowned <em>Palko v. Connecticut</em> and the criminal-procedure cases).</li>
</ol>
<div id="d8917c18" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    co_node</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.component <span class="op">==</span> <span class="dv">1</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    .sort(c.eigen, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">10</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    .select(c.case_name, c.term, c.eigen, c.degree)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="7">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (10, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">case_name</th>
<th data-quarto-table-cell-role="th">term</th>
<th data-quarto-table-cell-role="th">eigen</th>
<th data-quarto-table-cell-role="th">degree</th>
</tr>
<tr class="even">
<td>str</td>
<td>i64</td>
<td>f64</td>
<td>i64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"CANTWELL et al. v. CONNECTICUT"</td>
<td>1939</td>
<td>1.0</td>
<td>20</td>
</tr>
<tr class="even">
<td>"SCHNEIDER v. STATE (TOWN OF IR…</td>
<td>1939</td>
<td>0.997488</td>
<td>19</td>
</tr>
<tr class="odd">
<td>"WHITNEY v. CALIFORNIA"</td>
<td>1926</td>
<td>0.96251</td>
<td>17</td>
</tr>
<tr class="even">
<td>"NEW YORK TIMES CO. v. SULLIVAN"</td>
<td>1963</td>
<td>0.956679</td>
<td>17</td>
</tr>
<tr class="odd">
<td>"THORNHILL v. ALABAMA"</td>
<td>1939</td>
<td>0.940897</td>
<td>16</td>
</tr>
<tr class="even">
<td>"WEST VIRGINIA STATE BOARD OF E…</td>
<td>1942</td>
<td>0.92755</td>
<td>19</td>
</tr>
<tr class="odd">
<td>"NATIONAL ASSOCIATION FOR THE A…</td>
<td>1962</td>
<td>0.922516</td>
<td>17</td>
</tr>
<tr class="even">
<td>"NEAR v. MINNESOTA EX REL. OLSO…</td>
<td>1930</td>
<td>0.904015</td>
<td>16</td>
</tr>
<tr class="odd">
<td>"NATIONAL ASSOCIATION FOR THE A…</td>
<td>1957</td>
<td>0.870889</td>
<td>19</td>
</tr>
<tr class="even">
<td>"STROMBERG v. CALIFORNIA"</td>
<td>1930</td>
<td>0.850821</td>
<td>14</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The co-citation core is a different neighborhood of law entirely. Its center is <em>Cantwell v. Connecticut</em>, then <em>Schneider v. State</em>, <em>Whitney v. California</em>, <em>New York Times v. Sullivan</em>, <em>Thornhill v. Alabama</em> — the free-speech and First Amendment cases, not the criminal-procedure cases the direct network put in the middle. The reason is what co-citation measures: these cases keep getting cited <em>together</em> because later free-speech opinions reach for a whole line of precedent at once. Direct citation rewarded <em>Palko</em> for being pointed at often; co-citation rewards a case for being pointed at in company. They are two honest answers to “which case is central,” and they disagree because they are asking different questions.</p>
<ol start="4" type="1">
<li>Now change the other axis: instead of a different <em>definition</em> of an edge, keep the direct-citation edges but respect their <em>direction</em>. Rebuild the top-80 induced edge list from <code>cite</code> and pass it to <code>DSNetwork.process</code> with <code>directed=True</code>. Print the node table. Notice which columns are different from the undirected version.</li>
</ol>
<div id="b5bba643" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>edges <span class="op">=</span> (</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    cite</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.citing_case.is_in(top) <span class="op">&amp;</span> c.cited_case.is_in(top))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    .rename({<span class="st">"citing_case"</span>: <span class="st">"doc_id"</span>, <span class="st">"cited_case"</span>: <span class="st">"doc_id2"</span>})</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>di_node, di_edge, di_G <span class="op">=</span> DSNetwork.process(edges, directed<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>di_node <span class="op">=</span> di_node.join(</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    case.select(c.citation, c.case_name, c.term),</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    left_on<span class="op">=</span><span class="st">"id"</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    right_on<span class="op">=</span><span class="st">"citation"</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    how<span class="op">=</span><span class="st">"left"</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>di_node</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="8">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (77, 13)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">x</th>
<th data-quarto-table-cell-role="th">y</th>
<th data-quarto-table-cell-role="th">component</th>
<th data-quarto-table-cell-role="th">component_size</th>
<th data-quarto-table-cell-role="th">cluster</th>
<th data-quarto-table-cell-role="th">degree_out</th>
<th data-quarto-table-cell-role="th">degree_in</th>
<th data-quarto-table-cell-role="th">degree_total</th>
<th data-quarto-table-cell-role="th">eigen</th>
<th data-quarto-table-cell-role="th">between</th>
<th data-quarto-table-cell-role="th">case_name</th>
<th data-quarto-table-cell-role="th">term</th>
</tr>
<tr class="even">
<td>str</td>
<td>f64</td>
<td>f64</td>
<td>i64</td>
<td>i64</td>
<td>str</td>
<td>i64</td>
<td>i64</td>
<td>i64</td>
<td>null</td>
<td>null</td>
<td>str</td>
<td>i64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"100 U.S. 339"</td>
<td>2.303276</td>
<td>-1.01005</td>
<td>73</td>
<td>1</td>
<td>"0"</td>
<td>2</td>
<td>7</td>
<td>9</td>
<td>null</td>
<td>null</td>
<td>"ex parte VIRGINIA"</td>
<td>1879</td>
</tr>
<tr class="even">
<td>"5 U.S. 137"</td>
<td>0.029459</td>
<td>-0.48376</td>
<td>77</td>
<td>1</td>
<td>"1"</td>
<td>0</td>
<td>8</td>
<td>8</td>
<td>null</td>
<td>null</td>
<td>"WILLIAM MARBURY v. JAMES MADIS…</td>
<td>1803</td>
</tr>
<tr class="odd">
<td>"83 U.S. 36"</td>
<td>1.55479</td>
<td>-2.469824</td>
<td>74</td>
<td>1</td>
<td>"0"</td>
<td>2</td>
<td>8</td>
<td>10</td>
<td>null</td>
<td>null</td>
<td>"SLAUGHTER-HOUSE CASES.; THE BU…</td>
<td>1872</td>
</tr>
<tr class="even">
<td>"110 U.S. 516"</td>
<td>2.1055</td>
<td>-0.389018</td>
<td>71</td>
<td>1</td>
<td>"1"</td>
<td>1</td>
<td>7</td>
<td>8</td>
<td>null</td>
<td>null</td>
<td>"HURTADO v. PEOPLE OF CALIFORNI…</td>
<td>1883</td>
</tr>
<tr class="odd">
<td>"94 U.S. 113"</td>
<td>-0.719777</td>
<td>-1.275068</td>
<td>72</td>
<td>1</td>
<td>"2"</td>
<td>0</td>
<td>7</td>
<td>7</td>
<td>null</td>
<td>null</td>
<td>"MUNN v. ILLINOIS"</td>
<td>1876</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"408 U.S. 238"</td>
<td>1.656494</td>
<td>-0.412495</td>
<td>4</td>
<td>1</td>
<td>"1"</td>
<td>11</td>
<td>2</td>
<td>13</td>
<td>null</td>
<td>null</td>
<td>"FURMAN v. GEORGIA"</td>
<td>1971</td>
</tr>
<tr class="even">
<td>"424 U.S. 1"</td>
<td>0.785636</td>
<td>-0.11364</td>
<td>3</td>
<td>1</td>
<td>"2"</td>
<td>12</td>
<td>0</td>
<td>12</td>
<td>null</td>
<td>null</td>
<td>"BUCKLEY et al. v. VALEO, SECRE…</td>
<td>1975</td>
</tr>
<tr class="odd">
<td>"428 U.S. 153"</td>
<td>3.703865</td>
<td>-0.612873</td>
<td>2</td>
<td>1</td>
<td>"1"</td>
<td>3</td>
<td>1</td>
<td>4</td>
<td>null</td>
<td>null</td>
<td>"GREGG v. GEORGIA"</td>
<td>1975</td>
</tr>
<tr class="even">
<td>"466 U.S. 668"</td>
<td>4.317718</td>
<td>-0.101458</td>
<td>1</td>
<td>1</td>
<td>"1"</td>
<td>6</td>
<td>0</td>
<td>6</td>
<td>null</td>
<td>null</td>
<td>"STRICKLAND, SUPERINTENDENT, FL…</td>
<td>1983</td>
</tr>
<tr class="odd">
<td>"75 U.S. 168"</td>
<td>2.942411</td>
<td>-5.533079</td>
<td>75</td>
<td>1</td>
<td>"8"</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>null</td>
<td>null</td>
<td>null</td>
<td>null</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A directed network reports a different set of measurements. Closeness centrality is gone (it is not well defined once edges point one way), and in place of the single <code>degree</code> column there are now three: <code>degree_out</code>, the number of landmark cases this case cites; <code>degree_in</code>, the number of landmark cases that cite it; and <code>degree_total</code>, their sum. On an undirected network these two directions were blurred together into one number.</p>
<ol start="5" type="1">
<li>Plot in-degree against out-degree, following the chapter’s own directed example. Highlight a handful of well-known cases so the plot has some labels, and add a diagonal line where in-degree equals out-degree. Save the plot and look at it before reading the description.</li>
</ol>
<div id="6fe3ef48" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>highlight <span class="op">=</span> [</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"384 U.S. 436"</span>,   <span class="co"># Miranda v. Arizona</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"372 U.S. 335"</span>,   <span class="co"># Gideon v. Wainwright</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"17 U.S. 316"</span>,    <span class="co"># McCulloch v. Maryland</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"302 U.S. 319"</span>,   <span class="co"># Palko v. Connecticut</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"347 U.S. 483"</span>,   <span class="co"># Brown v. Board of Education</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"424 U.S. 1"</span>      <span class="co"># Buckley v. Valeo</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>di_highlight <span class="op">=</span> di_node.<span class="bu">filter</span>(c.<span class="bu">id</span>.is_in(highlight))</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    di_node</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(c.degree_out, c.degree_in))</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    .geom_point()</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    .geom_text(</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>        aes(label<span class="op">=</span>c.case_name),</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>        data<span class="op">=</span>di_highlight,</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>        size<span class="op">=</span><span class="dv">7</span>,</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>        nudge_y<span class="op">=</span><span class="fl">0.6</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>    .geom_abline(slope<span class="op">=</span><span class="dv">1</span>, intercept<span class="op">=</span><span class="dv">0</span>, linetype<span class="op">=</span><span class="st">"dashed"</span>)</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>    .labs(</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>        title<span class="op">=</span><span class="st">"In-degree vs Out-degree in the SCOTUS Landmark Network"</span>,</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>        x<span class="op">=</span><span class="st">"Out-degree (landmarks this case cites)"</span>,</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>        y<span class="op">=</span><span class="st">"In-degree (landmarks that cite this case)"</span></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>
<figure class="figure">
<p><a href="notebook46_files/figure-html/cell-11-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="notebook46_files/figure-html/cell-11-output-1.png" width="672" height="480" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p>The middle of the cloud is balanced, but the corners are pulled apart by era. The oldest foundational cases sit at the top-left, cited by many later landmarks but citing almost none: <em>McCulloch</em> (1819) cites none of the others while eight cite it, and <em>Palko</em> (1937) cites five while eighteen cite it. The most recent cases sit at the bottom-right: <em>Buckley v. Valeo</em> (1976) cites twelve other landmarks and is cited by none. A citation can only point backward in time, so on a set of cases spanning 150 years a case’s drift off the diagonal tracks when it was decided. The chapter’s Wikipedia version showed no such tilt, because its pages carry no fixed order to cite in.</p>
<ol start="6" type="1">
<li>Put a number on that. Compute the correlation between a case’s <code>term</code> and its out-degree, and between its <code>term</code> and its in-degree. Then count how many cases have an out-degree of exactly zero.</li>
</ol>
<div id="3010b534" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>di_node.select(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    corr_term_out <span class="op">=</span> pl.corr(c.term, c.degree_out),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    corr_term_in <span class="op">=</span> pl.corr(c.term, c.degree_in),</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    n_zero_out <span class="op">=</span> (c.degree_out <span class="op">==</span> <span class="dv">0</span>).<span class="bu">sum</span>()</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="10">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (1, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">corr_term_out</th>
<th data-quarto-table-cell-role="th">corr_term_in</th>
<th data-quarto-table-cell-role="th">n_zero_out</th>
</tr>
<tr class="even">
<td>f64</td>
<td>f64</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.627985</td>
<td>-0.251553</td>
<td>10</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Term and out-degree correlate at 0.63: the later a case, the more earlier landmarks it can and does cite. Term and in-degree correlate at −0.25, the opposite sign, for the same reason in reverse — an old case has had a century to accumulate citations from the rest of the set. Ten cases cite none of the other 79, and reading them back they are the oldest in the corpus, decided before there was a landmark canon to cite. This is the property the chapter says its Wikipedia network cannot show, because “there is no clear temporal ordering of the pages.” A court has nothing <em>but</em> temporal ordering, and it falls straight out of the degree counts.</p>
<ol start="7" type="1">
<li>The last two networks come from <em>distances</em> rather than citations. We have no text for these cases, so we build a distance from the citation structure itself: represent each case by the set of later cases that cite it, and call two cases close when those sets of citers overlap. Concretely, build a matrix with one row per landmark and one column per citing case, holding 1 where the citation exists, and compute the angle distance between every pair of rows — the same <code>to_numpy</code>/normalize/<code>arccos</code> construction the text chapter used for its own distances. Print the six closest pairs.</li>
</ol>
<div id="2929845a" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>profile <span class="op">=</span> (</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    cite</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.cited_case.is_in(top))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    .select(c.cited_case, c.citing_case)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    .with_columns(present <span class="op">=</span> pl.lit(<span class="dv">1</span>))</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    .pivot(on<span class="op">=</span><span class="st">"citing_case"</span>, index<span class="op">=</span><span class="st">"cited_case"</span>, values<span class="op">=</span><span class="st">"present"</span>, aggregate_function<span class="op">=</span><span class="st">"first"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    .fill_null(<span class="dv">0</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    .sort(<span class="st">"cited_case"</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>ids <span class="op">=</span> profile.get_column(<span class="st">"cited_case"</span>).to_list()</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> profile.drop(<span class="st">"cited_case"</span>).to_numpy().astype(<span class="bu">float</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> X <span class="op">/</span> np.linalg.norm(X, axis<span class="op">=</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>angles <span class="op">=</span> np.arccos(np.clip(X <span class="op">@</span> X.T, <span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>dist <span class="op">=</span> (</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    pl.DataFrame(angles, schema<span class="op">=</span>[<span class="bu">str</span>(i) <span class="cf">for</span> i <span class="kw">in</span> ids])</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>    .with_columns(doc_id <span class="op">=</span> pl.Series(ids))</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>    .unpivot(index<span class="op">=</span><span class="st">"doc_id"</span>, variable_name<span class="op">=</span><span class="st">"doc_id2"</span>, value_name<span class="op">=</span><span class="st">"distance"</span>)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.doc_id <span class="op">&lt;</span> c.doc_id2)</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>    dist</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>    .sort(c.distance)</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">6</span>)</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>    .join(case.select(c.citation, name_a<span class="op">=</span>c.case_name), left_on<span class="op">=</span><span class="st">"doc_id"</span>, right_on<span class="op">=</span><span class="st">"citation"</span>, how<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>    .join(case.select(c.citation, name_b<span class="op">=</span>c.case_name), left_on<span class="op">=</span><span class="st">"doc_id2"</span>, right_on<span class="op">=</span><span class="st">"citation"</span>, how<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>    .select(c.name_a, c.name_b, c.distance)</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="11">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (6, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">name_a</th>
<th data-quarto-table-cell-role="th">name_b</th>
<th data-quarto-table-cell-role="th">distance</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"FURMAN v. GEORGIA"</td>
<td>"GREGG v. GEORGIA"</td>
<td>0.846526</td>
</tr>
<tr class="even">
<td>"MEYER v. STATE OF NEBRASKA"</td>
<td>"PIERCE, GOVERNOR OF OREGON, et…</td>
<td>0.962523</td>
</tr>
<tr class="odd">
<td>"LOVELL v. CITY OF GRIFFIN"</td>
<td>"SCHNEIDER v. STATE (TOWN OF IR…</td>
<td>0.965771</td>
</tr>
<tr class="even">
<td>"SCHNEIDER v. STATE (TOWN OF IR…</td>
<td>"CANTWELL et al. v. CONNECTICUT"</td>
<td>1.034735</td>
</tr>
<tr class="odd">
<td>"HAGUE, MAYOR, et al. v. COMMIT…</td>
<td>"SCHNEIDER v. STATE (TOWN OF IR…</td>
<td>1.110559</td>
</tr>
<tr class="even">
<td>"LOVELL v. CITY OF GRIFFIN"</td>
<td>"CANTWELL et al. v. CONNECTICUT"</td>
<td>1.110799</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The closest pairs are ones a reader can check by eye. <em>Furman</em> and <em>Gregg</em>, the death-penalty pair again, are nearest of all at 0.85. Next are <em>Meyer v. Nebraska</em> and <em>Pierce v. Society of Sisters</em>, the two 1920s substantive-due- process cases about parents’ control over their children’s schooling, and then a run of the free-speech leafleting cases (<em>Lovell</em>, <em>Schneider</em>, <em>Cantwell</em>). The distance found real doctrinal pairs without ever being told what any case is about, only who cites it — which is exactly the spot-check-against-something-you- know the chapter asks for before trusting an embedding or a distance.</p>
<ol start="8" type="1">
<li>Before building a distance network, look at the distances themselves. Print the smallest and mean distance, and count how many of the pairs sit exactly at the maximum possible angle distance of π/2. Then, following the chapter, build a distance network by keeping every pair closer than a cutoff, and check how many components it lands in.</li>
</ol>
<div id="c46edfd5" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    dist.select(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>        smallest <span class="op">=</span> c.distance.<span class="bu">min</span>(),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>        mean <span class="op">=</span> c.distance.mean(),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>        n_orthogonal <span class="op">=</span> (c.distance <span class="op">&gt;</span> <span class="fl">1.5707</span>).<span class="bu">sum</span>(),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>        n_pairs <span class="op">=</span> pl.<span class="bu">len</span>()</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>dist_edges <span class="op">=</span> (</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    dist</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.distance <span class="op">&lt;</span> <span class="fl">1.4</span>)</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    .select(c.doc_id, c.doc_id2)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>dn_node, dn_edge, dn_G <span class="op">=</span> DSNetwork.process(dist_edges, directed<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>dn_node.group_by(c.component).agg(n <span class="op">=</span> pl.<span class="bu">len</span>()).sort(c.n, descending<span class="op">=</span><span class="va">True</span>).head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>shape: (1, 4)
┌──────────┬──────────┬──────────────┬─────────┐
│ smallest ┆ mean     ┆ n_orthogonal ┆ n_pairs │
│ ---      ┆ ---      ┆ ---          ┆ ---     │
│ f64      ┆ f64      ┆ u32          ┆ u32     │
╞══════════╪══════════╪══════════════╪═════════╡
│ 0.846526 ┆ 1.533037 ┆ 829          ┆ 3160    │
└──────────┴──────────┴──────────────┴─────────┘</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (5, 2)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">component</th>
<th data-quarto-table-cell-role="th">n</th>
</tr>
<tr class="even">
<td>i64</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5</td>
<td>22</td>
</tr>
<tr class="even">
<td>3</td>
<td>19</td>
</tr>
<tr class="odd">
<td>1</td>
<td>4</td>
</tr>
<tr class="even">
<td>4</td>
<td>3</td>
</tr>
<tr class="odd">
<td>6</td>
<td>2</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The mean distance is 1.53, almost the π/2 maximum, and 829 of the 3,160 pairs — better than a quarter — sit <em>exactly</em> at π/2, meaning they share no citer at all. This is the same crowding-against-the-maximum we saw with sparse text vectors: when each case has hundreds of citers spread across thousands of possible citing cases, almost any two of them are nearly orthogonal. A fixed distance cutoff is a blunt instrument here. Set it at 1.4 and the network shatters into a dozen disconnected pieces; nudge it to 1.5 and nearly every pair becomes an edge at once. There is no cutoff that gives a single readable network, because the distances are all bunched at one end. The next section fixes this by ranking neighbors instead of thresholding them.</p>
<ol start="9" type="1">
<li>A <em>symmetric nearest-neighbor</em> network sidesteps the cutoff problem. For each case, take its k closest neighbors, and keep an edge only when two cases are <em>mutually</em> in each other’s top k. Because the rule is per-case, a popular case cannot collect more than k edges, and the network can never have a degree above</li>
</ol>
<ol start="11" type="a">
<li>Build it with <code>k = 5</code>. Since your <code>dist</code> table has each pair once, first stack it with a copy of itself with the two columns swapped so every case sees all of its neighbors, take the 5 nearest per case, and keep only the pairs that appear from both directions.</li>
</ol>
<div id="92068abf" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>both <span class="op">=</span> pl.concat([</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    dist.select(c.doc_id, c.doc_id2, c.distance),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    dist.select(doc_id<span class="op">=</span>c.doc_id2, doc_id2<span class="op">=</span>c.doc_id, distance<span class="op">=</span>c.distance)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>knn <span class="op">=</span> (</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    both</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    .sort([c.doc_id, c.distance])</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    .group_by(c.doc_id, maintain_order<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    .head(k)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    .select(c.doc_id, c.doc_id2)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>nn_edges <span class="op">=</span> (</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    knn</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    .with_columns(</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>        a <span class="op">=</span> pl.min_horizontal(c.doc_id, c.doc_id2),</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>        b <span class="op">=</span> pl.max_horizontal(c.doc_id, c.doc_id2)</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>    .group_by([c.a, c.b])</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>    .agg(mutual <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.mutual <span class="op">==</span> <span class="dv">2</span>)</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>    .select(doc_id<span class="op">=</span>c.a, doc_id2<span class="op">=</span>c.b)</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>nn_node, nn_edge, nn_G <span class="op">=</span> DSNetwork.process(nn_edges, directed<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>nn_node <span class="op">=</span> nn_node.join(</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>    case.select(c.citation, c.case_name, c.term),</span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>    left_on<span class="op">=</span><span class="st">"id"</span>,</span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>    right_on<span class="op">=</span><span class="st">"citation"</span>,</span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>    how<span class="op">=</span><span class="st">"left"</span></span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a>nn_node.select(</span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a>    n_nodes <span class="op">=</span> pl.<span class="bu">len</span>(),</span>
<span id="cb14-39"><a href="#cb14-39" aria-hidden="true" tabindex="-1"></a>    n_components <span class="op">=</span> c.component.<span class="bu">max</span>(),</span>
<span id="cb14-40"><a href="#cb14-40" aria-hidden="true" tabindex="-1"></a>    max_degree <span class="op">=</span> c.degree.<span class="bu">max</span>(),</span>
<span id="cb14-41"><a href="#cb14-41" aria-hidden="true" tabindex="-1"></a>    mean_degree <span class="op">=</span> c.degree.mean().<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb14-42"><a href="#cb14-42" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="13">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (1, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">n_nodes</th>
<th data-quarto-table-cell-role="th">n_components</th>
<th data-quarto-table-cell-role="th">max_degree</th>
<th data-quarto-table-cell-role="th">mean_degree</th>
</tr>
<tr class="even">
<td>u32</td>
<td>i64</td>
<td>i64</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>77</td>
<td>1</td>
<td>5</td>
<td>3.22</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Where the fixed cutoff either fragmented or overconnected the network, the nearest-neighbor rule lands on a single connected component of all 77 cases with a maximum degree of exactly 5 — no case, however heavily cited, is allowed more than its five mutual neighbors. The <code>mutual == 2</code> filter is the “each direction counts once” trick: a pair survives only if it turned up when we took <em>A</em>’s neighbors and again when we took <em>B</em>’s.</p>
<ol start="10" type="1">
<li>The chapter’s central claim about nearest-neighbor networks is that eigenvalue and betweenness centrality, usually tightly correlated, come apart in this network type. Test it. Compute the correlation between <code>eigen</code> and <code>between</code> for the nearest-neighbor network, and for comparison, do the same on the direct-citation network from question 4’s edges (rebuilt undirected). Then print the nearest-neighbor network’s top cases by betweenness, with their eigenvalue alongside.</li>
</ol>
<div id="c207b4cc" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>un_node, un_edge, un_G <span class="op">=</span> DSNetwork.process(edges, directed<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"direct-citation:"</span>, un_node.<span class="bu">filter</span>(c.component <span class="op">==</span> <span class="dv">1</span>).select(pl.corr(c.eigen, c.between)).item())</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"nearest-neighbor:"</span>, nn_node.<span class="bu">filter</span>(c.component <span class="op">==</span> <span class="dv">1</span>).select(pl.corr(c.eigen, c.between)).item())</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    nn_node</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    .sort(c.between, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">6</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    .select(c.case_name, c.term, c.between, c.eigen, c.degree)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>direct-citation: 0.37150521319388724
nearest-neighbor: -0.14154213148713918</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (6, 5)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">case_name</th>
<th data-quarto-table-cell-role="th">term</th>
<th data-quarto-table-cell-role="th">between</th>
<th data-quarto-table-cell-role="th">eigen</th>
<th data-quarto-table-cell-role="th">degree</th>
</tr>
<tr class="even">
<td>str</td>
<td>i64</td>
<td>f64</td>
<td>f64</td>
<td>i64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"BROWN et al. v. BOARD OF EDUCA…</td>
<td>1953</td>
<td>1287.933333</td>
<td>0.001482</td>
<td>4</td>
</tr>
<tr class="even">
<td>"HURTADO v. PEOPLE OF CALIFORNI…</td>
<td>1883</td>
<td>1235.75</td>
<td>0.014941</td>
<td>5</td>
</tr>
<tr class="odd">
<td>"MEYER v. STATE OF NEBRASKA"</td>
<td>1922</td>
<td>1189.0</td>
<td>0.000391</td>
<td>3</td>
</tr>
<tr class="even">
<td>"ex parte VIRGINIA"</td>
<td>1879</td>
<td>1095.833333</td>
<td>0.003241</td>
<td>5</td>
</tr>
<tr class="odd">
<td>"PIERCE, GOVERNOR OF OREGON, et…</td>
<td>1924</td>
<td>962.5</td>
<td>0.000118</td>
<td>3</td>
</tr>
<tr class="even">
<td>"WEST VIRGINIA STATE BOARD OF E…</td>
<td>1942</td>
<td>960.0</td>
<td>0.000051</td>
<td>3</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>On the direct-citation network the two measures correlate at 0.37; on the nearest-neighbor network they correlate at −0.14, effectively unrelated. The top of the betweenness list shows why. <em>Brown v. Board of Education</em> has the highest betweenness in the whole network but an eigenvalue near zero — it has only four neighbors, and none of them is central, yet it sits on the shortest path between whole regions of the network. These are the gatekeeper nodes the chapter describes: cases that bridge otherwise separate lines of doctrine without being deeply embedded in any one of them. The direct-citation network could not show this because its most-bridging cases were also its most-cited; balancing the degree pulls the two apart.</p>
<ol start="11" type="1">
<li>Finally, read the communities the nearest-neighbor network found. Color the network by <code>cluster</code>, and print each cluster’s members. Check whether the groups correspond to recognizable areas of law rather than falling out arbitrarily.</li>
</ol>
<div id="5e636766" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    nn_node</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(c.x, c.y))</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    .geom_segment(</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>        aes(x<span class="op">=</span>c.x, y<span class="op">=</span>c.y, xend<span class="op">=</span>c.xend, yend<span class="op">=</span>c.yend),</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>        data<span class="op">=</span>nn_edge,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>        alpha<span class="op">=</span><span class="fl">0.2</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    .geom_point(aes(color<span class="op">=</span>c.cluster), size<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    .theme_void()</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    .labs(title<span class="op">=</span><span class="st">"Nearest-Neighbor Network by Cluster"</span>, color<span class="op">=</span><span class="st">"Cluster"</span>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>
<figure class="figure">
<p><a href="notebook46_files/figure-html/cell-17-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="notebook46_files/figure-html/cell-17-output-1.png" width="672" height="480" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
<div id="0e193fae" class="cell" data-execution_count="17">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    nn_node</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    .group_by(c.cluster)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    .agg(members <span class="op">=</span> c.case_name.<span class="bu">str</span>.join(<span class="st">"; "</span>))</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    .sort(c.cluster)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="16">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (12, 2)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">cluster</th>
<th data-quarto-table-cell-role="th">members</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"0"</td>
<td>"NATIONAL ASSOCIATION FOR THE A…</td>
</tr>
<tr class="even">
<td>"1"</td>
<td>"WEEKS v. UNITED STATES; MAPP v…</td>
</tr>
<tr class="odd">
<td>"10"</td>
<td>"THE STANDARD OIL COMPANY OF NE…</td>
</tr>
<tr class="even">
<td>"11"</td>
<td>"ERIE RAILROAD CO. v. TOMPKINS;…</td>
</tr>
<tr class="odd">
<td>"2"</td>
<td>"JOHNSON v. ZERBST, WARDEN; GID…</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"5"</td>
<td>"WILLIAM MARBURY v. JAMES MADIS…</td>
</tr>
<tr class="even">
<td>"6"</td>
<td>"CHAPLINSKY v. NEW HAMPSHIRE; S…</td>
</tr>
<tr class="odd">
<td>"7"</td>
<td>"MONROE et al. v. PAPE et al.; …</td>
</tr>
<tr class="even">
<td>"8"</td>
<td>"SECOND EMPLOYERS' LIABILITY CA…</td>
</tr>
<tr class="odd">
<td>"9"</td>
<td>"FURMAN v. GEORGIA; GREGG v. GE…</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The clusters are cleaner and more even in size than the direct network’s, which is the payoff the chapter promises for balancing the degree. One cluster is the Fourth Amendment search-and-seizure line (<em>Weeks</em>, <em>Carroll</em>, <em>Olmstead</em>, <em>Katz</em>, <em>Mapp</em>); another is the incorporation cases that asked which parts of the Bill of Rights bind the states (<em>Hurtado</em>, <em>Palko</em>, <em>Malloy</em>, <em>Duncan</em>); another the free-speech leafleting cases; the antitrust pair and the death- penalty pair each hold together as their own small groups. None of this was labeled — the network was handed nothing but who cites whom — yet the walktrap communities recover the syllabus of a constitutional-law course.</p>
<ol start="12" type="1">
<li><strong>Written question.</strong> This notebook built four different networks from one edge list: last notebook’s direct-citation network and this notebook’s co-citation, directed, and nearest-neighbor networks. In two or three sentences, say which network you would reach for to answer each of these questions, and why: (a) which case is the single most influential precedent; (b) which two doctrines a court treats as related; (c) which case quietly bridges otherwise separate lines of law. Note that the same 80 cases gave a different answer under each network, which is the chapter’s real point: the network you build is a choice, and it decides what you are able to see.</li>
</ol>
<p>The direct-citation network answers (a): raw and eigenvalue centrality on who cites whom is the natural measure of a precedent’s pull. The co-citation network answers (b), since its whole construction is “cited together,” and its components landed exactly on doctrinal families like the death-penalty and antitrust pairs. The nearest-neighbor network answers (c): only after balancing the degree did betweenness separate from eigenvalue and surface bridge cases like <em>Brown v. Board</em> that every other network buried among the hubs. The directed network, meanwhile, added the one thing none of the undirected versions could — the arrow of time, which on a court record is legible in the degree counts alone.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script>
document.addEventListener('DOMContentLoaded', function() {
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details .sourceCode");
      for (let i = 0; i < detailsSrc.length; i++) {
        const details = detailsSrc[i].closest('details');
        if (details) {
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
      }
      return false;
    };
  }
  // Replace buttons to strip the broken listeners Quarto attached, then re-add fixed ones
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    const fresh = hideAllCode.cloneNode(true);
    hideAllCode.parentNode.replaceChild(fresh, hideAllCode);
    fresh.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    const fresh = showAllCode.cloneNode(true);
    showAllCode.parentNode.replaceChild(fresh, showAllCode);
    fresh.addEventListener("click", toggleCodeHandler(true));
  }
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Notebook46"</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="an">solutions-release-date:</span><span class="co"> "2026-11-04"</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">### Setup</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>Run all of the following before starting the notebook.</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [noclear]</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a><span class="op">!</span> wget <span class="op">-</span>q <span class="op">-</span>nc https:<span class="op">//</span>raw.githubusercontent.com<span class="op">/</span>taylor<span class="op">-</span>arnold<span class="op">/</span>fds2<span class="op">/</span>refs<span class="op">/</span>heads<span class="op">/</span>main<span class="op">/</span>funs.py</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [noclear]</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotnine <span class="im">import</span> ggplot, aes, arrow</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> polars <span class="im">import</span> col <span class="im">as</span> c</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> funs</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> funs <span class="im">import</span> DSNetwork</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>ub <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/taylor-arnold/fds2/refs/heads/main/"</span></span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [remove]</span></span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a>ub <span class="op">=</span> <span class="st">""</span></span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-43"><a href="#cb19-43" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-44"><a href="#cb19-44" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [noclear]</span></span>
<span id="cb19-45"><a href="#cb19-45" aria-hidden="true" tabindex="-1"></a>case <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/scotus_case.csv"</span>)</span>
<span id="cb19-46"><a href="#cb19-46" aria-hidden="true" tabindex="-1"></a>cite <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/scotus_citation.csv"</span>)</span>
<span id="cb19-47"><a href="#cb19-47" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-48"><a href="#cb19-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-49"><a href="#cb19-49" aria-hidden="true" tabindex="-1"></a><span class="fu">### Questions</span></span>
<span id="cb19-50"><a href="#cb19-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-51"><a href="#cb19-51" aria-hidden="true" tabindex="-1"></a>This notebook continues with the U.S. Supreme Court citation network from the</span>
<span id="cb19-52"><a href="#cb19-52" aria-hidden="true" tabindex="-1"></a>previous notebook. A row of <span class="in">`case`</span> is one decided case, keyed by its reporter</span>
<span id="cb19-53"><a href="#cb19-53" aria-hidden="true" tabindex="-1"></a><span class="in">`citation`</span> (<span class="in">`"384 U.S. 436"`</span> is *Miranda v. Arizona*), with a <span class="in">`case_name`</span>, the</span>
<span id="cb19-54"><a href="#cb19-54" aria-hidden="true" tabindex="-1"></a><span class="in">`term`</span> it was argued, and the coded <span class="in">`issue_description`</span> and <span class="in">`lean`</span>. A row of</span>
<span id="cb19-55"><a href="#cb19-55" aria-hidden="true" tabindex="-1"></a><span class="in">`cite`</span> is one precedent link: <span class="in">`citing_case`</span> refers to the earlier <span class="in">`cited_case`</span></span>
<span id="cb19-56"><a href="#cb19-56" aria-hidden="true" tabindex="-1"></a>somewhere in its opinion. Last time we built one network, the direct-citation</span>
<span id="cb19-57"><a href="#cb19-57" aria-hidden="true" tabindex="-1"></a>network of the 80 most-cited cases, and measured its centrality. This time we</span>
<span id="cb19-58"><a href="#cb19-58" aria-hidden="true" tabindex="-1"></a>build three *other* kinds of network from the same edge list — a co-citation</span>
<span id="cb19-59"><a href="#cb19-59" aria-hidden="true" tabindex="-1"></a>network, a directed network, and a nearest-neighbor network — and see what each</span>
<span id="cb19-60"><a href="#cb19-60" aria-hidden="true" tabindex="-1"></a>one shows that the direct network could not. The book's own examples for these</span>
<span id="cb19-61"><a href="#cb19-61" aria-hidden="true" tabindex="-1"></a>sections use a Wikipedia author corpus, which it warns is too small and too</span>
<span id="cb19-62"><a href="#cb19-62" aria-hidden="true" tabindex="-1"></a>temporally scrambled to bring out the differences; a court is neither. Print</span>
<span id="cb19-63"><a href="#cb19-63" aria-hidden="true" tabindex="-1"></a>your results unless a question says to save them.</span>
<span id="cb19-64"><a href="#cb19-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-65"><a href="#cb19-65" aria-hidden="true" tabindex="-1"></a>We start, as before, by fixing the 80 most-cited cases so every network below</span>
<span id="cb19-66"><a href="#cb19-66" aria-hidden="true" tabindex="-1"></a>is built on the same set of nodes.</span>
<span id="cb19-67"><a href="#cb19-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-70"><a href="#cb19-70" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-71"><a href="#cb19-71" aria-hidden="true" tabindex="-1"></a>top <span class="op">=</span> (</span>
<span id="cb19-72"><a href="#cb19-72" aria-hidden="true" tabindex="-1"></a>    cite</span>
<span id="cb19-73"><a href="#cb19-73" aria-hidden="true" tabindex="-1"></a>    .group_by(c.cited_case)</span>
<span id="cb19-74"><a href="#cb19-74" aria-hidden="true" tabindex="-1"></a>    .agg(n_in <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb19-75"><a href="#cb19-75" aria-hidden="true" tabindex="-1"></a>    .sort([c.n_in, c.cited_case], descending<span class="op">=</span>[<span class="va">True</span>, <span class="va">False</span>])</span>
<span id="cb19-76"><a href="#cb19-76" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">80</span>)</span>
<span id="cb19-77"><a href="#cb19-77" aria-hidden="true" tabindex="-1"></a>    .get_column(<span class="st">"cited_case"</span>)</span>
<span id="cb19-78"><a href="#cb19-78" aria-hidden="true" tabindex="-1"></a>    .to_list()</span>
<span id="cb19-79"><a href="#cb19-79" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-80"><a href="#cb19-80" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-81"><a href="#cb19-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-82"><a href="#cb19-82" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>The direct-citation network joins two cases when one cites the other. A</span>
<span id="cb19-83"><a href="#cb19-83" aria-hidden="true" tabindex="-1"></a>*co-citation* network joins two cases when some third case cites *both* of them:</span>
<span id="cb19-84"><a href="#cb19-84" aria-hidden="true" tabindex="-1"></a>the idea is that a later court reaching for two precedents in the same opinion</span>
<span id="cb19-85"><a href="#cb19-85" aria-hidden="true" tabindex="-1"></a>is treating them as related. Build the co-citation edge list from <span class="in">`cite`</span> by</span>
<span id="cb19-86"><a href="#cb19-86" aria-hidden="true" tabindex="-1"></a>joining the citation table to itself on <span class="in">`citing_case`</span>, keeping only the rows</span>
<span id="cb19-87"><a href="#cb19-87" aria-hidden="true" tabindex="-1"></a>where both cited cases are in the top 80. Keep each unordered pair once with</span>
<span id="cb19-88"><a href="#cb19-88" aria-hidden="true" tabindex="-1"></a><span class="in">`c.cited_case &lt; c.cited_case_right`</span>, count how many third cases cite both, and</span>
<span id="cb19-89"><a href="#cb19-89" aria-hidden="true" tabindex="-1"></a>print the 10 pairs cited together most often. Join the names in so the pairs are</span>
<span id="cb19-90"><a href="#cb19-90" aria-hidden="true" tabindex="-1"></a>readable.</span>
<span id="cb19-91"><a href="#cb19-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-94"><a href="#cb19-94" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-95"><a href="#cb19-95" aria-hidden="true" tabindex="-1"></a>cc <span class="op">=</span> cite.<span class="bu">filter</span>(c.cited_case.is_in(top))</span>
<span id="cb19-96"><a href="#cb19-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-97"><a href="#cb19-97" aria-hidden="true" tabindex="-1"></a>cocite <span class="op">=</span> (</span>
<span id="cb19-98"><a href="#cb19-98" aria-hidden="true" tabindex="-1"></a>    cc</span>
<span id="cb19-99"><a href="#cb19-99" aria-hidden="true" tabindex="-1"></a>    .join(cc, on<span class="op">=</span><span class="st">"citing_case"</span>)</span>
<span id="cb19-100"><a href="#cb19-100" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.cited_case <span class="op">&lt;</span> c.cited_case_right)</span>
<span id="cb19-101"><a href="#cb19-101" aria-hidden="true" tabindex="-1"></a>    .group_by([c.cited_case, c.cited_case_right])</span>
<span id="cb19-102"><a href="#cb19-102" aria-hidden="true" tabindex="-1"></a>    .agg(count <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb19-103"><a href="#cb19-103" aria-hidden="true" tabindex="-1"></a>    .sort(c.count, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-104"><a href="#cb19-104" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-105"><a href="#cb19-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-106"><a href="#cb19-106" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb19-107"><a href="#cb19-107" aria-hidden="true" tabindex="-1"></a>    cocite</span>
<span id="cb19-108"><a href="#cb19-108" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">10</span>)</span>
<span id="cb19-109"><a href="#cb19-109" aria-hidden="true" tabindex="-1"></a>    .join(</span>
<span id="cb19-110"><a href="#cb19-110" aria-hidden="true" tabindex="-1"></a>        case.select(c.citation, name_a<span class="op">=</span>c.case_name),</span>
<span id="cb19-111"><a href="#cb19-111" aria-hidden="true" tabindex="-1"></a>        left_on<span class="op">=</span><span class="st">"cited_case"</span>,</span>
<span id="cb19-112"><a href="#cb19-112" aria-hidden="true" tabindex="-1"></a>        right_on<span class="op">=</span><span class="st">"citation"</span>,</span>
<span id="cb19-113"><a href="#cb19-113" aria-hidden="true" tabindex="-1"></a>        how<span class="op">=</span><span class="st">"left"</span></span>
<span id="cb19-114"><a href="#cb19-114" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb19-115"><a href="#cb19-115" aria-hidden="true" tabindex="-1"></a>    .join(</span>
<span id="cb19-116"><a href="#cb19-116" aria-hidden="true" tabindex="-1"></a>        case.select(c.citation, name_b<span class="op">=</span>c.case_name),</span>
<span id="cb19-117"><a href="#cb19-117" aria-hidden="true" tabindex="-1"></a>        left_on<span class="op">=</span><span class="st">"cited_case_right"</span>,</span>
<span id="cb19-118"><a href="#cb19-118" aria-hidden="true" tabindex="-1"></a>        right_on<span class="op">=</span><span class="st">"citation"</span>,</span>
<span id="cb19-119"><a href="#cb19-119" aria-hidden="true" tabindex="-1"></a>        how<span class="op">=</span><span class="st">"left"</span></span>
<span id="cb19-120"><a href="#cb19-120" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb19-121"><a href="#cb19-121" aria-hidden="true" tabindex="-1"></a>    .select(c.name_a, c.name_b, c.count)</span>
<span id="cb19-122"><a href="#cb19-122" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-123"><a href="#cb19-123" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-124"><a href="#cb19-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-125"><a href="#cb19-125" aria-hidden="true" tabindex="-1"></a>The top pair is *Schneider v. State* and *Cantwell v. Connecticut*, cited</span>
<span id="cb19-126"><a href="#cb19-126" aria-hidden="true" tabindex="-1"></a>together 84 times, two 1939 decisions at the root of modern free-speech and</span>
<span id="cb19-127"><a href="#cb19-127" aria-hidden="true" tabindex="-1"></a>free-exercise doctrine. The rest of the list is the same kind of thing: the</span>
<span id="cb19-128"><a href="#cb19-128" aria-hidden="true" tabindex="-1"></a>leafleting and speech cases (*Lovell*, *Thornhill*) that later First Amendment</span>
<span id="cb19-129"><a href="#cb19-129" aria-hidden="true" tabindex="-1"></a>opinions reach for as a block, and the death-penalty pair *Furman* and *Gregg*.</span>
<span id="cb19-130"><a href="#cb19-130" aria-hidden="true" tabindex="-1"></a>This is a self-join on a shared value, the join-chapter pattern, used here to</span>
<span id="cb19-131"><a href="#cb19-131" aria-hidden="true" tabindex="-1"></a>turn "who cites whom" into "who gets cited alongside whom." The chapter notes</span>
<span id="cb19-132"><a href="#cb19-132" aria-hidden="true" tabindex="-1"></a>that on</span>
<span id="cb19-133"><a href="#cb19-133" aria-hidden="true" tabindex="-1"></a>Wikipedia the citation and co-citation networks look nearly the same, because</span>
<span id="cb19-134"><a href="#cb19-134" aria-hidden="true" tabindex="-1"></a>its pages are edited continually and link freely in both directions; on a court</span>
<span id="cb19-135"><a href="#cb19-135" aria-hidden="true" tabindex="-1"></a>record, where an opinion can only cite backward and never forward, the two are</span>
<span id="cb19-136"><a href="#cb19-136" aria-hidden="true" tabindex="-1"></a>genuinely different objects.</span>
<span id="cb19-137"><a href="#cb19-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-138"><a href="#cb19-138" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Build an undirected network from the co-citation edges. As with any weighted</span>
<span id="cb19-139"><a href="#cb19-139" aria-hidden="true" tabindex="-1"></a>edge list, weak links are mostly noise, so first keep only the pairs cited</span>
<span id="cb19-140"><a href="#cb19-140" aria-hidden="true" tabindex="-1"></a>together at least 15 times, and rename the columns to the <span class="in">`doc_id`</span>/<span class="in">`doc_id2`</span></span>
<span id="cb19-141"><a href="#cb19-141" aria-hidden="true" tabindex="-1"></a>names <span class="in">`DSNetwork.process`</span> expects. Build the network, join the case names onto</span>
<span id="cb19-142"><a href="#cb19-142" aria-hidden="true" tabindex="-1"></a>the nodes, and then count the nodes in each component before trusting the</span>
<span id="cb19-143"><a href="#cb19-143" aria-hidden="true" tabindex="-1"></a>drawing.</span>
<span id="cb19-144"><a href="#cb19-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-147"><a href="#cb19-147" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-148"><a href="#cb19-148" aria-hidden="true" tabindex="-1"></a>cocite_edges <span class="op">=</span> (</span>
<span id="cb19-149"><a href="#cb19-149" aria-hidden="true" tabindex="-1"></a>    cocite</span>
<span id="cb19-150"><a href="#cb19-150" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.count <span class="op">&gt;=</span> <span class="dv">15</span>)</span>
<span id="cb19-151"><a href="#cb19-151" aria-hidden="true" tabindex="-1"></a>    .rename({<span class="st">"cited_case"</span>: <span class="st">"doc_id"</span>, <span class="st">"cited_case_right"</span>: <span class="st">"doc_id2"</span>})</span>
<span id="cb19-152"><a href="#cb19-152" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-153"><a href="#cb19-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-154"><a href="#cb19-154" aria-hidden="true" tabindex="-1"></a>co_node, co_edge, co_G <span class="op">=</span> DSNetwork.process(cocite_edges, directed<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb19-155"><a href="#cb19-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-156"><a href="#cb19-156" aria-hidden="true" tabindex="-1"></a>co_node <span class="op">=</span> co_node.join(</span>
<span id="cb19-157"><a href="#cb19-157" aria-hidden="true" tabindex="-1"></a>    case.select(c.citation, c.case_name, c.term, c.issue_description),</span>
<span id="cb19-158"><a href="#cb19-158" aria-hidden="true" tabindex="-1"></a>    left_on<span class="op">=</span><span class="st">"id"</span>,</span>
<span id="cb19-159"><a href="#cb19-159" aria-hidden="true" tabindex="-1"></a>    right_on<span class="op">=</span><span class="st">"citation"</span>,</span>
<span id="cb19-160"><a href="#cb19-160" aria-hidden="true" tabindex="-1"></a>    how<span class="op">=</span><span class="st">"left"</span></span>
<span id="cb19-161"><a href="#cb19-161" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-162"><a href="#cb19-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-163"><a href="#cb19-163" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb19-164"><a href="#cb19-164" aria-hidden="true" tabindex="-1"></a>    co_node</span>
<span id="cb19-165"><a href="#cb19-165" aria-hidden="true" tabindex="-1"></a>    .group_by(c.component)</span>
<span id="cb19-166"><a href="#cb19-166" aria-hidden="true" tabindex="-1"></a>    .agg(n <span class="op">=</span> pl.<span class="bu">len</span>(), size <span class="op">=</span> c.component_size.first())</span>
<span id="cb19-167"><a href="#cb19-167" aria-hidden="true" tabindex="-1"></a>    .sort(c.component)</span>
<span id="cb19-168"><a href="#cb19-168" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-169"><a href="#cb19-169" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-170"><a href="#cb19-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-171"><a href="#cb19-171" aria-hidden="true" tabindex="-1"></a>Unlike the direct-citation network, which came back as one connected piece, the</span>
<span id="cb19-172"><a href="#cb19-172" aria-hidden="true" tabindex="-1"></a>co-citation network splits into three components: a core of 68 cases and two</span>
<span id="cb19-173"><a href="#cb19-173" aria-hidden="true" tabindex="-1"></a>tiny islands of two cases each. Filtering to <span class="in">`count &gt;= 15`</span> is what separates</span>
<span id="cb19-174"><a href="#cb19-174" aria-hidden="true" tabindex="-1"></a>them — a pair of cases only reaches the core if it shares a citer with the rest</span>
<span id="cb19-175"><a href="#cb19-175" aria-hidden="true" tabindex="-1"></a>of the set that often. The two islands are worth reading: one is *Furman v.</span>
<span id="cb19-176"><a href="#cb19-176" aria-hidden="true" tabindex="-1"></a>Georgia* and *Gregg v. Georgia*, the pair that struck down and then restored the</span>
<span id="cb19-177"><a href="#cb19-177" aria-hidden="true" tabindex="-1"></a>death penalty, and the other is *Standard Oil* and *Socony-Vacuum*, two</span>
<span id="cb19-178"><a href="#cb19-178" aria-hidden="true" tabindex="-1"></a>antitrust decisions. Both pairs are heavily co-cited *with each other* and</span>
<span id="cb19-179"><a href="#cb19-179" aria-hidden="true" tabindex="-1"></a>almost never co-cited with the constitutional-rights core, so they float off on</span>
<span id="cb19-180"><a href="#cb19-180" aria-hidden="true" tabindex="-1"></a>their own. The component check is the same discipline from last notebook: a</span>
<span id="cb19-181"><a href="#cb19-181" aria-hidden="true" tabindex="-1"></a>network can quietly fall apart, and you want to know that before you read a</span>
<span id="cb19-182"><a href="#cb19-182" aria-hidden="true" tabindex="-1"></a>centrality score off it.</span>
<span id="cb19-183"><a href="#cb19-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-184"><a href="#cb19-184" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Compute eigenvalue centrality on the core. Because centrality is only defined</span>
<span id="cb19-185"><a href="#cb19-185" aria-hidden="true" tabindex="-1"></a>within a component, filter to <span class="in">`component == 1`</span> first, then print the 10 cases</span>
<span id="cb19-186"><a href="#cb19-186" aria-hidden="true" tabindex="-1"></a>with the highest <span class="in">`eigen`</span>, showing <span class="in">`degree`</span> alongside. Compare the top of this</span>
<span id="cb19-187"><a href="#cb19-187" aria-hidden="true" tabindex="-1"></a>list to what the direct-citation network ranked highest last notebook (degree</span>
<span id="cb19-188"><a href="#cb19-188" aria-hidden="true" tabindex="-1"></a>crowned *Palko v. Connecticut* and the criminal-procedure cases).</span>
<span id="cb19-189"><a href="#cb19-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-192"><a href="#cb19-192" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-193"><a href="#cb19-193" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb19-194"><a href="#cb19-194" aria-hidden="true" tabindex="-1"></a>    co_node</span>
<span id="cb19-195"><a href="#cb19-195" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.component <span class="op">==</span> <span class="dv">1</span>)</span>
<span id="cb19-196"><a href="#cb19-196" aria-hidden="true" tabindex="-1"></a>    .sort(c.eigen, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-197"><a href="#cb19-197" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">10</span>)</span>
<span id="cb19-198"><a href="#cb19-198" aria-hidden="true" tabindex="-1"></a>    .select(c.case_name, c.term, c.eigen, c.degree)</span>
<span id="cb19-199"><a href="#cb19-199" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-200"><a href="#cb19-200" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-201"><a href="#cb19-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-202"><a href="#cb19-202" aria-hidden="true" tabindex="-1"></a>The co-citation core is a different neighborhood of law entirely. Its center is</span>
<span id="cb19-203"><a href="#cb19-203" aria-hidden="true" tabindex="-1"></a>*Cantwell v. Connecticut*, then *Schneider v. State*, *Whitney v. California*,</span>
<span id="cb19-204"><a href="#cb19-204" aria-hidden="true" tabindex="-1"></a>*New York Times v. Sullivan*, *Thornhill v. Alabama* — the free-speech and</span>
<span id="cb19-205"><a href="#cb19-205" aria-hidden="true" tabindex="-1"></a>First Amendment cases, not the criminal-procedure cases the direct network put</span>
<span id="cb19-206"><a href="#cb19-206" aria-hidden="true" tabindex="-1"></a>in the middle. The reason is what co-citation measures: these cases keep getting</span>
<span id="cb19-207"><a href="#cb19-207" aria-hidden="true" tabindex="-1"></a>cited *together* because later free-speech opinions reach for a whole line of</span>
<span id="cb19-208"><a href="#cb19-208" aria-hidden="true" tabindex="-1"></a>precedent at once. Direct citation rewarded *Palko* for being pointed at often;</span>
<span id="cb19-209"><a href="#cb19-209" aria-hidden="true" tabindex="-1"></a>co-citation rewards a case for being pointed at in company. They are two honest</span>
<span id="cb19-210"><a href="#cb19-210" aria-hidden="true" tabindex="-1"></a>answers to "which case is central," and they disagree because they are asking</span>
<span id="cb19-211"><a href="#cb19-211" aria-hidden="true" tabindex="-1"></a>different questions.</span>
<span id="cb19-212"><a href="#cb19-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-213"><a href="#cb19-213" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Now change the other axis: instead of a different *definition* of an edge,</span>
<span id="cb19-214"><a href="#cb19-214" aria-hidden="true" tabindex="-1"></a>keep the direct-citation edges but respect their *direction*. Rebuild the</span>
<span id="cb19-215"><a href="#cb19-215" aria-hidden="true" tabindex="-1"></a>top-80 induced edge list from <span class="in">`cite`</span> and pass it to <span class="in">`DSNetwork.process`</span> with</span>
<span id="cb19-216"><a href="#cb19-216" aria-hidden="true" tabindex="-1"></a><span class="in">`directed=True`</span>. Print the node table. Notice which columns are different from</span>
<span id="cb19-217"><a href="#cb19-217" aria-hidden="true" tabindex="-1"></a>the undirected version.</span>
<span id="cb19-218"><a href="#cb19-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-221"><a href="#cb19-221" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-222"><a href="#cb19-222" aria-hidden="true" tabindex="-1"></a>edges <span class="op">=</span> (</span>
<span id="cb19-223"><a href="#cb19-223" aria-hidden="true" tabindex="-1"></a>    cite</span>
<span id="cb19-224"><a href="#cb19-224" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.citing_case.is_in(top) <span class="op">&amp;</span> c.cited_case.is_in(top))</span>
<span id="cb19-225"><a href="#cb19-225" aria-hidden="true" tabindex="-1"></a>    .rename({<span class="st">"citing_case"</span>: <span class="st">"doc_id"</span>, <span class="st">"cited_case"</span>: <span class="st">"doc_id2"</span>})</span>
<span id="cb19-226"><a href="#cb19-226" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-227"><a href="#cb19-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-228"><a href="#cb19-228" aria-hidden="true" tabindex="-1"></a>di_node, di_edge, di_G <span class="op">=</span> DSNetwork.process(edges, directed<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-229"><a href="#cb19-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-230"><a href="#cb19-230" aria-hidden="true" tabindex="-1"></a>di_node <span class="op">=</span> di_node.join(</span>
<span id="cb19-231"><a href="#cb19-231" aria-hidden="true" tabindex="-1"></a>    case.select(c.citation, c.case_name, c.term),</span>
<span id="cb19-232"><a href="#cb19-232" aria-hidden="true" tabindex="-1"></a>    left_on<span class="op">=</span><span class="st">"id"</span>,</span>
<span id="cb19-233"><a href="#cb19-233" aria-hidden="true" tabindex="-1"></a>    right_on<span class="op">=</span><span class="st">"citation"</span>,</span>
<span id="cb19-234"><a href="#cb19-234" aria-hidden="true" tabindex="-1"></a>    how<span class="op">=</span><span class="st">"left"</span></span>
<span id="cb19-235"><a href="#cb19-235" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-236"><a href="#cb19-236" aria-hidden="true" tabindex="-1"></a>di_node</span>
<span id="cb19-237"><a href="#cb19-237" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-238"><a href="#cb19-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-239"><a href="#cb19-239" aria-hidden="true" tabindex="-1"></a>A directed network reports a different set of measurements. Closeness centrality</span>
<span id="cb19-240"><a href="#cb19-240" aria-hidden="true" tabindex="-1"></a>is gone (it is not well defined once edges point one way), and in place of the</span>
<span id="cb19-241"><a href="#cb19-241" aria-hidden="true" tabindex="-1"></a>single <span class="in">`degree`</span> column there are now three: <span class="in">`degree_out`</span>, the number of</span>
<span id="cb19-242"><a href="#cb19-242" aria-hidden="true" tabindex="-1"></a>landmark cases this case cites; <span class="in">`degree_in`</span>, the number of landmark cases that</span>
<span id="cb19-243"><a href="#cb19-243" aria-hidden="true" tabindex="-1"></a>cite it; and <span class="in">`degree_total`</span>, their sum. On an undirected network these two</span>
<span id="cb19-244"><a href="#cb19-244" aria-hidden="true" tabindex="-1"></a>directions were blurred together into one number.</span>
<span id="cb19-245"><a href="#cb19-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-246"><a href="#cb19-246" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Plot in-degree against out-degree, following the chapter's own directed</span>
<span id="cb19-247"><a href="#cb19-247" aria-hidden="true" tabindex="-1"></a>example. Highlight a handful of well-known cases so the plot has some labels, and</span>
<span id="cb19-248"><a href="#cb19-248" aria-hidden="true" tabindex="-1"></a>add a diagonal line where in-degree equals out-degree. Save the plot and look at</span>
<span id="cb19-249"><a href="#cb19-249" aria-hidden="true" tabindex="-1"></a>it before reading the description.</span>
<span id="cb19-250"><a href="#cb19-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-253"><a href="#cb19-253" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-254"><a href="#cb19-254" aria-hidden="true" tabindex="-1"></a>highlight <span class="op">=</span> [</span>
<span id="cb19-255"><a href="#cb19-255" aria-hidden="true" tabindex="-1"></a>    <span class="st">"384 U.S. 436"</span>,   <span class="co"># Miranda v. Arizona</span></span>
<span id="cb19-256"><a href="#cb19-256" aria-hidden="true" tabindex="-1"></a>    <span class="st">"372 U.S. 335"</span>,   <span class="co"># Gideon v. Wainwright</span></span>
<span id="cb19-257"><a href="#cb19-257" aria-hidden="true" tabindex="-1"></a>    <span class="st">"17 U.S. 316"</span>,    <span class="co"># McCulloch v. Maryland</span></span>
<span id="cb19-258"><a href="#cb19-258" aria-hidden="true" tabindex="-1"></a>    <span class="st">"302 U.S. 319"</span>,   <span class="co"># Palko v. Connecticut</span></span>
<span id="cb19-259"><a href="#cb19-259" aria-hidden="true" tabindex="-1"></a>    <span class="st">"347 U.S. 483"</span>,   <span class="co"># Brown v. Board of Education</span></span>
<span id="cb19-260"><a href="#cb19-260" aria-hidden="true" tabindex="-1"></a>    <span class="st">"424 U.S. 1"</span>      <span class="co"># Buckley v. Valeo</span></span>
<span id="cb19-261"><a href="#cb19-261" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb19-262"><a href="#cb19-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-263"><a href="#cb19-263" aria-hidden="true" tabindex="-1"></a>di_highlight <span class="op">=</span> di_node.<span class="bu">filter</span>(c.<span class="bu">id</span>.is_in(highlight))</span>
<span id="cb19-264"><a href="#cb19-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-265"><a href="#cb19-265" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb19-266"><a href="#cb19-266" aria-hidden="true" tabindex="-1"></a>    di_node</span>
<span id="cb19-267"><a href="#cb19-267" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(c.degree_out, c.degree_in))</span>
<span id="cb19-268"><a href="#cb19-268" aria-hidden="true" tabindex="-1"></a>    .geom_point()</span>
<span id="cb19-269"><a href="#cb19-269" aria-hidden="true" tabindex="-1"></a>    .geom_text(</span>
<span id="cb19-270"><a href="#cb19-270" aria-hidden="true" tabindex="-1"></a>        aes(label<span class="op">=</span>c.case_name),</span>
<span id="cb19-271"><a href="#cb19-271" aria-hidden="true" tabindex="-1"></a>        data<span class="op">=</span>di_highlight,</span>
<span id="cb19-272"><a href="#cb19-272" aria-hidden="true" tabindex="-1"></a>        size<span class="op">=</span><span class="dv">7</span>,</span>
<span id="cb19-273"><a href="#cb19-273" aria-hidden="true" tabindex="-1"></a>        nudge_y<span class="op">=</span><span class="fl">0.6</span></span>
<span id="cb19-274"><a href="#cb19-274" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb19-275"><a href="#cb19-275" aria-hidden="true" tabindex="-1"></a>    .geom_abline(slope<span class="op">=</span><span class="dv">1</span>, intercept<span class="op">=</span><span class="dv">0</span>, linetype<span class="op">=</span><span class="st">"dashed"</span>)</span>
<span id="cb19-276"><a href="#cb19-276" aria-hidden="true" tabindex="-1"></a>    .labs(</span>
<span id="cb19-277"><a href="#cb19-277" aria-hidden="true" tabindex="-1"></a>        title<span class="op">=</span><span class="st">"In-degree vs Out-degree in the SCOTUS Landmark Network"</span>,</span>
<span id="cb19-278"><a href="#cb19-278" aria-hidden="true" tabindex="-1"></a>        x<span class="op">=</span><span class="st">"Out-degree (landmarks this case cites)"</span>,</span>
<span id="cb19-279"><a href="#cb19-279" aria-hidden="true" tabindex="-1"></a>        y<span class="op">=</span><span class="st">"In-degree (landmarks that cite this case)"</span></span>
<span id="cb19-280"><a href="#cb19-280" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb19-281"><a href="#cb19-281" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-282"><a href="#cb19-282" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-283"><a href="#cb19-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-284"><a href="#cb19-284" aria-hidden="true" tabindex="-1"></a>The middle of the cloud is balanced, but the corners are pulled apart by era.</span>
<span id="cb19-285"><a href="#cb19-285" aria-hidden="true" tabindex="-1"></a>The oldest foundational cases sit at the top-left, cited by many later landmarks</span>
<span id="cb19-286"><a href="#cb19-286" aria-hidden="true" tabindex="-1"></a>but citing almost none: *McCulloch* (1819) cites none of the others while eight</span>
<span id="cb19-287"><a href="#cb19-287" aria-hidden="true" tabindex="-1"></a>cite it, and *Palko* (1937) cites five while eighteen cite it. The most recent</span>
<span id="cb19-288"><a href="#cb19-288" aria-hidden="true" tabindex="-1"></a>cases sit at the bottom-right: *Buckley v. Valeo* (1976) cites twelve other</span>
<span id="cb19-289"><a href="#cb19-289" aria-hidden="true" tabindex="-1"></a>landmarks and is cited by none. A citation can only point backward in time, so</span>
<span id="cb19-290"><a href="#cb19-290" aria-hidden="true" tabindex="-1"></a>on a set of cases spanning 150 years a case's drift off the diagonal tracks when</span>
<span id="cb19-291"><a href="#cb19-291" aria-hidden="true" tabindex="-1"></a>it was decided. The chapter's Wikipedia version showed no such tilt, because its</span>
<span id="cb19-292"><a href="#cb19-292" aria-hidden="true" tabindex="-1"></a>pages carry no fixed order to cite in.</span>
<span id="cb19-293"><a href="#cb19-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-294"><a href="#cb19-294" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>Put a number on that. Compute the correlation between a case's <span class="in">`term`</span> and</span>
<span id="cb19-295"><a href="#cb19-295" aria-hidden="true" tabindex="-1"></a>its out-degree, and between its <span class="in">`term`</span> and its in-degree. Then count how many</span>
<span id="cb19-296"><a href="#cb19-296" aria-hidden="true" tabindex="-1"></a>cases have an out-degree of exactly zero.</span>
<span id="cb19-297"><a href="#cb19-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-300"><a href="#cb19-300" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-301"><a href="#cb19-301" aria-hidden="true" tabindex="-1"></a>di_node.select(</span>
<span id="cb19-302"><a href="#cb19-302" aria-hidden="true" tabindex="-1"></a>    corr_term_out <span class="op">=</span> pl.corr(c.term, c.degree_out),</span>
<span id="cb19-303"><a href="#cb19-303" aria-hidden="true" tabindex="-1"></a>    corr_term_in <span class="op">=</span> pl.corr(c.term, c.degree_in),</span>
<span id="cb19-304"><a href="#cb19-304" aria-hidden="true" tabindex="-1"></a>    n_zero_out <span class="op">=</span> (c.degree_out <span class="op">==</span> <span class="dv">0</span>).<span class="bu">sum</span>()</span>
<span id="cb19-305"><a href="#cb19-305" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-306"><a href="#cb19-306" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-307"><a href="#cb19-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-308"><a href="#cb19-308" aria-hidden="true" tabindex="-1"></a>Term and out-degree correlate at 0.63: the later a case, the more earlier</span>
<span id="cb19-309"><a href="#cb19-309" aria-hidden="true" tabindex="-1"></a>landmarks it can and does cite. Term and in-degree correlate at −0.25, the</span>
<span id="cb19-310"><a href="#cb19-310" aria-hidden="true" tabindex="-1"></a>opposite sign, for the same reason in reverse — an old case has had a century to</span>
<span id="cb19-311"><a href="#cb19-311" aria-hidden="true" tabindex="-1"></a>accumulate citations from the rest of the set. Ten cases cite none of the other</span>
<span id="cb19-312"><a href="#cb19-312" aria-hidden="true" tabindex="-1"></a>79, and reading them back they are the oldest in the corpus, decided before</span>
<span id="cb19-313"><a href="#cb19-313" aria-hidden="true" tabindex="-1"></a>there was a landmark canon to cite. This is the property the chapter says its</span>
<span id="cb19-314"><a href="#cb19-314" aria-hidden="true" tabindex="-1"></a>Wikipedia network cannot show, because "there is no clear temporal ordering of</span>
<span id="cb19-315"><a href="#cb19-315" aria-hidden="true" tabindex="-1"></a>the pages." A court has nothing *but* temporal ordering, and it falls straight</span>
<span id="cb19-316"><a href="#cb19-316" aria-hidden="true" tabindex="-1"></a>out of the degree counts.</span>
<span id="cb19-317"><a href="#cb19-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-318"><a href="#cb19-318" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>The last two networks come from *distances* rather than citations. We have no</span>
<span id="cb19-319"><a href="#cb19-319" aria-hidden="true" tabindex="-1"></a>text for these cases, so we build a distance from the citation structure itself:</span>
<span id="cb19-320"><a href="#cb19-320" aria-hidden="true" tabindex="-1"></a>represent each case by the set of later cases that cite it, and call two cases</span>
<span id="cb19-321"><a href="#cb19-321" aria-hidden="true" tabindex="-1"></a>close when those sets of citers overlap. Concretely, build a matrix with one row</span>
<span id="cb19-322"><a href="#cb19-322" aria-hidden="true" tabindex="-1"></a>per landmark and one column per citing case, holding 1 where the citation</span>
<span id="cb19-323"><a href="#cb19-323" aria-hidden="true" tabindex="-1"></a>exists, and compute the angle distance between every pair of rows — the same</span>
<span id="cb19-324"><a href="#cb19-324" aria-hidden="true" tabindex="-1"></a><span class="in">`to_numpy`</span>/normalize/<span class="in">`arccos`</span> construction the text chapter used for its own</span>
<span id="cb19-325"><a href="#cb19-325" aria-hidden="true" tabindex="-1"></a>distances. Print the six closest pairs.</span>
<span id="cb19-326"><a href="#cb19-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-329"><a href="#cb19-329" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-330"><a href="#cb19-330" aria-hidden="true" tabindex="-1"></a>profile <span class="op">=</span> (</span>
<span id="cb19-331"><a href="#cb19-331" aria-hidden="true" tabindex="-1"></a>    cite</span>
<span id="cb19-332"><a href="#cb19-332" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.cited_case.is_in(top))</span>
<span id="cb19-333"><a href="#cb19-333" aria-hidden="true" tabindex="-1"></a>    .select(c.cited_case, c.citing_case)</span>
<span id="cb19-334"><a href="#cb19-334" aria-hidden="true" tabindex="-1"></a>    .with_columns(present <span class="op">=</span> pl.lit(<span class="dv">1</span>))</span>
<span id="cb19-335"><a href="#cb19-335" aria-hidden="true" tabindex="-1"></a>    .pivot(on<span class="op">=</span><span class="st">"citing_case"</span>, index<span class="op">=</span><span class="st">"cited_case"</span>, values<span class="op">=</span><span class="st">"present"</span>, aggregate_function<span class="op">=</span><span class="st">"first"</span>)</span>
<span id="cb19-336"><a href="#cb19-336" aria-hidden="true" tabindex="-1"></a>    .fill_null(<span class="dv">0</span>)</span>
<span id="cb19-337"><a href="#cb19-337" aria-hidden="true" tabindex="-1"></a>    .sort(<span class="st">"cited_case"</span>)</span>
<span id="cb19-338"><a href="#cb19-338" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-339"><a href="#cb19-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-340"><a href="#cb19-340" aria-hidden="true" tabindex="-1"></a>ids <span class="op">=</span> profile.get_column(<span class="st">"cited_case"</span>).to_list()</span>
<span id="cb19-341"><a href="#cb19-341" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> profile.drop(<span class="st">"cited_case"</span>).to_numpy().astype(<span class="bu">float</span>)</span>
<span id="cb19-342"><a href="#cb19-342" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> X <span class="op">/</span> np.linalg.norm(X, axis<span class="op">=</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-343"><a href="#cb19-343" aria-hidden="true" tabindex="-1"></a>angles <span class="op">=</span> np.arccos(np.clip(X <span class="op">@</span> X.T, <span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb19-344"><a href="#cb19-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-345"><a href="#cb19-345" aria-hidden="true" tabindex="-1"></a>dist <span class="op">=</span> (</span>
<span id="cb19-346"><a href="#cb19-346" aria-hidden="true" tabindex="-1"></a>    pl.DataFrame(angles, schema<span class="op">=</span>[<span class="bu">str</span>(i) <span class="cf">for</span> i <span class="kw">in</span> ids])</span>
<span id="cb19-347"><a href="#cb19-347" aria-hidden="true" tabindex="-1"></a>    .with_columns(doc_id <span class="op">=</span> pl.Series(ids))</span>
<span id="cb19-348"><a href="#cb19-348" aria-hidden="true" tabindex="-1"></a>    .unpivot(index<span class="op">=</span><span class="st">"doc_id"</span>, variable_name<span class="op">=</span><span class="st">"doc_id2"</span>, value_name<span class="op">=</span><span class="st">"distance"</span>)</span>
<span id="cb19-349"><a href="#cb19-349" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.doc_id <span class="op">&lt;</span> c.doc_id2)</span>
<span id="cb19-350"><a href="#cb19-350" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-351"><a href="#cb19-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-352"><a href="#cb19-352" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb19-353"><a href="#cb19-353" aria-hidden="true" tabindex="-1"></a>    dist</span>
<span id="cb19-354"><a href="#cb19-354" aria-hidden="true" tabindex="-1"></a>    .sort(c.distance)</span>
<span id="cb19-355"><a href="#cb19-355" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">6</span>)</span>
<span id="cb19-356"><a href="#cb19-356" aria-hidden="true" tabindex="-1"></a>    .join(case.select(c.citation, name_a<span class="op">=</span>c.case_name), left_on<span class="op">=</span><span class="st">"doc_id"</span>, right_on<span class="op">=</span><span class="st">"citation"</span>, how<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb19-357"><a href="#cb19-357" aria-hidden="true" tabindex="-1"></a>    .join(case.select(c.citation, name_b<span class="op">=</span>c.case_name), left_on<span class="op">=</span><span class="st">"doc_id2"</span>, right_on<span class="op">=</span><span class="st">"citation"</span>, how<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb19-358"><a href="#cb19-358" aria-hidden="true" tabindex="-1"></a>    .select(c.name_a, c.name_b, c.distance)</span>
<span id="cb19-359"><a href="#cb19-359" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-360"><a href="#cb19-360" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-361"><a href="#cb19-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-362"><a href="#cb19-362" aria-hidden="true" tabindex="-1"></a>The closest pairs are ones a reader can check by eye. *Furman* and *Gregg*, the</span>
<span id="cb19-363"><a href="#cb19-363" aria-hidden="true" tabindex="-1"></a>death-penalty pair again, are nearest of all at 0.85. Next are *Meyer v.</span>
<span id="cb19-364"><a href="#cb19-364" aria-hidden="true" tabindex="-1"></a>Nebraska* and *Pierce v. Society of Sisters*, the two 1920s substantive-due-</span>
<span id="cb19-365"><a href="#cb19-365" aria-hidden="true" tabindex="-1"></a>process cases about parents' control over their children's schooling, and then</span>
<span id="cb19-366"><a href="#cb19-366" aria-hidden="true" tabindex="-1"></a>a run of the free-speech leafleting cases (*Lovell*, *Schneider*, *Cantwell*).</span>
<span id="cb19-367"><a href="#cb19-367" aria-hidden="true" tabindex="-1"></a>The distance found real doctrinal pairs without ever being told what any case is</span>
<span id="cb19-368"><a href="#cb19-368" aria-hidden="true" tabindex="-1"></a>about, only who cites it — which is exactly the spot-check-against-something-you-</span>
<span id="cb19-369"><a href="#cb19-369" aria-hidden="true" tabindex="-1"></a>know the chapter asks for before trusting an embedding or a distance.</span>
<span id="cb19-370"><a href="#cb19-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-371"><a href="#cb19-371" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>Before building a distance network, look at the distances themselves. Print</span>
<span id="cb19-372"><a href="#cb19-372" aria-hidden="true" tabindex="-1"></a>the smallest and mean distance, and count how many of the pairs sit exactly at</span>
<span id="cb19-373"><a href="#cb19-373" aria-hidden="true" tabindex="-1"></a>the maximum possible angle distance of π/2. Then, following the chapter, build a</span>
<span id="cb19-374"><a href="#cb19-374" aria-hidden="true" tabindex="-1"></a>distance network by keeping every pair closer than a cutoff, and check how many</span>
<span id="cb19-375"><a href="#cb19-375" aria-hidden="true" tabindex="-1"></a>components it lands in.</span>
<span id="cb19-376"><a href="#cb19-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-379"><a href="#cb19-379" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-380"><a href="#cb19-380" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb19-381"><a href="#cb19-381" aria-hidden="true" tabindex="-1"></a>    dist.select(</span>
<span id="cb19-382"><a href="#cb19-382" aria-hidden="true" tabindex="-1"></a>        smallest <span class="op">=</span> c.distance.<span class="bu">min</span>(),</span>
<span id="cb19-383"><a href="#cb19-383" aria-hidden="true" tabindex="-1"></a>        mean <span class="op">=</span> c.distance.mean(),</span>
<span id="cb19-384"><a href="#cb19-384" aria-hidden="true" tabindex="-1"></a>        n_orthogonal <span class="op">=</span> (c.distance <span class="op">&gt;</span> <span class="fl">1.5707</span>).<span class="bu">sum</span>(),</span>
<span id="cb19-385"><a href="#cb19-385" aria-hidden="true" tabindex="-1"></a>        n_pairs <span class="op">=</span> pl.<span class="bu">len</span>()</span>
<span id="cb19-386"><a href="#cb19-386" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb19-387"><a href="#cb19-387" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-388"><a href="#cb19-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-389"><a href="#cb19-389" aria-hidden="true" tabindex="-1"></a>dist_edges <span class="op">=</span> (</span>
<span id="cb19-390"><a href="#cb19-390" aria-hidden="true" tabindex="-1"></a>    dist</span>
<span id="cb19-391"><a href="#cb19-391" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.distance <span class="op">&lt;</span> <span class="fl">1.4</span>)</span>
<span id="cb19-392"><a href="#cb19-392" aria-hidden="true" tabindex="-1"></a>    .select(c.doc_id, c.doc_id2)</span>
<span id="cb19-393"><a href="#cb19-393" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-394"><a href="#cb19-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-395"><a href="#cb19-395" aria-hidden="true" tabindex="-1"></a>dn_node, dn_edge, dn_G <span class="op">=</span> DSNetwork.process(dist_edges, directed<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb19-396"><a href="#cb19-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-397"><a href="#cb19-397" aria-hidden="true" tabindex="-1"></a>dn_node.group_by(c.component).agg(n <span class="op">=</span> pl.<span class="bu">len</span>()).sort(c.n, descending<span class="op">=</span><span class="va">True</span>).head()</span>
<span id="cb19-398"><a href="#cb19-398" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-399"><a href="#cb19-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-400"><a href="#cb19-400" aria-hidden="true" tabindex="-1"></a>The mean distance is 1.53, almost the π/2 maximum, and 829 of the 3,160 pairs —</span>
<span id="cb19-401"><a href="#cb19-401" aria-hidden="true" tabindex="-1"></a>better than a quarter — sit *exactly* at π/2, meaning they share no citer at</span>
<span id="cb19-402"><a href="#cb19-402" aria-hidden="true" tabindex="-1"></a>all. This is the same crowding-against-the-maximum we saw with sparse text</span>
<span id="cb19-403"><a href="#cb19-403" aria-hidden="true" tabindex="-1"></a>vectors: when each case has hundreds of citers spread across thousands of</span>
<span id="cb19-404"><a href="#cb19-404" aria-hidden="true" tabindex="-1"></a>possible citing cases, almost any two of them are nearly orthogonal. A fixed</span>
<span id="cb19-405"><a href="#cb19-405" aria-hidden="true" tabindex="-1"></a>distance cutoff is a blunt instrument here. Set it at 1.4 and the network</span>
<span id="cb19-406"><a href="#cb19-406" aria-hidden="true" tabindex="-1"></a>shatters into a dozen disconnected pieces; nudge it to 1.5 and nearly every pair</span>
<span id="cb19-407"><a href="#cb19-407" aria-hidden="true" tabindex="-1"></a>becomes an edge at once. There is no cutoff that gives a single readable network,</span>
<span id="cb19-408"><a href="#cb19-408" aria-hidden="true" tabindex="-1"></a>because the distances are all bunched at one end. The next section fixes this by</span>
<span id="cb19-409"><a href="#cb19-409" aria-hidden="true" tabindex="-1"></a>ranking neighbors instead of thresholding them.</span>
<span id="cb19-410"><a href="#cb19-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-411"><a href="#cb19-411" aria-hidden="true" tabindex="-1"></a><span class="ss">9. </span>A *symmetric nearest-neighbor* network sidesteps the cutoff problem. For each</span>
<span id="cb19-412"><a href="#cb19-412" aria-hidden="true" tabindex="-1"></a>case, take its k closest neighbors, and keep an edge only when two cases are</span>
<span id="cb19-413"><a href="#cb19-413" aria-hidden="true" tabindex="-1"></a>*mutually* in each other's top k. Because the rule is per-case, a popular case</span>
<span id="cb19-414"><a href="#cb19-414" aria-hidden="true" tabindex="-1"></a>cannot collect more than k edges, and the network can never have a degree above</span>
<span id="cb19-415"><a href="#cb19-415" aria-hidden="true" tabindex="-1"></a>k. Build it with <span class="in">`k = 5`</span>. Since your <span class="in">`dist`</span> table has each pair once, first</span>
<span id="cb19-416"><a href="#cb19-416" aria-hidden="true" tabindex="-1"></a>stack it with a copy of itself with the two columns swapped so every case sees</span>
<span id="cb19-417"><a href="#cb19-417" aria-hidden="true" tabindex="-1"></a>all of its neighbors, take the 5 nearest per case, and keep only the pairs that</span>
<span id="cb19-418"><a href="#cb19-418" aria-hidden="true" tabindex="-1"></a>appear from both directions.</span>
<span id="cb19-419"><a href="#cb19-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-422"><a href="#cb19-422" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-423"><a href="#cb19-423" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb19-424"><a href="#cb19-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-425"><a href="#cb19-425" aria-hidden="true" tabindex="-1"></a>both <span class="op">=</span> pl.concat([</span>
<span id="cb19-426"><a href="#cb19-426" aria-hidden="true" tabindex="-1"></a>    dist.select(c.doc_id, c.doc_id2, c.distance),</span>
<span id="cb19-427"><a href="#cb19-427" aria-hidden="true" tabindex="-1"></a>    dist.select(doc_id<span class="op">=</span>c.doc_id2, doc_id2<span class="op">=</span>c.doc_id, distance<span class="op">=</span>c.distance)</span>
<span id="cb19-428"><a href="#cb19-428" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb19-429"><a href="#cb19-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-430"><a href="#cb19-430" aria-hidden="true" tabindex="-1"></a>knn <span class="op">=</span> (</span>
<span id="cb19-431"><a href="#cb19-431" aria-hidden="true" tabindex="-1"></a>    both</span>
<span id="cb19-432"><a href="#cb19-432" aria-hidden="true" tabindex="-1"></a>    .sort([c.doc_id, c.distance])</span>
<span id="cb19-433"><a href="#cb19-433" aria-hidden="true" tabindex="-1"></a>    .group_by(c.doc_id, maintain_order<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-434"><a href="#cb19-434" aria-hidden="true" tabindex="-1"></a>    .head(k)</span>
<span id="cb19-435"><a href="#cb19-435" aria-hidden="true" tabindex="-1"></a>    .select(c.doc_id, c.doc_id2)</span>
<span id="cb19-436"><a href="#cb19-436" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-437"><a href="#cb19-437" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-438"><a href="#cb19-438" aria-hidden="true" tabindex="-1"></a>nn_edges <span class="op">=</span> (</span>
<span id="cb19-439"><a href="#cb19-439" aria-hidden="true" tabindex="-1"></a>    knn</span>
<span id="cb19-440"><a href="#cb19-440" aria-hidden="true" tabindex="-1"></a>    .with_columns(</span>
<span id="cb19-441"><a href="#cb19-441" aria-hidden="true" tabindex="-1"></a>        a <span class="op">=</span> pl.min_horizontal(c.doc_id, c.doc_id2),</span>
<span id="cb19-442"><a href="#cb19-442" aria-hidden="true" tabindex="-1"></a>        b <span class="op">=</span> pl.max_horizontal(c.doc_id, c.doc_id2)</span>
<span id="cb19-443"><a href="#cb19-443" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb19-444"><a href="#cb19-444" aria-hidden="true" tabindex="-1"></a>    .group_by([c.a, c.b])</span>
<span id="cb19-445"><a href="#cb19-445" aria-hidden="true" tabindex="-1"></a>    .agg(mutual <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb19-446"><a href="#cb19-446" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.mutual <span class="op">==</span> <span class="dv">2</span>)</span>
<span id="cb19-447"><a href="#cb19-447" aria-hidden="true" tabindex="-1"></a>    .select(doc_id<span class="op">=</span>c.a, doc_id2<span class="op">=</span>c.b)</span>
<span id="cb19-448"><a href="#cb19-448" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-449"><a href="#cb19-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-450"><a href="#cb19-450" aria-hidden="true" tabindex="-1"></a>nn_node, nn_edge, nn_G <span class="op">=</span> DSNetwork.process(nn_edges, directed<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb19-451"><a href="#cb19-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-452"><a href="#cb19-452" aria-hidden="true" tabindex="-1"></a>nn_node <span class="op">=</span> nn_node.join(</span>
<span id="cb19-453"><a href="#cb19-453" aria-hidden="true" tabindex="-1"></a>    case.select(c.citation, c.case_name, c.term),</span>
<span id="cb19-454"><a href="#cb19-454" aria-hidden="true" tabindex="-1"></a>    left_on<span class="op">=</span><span class="st">"id"</span>,</span>
<span id="cb19-455"><a href="#cb19-455" aria-hidden="true" tabindex="-1"></a>    right_on<span class="op">=</span><span class="st">"citation"</span>,</span>
<span id="cb19-456"><a href="#cb19-456" aria-hidden="true" tabindex="-1"></a>    how<span class="op">=</span><span class="st">"left"</span></span>
<span id="cb19-457"><a href="#cb19-457" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-458"><a href="#cb19-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-459"><a href="#cb19-459" aria-hidden="true" tabindex="-1"></a>nn_node.select(</span>
<span id="cb19-460"><a href="#cb19-460" aria-hidden="true" tabindex="-1"></a>    n_nodes <span class="op">=</span> pl.<span class="bu">len</span>(),</span>
<span id="cb19-461"><a href="#cb19-461" aria-hidden="true" tabindex="-1"></a>    n_components <span class="op">=</span> c.component.<span class="bu">max</span>(),</span>
<span id="cb19-462"><a href="#cb19-462" aria-hidden="true" tabindex="-1"></a>    max_degree <span class="op">=</span> c.degree.<span class="bu">max</span>(),</span>
<span id="cb19-463"><a href="#cb19-463" aria-hidden="true" tabindex="-1"></a>    mean_degree <span class="op">=</span> c.degree.mean().<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb19-464"><a href="#cb19-464" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-465"><a href="#cb19-465" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-466"><a href="#cb19-466" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-467"><a href="#cb19-467" aria-hidden="true" tabindex="-1"></a>Where the fixed cutoff either fragmented or overconnected the network, the</span>
<span id="cb19-468"><a href="#cb19-468" aria-hidden="true" tabindex="-1"></a>nearest-neighbor rule lands on a single connected component of all 77 cases with</span>
<span id="cb19-469"><a href="#cb19-469" aria-hidden="true" tabindex="-1"></a>a maximum degree of exactly 5 — no case, however heavily cited, is allowed more</span>
<span id="cb19-470"><a href="#cb19-470" aria-hidden="true" tabindex="-1"></a>than its five mutual neighbors. The <span class="in">`mutual == 2`</span> filter is the "each direction</span>
<span id="cb19-471"><a href="#cb19-471" aria-hidden="true" tabindex="-1"></a>counts once" trick: a pair survives only if it turned up when we took *A*'s</span>
<span id="cb19-472"><a href="#cb19-472" aria-hidden="true" tabindex="-1"></a>neighbors and again when we took *B*'s.</span>
<span id="cb19-473"><a href="#cb19-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-474"><a href="#cb19-474" aria-hidden="true" tabindex="-1"></a><span class="ss">10. </span>The chapter's central claim about nearest-neighbor networks is that</span>
<span id="cb19-475"><a href="#cb19-475" aria-hidden="true" tabindex="-1"></a>eigenvalue and betweenness centrality, usually tightly correlated, come apart in</span>
<span id="cb19-476"><a href="#cb19-476" aria-hidden="true" tabindex="-1"></a>this network type. Test it. Compute the correlation between <span class="in">`eigen`</span> and <span class="in">`between`</span></span>
<span id="cb19-477"><a href="#cb19-477" aria-hidden="true" tabindex="-1"></a>for the nearest-neighbor network, and for comparison, do the same on the</span>
<span id="cb19-478"><a href="#cb19-478" aria-hidden="true" tabindex="-1"></a>direct-citation network from question 4's edges (rebuilt undirected). Then print</span>
<span id="cb19-479"><a href="#cb19-479" aria-hidden="true" tabindex="-1"></a>the nearest-neighbor network's top cases by betweenness, with their eigenvalue</span>
<span id="cb19-480"><a href="#cb19-480" aria-hidden="true" tabindex="-1"></a>alongside.</span>
<span id="cb19-481"><a href="#cb19-481" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-484"><a href="#cb19-484" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-485"><a href="#cb19-485" aria-hidden="true" tabindex="-1"></a>un_node, un_edge, un_G <span class="op">=</span> DSNetwork.process(edges, directed<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb19-486"><a href="#cb19-486" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-487"><a href="#cb19-487" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"direct-citation:"</span>, un_node.<span class="bu">filter</span>(c.component <span class="op">==</span> <span class="dv">1</span>).select(pl.corr(c.eigen, c.between)).item())</span>
<span id="cb19-488"><a href="#cb19-488" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"nearest-neighbor:"</span>, nn_node.<span class="bu">filter</span>(c.component <span class="op">==</span> <span class="dv">1</span>).select(pl.corr(c.eigen, c.between)).item())</span>
<span id="cb19-489"><a href="#cb19-489" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-490"><a href="#cb19-490" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb19-491"><a href="#cb19-491" aria-hidden="true" tabindex="-1"></a>    nn_node</span>
<span id="cb19-492"><a href="#cb19-492" aria-hidden="true" tabindex="-1"></a>    .sort(c.between, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-493"><a href="#cb19-493" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">6</span>)</span>
<span id="cb19-494"><a href="#cb19-494" aria-hidden="true" tabindex="-1"></a>    .select(c.case_name, c.term, c.between, c.eigen, c.degree)</span>
<span id="cb19-495"><a href="#cb19-495" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-496"><a href="#cb19-496" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-497"><a href="#cb19-497" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-498"><a href="#cb19-498" aria-hidden="true" tabindex="-1"></a>On the direct-citation network the two measures correlate at 0.37; on the</span>
<span id="cb19-499"><a href="#cb19-499" aria-hidden="true" tabindex="-1"></a>nearest-neighbor network they correlate at −0.14, effectively unrelated. The top</span>
<span id="cb19-500"><a href="#cb19-500" aria-hidden="true" tabindex="-1"></a>of the betweenness list shows why. *Brown v. Board of Education* has the highest</span>
<span id="cb19-501"><a href="#cb19-501" aria-hidden="true" tabindex="-1"></a>betweenness in the whole network but an eigenvalue near zero — it has only four</span>
<span id="cb19-502"><a href="#cb19-502" aria-hidden="true" tabindex="-1"></a>neighbors, and none of them is central, yet it sits on the shortest path between</span>
<span id="cb19-503"><a href="#cb19-503" aria-hidden="true" tabindex="-1"></a>whole regions of the network. These are the gatekeeper nodes the chapter</span>
<span id="cb19-504"><a href="#cb19-504" aria-hidden="true" tabindex="-1"></a>describes: cases that bridge otherwise separate lines of doctrine without being</span>
<span id="cb19-505"><a href="#cb19-505" aria-hidden="true" tabindex="-1"></a>deeply embedded in any one of them. The direct-citation network could not show</span>
<span id="cb19-506"><a href="#cb19-506" aria-hidden="true" tabindex="-1"></a>this because its most-bridging cases were also its most-cited; balancing the</span>
<span id="cb19-507"><a href="#cb19-507" aria-hidden="true" tabindex="-1"></a>degree pulls the two apart.</span>
<span id="cb19-508"><a href="#cb19-508" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-509"><a href="#cb19-509" aria-hidden="true" tabindex="-1"></a><span class="ss">11. </span>Finally, read the communities the nearest-neighbor network found. Color the</span>
<span id="cb19-510"><a href="#cb19-510" aria-hidden="true" tabindex="-1"></a>network by <span class="in">`cluster`</span>, and print each cluster's members. Check whether the groups</span>
<span id="cb19-511"><a href="#cb19-511" aria-hidden="true" tabindex="-1"></a>correspond to recognizable areas of law rather than falling out arbitrarily.</span>
<span id="cb19-512"><a href="#cb19-512" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-515"><a href="#cb19-515" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-516"><a href="#cb19-516" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb19-517"><a href="#cb19-517" aria-hidden="true" tabindex="-1"></a>    nn_node</span>
<span id="cb19-518"><a href="#cb19-518" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(c.x, c.y))</span>
<span id="cb19-519"><a href="#cb19-519" aria-hidden="true" tabindex="-1"></a>    .geom_segment(</span>
<span id="cb19-520"><a href="#cb19-520" aria-hidden="true" tabindex="-1"></a>        aes(x<span class="op">=</span>c.x, y<span class="op">=</span>c.y, xend<span class="op">=</span>c.xend, yend<span class="op">=</span>c.yend),</span>
<span id="cb19-521"><a href="#cb19-521" aria-hidden="true" tabindex="-1"></a>        data<span class="op">=</span>nn_edge,</span>
<span id="cb19-522"><a href="#cb19-522" aria-hidden="true" tabindex="-1"></a>        alpha<span class="op">=</span><span class="fl">0.2</span></span>
<span id="cb19-523"><a href="#cb19-523" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb19-524"><a href="#cb19-524" aria-hidden="true" tabindex="-1"></a>    .geom_point(aes(color<span class="op">=</span>c.cluster), size<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb19-525"><a href="#cb19-525" aria-hidden="true" tabindex="-1"></a>    .theme_void()</span>
<span id="cb19-526"><a href="#cb19-526" aria-hidden="true" tabindex="-1"></a>    .labs(title<span class="op">=</span><span class="st">"Nearest-Neighbor Network by Cluster"</span>, color<span class="op">=</span><span class="st">"Cluster"</span>)</span>
<span id="cb19-527"><a href="#cb19-527" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-528"><a href="#cb19-528" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-529"><a href="#cb19-529" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-532"><a href="#cb19-532" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb19-533"><a href="#cb19-533" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb19-534"><a href="#cb19-534" aria-hidden="true" tabindex="-1"></a>    nn_node</span>
<span id="cb19-535"><a href="#cb19-535" aria-hidden="true" tabindex="-1"></a>    .group_by(c.cluster)</span>
<span id="cb19-536"><a href="#cb19-536" aria-hidden="true" tabindex="-1"></a>    .agg(members <span class="op">=</span> c.case_name.<span class="bu">str</span>.join(<span class="st">"; "</span>))</span>
<span id="cb19-537"><a href="#cb19-537" aria-hidden="true" tabindex="-1"></a>    .sort(c.cluster)</span>
<span id="cb19-538"><a href="#cb19-538" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-539"><a href="#cb19-539" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-540"><a href="#cb19-540" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-541"><a href="#cb19-541" aria-hidden="true" tabindex="-1"></a>The clusters are cleaner and more even in size than the direct network's, which</span>
<span id="cb19-542"><a href="#cb19-542" aria-hidden="true" tabindex="-1"></a>is the payoff the chapter promises for balancing the degree. One cluster is the</span>
<span id="cb19-543"><a href="#cb19-543" aria-hidden="true" tabindex="-1"></a>Fourth Amendment search-and-seizure line (*Weeks*, *Carroll*, *Olmstead*,</span>
<span id="cb19-544"><a href="#cb19-544" aria-hidden="true" tabindex="-1"></a>*Katz*, *Mapp*); another is the incorporation cases that asked which parts of</span>
<span id="cb19-545"><a href="#cb19-545" aria-hidden="true" tabindex="-1"></a>the Bill of Rights bind the states (*Hurtado*, *Palko*, *Malloy*, *Duncan*);</span>
<span id="cb19-546"><a href="#cb19-546" aria-hidden="true" tabindex="-1"></a>another the free-speech leafleting cases; the antitrust pair and the death-</span>
<span id="cb19-547"><a href="#cb19-547" aria-hidden="true" tabindex="-1"></a>penalty pair each hold together as their own small groups. None of this was</span>
<span id="cb19-548"><a href="#cb19-548" aria-hidden="true" tabindex="-1"></a>labeled — the network was handed nothing but who cites whom — yet the walktrap</span>
<span id="cb19-549"><a href="#cb19-549" aria-hidden="true" tabindex="-1"></a>communities recover the syllabus of a constitutional-law course.</span>
<span id="cb19-550"><a href="#cb19-550" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-551"><a href="#cb19-551" aria-hidden="true" tabindex="-1"></a><span class="ss">12. </span>**Written question.** This notebook built four different networks from one</span>
<span id="cb19-552"><a href="#cb19-552" aria-hidden="true" tabindex="-1"></a>edge list: last notebook's direct-citation network and this notebook's</span>
<span id="cb19-553"><a href="#cb19-553" aria-hidden="true" tabindex="-1"></a>co-citation, directed, and nearest-neighbor networks. In two or three sentences,</span>
<span id="cb19-554"><a href="#cb19-554" aria-hidden="true" tabindex="-1"></a>say which network you would reach for to answer each of these questions, and</span>
<span id="cb19-555"><a href="#cb19-555" aria-hidden="true" tabindex="-1"></a>why: (a) which case is the single most influential precedent; (b) which two</span>
<span id="cb19-556"><a href="#cb19-556" aria-hidden="true" tabindex="-1"></a>doctrines a court treats as related; (c) which case quietly bridges otherwise</span>
<span id="cb19-557"><a href="#cb19-557" aria-hidden="true" tabindex="-1"></a>separate lines of law. Note that the same 80 cases gave a different answer under</span>
<span id="cb19-558"><a href="#cb19-558" aria-hidden="true" tabindex="-1"></a>each network, which is the chapter's real point: the network you build is a</span>
<span id="cb19-559"><a href="#cb19-559" aria-hidden="true" tabindex="-1"></a>choice, and it decides what you are able to see.</span>
<span id="cb19-560"><a href="#cb19-560" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-561"><a href="#cb19-561" aria-hidden="true" tabindex="-1"></a>The direct-citation network answers (a): raw and eigenvalue centrality on who</span>
<span id="cb19-562"><a href="#cb19-562" aria-hidden="true" tabindex="-1"></a>cites whom is the natural measure of a precedent's pull. The co-citation network</span>
<span id="cb19-563"><a href="#cb19-563" aria-hidden="true" tabindex="-1"></a>answers (b), since its whole construction is "cited together," and its</span>
<span id="cb19-564"><a href="#cb19-564" aria-hidden="true" tabindex="-1"></a>components landed exactly on doctrinal families like the death-penalty and</span>
<span id="cb19-565"><a href="#cb19-565" aria-hidden="true" tabindex="-1"></a>antitrust pairs. The nearest-neighbor network answers (c): only after balancing</span>
<span id="cb19-566"><a href="#cb19-566" aria-hidden="true" tabindex="-1"></a>the degree did betweenness separate from eigenvalue and surface bridge cases like</span>
<span id="cb19-567"><a href="#cb19-567" aria-hidden="true" tabindex="-1"></a>*Brown v. Board* that every other network buried among the hubs. The directed</span>
<span id="cb19-568"><a href="#cb19-568" aria-hidden="true" tabindex="-1"></a>network, meanwhile, added the one thing none of the undirected versions could —</span>
<span id="cb19-569"><a href="#cb19-569" aria-hidden="true" tabindex="-1"></a>the arrow of time, which on a court record is legible in the degree counts</span>
<span id="cb19-570"><a href="#cb19-570" aria-hidden="true" tabindex="-1"></a>alone.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>