<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Notebook20 – Foundations of Data Science: Notebooks</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-77a666a5542a07a54dbe0a7f6e3b86cd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-sidebar docked fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./notebook20.html">Notebook20</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Foundations of Data Science: Notebooks</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook01</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook02</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook03</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook04</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook05</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook06</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook07</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook08</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook09</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook10</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook11</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook12</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook13</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook14</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook15</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook17</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook18</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook19</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook20.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Notebook20</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Notebook20</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="setup" class="level3">
<h3 class="anchored" data-anchor-id="setup">Setup</h3>
<p>Run all of the following before starting the notebook.</p>
<div id="3e0e30fe" class="cell" data-tags="[&quot;noclear&quot;]" data-execution_count="1">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span> wget <span class="op">-</span>q <span class="op">-</span>nc https:<span class="op">//</span>raw.githubusercontent.com<span class="op">/</span>taylor<span class="op">-</span>arnold<span class="op">/</span>fds2<span class="op">/</span>refs<span class="op">/</span>heads<span class="op">/</span>main<span class="op">/</span>funs.py</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="c2ffa66d" class="cell" data-tags="[&quot;noclear&quot;]" data-execution_count="2">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotnine <span class="im">import</span> ggplot, aes</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> polars <span class="im">import</span> col <span class="im">as</span> c</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> funs</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>ub <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/taylor-arnold/fds2/refs/heads/main/"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="3b6edad5" class="cell" data-tags="[&quot;noclear&quot;]" data-execution_count="4">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>play <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/shakespeare_plays.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>char <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/shakespeare_characters.csv"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>line <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/shakespeare_lines.csv.gz"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="questions" class="level3">
<h3 class="anchored" data-anchor-id="questions">Questions</h3>
<p>Back to the Folger Shakespeare corpus, and back to the three tables we spent an earlier class diagnosing. A row of <code>play</code> is a play (37 of them), a row of <code>char</code> is a character in a play (1,126, and remember that <code>character_id</code> alone does not identify one), and a row of <code>line</code> is a single printed line (80,592), with an <code>act</code>, a <code>scene</code>, a <code>line_number</code> such as <code>"3.1.64"</code>, and the <code>text</code> itself.</p>
<p>We left that class holding three IOUs. We could not sort a scene, because the number that orders the speeches was buried inside a string. We could not count Macbeth’s speaking parts, because some cells held three speakers at once. And we could not build a table with one row per play and one column per act, because that is a pivot and we did not have one.</p>
<p>This is the class where we pay all three. <code>.pivot()</code> and <code>.unpivot()</code> change a table’s shape without changing anything in it, and <code>.explode()</code> gives every element of a packed cell its own row. You also have joins now, which we did not have last time, so the tables can finally talk to each other.</p>
<p>What comes out at the end is not a tidier table. It is a fact about this corpus that we had no way of reaching before today, and once you see it you cannot unsee it.</p>
<p>Unless a question says otherwise, just print the result of each block; do not save it to a variable.</p>
<ol type="1">
<li>Start with the IOU we ended on last time. Count the lines in each act of each play, then reshape the result so that there is one row per play and one column per act. Join <code>play</code> so the rows have readable names.</li>
</ol>
<div id="d6c8e0ac" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    .group_by(c.play_id, c.act)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    .sort(c.act)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    .pivot(index<span class="op">=</span>c.play_id, on<span class="op">=</span>c.act, values<span class="op">=</span>c.n_lines)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    .join(play.select(c.play_id, c.short_title), on<span class="op">=</span>c.play_id)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    .sort(c.short_title)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">8</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="4">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (8, 7)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">play_id</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">5</th>
<th data-quarto-table-cell-role="th">short_title</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
<td>u32</td>
<td>u32</td>
<td>u32</td>
<td>u32</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"1h4"</td>
<td>439</td>
<td>115</td>
<td>436</td>
<td>306</td>
<td>434</td>
<td>"1H4"</td>
</tr>
<tr class="even">
<td>"1h6"</td>
<td>594</td>
<td>494</td>
<td>477</td>
<td>559</td>
<td>565</td>
<td>"1H6"</td>
</tr>
<tr class="odd">
<td>"2h4"</td>
<td>340</td>
<td>97</td>
<td>111</td>
<td>760</td>
<td>241</td>
<td>"2H4"</td>
</tr>
<tr class="even">
<td>"2h6"</td>
<td>584</td>
<td>410</td>
<td>831</td>
<td>433</td>
<td>340</td>
<td>"2H6"</td>
</tr>
<tr class="odd">
<td>"3h6"</td>
<td>584</td>
<td>702</td>
<td>566</td>
<td>558</td>
<td>495</td>
<td>"3H6"</td>
</tr>
<tr class="even">
<td>"aww"</td>
<td>320</td>
<td>445</td>
<td>321</td>
<td>166</td>
<td>369</td>
<td>"AWW"</td>
</tr>
<tr class="odd">
<td>"ayl"</td>
<td>175</td>
<td>460</td>
<td>238</td>
<td>156</td>
<td>176</td>
<td>"AYL"</td>
</tr>
<tr class="even">
<td>"ado"</td>
<td>40</td>
<td>50</td>
<td>118</td>
<td>243</td>
<td>314</td>
<td>"Ado"</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Answer</strong>: The <code>group_by</code> and <code>agg</code> give the numbers long: 185 rows, one per play × act, with an <code>act</code> column and an <code>n_lines</code> column. The <code>.pivot()</code> then moves <code>act</code> out of the data and into the column names. <code>index</code> is the column that stays and becomes the new unit of observation, <code>on</code> is the column whose values become new column names, and <code>values</code> is what fills the cells.</p>
<p>Note the <code>.sort(c.act)</code> in front of the pivot. Without it the columns come out <code>1, 3, 5, 4, 2</code>, because the new column names appear in the order the values are first seen in the data, and a <code>group_by</code> does not promise you an order. This is the same rule that governs a categorical axis in plotnine: if you want an order, sort for it.</p>
<p>Nothing was gained or lost here. There are 37 plays and 5 acts in both shapes, and the 185 numbers are the same 185 numbers.</p>
<ol start="2" type="1">
<li>Now do the same thing one level down, and watch what changes. Take the principal speakers of <em>Macbeth</em>, meaning anyone with at least 60 lines in the play, and build a table with one row per speaker and one column per act.</li>
</ol>
<div id="a231da2e" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mac_big <span class="op">=</span> (</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    .agg(total <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.total <span class="op">&gt;=</span> <span class="dv">60</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    .join(mac_big, on<span class="op">=</span>c.character_id, how<span class="op">=</span><span class="st">"semi"</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id, c.act)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    .sort(c.act)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    .pivot(index<span class="op">=</span>c.character_id, on<span class="op">=</span>c.act, values<span class="op">=</span>c.n_lines)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    .sort(c.character_id)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="5">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (8, 6)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">character_id</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">5</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
<td>u32</td>
<td>u32</td>
<td>u32</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Banquo_Mac"</td>
<td>52</td>
<td>34</td>
<td>25</td>
<td>null</td>
<td>null</td>
</tr>
<tr class="even">
<td>"Duncan_Mac"</td>
<td>69</td>
<td>null</td>
<td>null</td>
<td>null</td>
<td>null</td>
</tr>
<tr class="odd">
<td>"LadyMacbeth_Mac"</td>
<td>113</td>
<td>55</td>
<td>62</td>
<td>null</td>
<td>null</td>
</tr>
<tr class="even">
<td>"Lennox_Mac"</td>
<td>2</td>
<td>18</td>
<td>37</td>
<td>6</td>
<td>7</td>
</tr>
<tr class="odd">
<td>"Macbeth_Mac"</td>
<td>119</td>
<td>115</td>
<td>262</td>
<td>77</td>
<td>138</td>
</tr>
<tr class="even">
<td>"Macduff_Mac"</td>
<td>null</td>
<td>52</td>
<td>null</td>
<td>89</td>
<td>34</td>
</tr>
<tr class="odd">
<td>"Malcolm_Mac"</td>
<td>16</td>
<td>13</td>
<td>null</td>
<td>142</td>
<td>38</td>
</tr>
<tr class="even">
<td>"Ross_Mac"</td>
<td>34</td>
<td>27</td>
<td>5</td>
<td>59</td>
<td>9</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Answer</strong>: This pivot has holes in it. Not every speaker talks in every act, so some combinations of speaker and act never occur in the long table, and Polars fills those cells with <code>null</code>.</p>
<p>Read the nulls, because they are the play. Duncan speaks 69 lines in act 1 and then nothing, which is correct: he is murdered in act 2. Banquo goes quiet after act 3, having been murdered in 3.3, and Macduff has nothing in act 1 because he has not arrived yet. A pivot that is full of holes is often telling you something true about the world.</p>
<p>Then there is Lady Macbeth, who has 113 lines in act 1 and nothing at all in act 5. Hold on to that. She is alive in act 5 and she has the most famous scene in the play, the one where she walks in her sleep and cannot wash her hands. Her cell says <code>null</code>.</p>
<ol start="3" type="1">
<li>Sometimes a hole means zero and sometimes it means something else, and a pivot cannot tell you which. Fill them with zero and then undo the entire reshape, returning the table to the shape it had before question 2.</li>
</ol>
<div id="1d9edb6c" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>mac_wide <span class="op">=</span> (</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    .join(mac_big, on<span class="op">=</span>c.character_id, how<span class="op">=</span><span class="st">"semi"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id, c.act)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    .sort(c.act)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    .pivot(index<span class="op">=</span>c.character_id, on<span class="op">=</span>c.act, values<span class="op">=</span>c.n_lines)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    .fill_null(<span class="dv">0</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    mac_wide</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    .unpivot(index<span class="op">=</span><span class="st">"character_id"</span>, variable_name<span class="op">=</span><span class="st">"act"</span>, value_name<span class="op">=</span><span class="st">"n_lines"</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.character_id <span class="op">==</span> <span class="st">"Duncan_Mac"</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="6">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (5, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">character_id</th>
<th data-quarto-table-cell-role="th">act</th>
<th data-quarto-table-cell-role="th">n_lines</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Duncan_Mac"</td>
<td>"1"</td>
<td>69</td>
</tr>
<tr class="even">
<td>"Duncan_Mac"</td>
<td>"2"</td>
<td>0</td>
</tr>
<tr class="odd">
<td>"Duncan_Mac"</td>
<td>"3"</td>
<td>0</td>
</tr>
<tr class="even">
<td>"Duncan_Mac"</td>
<td>"4"</td>
<td>0</td>
</tr>
<tr class="odd">
<td>"Duncan_Mac"</td>
<td>"5"</td>
<td>0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Answer</strong>: <code>.fill_null(0)</code> sets every empty cell to zero, and <code>.unpivot()</code> folds the act columns back into a single <code>act</code> column and a single <code>n_lines</code> column, which is exactly the layout we pivoted away from. Give it <code>index</code> to say which column stays put, and <code>variable_name</code> and <code>value_name</code> to name the two columns it creates, or you get <code>variable</code> and <code>value</code>.</p>
<p>This is a round trip. Pivot moved values from cells into column names, unpivot moved them back, and no number changed on the way. That is the whole promise of these two methods, and it is worth stating plainly: <strong>they rearrange, they do not compute</strong>.</p>
<p>The <code>fill_null(0)</code> did change something, though. Duncan now comes back with four rows of zero that were never in the original table, and they are correct, because Duncan really does speak zero lines in acts 2 through 5. Lady Macbeth also comes back with a zero for act 5, and that zero is a lie. We will find out what it is covering up in question 7.</p>
<p>Notice also that <code>act</code> came back as a string. It went into the column names, and column names are text.</p>
<ol start="4" type="1">
<li>A wide table is easy to read and hard to plot. Take the play × act counts from question 1, keep the four great tragedies, and draw one line per play showing how the number of lines moves across the five acts.</li>
</ol>
<div id="c64c4bd8" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>act_wide <span class="op">=</span> (</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    .group_by(c.play_id, c.act)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    .sort(c.act)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    .pivot(index<span class="op">=</span>c.play_id, on<span class="op">=</span>c.act, values<span class="op">=</span>c.n_lines)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id.is_in([<span class="st">"ham"</span>, <span class="st">"mac"</span>, <span class="st">"oth"</span>, <span class="st">"lr"</span>]))</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    act_wide</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    .unpivot(index<span class="op">=</span><span class="st">"play_id"</span>, variable_name<span class="op">=</span><span class="st">"act"</span>, value_name<span class="op">=</span><span class="st">"n_lines"</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    .with_columns(c.act.cast(pl.Int64))</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    .sort(c.play_id, c.act)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(x<span class="op">=</span>c.act, y<span class="op">=</span>c.n_lines, color<span class="op">=</span>c.play_id))</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    .geom_line()</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    .geom_point()</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    .labs(</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>        x<span class="op">=</span><span class="st">"Act"</span>,</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>        y<span class="op">=</span><span class="st">"Lines"</span>,</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">"Play"</span>,</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>        title<span class="op">=</span><span class="st">"Where the lines are in the four great tragedies"</span>,</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>        caption<span class="op">=</span><span class="st">"Folger Shakespeare Library"</span></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>    .theme_tufte()</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>
<figure class="figure">
<p><a href="notebook20_files/figure-html/cell-9-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="notebook20_files/figure-html/cell-9-output-1.png" width="672" height="480" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p><strong>Answer</strong>: Try to draw this from <code>act_wide</code> and you cannot. There is no <code>act</code> column to put on the x axis and no <code>play_id</code> to map to color; there are five columns named <code>1</code> through <code>5</code> and a <code>play_id</code> down the side. You could hardcode <code>y=c["3"]</code> for a single act, but there is no way to write “one line per play across the acts”, because acts are not a variable in that table. They are column names.</p>
<p>Unpivot puts act back into the data as a column and the plot becomes one line of aesthetics. This is the general rule: before you plot, check that every variable you want to map to an aesthetic has a column of its own. If it does not, unpivot first.</p>
<p>The <code>.cast(pl.Int64)</code> is there because <code>act</code> came back as text, and a text axis would draw five categories rather than a numeric line.</p>
<p>Now read the plot, because one of these lines is strange. <em>Othello</em> peaks in act 3, the long scene where Iago talks Othello into it, and <em>Lear</em> is flat, and both of those are reasonable. <em>Hamlet</em> is not. It has 897 lines in act 1 and 423 in act 2, a drop of more than half, and act 2 of <em>Hamlet</em> is not a short act. It has Polonius, the arrival of the players, the whole of Rosencrantz and Guildenstern, and “What a piece of work is a man”. On the page it is nearly as long as act 1.</p>
<p>Something is missing from act 2, and this chart cannot tell you what. Remember the shape of that line. Question 8 explains it.</p>
<ol start="5" type="1">
<li>On to <code>.explode()</code> and the second IOU. Some cells of <code>character_id</code> hold more than one speaker, joined with a hash, which is how the Folger records characters speaking in unison. Split those cells apart, give each speaker their own row, and recount the speakers of <em>Macbeth</em>.</li>
</ol>
<div id="4702cfe1" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>speak <span class="op">=</span> (</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    .with_columns(speaker <span class="op">=</span> c.character_id.<span class="bu">str</span>.split(<span class="st">" #"</span>))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    .explode(c.speaker)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(line.select(rows <span class="op">=</span> pl.<span class="bu">len</span>()))</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(speak.select(rows <span class="op">=</span> pl.<span class="bu">len</span>()))</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(line.<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>).select(mac_speakers <span class="op">=</span> c.character_id.n_unique()))</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(speak.<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>).select(mac_speakers <span class="op">=</span> c.speaker.n_unique()))</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    speak</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    .group_by(c.speaker)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.speaker.<span class="bu">str</span>.contains(<span class="st">"WITCH"</span>))</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>shape: (1, 1)
┌───────┐
│ rows  │
│ ---   │
│ u32   │
╞═══════╡
│ 80592 │
└───────┘
shape: (1, 1)
┌───────┐
│ rows  │
│ ---   │
│ u32   │
╞═══════╡
│ 80968 │
└───────┘
shape: (1, 1)
┌──────────────┐
│ mac_speakers │
│ ---          │
│ u32          │
╞══════════════╡
│ 49           │
└──────────────┘
shape: (1, 1)
┌──────────────┐
│ mac_speakers │
│ ---          │
│ u32          │
╞══════════════╡
│ 44           │
└──────────────┘</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/5w/rxshd8hd6vv8mxsbj211mr_m0000gn/T/ipykernel_48051/2666984616.py:4: DeprecationWarning: In Polars 2.0, the default behavior for `empty_as_null` will change to `False`. To keep the current behavior, explicitly set `empty_as_null=True`.</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (3, 2)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">speaker</th>
<th data-quarto-table-cell-role="th">n_lines</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"WITCHES.1_Mac"</td>
<td>80</td>
</tr>
<tr class="even">
<td>"WITCHES.3_Mac"</td>
<td>46</td>
</tr>
<tr class="odd">
<td>"WITCHES.2_Mac"</td>
<td>45</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Answer</strong>: <code>.str.split(" #")</code> turns each cell into a list, usually a list of one. <code>.explode()</code> then gives every element of every list its own row, copying the rest of the row alongside it. The table grows from 80,592 rows to 80,968, which is 376 extra rows out of the 177 lines that had more than one speaker in them.</p>
<p>The Witches are the payoff. Before the explode, the lines table had four witch-shaped speakers: three witches with 59, 25, and 24 lines, and a phantom fourth called <code>WITCHES.1_Mac #WITCHES.2_Mac #WITCHES.3_Mac</code> with 21 more. Afterwards there are three, with 80, 45, and 46, and the unison lines have been credited to all three of the characters who actually say them. <em>Macbeth</em> goes from 49 distinct speakers to 44, and the 49 was never a real number.</p>
<p>This is what <code>.explode()</code> is for: a cell that holds a <em>set</em> of values of the same kind. It undoes the packing without deciding anything.</p>
<ol start="6" type="1">
<li>Now draw the twelve biggest parts in Shakespeare, using the speakers you just unpacked and the compound key from last time, and label the bars with the characters’ real names from <code>char</code>.</li>
</ol>
<div id="fd046ec6" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    speak</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    .group_by(c.speaker, c.play_id)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">12</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    .join(char, left_on<span class="op">=</span>[c.speaker, c.play_id], right_on<span class="op">=</span>[c.character_id, c.play_id])</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(c.name, c.n_lines))</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    .geom_col(fill<span class="op">=</span><span class="st">"#F5276C"</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    .coord_flip()</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    .labs(</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>        x<span class="op">=</span><span class="st">""</span>,</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>        y<span class="op">=</span><span class="st">"Lines spoken"</span>,</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>        title<span class="op">=</span><span class="st">"The twelve biggest parts in Shakespeare"</span>,</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>        caption<span class="op">=</span><span class="st">"Folger Shakespeare Library"</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>    .theme_tufte()</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>
<figure class="figure">
<p><a href="notebook20_files/figure-html/cell-11-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="notebook20_files/figure-html/cell-11-output-1.png" width="672" height="480" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p><strong>Answer</strong>: The last time we drew this chart the fifth bar was labelled <code>Antony_JC</code> and the lines were from <em>Antony and Cleopatra</em>, because the id was minted in <em>Julius Caesar</em> and the id was all we had. Now the bar says Antony, because the name came from <code>char</code>.</p>
<p>Look closely at the join. It matches on <strong>both</strong> <code>speaker</code> and <code>play_id</code>, and it has to. Join on <code>character_id</code> alone and the twelve rows come back as seventeen, because <code>RichardIII_R3</code> has three rows in <code>char</code> (Richard of Gloucester turns up in both parts of <em>Henry VI</em> before he gets his own play) and the join copies his bar three times. That is the fan-out from last class, and what causes it is the broken key from the class before that: a right-hand table whose key repeats will multiply your rows, and <code>char</code> is that table. The compound key <code>character_id</code> plus <code>play_id</code> is unique, so joining on both returns twelve rows and twelve bars.</p>
<p>One more thing about this chart, and it is a name that is <em>not</em> on it. Falstaff is the largest comic part Shakespeare ever wrote and he does not make the top twelve. Keep that in your pocket too.</p>
<ol start="7" type="1">
<li>The last IOU, and the hardest. <code>line_number</code> holds <code>"3.1.64"</code>: three variables glued into one cell with periods. Split it and explode it, and see what you get.</li>
</ol>
<div id="fd58bd93" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    .select(c.line_id, c.line_number)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    .with_columns(piece <span class="op">=</span> c.line_number.<span class="bu">str</span>.split(<span class="st">"."</span>))</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    .explode(c.piece)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">6</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/5w/rxshd8hd6vv8mxsbj211mr_m0000gn/T/ipykernel_48051/3839429912.py:5: DeprecationWarning: In Polars 2.0, the default behavior for `empty_as_null` will change to `False`. To keep the current behavior, explicitly set `empty_as_null=True`.</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (6, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">line_id</th>
<th data-quarto-table-cell-role="th">line_number</th>
<th data-quarto-table-cell-role="th">piece</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"mnd_line_000001"</td>
<td>"1.1.1"</td>
<td>"1"</td>
</tr>
<tr class="even">
<td>"mnd_line_000001"</td>
<td>"1.1.1"</td>
<td>"1"</td>
</tr>
<tr class="odd">
<td>"mnd_line_000001"</td>
<td>"1.1.1"</td>
<td>"1"</td>
</tr>
<tr class="even">
<td>"mnd_line_000002"</td>
<td>"1.1.2"</td>
<td>"1"</td>
</tr>
<tr class="odd">
<td>"mnd_line_000002"</td>
<td>"1.1.2"</td>
<td>"1"</td>
</tr>
<tr class="even">
<td>"mnd_line_000002"</td>
<td>"1.1.2"</td>
<td>"2"</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Answer</strong>: Three rows per line, and they are useless. Explode was the right tool for the multi-speaker cells, where a cell held three values of the <em>same</em> variable, and it is the wrong tool here, where a cell holds one value each of <em>three different</em> variables. Stacking act, scene, and line number into a column called <code>piece</code> is not a repair. It is a worse packing.</p>
<p>What we need is for those three pieces to become three columns, and turning rows into columns is a pivot. So: explode to get one piece per row, number the pieces within each line so the pivot knows which column each one belongs in, then pivot them back out. Use <code>.cum_count()</code>, which is <code>.cum_sum()</code>’s sibling and counts rows rather than adding them up.</p>
<div id="8f71c4bc" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>line_num <span class="op">=</span> (</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    .select(c.line_id, c.line_number)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    .with_columns(piece <span class="op">=</span> c.line_number.<span class="bu">str</span>.split(<span class="st">"."</span>))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    .explode(c.piece)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    .with_columns(part <span class="op">=</span> c.piece.cum_count().over(c.line_id))</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    .pivot(index<span class="op">=</span>c.line_id, on<span class="op">=</span>c.part, values<span class="op">=</span>c.piece)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    .rename({<span class="st">"1"</span>: <span class="st">"act_n"</span>, <span class="st">"2"</span>: <span class="st">"scene_n"</span>, <span class="st">"3"</span>: <span class="st">"num"</span>})</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    .with_columns(c.num.cast(pl.Int64))</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    .select(c.line_id, c.num)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>lines <span class="op">=</span> line.join(line_num, on<span class="op">=</span>c.line_id)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    lines</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"ham"</span>, c.act <span class="op">==</span> <span class="dv">3</span>, c.scene <span class="op">==</span> <span class="dv">1</span>)</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    .sort(c.num)</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>    .select(c.num, c.character_id, c.text)</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">4</span>)</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/5w/rxshd8hd6vv8mxsbj211mr_m0000gn/T/ipykernel_48051/2351309922.py:5: DeprecationWarning: In Polars 2.0, the default behavior for `empty_as_null` will change to `False`. To keep the current behavior, explicitly set `empty_as_null=True`.</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (4, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">num</th>
<th data-quarto-table-cell-role="th">character_id</th>
<th data-quarto-table-cell-role="th">text</th>
</tr>
<tr class="even">
<td>i64</td>
<td>str</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>"Claudius_Ham"</td>
<td>"And can you by no drift of con…</td>
</tr>
<tr class="even">
<td>2</td>
<td>"Claudius_Ham"</td>
<td>"Get from him why he puts on th…</td>
</tr>
<tr class="odd">
<td>3</td>
<td>"Claudius_Ham"</td>
<td>"Grating so harshly all his day…</td>
</tr>
<tr class="even">
<td>4</td>
<td>"Claudius_Ham"</td>
<td>"With turbulent and dangerous l…</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The scene now sorts. Last time this block gave us 3.1.1, then 3.1.10, then 3.1.100, because <code>line_number</code> was text and text sorts alphabetically. Now <code>num</code> is an <code>i64</code> and the lines come out in the order they are spoken.</p>
<p>And the line we went looking for is exactly where the packed string said it was:</p>
<div id="6008ec76" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    lines</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"ham"</span>, c.act <span class="op">==</span> <span class="dv">3</span>, c.scene <span class="op">==</span> <span class="dv">1</span>, c.num <span class="op">==</span> <span class="dv">64</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    .select(c.text)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="12">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (1, 1)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">text</th>
</tr>
<tr class="even">
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"To be or not to be — that is t…</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ol start="8" type="1">
<li>Now use the column we just built to ask a question we could not even phrase last class. Every scene numbers its lines from 1, so the highest number in a scene tells you how many lines that scene has. Compare that with how many lines the table actually holds.</li>
</ol>
<div id="0e4f0e06" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    lines</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    .group_by(c.play_id, c.act, c.scene)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    .agg(recorded <span class="op">=</span> pl.<span class="bu">len</span>(), highest <span class="op">=</span> c.num.<span class="bu">max</span>())</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    .select(</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>        scenes <span class="op">=</span> pl.<span class="bu">len</span>(),</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>        recorded <span class="op">=</span> c.recorded.<span class="bu">sum</span>(),</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>        printed <span class="op">=</span> c.highest.<span class="bu">sum</span>(),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="13">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (1, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">scenes</th>
<th data-quarto-table-cell-role="th">recorded</th>
<th data-quarto-table-cell-role="th">printed</th>
</tr>
<tr class="even">
<td>u32</td>
<td>u32</td>
<td>i64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>688</td>
<td>80592</td>
<td>101886</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="5441fe5d" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    lines</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    .group_by(c.play_id, c.act, c.scene)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    .agg(recorded <span class="op">=</span> pl.<span class="bu">len</span>(), highest <span class="op">=</span> c.num.<span class="bu">max</span>())</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    .with_columns(missing <span class="op">=</span> c.highest <span class="op">-</span> c.recorded)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    .sort(c.missing, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">6</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="14">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (6, 6)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">play_id</th>
<th data-quarto-table-cell-role="th">act</th>
<th data-quarto-table-cell-role="th">scene</th>
<th data-quarto-table-cell-role="th">recorded</th>
<th data-quarto-table-cell-role="th">highest</th>
<th data-quarto-table-cell-role="th">missing</th>
</tr>
<tr class="even">
<td>str</td>
<td>i64</td>
<td>i64</td>
<td>u32</td>
<td>i64</td>
<td>i64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"1h4"</td>
<td>2</td>
<td>4</td>
<td>24</td>
<td>545</td>
<td>521</td>
</tr>
<tr class="even">
<td>"2h4"</td>
<td>2</td>
<td>4</td>
<td>15</td>
<td>381</td>
<td>366</td>
</tr>
<tr class="odd">
<td>"aww"</td>
<td>4</td>
<td>3</td>
<td>19</td>
<td>362</td>
<td>343</td>
</tr>
<tr class="even">
<td>"ham"</td>
<td>2</td>
<td>2</td>
<td>299</td>
<td>634</td>
<td>335</td>
</tr>
<tr class="odd">
<td>"tn"</td>
<td>3</td>
<td>4</td>
<td>93</td>
<td>404</td>
<td>311</td>
</tr>
<tr class="even">
<td>"ham"</td>
<td>3</td>
<td>2</td>
<td>144</td>
<td>432</td>
<td>288</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Answer</strong>: The table holds 80,592 lines. The line numbers say there should be 101,886. More than twenty thousand lines of Shakespeare are missing, and only 123 of the 688 scenes are complete.</p>
<p>Go and look at the worst one. <em>1 Henry IV</em> 2.4 is numbered up to 545 and the table has 24 of them. That is the tavern scene at the Boar’s Head, and it is Falstaff’s scene, and Falstaff speaks prose. That is why he was not on the chart in question 6: he has <strong>eight</strong> lines in <em>1 Henry IV</em>.</p>
<p>Once you know what you are looking for, the corpus is full of it. Macbeth 5.1 starts at line 75, because lines 1 through 74 are the sleepwalking scene, and “Out, damned spot” is not in this corpus at all, which is why Lady Macbeth had a <code>null</code> in act 5 back in question 2. Macbeth 2.3 starts at line 22, because the Porter’s speech is prose, and <code>Porter_Mac</code> has a row in <code>char</code> and zero lines in <code>line</code>. And <em>Hamlet</em> act 2, the line on the chart in question 4 that fell off a cliff, is numbered up to 768 and keeps 423, because act 2 is where Hamlet starts talking to people in prose.</p>
<p>So go back and look at <code>line_type</code> one more time. Every one of the 80,592 rows says <code>verse</code>, and last class we called that a broken label on a column that could not vary. It was not broken. It was telling the truth. This table holds the verse and nothing else, and the prose was never in it. The column with one value was not a useless column. It was a decision somebody made, recorded honestly, and we could not read it until we had prised a variable out of a packed cell.</p>
<ol start="9" type="1">
<li>Draw it. Compute, for each play, the share of its numbered lines that the table actually holds, and plot the twelve plays that come off worst.</li>
</ol>
<div id="4cf4d8e5" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    lines</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    .group_by(c.play_id, c.act, c.scene)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    .agg(recorded <span class="op">=</span> pl.<span class="bu">len</span>(), highest <span class="op">=</span> c.num.<span class="bu">max</span>())</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    .group_by(c.play_id)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    .agg(recorded <span class="op">=</span> c.recorded.<span class="bu">sum</span>(), printed <span class="op">=</span> c.highest.<span class="bu">sum</span>())</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    .with_columns(share <span class="op">=</span> c.recorded <span class="op">/</span> c.printed)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    .join(play.select(c.play_id, c.short_title), on<span class="op">=</span>c.play_id)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    .sort(c.share)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">12</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    .sort(c.share, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(c.short_title, c.share))</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    .geom_col(fill<span class="op">=</span><span class="st">"#F5276C"</span>)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    .coord_flip()</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>    .labs(</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>        x<span class="op">=</span><span class="st">""</span>,</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>        y<span class="op">=</span><span class="st">"Share of numbered lines present in the table"</span>,</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>        title<span class="op">=</span><span class="st">"The plays this corpus loses the most of"</span>,</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>        caption<span class="op">=</span><span class="st">"Folger Shakespeare Library"</span></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>    .theme_tufte()</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>
<figure class="figure">
<p><a href="notebook20_files/figure-html/cell-17-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="notebook20_files/figure-html/cell-17-output-1.png" width="672" height="480" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p><strong>Answer</strong>: If the missing lines are the prose, then this chart is a ranking of Shakespeare’s plays by how much prose is in them, and it should be checkable against what people already know about the plays. It is.</p>
<p>At the bottom is <em>The Merry Wives of Windsor</em>, which keeps 30 percent of its lines and is the most prose-heavy thing Shakespeare wrote. Above it come <em>Twelfth Night</em>, <em>Much Ado About Nothing</em>, <em>All’s Well</em>, <em>1 Henry IV</em> and <em>As You Like It</em>: the comedies and the Falstaff plays, which is exactly where the prose lives. Run the same chain sorted the other way and the top of the list is <em>1 Henry VI</em>, <em>King John</em>, <em>3 Henry VI</em> and <em>Richard II</em>, all of them at 97 percent or better, and <em>Richard II</em> is famous for being written entirely in verse.</p>
<p>Two honest notes. The share is approximate, since even the all-verse plays come in a point or two below 100, so a line goes missing here and there for reasons that have nothing to do with prose. And no amount of reshaping will get the prose back. Everything else in this notebook was a change of shape; this is a hole in the data.</p>
<ol start="10" type="1">
<li>Last question, and it is a written one. We used four methods today. <code>.pivot()</code> and <code>.unpivot()</code> are reversible, and <code>.explode()</code> is close to it. <code>.group_by()</code> and <code>.agg()</code>, which we have had since chapter 5, are not. Why does that difference matter, and what does it tell you about how to store a table?</li>
</ol>
<p><strong>Answer</strong>: A pivot moves values between cells and column names and invents nothing, so an unpivot puts them back. Question 3 did the round trip and every number survived it. Aggregation is not a reshape. When we counted lines per act in question 1 we destroyed 80,592 rows of text to make 185 numbers, and there is no method that gives the text back. Aggregation runs downhill only.</p>
<p>That is the argument for storing data long. A long table can be pivoted into any wide shape an analysis wants and pivoted back afterwards, so the wide table costs nothing and commits you to nothing. A table that has already been aggregated is a decision that somebody else made on your behalf, permanently. The Folger stored the lines and let us count them; had they stored the counts, this notebook would have been one question long.</p>
<p>Which is the right note to end the semester on, because the corpus turns out to prove the point against itself. Somebody, somewhere upstream, ran a filter and kept the verse. It was not recorded as a decision. It was recorded as a column called <code>line_type</code> with one value in it, and a set of line numbers that no longer added up, and it took a pivot, an explode, and another pivot to notice. Every table you are ever handed is the output of choices like that one. Your job is to find out what they were before you build on top of them.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script>
document.addEventListener('DOMContentLoaded', function() {
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details .sourceCode");
      for (let i = 0; i < detailsSrc.length; i++) {
        const details = detailsSrc[i].closest('details');
        if (details) {
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
      }
      return false;
    };
  }
  // Replace buttons to strip the broken listeners Quarto attached, then re-add fixed ones
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    const fresh = hideAllCode.cloneNode(true);
    hideAllCode.parentNode.replaceChild(fresh, hideAllCode);
    fresh.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    const fresh = showAllCode.cloneNode(true);
    showAllCode.parentNode.replaceChild(fresh, showAllCode);
    fresh.addEventListener("click", toggleCodeHandler(true));
  }
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Notebook20"</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="an">solutions-release-date:</span><span class="co"> "2026-11-11"</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">### Setup</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>Run all of the following before starting the notebook.</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [noclear]</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a><span class="op">!</span> wget <span class="op">-</span>q <span class="op">-</span>nc https:<span class="op">//</span>raw.githubusercontent.com<span class="op">/</span>taylor<span class="op">-</span>arnold<span class="op">/</span>fds2<span class="op">/</span>refs<span class="op">/</span>heads<span class="op">/</span>main<span class="op">/</span>funs.py</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [noclear]</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotnine <span class="im">import</span> ggplot, aes</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> polars <span class="im">import</span> col <span class="im">as</span> c</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> funs</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>ub <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/taylor-arnold/fds2/refs/heads/main/"</span></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [remove]</span></span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a>ub <span class="op">=</span> <span class="st">""</span></span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-41"><a href="#cb20-41" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-42"><a href="#cb20-42" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [noclear]</span></span>
<span id="cb20-43"><a href="#cb20-43" aria-hidden="true" tabindex="-1"></a>play <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/shakespeare_plays.csv"</span>)</span>
<span id="cb20-44"><a href="#cb20-44" aria-hidden="true" tabindex="-1"></a>char <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/shakespeare_characters.csv"</span>)</span>
<span id="cb20-45"><a href="#cb20-45" aria-hidden="true" tabindex="-1"></a>line <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/shakespeare_lines.csv.gz"</span>)</span>
<span id="cb20-46"><a href="#cb20-46" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-47"><a href="#cb20-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-48"><a href="#cb20-48" aria-hidden="true" tabindex="-1"></a><span class="fu">### Questions</span></span>
<span id="cb20-49"><a href="#cb20-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-50"><a href="#cb20-50" aria-hidden="true" tabindex="-1"></a>Back to the Folger Shakespeare corpus, and back to the three tables we spent an earlier</span>
<span id="cb20-51"><a href="#cb20-51" aria-hidden="true" tabindex="-1"></a>class diagnosing. A row of <span class="in">`play`</span> is a play (37 of them), a row of <span class="in">`char`</span> is a character in</span>
<span id="cb20-52"><a href="#cb20-52" aria-hidden="true" tabindex="-1"></a>a play (1,126, and remember that <span class="in">`character_id`</span> alone does not identify one), and a row of</span>
<span id="cb20-53"><a href="#cb20-53" aria-hidden="true" tabindex="-1"></a><span class="in">`line`</span> is a single printed line (80,592), with an <span class="in">`act`</span>, a <span class="in">`scene`</span>, a <span class="in">`line_number`</span> such as</span>
<span id="cb20-54"><a href="#cb20-54" aria-hidden="true" tabindex="-1"></a><span class="in">`"3.1.64"`</span>, and the <span class="in">`text`</span> itself.</span>
<span id="cb20-55"><a href="#cb20-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-56"><a href="#cb20-56" aria-hidden="true" tabindex="-1"></a>We left that class holding three IOUs. We could not sort a scene, because the number that</span>
<span id="cb20-57"><a href="#cb20-57" aria-hidden="true" tabindex="-1"></a>orders the speeches was buried inside a string. We could not count Macbeth's speaking parts,</span>
<span id="cb20-58"><a href="#cb20-58" aria-hidden="true" tabindex="-1"></a>because some cells held three speakers at once. And we could not build a table with one row</span>
<span id="cb20-59"><a href="#cb20-59" aria-hidden="true" tabindex="-1"></a>per play and one column per act, because that is a pivot and we did not have one.</span>
<span id="cb20-60"><a href="#cb20-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-61"><a href="#cb20-61" aria-hidden="true" tabindex="-1"></a>This is the class where we pay all three. <span class="in">`.pivot()`</span> and <span class="in">`.unpivot()`</span> change a table's shape</span>
<span id="cb20-62"><a href="#cb20-62" aria-hidden="true" tabindex="-1"></a>without changing anything in it, and <span class="in">`.explode()`</span> gives every element of a packed cell its</span>
<span id="cb20-63"><a href="#cb20-63" aria-hidden="true" tabindex="-1"></a>own row. You also have joins now, which we did not have last time, so the tables can finally</span>
<span id="cb20-64"><a href="#cb20-64" aria-hidden="true" tabindex="-1"></a>talk to each other.</span>
<span id="cb20-65"><a href="#cb20-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-66"><a href="#cb20-66" aria-hidden="true" tabindex="-1"></a>What comes out at the end is not a tidier table. It is a fact about this corpus that we had</span>
<span id="cb20-67"><a href="#cb20-67" aria-hidden="true" tabindex="-1"></a>no way of reaching before today, and once you see it you cannot unsee it.</span>
<span id="cb20-68"><a href="#cb20-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-69"><a href="#cb20-69" aria-hidden="true" tabindex="-1"></a>Unless a question says otherwise, just print the result of each block; do not save it to a</span>
<span id="cb20-70"><a href="#cb20-70" aria-hidden="true" tabindex="-1"></a>variable.</span>
<span id="cb20-71"><a href="#cb20-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-72"><a href="#cb20-72" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Start with the IOU we ended on last time. Count the lines in each act of each play, then</span>
<span id="cb20-73"><a href="#cb20-73" aria-hidden="true" tabindex="-1"></a>reshape the result so that there is one row per play and one column per act. Join <span class="in">`play`</span> so</span>
<span id="cb20-74"><a href="#cb20-74" aria-hidden="true" tabindex="-1"></a>the rows have readable names.</span>
<span id="cb20-75"><a href="#cb20-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-78"><a href="#cb20-78" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-79"><a href="#cb20-79" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb20-80"><a href="#cb20-80" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb20-81"><a href="#cb20-81" aria-hidden="true" tabindex="-1"></a>    .group_by(c.play_id, c.act)</span>
<span id="cb20-82"><a href="#cb20-82" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb20-83"><a href="#cb20-83" aria-hidden="true" tabindex="-1"></a>    .sort(c.act)</span>
<span id="cb20-84"><a href="#cb20-84" aria-hidden="true" tabindex="-1"></a>    .pivot(index<span class="op">=</span>c.play_id, on<span class="op">=</span>c.act, values<span class="op">=</span>c.n_lines)</span>
<span id="cb20-85"><a href="#cb20-85" aria-hidden="true" tabindex="-1"></a>    .join(play.select(c.play_id, c.short_title), on<span class="op">=</span>c.play_id)</span>
<span id="cb20-86"><a href="#cb20-86" aria-hidden="true" tabindex="-1"></a>    .sort(c.short_title)</span>
<span id="cb20-87"><a href="#cb20-87" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">8</span>)</span>
<span id="cb20-88"><a href="#cb20-88" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-89"><a href="#cb20-89" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-90"><a href="#cb20-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-91"><a href="#cb20-91" aria-hidden="true" tabindex="-1"></a>**Answer**: The <span class="in">`group_by`</span> and <span class="in">`agg`</span> give the numbers long: 185 rows, one per play × act,</span>
<span id="cb20-92"><a href="#cb20-92" aria-hidden="true" tabindex="-1"></a>with an <span class="in">`act`</span> column and an <span class="in">`n_lines`</span> column. The <span class="in">`.pivot()`</span> then moves <span class="in">`act`</span> out of the</span>
<span id="cb20-93"><a href="#cb20-93" aria-hidden="true" tabindex="-1"></a>data and into the column names. <span class="in">`index`</span> is the column that stays and becomes the new unit of</span>
<span id="cb20-94"><a href="#cb20-94" aria-hidden="true" tabindex="-1"></a>observation, <span class="in">`on`</span> is the column whose values become new column names, and <span class="in">`values`</span> is what</span>
<span id="cb20-95"><a href="#cb20-95" aria-hidden="true" tabindex="-1"></a>fills the cells.</span>
<span id="cb20-96"><a href="#cb20-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-97"><a href="#cb20-97" aria-hidden="true" tabindex="-1"></a>Note the <span class="in">`.sort(c.act)`</span> in front of the pivot. Without it the columns come out `1, 3, 5, 4,</span>
<span id="cb20-98"><a href="#cb20-98" aria-hidden="true" tabindex="-1"></a>2`, because the new column names appear in the order the values are first seen in the data,</span>
<span id="cb20-99"><a href="#cb20-99" aria-hidden="true" tabindex="-1"></a>and a <span class="in">`group_by`</span> does not promise you an order. This is the same rule that governs a</span>
<span id="cb20-100"><a href="#cb20-100" aria-hidden="true" tabindex="-1"></a>categorical axis in plotnine: if you want an order, sort for it.</span>
<span id="cb20-101"><a href="#cb20-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-102"><a href="#cb20-102" aria-hidden="true" tabindex="-1"></a>Nothing was gained or lost here. There are 37 plays and 5 acts in both shapes, and the 185</span>
<span id="cb20-103"><a href="#cb20-103" aria-hidden="true" tabindex="-1"></a>numbers are the same 185 numbers.</span>
<span id="cb20-104"><a href="#cb20-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-105"><a href="#cb20-105" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Now do the same thing one level down, and watch what changes. Take the principal</span>
<span id="cb20-106"><a href="#cb20-106" aria-hidden="true" tabindex="-1"></a>speakers of *Macbeth*, meaning anyone with at least 60 lines in the play, and build a table</span>
<span id="cb20-107"><a href="#cb20-107" aria-hidden="true" tabindex="-1"></a>with one row per speaker and one column per act.</span>
<span id="cb20-108"><a href="#cb20-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-111"><a href="#cb20-111" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-112"><a href="#cb20-112" aria-hidden="true" tabindex="-1"></a>mac_big <span class="op">=</span> (</span>
<span id="cb20-113"><a href="#cb20-113" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb20-114"><a href="#cb20-114" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>)</span>
<span id="cb20-115"><a href="#cb20-115" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id)</span>
<span id="cb20-116"><a href="#cb20-116" aria-hidden="true" tabindex="-1"></a>    .agg(total <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb20-117"><a href="#cb20-117" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.total <span class="op">&gt;=</span> <span class="dv">60</span>)</span>
<span id="cb20-118"><a href="#cb20-118" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-119"><a href="#cb20-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-120"><a href="#cb20-120" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb20-121"><a href="#cb20-121" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb20-122"><a href="#cb20-122" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>)</span>
<span id="cb20-123"><a href="#cb20-123" aria-hidden="true" tabindex="-1"></a>    .join(mac_big, on<span class="op">=</span>c.character_id, how<span class="op">=</span><span class="st">"semi"</span>)</span>
<span id="cb20-124"><a href="#cb20-124" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id, c.act)</span>
<span id="cb20-125"><a href="#cb20-125" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb20-126"><a href="#cb20-126" aria-hidden="true" tabindex="-1"></a>    .sort(c.act)</span>
<span id="cb20-127"><a href="#cb20-127" aria-hidden="true" tabindex="-1"></a>    .pivot(index<span class="op">=</span>c.character_id, on<span class="op">=</span>c.act, values<span class="op">=</span>c.n_lines)</span>
<span id="cb20-128"><a href="#cb20-128" aria-hidden="true" tabindex="-1"></a>    .sort(c.character_id)</span>
<span id="cb20-129"><a href="#cb20-129" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-130"><a href="#cb20-130" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-131"><a href="#cb20-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-132"><a href="#cb20-132" aria-hidden="true" tabindex="-1"></a>**Answer**: This pivot has holes in it. Not every speaker talks in every act, so some</span>
<span id="cb20-133"><a href="#cb20-133" aria-hidden="true" tabindex="-1"></a>combinations of speaker and act never occur in the long table, and Polars fills those cells</span>
<span id="cb20-134"><a href="#cb20-134" aria-hidden="true" tabindex="-1"></a>with <span class="in">`null`</span>.</span>
<span id="cb20-135"><a href="#cb20-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-136"><a href="#cb20-136" aria-hidden="true" tabindex="-1"></a>Read the nulls, because they are the play. Duncan speaks 69 lines in act 1 and then nothing,</span>
<span id="cb20-137"><a href="#cb20-137" aria-hidden="true" tabindex="-1"></a>which is correct: he is murdered in act 2. Banquo goes quiet after act 3, having been</span>
<span id="cb20-138"><a href="#cb20-138" aria-hidden="true" tabindex="-1"></a>murdered in 3.3, and Macduff has nothing in act 1 because he has not arrived yet. A pivot</span>
<span id="cb20-139"><a href="#cb20-139" aria-hidden="true" tabindex="-1"></a>that is full of holes is often telling you something true about the world.</span>
<span id="cb20-140"><a href="#cb20-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-141"><a href="#cb20-141" aria-hidden="true" tabindex="-1"></a>Then there is Lady Macbeth, who has 113 lines in act 1 and nothing at all in act 5. Hold on</span>
<span id="cb20-142"><a href="#cb20-142" aria-hidden="true" tabindex="-1"></a>to that. She is alive in act 5 and she has the most famous scene in the play, the one where</span>
<span id="cb20-143"><a href="#cb20-143" aria-hidden="true" tabindex="-1"></a>she walks in her sleep and cannot wash her hands. Her cell says <span class="in">`null`</span>.</span>
<span id="cb20-144"><a href="#cb20-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-145"><a href="#cb20-145" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Sometimes a hole means zero and sometimes it means something else, and a pivot cannot</span>
<span id="cb20-146"><a href="#cb20-146" aria-hidden="true" tabindex="-1"></a>tell you which. Fill them with zero and then undo the entire reshape, returning the table to</span>
<span id="cb20-147"><a href="#cb20-147" aria-hidden="true" tabindex="-1"></a>the shape it had before question 2.</span>
<span id="cb20-148"><a href="#cb20-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-151"><a href="#cb20-151" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-152"><a href="#cb20-152" aria-hidden="true" tabindex="-1"></a>mac_wide <span class="op">=</span> (</span>
<span id="cb20-153"><a href="#cb20-153" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb20-154"><a href="#cb20-154" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>)</span>
<span id="cb20-155"><a href="#cb20-155" aria-hidden="true" tabindex="-1"></a>    .join(mac_big, on<span class="op">=</span>c.character_id, how<span class="op">=</span><span class="st">"semi"</span>)</span>
<span id="cb20-156"><a href="#cb20-156" aria-hidden="true" tabindex="-1"></a>    .group_by(c.character_id, c.act)</span>
<span id="cb20-157"><a href="#cb20-157" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb20-158"><a href="#cb20-158" aria-hidden="true" tabindex="-1"></a>    .sort(c.act)</span>
<span id="cb20-159"><a href="#cb20-159" aria-hidden="true" tabindex="-1"></a>    .pivot(index<span class="op">=</span>c.character_id, on<span class="op">=</span>c.act, values<span class="op">=</span>c.n_lines)</span>
<span id="cb20-160"><a href="#cb20-160" aria-hidden="true" tabindex="-1"></a>    .fill_null(<span class="dv">0</span>)</span>
<span id="cb20-161"><a href="#cb20-161" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-162"><a href="#cb20-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-163"><a href="#cb20-163" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb20-164"><a href="#cb20-164" aria-hidden="true" tabindex="-1"></a>    mac_wide</span>
<span id="cb20-165"><a href="#cb20-165" aria-hidden="true" tabindex="-1"></a>    .unpivot(index<span class="op">=</span><span class="st">"character_id"</span>, variable_name<span class="op">=</span><span class="st">"act"</span>, value_name<span class="op">=</span><span class="st">"n_lines"</span>)</span>
<span id="cb20-166"><a href="#cb20-166" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.character_id <span class="op">==</span> <span class="st">"Duncan_Mac"</span>)</span>
<span id="cb20-167"><a href="#cb20-167" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-168"><a href="#cb20-168" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-169"><a href="#cb20-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-170"><a href="#cb20-170" aria-hidden="true" tabindex="-1"></a>**Answer**: <span class="in">`.fill_null(0)`</span> sets every empty cell to zero, and <span class="in">`.unpivot()`</span> folds the act</span>
<span id="cb20-171"><a href="#cb20-171" aria-hidden="true" tabindex="-1"></a>columns back into a single <span class="in">`act`</span> column and a single <span class="in">`n_lines`</span> column, which is exactly the</span>
<span id="cb20-172"><a href="#cb20-172" aria-hidden="true" tabindex="-1"></a>layout we pivoted away from. Give it <span class="in">`index`</span> to say which column stays put, and</span>
<span id="cb20-173"><a href="#cb20-173" aria-hidden="true" tabindex="-1"></a><span class="in">`variable_name`</span> and <span class="in">`value_name`</span> to name the two columns it creates, or you get <span class="in">`variable`</span></span>
<span id="cb20-174"><a href="#cb20-174" aria-hidden="true" tabindex="-1"></a>and <span class="in">`value`</span>.</span>
<span id="cb20-175"><a href="#cb20-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-176"><a href="#cb20-176" aria-hidden="true" tabindex="-1"></a>This is a round trip. Pivot moved values from cells into column names, unpivot moved them</span>
<span id="cb20-177"><a href="#cb20-177" aria-hidden="true" tabindex="-1"></a>back, and no number changed on the way. That is the whole promise of these two methods, and</span>
<span id="cb20-178"><a href="#cb20-178" aria-hidden="true" tabindex="-1"></a>it is worth stating plainly: **they rearrange, they do not compute**.</span>
<span id="cb20-179"><a href="#cb20-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-180"><a href="#cb20-180" aria-hidden="true" tabindex="-1"></a>The <span class="in">`fill_null(0)`</span> did change something, though. Duncan now comes back with four rows of</span>
<span id="cb20-181"><a href="#cb20-181" aria-hidden="true" tabindex="-1"></a>zero that were never in the original table, and they are correct, because Duncan really does</span>
<span id="cb20-182"><a href="#cb20-182" aria-hidden="true" tabindex="-1"></a>speak zero lines in acts 2 through 5. Lady Macbeth also comes back with a zero for act 5,</span>
<span id="cb20-183"><a href="#cb20-183" aria-hidden="true" tabindex="-1"></a>and that zero is a lie. We will find out what it is covering up in question 7.</span>
<span id="cb20-184"><a href="#cb20-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-185"><a href="#cb20-185" aria-hidden="true" tabindex="-1"></a>Notice also that <span class="in">`act`</span> came back as a string. It went into the column names, and column</span>
<span id="cb20-186"><a href="#cb20-186" aria-hidden="true" tabindex="-1"></a>names are text.</span>
<span id="cb20-187"><a href="#cb20-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-188"><a href="#cb20-188" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>A wide table is easy to read and hard to plot. Take the play × act counts from question</span>
<span id="cb20-189"><a href="#cb20-189" aria-hidden="true" tabindex="-1"></a>1, keep the four great tragedies, and draw one line per play showing how the number of lines</span>
<span id="cb20-190"><a href="#cb20-190" aria-hidden="true" tabindex="-1"></a>moves across the five acts.</span>
<span id="cb20-191"><a href="#cb20-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-194"><a href="#cb20-194" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-195"><a href="#cb20-195" aria-hidden="true" tabindex="-1"></a>act_wide <span class="op">=</span> (</span>
<span id="cb20-196"><a href="#cb20-196" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb20-197"><a href="#cb20-197" aria-hidden="true" tabindex="-1"></a>    .group_by(c.play_id, c.act)</span>
<span id="cb20-198"><a href="#cb20-198" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb20-199"><a href="#cb20-199" aria-hidden="true" tabindex="-1"></a>    .sort(c.act)</span>
<span id="cb20-200"><a href="#cb20-200" aria-hidden="true" tabindex="-1"></a>    .pivot(index<span class="op">=</span>c.play_id, on<span class="op">=</span>c.act, values<span class="op">=</span>c.n_lines)</span>
<span id="cb20-201"><a href="#cb20-201" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id.is_in([<span class="st">"ham"</span>, <span class="st">"mac"</span>, <span class="st">"oth"</span>, <span class="st">"lr"</span>]))</span>
<span id="cb20-202"><a href="#cb20-202" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-203"><a href="#cb20-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-204"><a href="#cb20-204" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb20-205"><a href="#cb20-205" aria-hidden="true" tabindex="-1"></a>    act_wide</span>
<span id="cb20-206"><a href="#cb20-206" aria-hidden="true" tabindex="-1"></a>    .unpivot(index<span class="op">=</span><span class="st">"play_id"</span>, variable_name<span class="op">=</span><span class="st">"act"</span>, value_name<span class="op">=</span><span class="st">"n_lines"</span>)</span>
<span id="cb20-207"><a href="#cb20-207" aria-hidden="true" tabindex="-1"></a>    .with_columns(c.act.cast(pl.Int64))</span>
<span id="cb20-208"><a href="#cb20-208" aria-hidden="true" tabindex="-1"></a>    .sort(c.play_id, c.act)</span>
<span id="cb20-209"><a href="#cb20-209" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(x<span class="op">=</span>c.act, y<span class="op">=</span>c.n_lines, color<span class="op">=</span>c.play_id))</span>
<span id="cb20-210"><a href="#cb20-210" aria-hidden="true" tabindex="-1"></a>    .geom_line()</span>
<span id="cb20-211"><a href="#cb20-211" aria-hidden="true" tabindex="-1"></a>    .geom_point()</span>
<span id="cb20-212"><a href="#cb20-212" aria-hidden="true" tabindex="-1"></a>    .labs(</span>
<span id="cb20-213"><a href="#cb20-213" aria-hidden="true" tabindex="-1"></a>        x<span class="op">=</span><span class="st">"Act"</span>,</span>
<span id="cb20-214"><a href="#cb20-214" aria-hidden="true" tabindex="-1"></a>        y<span class="op">=</span><span class="st">"Lines"</span>,</span>
<span id="cb20-215"><a href="#cb20-215" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">"Play"</span>,</span>
<span id="cb20-216"><a href="#cb20-216" aria-hidden="true" tabindex="-1"></a>        title<span class="op">=</span><span class="st">"Where the lines are in the four great tragedies"</span>,</span>
<span id="cb20-217"><a href="#cb20-217" aria-hidden="true" tabindex="-1"></a>        caption<span class="op">=</span><span class="st">"Folger Shakespeare Library"</span></span>
<span id="cb20-218"><a href="#cb20-218" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb20-219"><a href="#cb20-219" aria-hidden="true" tabindex="-1"></a>    .theme_tufte()</span>
<span id="cb20-220"><a href="#cb20-220" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-221"><a href="#cb20-221" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-222"><a href="#cb20-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-223"><a href="#cb20-223" aria-hidden="true" tabindex="-1"></a>**Answer**: Try to draw this from <span class="in">`act_wide`</span> and you cannot. There is no <span class="in">`act`</span> column to put</span>
<span id="cb20-224"><a href="#cb20-224" aria-hidden="true" tabindex="-1"></a>on the x axis and no <span class="in">`play_id`</span> to map to color; there are five columns named <span class="in">`1`</span> through <span class="in">`5`</span></span>
<span id="cb20-225"><a href="#cb20-225" aria-hidden="true" tabindex="-1"></a>and a <span class="in">`play_id`</span> down the side. You could hardcode <span class="in">`y=c["3"]`</span> for a single act, but there is</span>
<span id="cb20-226"><a href="#cb20-226" aria-hidden="true" tabindex="-1"></a>no way to write "one line per play across the acts", because acts are not a variable in that</span>
<span id="cb20-227"><a href="#cb20-227" aria-hidden="true" tabindex="-1"></a>table. They are column names.</span>
<span id="cb20-228"><a href="#cb20-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-229"><a href="#cb20-229" aria-hidden="true" tabindex="-1"></a>Unpivot puts act back into the data as a column and the plot becomes one line of aesthetics.</span>
<span id="cb20-230"><a href="#cb20-230" aria-hidden="true" tabindex="-1"></a>This is the general rule: before you plot, check that every variable you want to map to an</span>
<span id="cb20-231"><a href="#cb20-231" aria-hidden="true" tabindex="-1"></a>aesthetic has a column of its own. If it does not, unpivot first.</span>
<span id="cb20-232"><a href="#cb20-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-233"><a href="#cb20-233" aria-hidden="true" tabindex="-1"></a>The <span class="in">`.cast(pl.Int64)`</span> is there because <span class="in">`act`</span> came back as text, and a text axis would draw</span>
<span id="cb20-234"><a href="#cb20-234" aria-hidden="true" tabindex="-1"></a>five categories rather than a numeric line.</span>
<span id="cb20-235"><a href="#cb20-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-236"><a href="#cb20-236" aria-hidden="true" tabindex="-1"></a>Now read the plot, because one of these lines is strange. *Othello* peaks in act 3, the long</span>
<span id="cb20-237"><a href="#cb20-237" aria-hidden="true" tabindex="-1"></a>scene where Iago talks Othello into it, and *Lear* is flat, and both of those are reasonable.</span>
<span id="cb20-238"><a href="#cb20-238" aria-hidden="true" tabindex="-1"></a>*Hamlet* is not. It has 897 lines in act 1 and 423 in act 2, a drop of more than half, and</span>
<span id="cb20-239"><a href="#cb20-239" aria-hidden="true" tabindex="-1"></a>act 2 of *Hamlet* is not a short act. It has Polonius, the arrival of the players, the whole</span>
<span id="cb20-240"><a href="#cb20-240" aria-hidden="true" tabindex="-1"></a>of Rosencrantz and Guildenstern, and "What a piece of work is a man". On the page it is</span>
<span id="cb20-241"><a href="#cb20-241" aria-hidden="true" tabindex="-1"></a>nearly as long as act 1.</span>
<span id="cb20-242"><a href="#cb20-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-243"><a href="#cb20-243" aria-hidden="true" tabindex="-1"></a>Something is missing from act 2, and this chart cannot tell you what. Remember the shape of</span>
<span id="cb20-244"><a href="#cb20-244" aria-hidden="true" tabindex="-1"></a>that line. Question 8 explains it.</span>
<span id="cb20-245"><a href="#cb20-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-246"><a href="#cb20-246" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>On to <span class="in">`.explode()`</span> and the second IOU. Some cells of <span class="in">`character_id`</span> hold more than one</span>
<span id="cb20-247"><a href="#cb20-247" aria-hidden="true" tabindex="-1"></a>speaker, joined with a hash, which is how the Folger records characters speaking in unison.</span>
<span id="cb20-248"><a href="#cb20-248" aria-hidden="true" tabindex="-1"></a>Split those cells apart, give each speaker their own row, and recount the speakers of</span>
<span id="cb20-249"><a href="#cb20-249" aria-hidden="true" tabindex="-1"></a>*Macbeth*.</span>
<span id="cb20-250"><a href="#cb20-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-253"><a href="#cb20-253" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-254"><a href="#cb20-254" aria-hidden="true" tabindex="-1"></a>speak <span class="op">=</span> (</span>
<span id="cb20-255"><a href="#cb20-255" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb20-256"><a href="#cb20-256" aria-hidden="true" tabindex="-1"></a>    .with_columns(speaker <span class="op">=</span> c.character_id.<span class="bu">str</span>.split(<span class="st">" #"</span>))</span>
<span id="cb20-257"><a href="#cb20-257" aria-hidden="true" tabindex="-1"></a>    .explode(c.speaker)</span>
<span id="cb20-258"><a href="#cb20-258" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-259"><a href="#cb20-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-260"><a href="#cb20-260" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(line.select(rows <span class="op">=</span> pl.<span class="bu">len</span>()))</span>
<span id="cb20-261"><a href="#cb20-261" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(speak.select(rows <span class="op">=</span> pl.<span class="bu">len</span>()))</span>
<span id="cb20-262"><a href="#cb20-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-263"><a href="#cb20-263" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(line.<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>).select(mac_speakers <span class="op">=</span> c.character_id.n_unique()))</span>
<span id="cb20-264"><a href="#cb20-264" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(speak.<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>).select(mac_speakers <span class="op">=</span> c.speaker.n_unique()))</span>
<span id="cb20-265"><a href="#cb20-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-266"><a href="#cb20-266" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb20-267"><a href="#cb20-267" aria-hidden="true" tabindex="-1"></a>    speak</span>
<span id="cb20-268"><a href="#cb20-268" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"mac"</span>)</span>
<span id="cb20-269"><a href="#cb20-269" aria-hidden="true" tabindex="-1"></a>    .group_by(c.speaker)</span>
<span id="cb20-270"><a href="#cb20-270" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb20-271"><a href="#cb20-271" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.speaker.<span class="bu">str</span>.contains(<span class="st">"WITCH"</span>))</span>
<span id="cb20-272"><a href="#cb20-272" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb20-273"><a href="#cb20-273" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-274"><a href="#cb20-274" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-275"><a href="#cb20-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-276"><a href="#cb20-276" aria-hidden="true" tabindex="-1"></a>**Answer**: <span class="in">`.str.split(" #")`</span> turns each cell into a list, usually a list of one.</span>
<span id="cb20-277"><a href="#cb20-277" aria-hidden="true" tabindex="-1"></a><span class="in">`.explode()`</span> then gives every element of every list its own row, copying the rest of the row</span>
<span id="cb20-278"><a href="#cb20-278" aria-hidden="true" tabindex="-1"></a>alongside it. The table grows from 80,592 rows to 80,968, which is 376 extra rows out of the</span>
<span id="cb20-279"><a href="#cb20-279" aria-hidden="true" tabindex="-1"></a>177 lines that had more than one speaker in them.</span>
<span id="cb20-280"><a href="#cb20-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-281"><a href="#cb20-281" aria-hidden="true" tabindex="-1"></a>The Witches are the payoff. Before the explode, the lines table had four witch-shaped</span>
<span id="cb20-282"><a href="#cb20-282" aria-hidden="true" tabindex="-1"></a>speakers: three witches with 59, 25, and 24 lines, and a phantom fourth called</span>
<span id="cb20-283"><a href="#cb20-283" aria-hidden="true" tabindex="-1"></a><span class="in">`WITCHES.1_Mac #WITCHES.2_Mac #WITCHES.3_Mac`</span> with 21 more. Afterwards there are three, with</span>
<span id="cb20-284"><a href="#cb20-284" aria-hidden="true" tabindex="-1"></a>80, 45, and 46, and the unison lines have been credited to all three of the characters who</span>
<span id="cb20-285"><a href="#cb20-285" aria-hidden="true" tabindex="-1"></a>actually say them. *Macbeth* goes from 49 distinct speakers to 44, and the 49 was never a</span>
<span id="cb20-286"><a href="#cb20-286" aria-hidden="true" tabindex="-1"></a>real number.</span>
<span id="cb20-287"><a href="#cb20-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-288"><a href="#cb20-288" aria-hidden="true" tabindex="-1"></a>This is what <span class="in">`.explode()`</span> is for: a cell that holds a *set* of values of the same kind. It</span>
<span id="cb20-289"><a href="#cb20-289" aria-hidden="true" tabindex="-1"></a>undoes the packing without deciding anything.</span>
<span id="cb20-290"><a href="#cb20-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-291"><a href="#cb20-291" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>Now draw the twelve biggest parts in Shakespeare, using the speakers you just unpacked</span>
<span id="cb20-292"><a href="#cb20-292" aria-hidden="true" tabindex="-1"></a>and the compound key from last time, and label the bars with the characters' real names from</span>
<span id="cb20-293"><a href="#cb20-293" aria-hidden="true" tabindex="-1"></a><span class="in">`char`</span>.</span>
<span id="cb20-294"><a href="#cb20-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-297"><a href="#cb20-297" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-298"><a href="#cb20-298" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb20-299"><a href="#cb20-299" aria-hidden="true" tabindex="-1"></a>    speak</span>
<span id="cb20-300"><a href="#cb20-300" aria-hidden="true" tabindex="-1"></a>    .group_by(c.speaker, c.play_id)</span>
<span id="cb20-301"><a href="#cb20-301" aria-hidden="true" tabindex="-1"></a>    .agg(n_lines <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb20-302"><a href="#cb20-302" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb20-303"><a href="#cb20-303" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">12</span>)</span>
<span id="cb20-304"><a href="#cb20-304" aria-hidden="true" tabindex="-1"></a>    .join(char, left_on<span class="op">=</span>[c.speaker, c.play_id], right_on<span class="op">=</span>[c.character_id, c.play_id])</span>
<span id="cb20-305"><a href="#cb20-305" aria-hidden="true" tabindex="-1"></a>    .sort(c.n_lines)</span>
<span id="cb20-306"><a href="#cb20-306" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(c.name, c.n_lines))</span>
<span id="cb20-307"><a href="#cb20-307" aria-hidden="true" tabindex="-1"></a>    .geom_col(fill<span class="op">=</span><span class="st">"#F5276C"</span>)</span>
<span id="cb20-308"><a href="#cb20-308" aria-hidden="true" tabindex="-1"></a>    .coord_flip()</span>
<span id="cb20-309"><a href="#cb20-309" aria-hidden="true" tabindex="-1"></a>    .labs(</span>
<span id="cb20-310"><a href="#cb20-310" aria-hidden="true" tabindex="-1"></a>        x<span class="op">=</span><span class="st">""</span>,</span>
<span id="cb20-311"><a href="#cb20-311" aria-hidden="true" tabindex="-1"></a>        y<span class="op">=</span><span class="st">"Lines spoken"</span>,</span>
<span id="cb20-312"><a href="#cb20-312" aria-hidden="true" tabindex="-1"></a>        title<span class="op">=</span><span class="st">"The twelve biggest parts in Shakespeare"</span>,</span>
<span id="cb20-313"><a href="#cb20-313" aria-hidden="true" tabindex="-1"></a>        caption<span class="op">=</span><span class="st">"Folger Shakespeare Library"</span></span>
<span id="cb20-314"><a href="#cb20-314" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb20-315"><a href="#cb20-315" aria-hidden="true" tabindex="-1"></a>    .theme_tufte()</span>
<span id="cb20-316"><a href="#cb20-316" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-317"><a href="#cb20-317" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-318"><a href="#cb20-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-319"><a href="#cb20-319" aria-hidden="true" tabindex="-1"></a>**Answer**: The last time we drew this chart the fifth bar was labelled <span class="in">`Antony_JC`</span> and the</span>
<span id="cb20-320"><a href="#cb20-320" aria-hidden="true" tabindex="-1"></a>lines were from *Antony and Cleopatra*, because the id was minted in *Julius Caesar* and the</span>
<span id="cb20-321"><a href="#cb20-321" aria-hidden="true" tabindex="-1"></a>id was all we had. Now the bar says Antony, because the name came from <span class="in">`char`</span>.</span>
<span id="cb20-322"><a href="#cb20-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-323"><a href="#cb20-323" aria-hidden="true" tabindex="-1"></a>Look closely at the join. It matches on **both** <span class="in">`speaker`</span> and <span class="in">`play_id`</span>, and it has to.</span>
<span id="cb20-324"><a href="#cb20-324" aria-hidden="true" tabindex="-1"></a>Join on <span class="in">`character_id`</span> alone and the twelve rows come back as seventeen, because</span>
<span id="cb20-325"><a href="#cb20-325" aria-hidden="true" tabindex="-1"></a><span class="in">`RichardIII_R3`</span> has three rows in <span class="in">`char`</span> (Richard of Gloucester turns up in both parts of</span>
<span id="cb20-326"><a href="#cb20-326" aria-hidden="true" tabindex="-1"></a>*Henry VI* before he gets his own play) and the join copies his bar three times. That is the</span>
<span id="cb20-327"><a href="#cb20-327" aria-hidden="true" tabindex="-1"></a>fan-out from last class, and what causes it is the broken key from the class before that: a</span>
<span id="cb20-328"><a href="#cb20-328" aria-hidden="true" tabindex="-1"></a>right-hand table whose key repeats will multiply your rows, and <span class="in">`char`</span> is that table. The</span>
<span id="cb20-329"><a href="#cb20-329" aria-hidden="true" tabindex="-1"></a>compound key <span class="in">`character_id`</span> plus <span class="in">`play_id`</span> is unique, so joining on both returns twelve rows</span>
<span id="cb20-330"><a href="#cb20-330" aria-hidden="true" tabindex="-1"></a>and twelve bars.</span>
<span id="cb20-331"><a href="#cb20-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-332"><a href="#cb20-332" aria-hidden="true" tabindex="-1"></a>One more thing about this chart, and it is a name that is *not* on it. Falstaff is the largest</span>
<span id="cb20-333"><a href="#cb20-333" aria-hidden="true" tabindex="-1"></a>comic part Shakespeare ever wrote and he does not make the top twelve. Keep that in your pocket</span>
<span id="cb20-334"><a href="#cb20-334" aria-hidden="true" tabindex="-1"></a>too.</span>
<span id="cb20-335"><a href="#cb20-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-336"><a href="#cb20-336" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>The last IOU, and the hardest. <span class="in">`line_number`</span> holds <span class="in">`"3.1.64"`</span>: three variables glued into</span>
<span id="cb20-337"><a href="#cb20-337" aria-hidden="true" tabindex="-1"></a>one cell with periods. Split it and explode it, and see what you get.</span>
<span id="cb20-338"><a href="#cb20-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-341"><a href="#cb20-341" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-342"><a href="#cb20-342" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb20-343"><a href="#cb20-343" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb20-344"><a href="#cb20-344" aria-hidden="true" tabindex="-1"></a>    .select(c.line_id, c.line_number)</span>
<span id="cb20-345"><a href="#cb20-345" aria-hidden="true" tabindex="-1"></a>    .with_columns(piece <span class="op">=</span> c.line_number.<span class="bu">str</span>.split(<span class="st">"."</span>))</span>
<span id="cb20-346"><a href="#cb20-346" aria-hidden="true" tabindex="-1"></a>    .explode(c.piece)</span>
<span id="cb20-347"><a href="#cb20-347" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">6</span>)</span>
<span id="cb20-348"><a href="#cb20-348" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-349"><a href="#cb20-349" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-350"><a href="#cb20-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-351"><a href="#cb20-351" aria-hidden="true" tabindex="-1"></a>**Answer**: Three rows per line, and they are useless. Explode was the right tool for the</span>
<span id="cb20-352"><a href="#cb20-352" aria-hidden="true" tabindex="-1"></a>multi-speaker cells, where a cell held three values of the *same* variable, and it is the</span>
<span id="cb20-353"><a href="#cb20-353" aria-hidden="true" tabindex="-1"></a>wrong tool here, where a cell holds one value each of *three different* variables. Stacking</span>
<span id="cb20-354"><a href="#cb20-354" aria-hidden="true" tabindex="-1"></a>act, scene, and line number into a column called <span class="in">`piece`</span> is not a repair. It is a worse</span>
<span id="cb20-355"><a href="#cb20-355" aria-hidden="true" tabindex="-1"></a>packing.</span>
<span id="cb20-356"><a href="#cb20-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-357"><a href="#cb20-357" aria-hidden="true" tabindex="-1"></a>What we need is for those three pieces to become three columns, and turning rows into</span>
<span id="cb20-358"><a href="#cb20-358" aria-hidden="true" tabindex="-1"></a>columns is a pivot. So: explode to get one piece per row, number the pieces within each line</span>
<span id="cb20-359"><a href="#cb20-359" aria-hidden="true" tabindex="-1"></a>so the pivot knows which column each one belongs in, then pivot them back out. Use</span>
<span id="cb20-360"><a href="#cb20-360" aria-hidden="true" tabindex="-1"></a><span class="in">`.cum_count()`</span>, which is <span class="in">`.cum_sum()`</span>'s sibling and counts rows rather than adding them up.</span>
<span id="cb20-361"><a href="#cb20-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-364"><a href="#cb20-364" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-365"><a href="#cb20-365" aria-hidden="true" tabindex="-1"></a>line_num <span class="op">=</span> (</span>
<span id="cb20-366"><a href="#cb20-366" aria-hidden="true" tabindex="-1"></a>    line</span>
<span id="cb20-367"><a href="#cb20-367" aria-hidden="true" tabindex="-1"></a>    .select(c.line_id, c.line_number)</span>
<span id="cb20-368"><a href="#cb20-368" aria-hidden="true" tabindex="-1"></a>    .with_columns(piece <span class="op">=</span> c.line_number.<span class="bu">str</span>.split(<span class="st">"."</span>))</span>
<span id="cb20-369"><a href="#cb20-369" aria-hidden="true" tabindex="-1"></a>    .explode(c.piece)</span>
<span id="cb20-370"><a href="#cb20-370" aria-hidden="true" tabindex="-1"></a>    .with_columns(part <span class="op">=</span> c.piece.cum_count().over(c.line_id))</span>
<span id="cb20-371"><a href="#cb20-371" aria-hidden="true" tabindex="-1"></a>    .pivot(index<span class="op">=</span>c.line_id, on<span class="op">=</span>c.part, values<span class="op">=</span>c.piece)</span>
<span id="cb20-372"><a href="#cb20-372" aria-hidden="true" tabindex="-1"></a>    .rename({<span class="st">"1"</span>: <span class="st">"act_n"</span>, <span class="st">"2"</span>: <span class="st">"scene_n"</span>, <span class="st">"3"</span>: <span class="st">"num"</span>})</span>
<span id="cb20-373"><a href="#cb20-373" aria-hidden="true" tabindex="-1"></a>    .with_columns(c.num.cast(pl.Int64))</span>
<span id="cb20-374"><a href="#cb20-374" aria-hidden="true" tabindex="-1"></a>    .select(c.line_id, c.num)</span>
<span id="cb20-375"><a href="#cb20-375" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-376"><a href="#cb20-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-377"><a href="#cb20-377" aria-hidden="true" tabindex="-1"></a>lines <span class="op">=</span> line.join(line_num, on<span class="op">=</span>c.line_id)</span>
<span id="cb20-378"><a href="#cb20-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-379"><a href="#cb20-379" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb20-380"><a href="#cb20-380" aria-hidden="true" tabindex="-1"></a>    lines</span>
<span id="cb20-381"><a href="#cb20-381" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"ham"</span>, c.act <span class="op">==</span> <span class="dv">3</span>, c.scene <span class="op">==</span> <span class="dv">1</span>)</span>
<span id="cb20-382"><a href="#cb20-382" aria-hidden="true" tabindex="-1"></a>    .sort(c.num)</span>
<span id="cb20-383"><a href="#cb20-383" aria-hidden="true" tabindex="-1"></a>    .select(c.num, c.character_id, c.text)</span>
<span id="cb20-384"><a href="#cb20-384" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">4</span>)</span>
<span id="cb20-385"><a href="#cb20-385" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-386"><a href="#cb20-386" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-387"><a href="#cb20-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-388"><a href="#cb20-388" aria-hidden="true" tabindex="-1"></a>The scene now sorts. Last time this block gave us 3.1.1, then 3.1.10, then 3.1.100, because</span>
<span id="cb20-389"><a href="#cb20-389" aria-hidden="true" tabindex="-1"></a><span class="in">`line_number`</span> was text and text sorts alphabetically. Now <span class="in">`num`</span> is an <span class="in">`i64`</span> and the lines</span>
<span id="cb20-390"><a href="#cb20-390" aria-hidden="true" tabindex="-1"></a>come out in the order they are spoken.</span>
<span id="cb20-391"><a href="#cb20-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-392"><a href="#cb20-392" aria-hidden="true" tabindex="-1"></a>And the line we went looking for is exactly where the packed string said it was:</span>
<span id="cb20-393"><a href="#cb20-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-396"><a href="#cb20-396" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-397"><a href="#cb20-397" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb20-398"><a href="#cb20-398" aria-hidden="true" tabindex="-1"></a>    lines</span>
<span id="cb20-399"><a href="#cb20-399" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.play_id <span class="op">==</span> <span class="st">"ham"</span>, c.act <span class="op">==</span> <span class="dv">3</span>, c.scene <span class="op">==</span> <span class="dv">1</span>, c.num <span class="op">==</span> <span class="dv">64</span>)</span>
<span id="cb20-400"><a href="#cb20-400" aria-hidden="true" tabindex="-1"></a>    .select(c.text)</span>
<span id="cb20-401"><a href="#cb20-401" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-402"><a href="#cb20-402" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-403"><a href="#cb20-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-404"><a href="#cb20-404" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>Now use the column we just built to ask a question we could not even phrase last class.</span>
<span id="cb20-405"><a href="#cb20-405" aria-hidden="true" tabindex="-1"></a>Every scene numbers its lines from 1, so the highest number in a scene tells you how many</span>
<span id="cb20-406"><a href="#cb20-406" aria-hidden="true" tabindex="-1"></a>lines that scene has. Compare that with how many lines the table actually holds.</span>
<span id="cb20-407"><a href="#cb20-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-410"><a href="#cb20-410" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-411"><a href="#cb20-411" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb20-412"><a href="#cb20-412" aria-hidden="true" tabindex="-1"></a>    lines</span>
<span id="cb20-413"><a href="#cb20-413" aria-hidden="true" tabindex="-1"></a>    .group_by(c.play_id, c.act, c.scene)</span>
<span id="cb20-414"><a href="#cb20-414" aria-hidden="true" tabindex="-1"></a>    .agg(recorded <span class="op">=</span> pl.<span class="bu">len</span>(), highest <span class="op">=</span> c.num.<span class="bu">max</span>())</span>
<span id="cb20-415"><a href="#cb20-415" aria-hidden="true" tabindex="-1"></a>    .select(</span>
<span id="cb20-416"><a href="#cb20-416" aria-hidden="true" tabindex="-1"></a>        scenes <span class="op">=</span> pl.<span class="bu">len</span>(),</span>
<span id="cb20-417"><a href="#cb20-417" aria-hidden="true" tabindex="-1"></a>        recorded <span class="op">=</span> c.recorded.<span class="bu">sum</span>(),</span>
<span id="cb20-418"><a href="#cb20-418" aria-hidden="true" tabindex="-1"></a>        printed <span class="op">=</span> c.highest.<span class="bu">sum</span>(),</span>
<span id="cb20-419"><a href="#cb20-419" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb20-420"><a href="#cb20-420" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-421"><a href="#cb20-421" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-422"><a href="#cb20-422" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-425"><a href="#cb20-425" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-426"><a href="#cb20-426" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb20-427"><a href="#cb20-427" aria-hidden="true" tabindex="-1"></a>    lines</span>
<span id="cb20-428"><a href="#cb20-428" aria-hidden="true" tabindex="-1"></a>    .group_by(c.play_id, c.act, c.scene)</span>
<span id="cb20-429"><a href="#cb20-429" aria-hidden="true" tabindex="-1"></a>    .agg(recorded <span class="op">=</span> pl.<span class="bu">len</span>(), highest <span class="op">=</span> c.num.<span class="bu">max</span>())</span>
<span id="cb20-430"><a href="#cb20-430" aria-hidden="true" tabindex="-1"></a>    .with_columns(missing <span class="op">=</span> c.highest <span class="op">-</span> c.recorded)</span>
<span id="cb20-431"><a href="#cb20-431" aria-hidden="true" tabindex="-1"></a>    .sort(c.missing, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb20-432"><a href="#cb20-432" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">6</span>)</span>
<span id="cb20-433"><a href="#cb20-433" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-434"><a href="#cb20-434" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-435"><a href="#cb20-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-436"><a href="#cb20-436" aria-hidden="true" tabindex="-1"></a>**Answer**: The table holds 80,592 lines. The line numbers say there should be 101,886. More</span>
<span id="cb20-437"><a href="#cb20-437" aria-hidden="true" tabindex="-1"></a>than twenty thousand lines of Shakespeare are missing, and only 123 of the 688 scenes are</span>
<span id="cb20-438"><a href="#cb20-438" aria-hidden="true" tabindex="-1"></a>complete.</span>
<span id="cb20-439"><a href="#cb20-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-440"><a href="#cb20-440" aria-hidden="true" tabindex="-1"></a>Go and look at the worst one. *1 Henry IV* 2.4 is numbered up to 545 and the table has 24 of</span>
<span id="cb20-441"><a href="#cb20-441" aria-hidden="true" tabindex="-1"></a>them. That is the tavern scene at the Boar's Head, and it is Falstaff's scene, and Falstaff</span>
<span id="cb20-442"><a href="#cb20-442" aria-hidden="true" tabindex="-1"></a>speaks prose. That is why he was not on the chart in question 6: he has **eight** lines in</span>
<span id="cb20-443"><a href="#cb20-443" aria-hidden="true" tabindex="-1"></a>*1 Henry IV*.</span>
<span id="cb20-444"><a href="#cb20-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-445"><a href="#cb20-445" aria-hidden="true" tabindex="-1"></a>Once you know what you are looking for, the corpus is full of it. Macbeth 5.1 starts at line</span>
<span id="cb20-446"><a href="#cb20-446" aria-hidden="true" tabindex="-1"></a>75, because lines 1 through 74 are the sleepwalking scene, and "Out, damned spot" is not in</span>
<span id="cb20-447"><a href="#cb20-447" aria-hidden="true" tabindex="-1"></a>this corpus at all, which is why Lady Macbeth had a <span class="in">`null`</span> in act 5 back in question 2.</span>
<span id="cb20-448"><a href="#cb20-448" aria-hidden="true" tabindex="-1"></a>Macbeth 2.3 starts at line 22, because the Porter's speech is prose, and <span class="in">`Porter_Mac`</span> has a</span>
<span id="cb20-449"><a href="#cb20-449" aria-hidden="true" tabindex="-1"></a>row in <span class="in">`char`</span> and zero lines in <span class="in">`line`</span>. And *Hamlet* act 2, the line on the chart in question</span>
<span id="cb20-450"><a href="#cb20-450" aria-hidden="true" tabindex="-1"></a>4 that fell off a cliff, is numbered up to 768 and keeps 423, because act 2 is where Hamlet</span>
<span id="cb20-451"><a href="#cb20-451" aria-hidden="true" tabindex="-1"></a>starts talking to people in prose.</span>
<span id="cb20-452"><a href="#cb20-452" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-453"><a href="#cb20-453" aria-hidden="true" tabindex="-1"></a>So go back and look at <span class="in">`line_type`</span> one more time. Every one of the 80,592 rows says <span class="in">`verse`</span>,</span>
<span id="cb20-454"><a href="#cb20-454" aria-hidden="true" tabindex="-1"></a>and last class we called that a broken label on a column that could not vary. It was not</span>
<span id="cb20-455"><a href="#cb20-455" aria-hidden="true" tabindex="-1"></a>broken. It was telling the truth. This table holds the verse and nothing else, and the prose</span>
<span id="cb20-456"><a href="#cb20-456" aria-hidden="true" tabindex="-1"></a>was never in it. The column with one value was not a useless column. It was a decision</span>
<span id="cb20-457"><a href="#cb20-457" aria-hidden="true" tabindex="-1"></a>somebody made, recorded honestly, and we could not read it until we had prised a variable out</span>
<span id="cb20-458"><a href="#cb20-458" aria-hidden="true" tabindex="-1"></a>of a packed cell.</span>
<span id="cb20-459"><a href="#cb20-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-460"><a href="#cb20-460" aria-hidden="true" tabindex="-1"></a><span class="ss">9. </span>Draw it. Compute, for each play, the share of its numbered lines that the table actually</span>
<span id="cb20-461"><a href="#cb20-461" aria-hidden="true" tabindex="-1"></a>holds, and plot the twelve plays that come off worst.</span>
<span id="cb20-462"><a href="#cb20-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-465"><a href="#cb20-465" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb20-466"><a href="#cb20-466" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb20-467"><a href="#cb20-467" aria-hidden="true" tabindex="-1"></a>    lines</span>
<span id="cb20-468"><a href="#cb20-468" aria-hidden="true" tabindex="-1"></a>    .group_by(c.play_id, c.act, c.scene)</span>
<span id="cb20-469"><a href="#cb20-469" aria-hidden="true" tabindex="-1"></a>    .agg(recorded <span class="op">=</span> pl.<span class="bu">len</span>(), highest <span class="op">=</span> c.num.<span class="bu">max</span>())</span>
<span id="cb20-470"><a href="#cb20-470" aria-hidden="true" tabindex="-1"></a>    .group_by(c.play_id)</span>
<span id="cb20-471"><a href="#cb20-471" aria-hidden="true" tabindex="-1"></a>    .agg(recorded <span class="op">=</span> c.recorded.<span class="bu">sum</span>(), printed <span class="op">=</span> c.highest.<span class="bu">sum</span>())</span>
<span id="cb20-472"><a href="#cb20-472" aria-hidden="true" tabindex="-1"></a>    .with_columns(share <span class="op">=</span> c.recorded <span class="op">/</span> c.printed)</span>
<span id="cb20-473"><a href="#cb20-473" aria-hidden="true" tabindex="-1"></a>    .join(play.select(c.play_id, c.short_title), on<span class="op">=</span>c.play_id)</span>
<span id="cb20-474"><a href="#cb20-474" aria-hidden="true" tabindex="-1"></a>    .sort(c.share)</span>
<span id="cb20-475"><a href="#cb20-475" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">12</span>)</span>
<span id="cb20-476"><a href="#cb20-476" aria-hidden="true" tabindex="-1"></a>    .sort(c.share, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb20-477"><a href="#cb20-477" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(c.short_title, c.share))</span>
<span id="cb20-478"><a href="#cb20-478" aria-hidden="true" tabindex="-1"></a>    .geom_col(fill<span class="op">=</span><span class="st">"#F5276C"</span>)</span>
<span id="cb20-479"><a href="#cb20-479" aria-hidden="true" tabindex="-1"></a>    .coord_flip()</span>
<span id="cb20-480"><a href="#cb20-480" aria-hidden="true" tabindex="-1"></a>    .labs(</span>
<span id="cb20-481"><a href="#cb20-481" aria-hidden="true" tabindex="-1"></a>        x<span class="op">=</span><span class="st">""</span>,</span>
<span id="cb20-482"><a href="#cb20-482" aria-hidden="true" tabindex="-1"></a>        y<span class="op">=</span><span class="st">"Share of numbered lines present in the table"</span>,</span>
<span id="cb20-483"><a href="#cb20-483" aria-hidden="true" tabindex="-1"></a>        title<span class="op">=</span><span class="st">"The plays this corpus loses the most of"</span>,</span>
<span id="cb20-484"><a href="#cb20-484" aria-hidden="true" tabindex="-1"></a>        caption<span class="op">=</span><span class="st">"Folger Shakespeare Library"</span></span>
<span id="cb20-485"><a href="#cb20-485" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb20-486"><a href="#cb20-486" aria-hidden="true" tabindex="-1"></a>    .theme_tufte()</span>
<span id="cb20-487"><a href="#cb20-487" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-488"><a href="#cb20-488" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb20-489"><a href="#cb20-489" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-490"><a href="#cb20-490" aria-hidden="true" tabindex="-1"></a>**Answer**: If the missing lines are the prose, then this chart is a ranking of Shakespeare's</span>
<span id="cb20-491"><a href="#cb20-491" aria-hidden="true" tabindex="-1"></a>plays by how much prose is in them, and it should be checkable against what people already</span>
<span id="cb20-492"><a href="#cb20-492" aria-hidden="true" tabindex="-1"></a>know about the plays. It is.</span>
<span id="cb20-493"><a href="#cb20-493" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-494"><a href="#cb20-494" aria-hidden="true" tabindex="-1"></a>At the bottom is *The Merry Wives of Windsor*, which keeps 30 percent of its lines and is the</span>
<span id="cb20-495"><a href="#cb20-495" aria-hidden="true" tabindex="-1"></a>most prose-heavy thing Shakespeare wrote. Above it come *Twelfth Night*, *Much Ado About</span>
<span id="cb20-496"><a href="#cb20-496" aria-hidden="true" tabindex="-1"></a>Nothing*, *All's Well*, *1 Henry IV* and *As You Like It*: the comedies and the Falstaff</span>
<span id="cb20-497"><a href="#cb20-497" aria-hidden="true" tabindex="-1"></a>plays, which is exactly where the prose lives. Run the same chain sorted the other way and</span>
<span id="cb20-498"><a href="#cb20-498" aria-hidden="true" tabindex="-1"></a>the top of the list is *1 Henry VI*, *King John*, *3 Henry VI* and *Richard II*, all of them</span>
<span id="cb20-499"><a href="#cb20-499" aria-hidden="true" tabindex="-1"></a>at 97 percent or better, and *Richard II* is famous for being written entirely in verse.</span>
<span id="cb20-500"><a href="#cb20-500" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-501"><a href="#cb20-501" aria-hidden="true" tabindex="-1"></a>Two honest notes. The share is approximate, since even the all-verse plays come in a point or</span>
<span id="cb20-502"><a href="#cb20-502" aria-hidden="true" tabindex="-1"></a>two below 100, so a line goes missing here and there for reasons that have nothing to do with</span>
<span id="cb20-503"><a href="#cb20-503" aria-hidden="true" tabindex="-1"></a>prose. And no amount of reshaping will get the prose back. Everything else in this notebook</span>
<span id="cb20-504"><a href="#cb20-504" aria-hidden="true" tabindex="-1"></a>was a change of shape; this is a hole in the data.</span>
<span id="cb20-505"><a href="#cb20-505" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-506"><a href="#cb20-506" aria-hidden="true" tabindex="-1"></a><span class="ss">10. </span>Last question, and it is a written one. We used four methods today. <span class="in">`.pivot()`</span> and</span>
<span id="cb20-507"><a href="#cb20-507" aria-hidden="true" tabindex="-1"></a><span class="in">`.unpivot()`</span> are reversible, and <span class="in">`.explode()`</span> is close to it. <span class="in">`.group_by()`</span> and <span class="in">`.agg()`</span>,</span>
<span id="cb20-508"><a href="#cb20-508" aria-hidden="true" tabindex="-1"></a>which we have had since chapter 5, are not. Why does that difference matter, and what does it</span>
<span id="cb20-509"><a href="#cb20-509" aria-hidden="true" tabindex="-1"></a>tell you about how to store a table?</span>
<span id="cb20-510"><a href="#cb20-510" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-511"><a href="#cb20-511" aria-hidden="true" tabindex="-1"></a>**Answer**: A pivot moves values between cells and column names and invents nothing, so an</span>
<span id="cb20-512"><a href="#cb20-512" aria-hidden="true" tabindex="-1"></a>unpivot puts them back. Question 3 did the round trip and every number survived it.</span>
<span id="cb20-513"><a href="#cb20-513" aria-hidden="true" tabindex="-1"></a>Aggregation is not a reshape. When we counted lines per act in question 1 we destroyed 80,592</span>
<span id="cb20-514"><a href="#cb20-514" aria-hidden="true" tabindex="-1"></a>rows of text to make 185 numbers, and there is no method that gives the text back. Aggregation</span>
<span id="cb20-515"><a href="#cb20-515" aria-hidden="true" tabindex="-1"></a>runs downhill only.</span>
<span id="cb20-516"><a href="#cb20-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-517"><a href="#cb20-517" aria-hidden="true" tabindex="-1"></a>That is the argument for storing data long. A long table can be pivoted into any wide shape an</span>
<span id="cb20-518"><a href="#cb20-518" aria-hidden="true" tabindex="-1"></a>analysis wants and pivoted back afterwards, so the wide table costs nothing and commits you to</span>
<span id="cb20-519"><a href="#cb20-519" aria-hidden="true" tabindex="-1"></a>nothing. A table that has already been aggregated is a decision that somebody else made on your</span>
<span id="cb20-520"><a href="#cb20-520" aria-hidden="true" tabindex="-1"></a>behalf, permanently. The Folger stored the lines and let us count them; had they stored the</span>
<span id="cb20-521"><a href="#cb20-521" aria-hidden="true" tabindex="-1"></a>counts, this notebook would have been one question long.</span>
<span id="cb20-522"><a href="#cb20-522" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-523"><a href="#cb20-523" aria-hidden="true" tabindex="-1"></a>Which is the right note to end the semester on, because the corpus turns out to prove the point</span>
<span id="cb20-524"><a href="#cb20-524" aria-hidden="true" tabindex="-1"></a>against itself. Somebody, somewhere upstream, ran a filter and kept the verse. It was not</span>
<span id="cb20-525"><a href="#cb20-525" aria-hidden="true" tabindex="-1"></a>recorded as a decision. It was recorded as a column called <span class="in">`line_type`</span> with one value in it,</span>
<span id="cb20-526"><a href="#cb20-526" aria-hidden="true" tabindex="-1"></a>and a set of line numbers that no longer added up, and it took a pivot, an explode, and another</span>
<span id="cb20-527"><a href="#cb20-527" aria-hidden="true" tabindex="-1"></a>pivot to notice. Every table you are ever handed is the output of choices like that one. Your</span>
<span id="cb20-528"><a href="#cb20-528" aria-hidden="true" tabindex="-1"></a>job is to find out what they were before you build on top of them.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>