<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Notebook43 – Foundations of Data Science: Notebooks</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-77a666a5542a07a54dbe0a7f6e3b86cd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-sidebar docked fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./notebook43.html">Notebook43</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Foundations of Data Science: Notebooks</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook30.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook30</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook31.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook31</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook32.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook32</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook33.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook33</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook34.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook34</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook35.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook35</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook36.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook36</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook37.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook37</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook38.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook38</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook39.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook39</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook40.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook40</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook41.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook41</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook42.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook42</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook43.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Notebook43</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook45.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook45</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook46.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook46</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook47.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook47</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebook48.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notebook48</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Notebook43</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="setup" class="level3">
<h3 class="anchored" data-anchor-id="setup">Setup</h3>
<p>Run all of the following before starting the notebook.</p>
<div id="5071eac2" class="cell" data-tags="[&quot;noclear&quot;]" data-execution_count="1">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span> wget <span class="op">-</span>q <span class="op">-</span>nc https:<span class="op">//</span>raw.githubusercontent.com<span class="op">/</span>taylor<span class="op">-</span>arnold<span class="op">/</span>fds2<span class="op">/</span>refs<span class="op">/</span>heads<span class="op">/</span>main<span class="op">/</span>funs.py</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="53eb0ca1" class="cell" data-tags="[&quot;noclear&quot;]" data-execution_count="2">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span> pip install umap<span class="op">-</span>learn <span class="op">--</span>quiet</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span> python <span class="op">-</span>m spacy download en_core_web_sm</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span> python <span class="op">-</span>m spacy download fr_core_news_sm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="3f16f09d" class="cell" data-tags="[&quot;noclear&quot;]" data-execution_count="3">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotnine <span class="im">import</span> ggplot, aes</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> polars <span class="im">import</span> col <span class="im">as</span> c</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> funs</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> funs <span class="im">import</span> DSText, umap_text</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> spacy</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>ub <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/taylor-arnold/fds2/refs/heads/main/"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="73ad7e4c" class="cell" data-tags="[&quot;noclear&quot;]" data-execution_count="5">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>meta <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/wiki_uk_meta.csv.gz"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>text_en <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/wiki_uk_authors_text.csv"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>text_fr <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/wiki_uk_authors_text_fr.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="2952a904" class="cell" data-tags="[&quot;noclear&quot;]" data-execution_count="6">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>nlp_en <span class="op">=</span> spacy.load(<span class="st">"en_core_web_sm"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>nlp_fr <span class="op">=</span> spacy.load(<span class="st">"fr_core_news_sm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="questions" class="level3">
<h3 class="anchored" data-anchor-id="questions">Questions</h3>
<p><code>meta</code> holds one row per author, with a birth and death year, a literary <code>era</code>, a <code>gender</code>, and the <code>link</code>/<code>short</code> names used elsewhere in the corpus. <code>text_en</code> has one row per author with the full text of their English Wikipedia page; <code>text_fr</code> is the same idea for the French edition. This is the same 75-author corpus the chapter itself builds its cross-language section on, because it is the only French-paired text in the whole catalogue — there is no second bilingual corpus to swap in instead. The first question below investigates a real narrowing this notebook has to make before doing anything else: <code>text_fr</code> does not have 75 rows. Print results unless a question says otherwise.</p>
<ol type="1">
<li>How many of the 75 authors in <code>text_en</code> also have a row in <code>text_fr</code>? Anti-join to find the author(s) missing a French page, and join the result to <code>meta</code> for their era and gender.</li>
</ol>
<div id="7855fe51" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>n_common <span class="op">=</span> (</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    text_en</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    .join(text_fr.select(c.doc_id), on<span class="op">=</span><span class="st">"doc_id"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    .height</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(n_common, <span class="st">"of"</span>, text_en.height, <span class="st">"authors have a French page"</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>missing <span class="op">=</span> text_en.join(text_fr.select(c.doc_id), on<span class="op">=</span><span class="st">"doc_id"</span>, how<span class="op">=</span><span class="st">"anti"</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    missing</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    .join(meta, on<span class="op">=</span><span class="st">"doc_id"</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    .select(c.doc_id, c.era, c.gender)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>73 of 75 authors have a French page</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (2, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">doc_id</th>
<th data-quarto-table-cell-role="th">era</th>
<th data-quarto-table-cell-role="th">gender</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Edward Upward"</td>
<td>"Twentieth C"</td>
<td>"male"</td>
</tr>
<tr class="even">
<td>"Rex Warner"</td>
<td>"Twentieth C"</td>
<td>"male"</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Now rank all 75 authors by the character length of their English page, and report where the two missing authors fall in that ranking.</p>
<div id="7b86f4dc" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    text_en</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    .with_columns(n_chars <span class="op">=</span> c.text.<span class="bu">str</span>.len_chars())</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    .with_columns(rank <span class="op">=</span> c.n_chars.rank())</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.doc_id.is_in(missing.select(c.doc_id).to_series()))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    .select(c.doc_id, c.n_chars, c.rank)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/5w/rxshd8hd6vv8mxsbj211mr_m0000gn/T/ipykernel_48597/408388340.py:5: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (2, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">doc_id</th>
<th data-quarto-table-cell-role="th">n_chars</th>
<th data-quarto-table-cell-role="th">rank</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Edward Upward"</td>
<td>6574</td>
<td>3.0</td>
</tr>
<tr class="even">
<td>"Rex Warner"</td>
<td>4560</td>
<td>1.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Only 73 of the 75 authors have a French Wikipedia page. Both authors missing one, Rex Warner and Edward Upward, are Twentieth Century writers, but era alone does not explain the gap: plenty of other Twentieth Century authors in this corpus do have a French page. Page length does explain it. Rex Warner has the single shortest English page in the entire 75-author corpus, and Edward Upward has the third shortest. The two authors with no French Wikipedia page at all are also, independently, two of the three least-covered figures on the English side. Missing translation coverage here tracks obscurity, not a random gap or a cutoff by time period.</p>
<ol start="2" type="1">
<li>In the first block, restrict <code>text_en</code> and <code>text_fr</code> to the 73 shared authors, sort both by <code>doc_id</code>, and confirm the two tables now cover the exact same set of authors. In the second block, run each language’s text through its own spaCy pipeline with <code>DSText.process</code>, and print the resulting shapes.</li>
</ol>
<div id="e05aacc2" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>docs_en <span class="op">=</span> (</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    text_en</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    .join(text_fr.select(c.doc_id), on<span class="op">=</span><span class="st">"doc_id"</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    .sort(c.doc_id)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>docs_fr <span class="op">=</span> text_fr.sort(c.doc_id)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(docs_en.select(c.doc_id).equals(docs_fr.select(c.doc_id)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>True</code></pre>
</div>
</div>
<div id="62a1f8ec" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>anno_en <span class="op">=</span> DSText.process(docs_en, nlp_en)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>anno_fr <span class="op">=</span> DSText.process(docs_fr, nlp_fr)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(anno_en.shape)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(anno_fr.shape)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(406735, 15)
(203785, 15)</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>For each language, compute the average number of alphabetic tokens per document and the average number of distinct lemmas per document. In the first block, do this for English (<code>anno_en</code>); in the second, for French (<code>anno_fr</code>).</li>
</ol>
<div id="e83caea1" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    anno_en</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.is_alpha)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    .group_by(c.doc_id)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    .agg(n_tokens <span class="op">=</span> pl.<span class="bu">len</span>(), n_lemmas <span class="op">=</span> c.lemma.n_unique())</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    .select(c.n_tokens.mean(), c.n_lemmas.mean())</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="9">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (1, 2)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">n_tokens</th>
<th data-quarto-table-cell-role="th">n_lemmas</th>
</tr>
<tr class="even">
<td>f64</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5184.287671</td>
<td>1445.520548</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="6b2e68a0" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    anno_fr</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.is_alpha)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    .group_by(c.doc_id)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    .agg(n_tokens <span class="op">=</span> pl.<span class="bu">len</span>(), n_lemmas <span class="op">=</span> c.lemma.n_unique())</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    .select(c.n_tokens.mean(), c.n_lemmas.mean())</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="10">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (1, 2)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">n_tokens</th>
<th data-quarto-table-cell-role="th">n_lemmas</th>
</tr>
<tr class="even">
<td>f64</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2578.972603</td>
<td>822.369863</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>An English page runs about 5,184 alphabetic tokens on average, drawn from about 1,446 distinct lemmas; a French page for the very same author runs about 2,579 tokens from about 822 distinct lemmas. Both halve at roughly the same rate, which matches the character-length gap between the two text columns: French Wikipedia’s coverage of these authors is real, but consistently shorter than English Wikipedia’s.</p>
<ol start="4" type="1">
<li>Compute the TF-IDF table for each language with <code>DSText.compute_tfidf(..., min_df=0.01, max_df=1.0)</code>, the exact call the chapter itself uses for <code>anno_fr</code>. Print the top 10 terms for <code>"Jane Austen"</code> in both languages. Do these lists match the chapter’s own description of what a top-TF-IDF list should look like?</li>
</ol>
<div id="8bc9cda8" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> author <span class="kw">in</span> [<span class="st">"Jane Austen"</span>]:</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"EN"</span>, author, DSText.compute_tfidf(anno_en, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">1.0</span>).<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">10</span>).select(c.lemma).to_series().to_list())</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"FR"</span>, author, DSText.compute_tfidf(anno_fr, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">1.0</span>).<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">10</span>).select(c.lemma).to_series().to_list())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>EN Jane Austen ['Austen', 'the', 'and', 'of', 'be', 'in', 'Austens', 'to', 'a', 'her']
FR Jane Austen ['de', 'le', 'Austen', 'Jane', 'son', 'à', 'et', 'un', 'être', 'en']</code></pre>
</div>
</div>
<p>No.&nbsp;The chapter’s own text claims that TF-IDF “downweights generic terms… and what remains are the names, places, and titles that actually identify each author,” but with <code>max_df=1.0</code> nothing actually gets downweighted enough to matter: <code>the</code>, <code>of</code>, <code>and</code>, <code>in</code>, <code>to</code>, and <code>her</code> fill six of Austen’s ten English slots, and <code>de</code>, <code>le</code>, <code>à</code>, <code>et</code>, <code>un</code>, <code>être</code>, and <code>en</code> fill seven of her ten French ones. This is not an artifact of the 73-author subset — the book’s own rendered table for the full 75-author English corpus shows exactly the same pattern (<code>"Louis MacNeice" → "MacNeice; the; and; in; be; of…"</code>, <code>"George Bernard Shaw" → "the; Shaw; in; and; of; be; a;…"</code>), so this is the chapter’s own documented behavior, not something this notebook introduced. Without a <code>max_df</code> cutoff, a word appearing in every single document (<code>the</code> sits at <code>df_docs = 73</code> here) still keeps an <code>idf</code> of exactly 1, and a common English or French function word’s raw in-document count is large enough that it still outranks a genuinely rare, document- specific proper noun.</p>
<ol start="5" type="1">
<li>Recompute the TF-IDF tables with the stricter <code>max_df=0.5</code> the chapter’s own UMAP and distance sections use elsewhere in this same chapter, for both languages, and re-check <code>"Jane Austen"</code>, <code>"A. A. Milne"</code>, and <code>"T. S. Eliot"</code>. Does this cutoff produce the clean lists the chapter’s prose described? Does anything still look out of place?</li>
</ol>
<div id="df008e38" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>tfidf_en <span class="op">=</span> DSText.compute_tfidf(anno_en, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>tfidf_fr <span class="op">=</span> DSText.compute_tfidf(anno_fr, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> author <span class="kw">in</span> [<span class="st">"Jane Austen"</span>, <span class="st">"A. A. Milne"</span>, <span class="st">"T. S. Eliot"</span>]:</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"EN"</span>, author, tfidf_en.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">10</span>).select(c.lemma).to_series().to_list())</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"FR"</span>, author, tfidf_fr.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">10</span>).select(c.lemma).to_series().to_list())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>EN Jane Austen ['Austen', 'Austens', 'Cassandra', 'Jane', 'Sensibility', 'Lefroy', 'Prejudice', 'Pride', 'Sense', 'austen']
FR Jane Austen ['Austen', 'Jane', 'Cassandra', 'Henry', 'Abbey', 'Mansfield', 'Park', 'Northanger', 'Pride', 'quel']
EN A. A. Milne ['Milne', 'Pooh', 'Winnie', 'Milnes', 'Robin', 'Christopher', 'Ashdown', 'parser', 'Shepard', 'Forest']
FR A. A. Milne ['Milne', 'Honour', 'Hartfield', 'with', 'mondial', 'démobiliser', 'Alan', 'antimilitariste', 'kenneth', 'saule']
EN T. S. Eliot ['Eliot', 'Eliots', 'Waste', 'parser', 'Land', 'output', 'Harvard', 'Vivienne', 'Prufrock', 'Quartets']
FR T. S. Eliot ['Eliot', 'Waste', 'Land', 'Harvard', 'deliot', 'Prufrock', 'Quatre', 'je', 'Washington', 'quatuor']</code></pre>
</div>
</div>
<p>Mostly yes. Dropping every lemma that appears in more than half the corpus clears out the function words from all three lists, and what is left for Austen is her own name, her sister Cassandra, and her novels — the clean result question 4 promised but did not deliver. Milne’s and Eliot’s English lists are almost as clean, but both still contain <code>"parser"</code>, a word with no obvious connection to either a children’s author or a modernist poet. Neither French list has anything like it. The next question tracks that down.</p>
<ol start="6" type="1">
<li>In the first block, search both raw text columns for the substring <code>"mw-parser-output"</code>, count how many characters match it per document, compare the two languages, and list the documents with any matches sorted by count. In the second block, filter <code>anno_en</code> to the token <code>"parser"</code> and check its <code>upos</code> tag and <code>is_alpha</code> flag. In the third block, print the raw text around the first occurrence of <code>"parser"</code> on A. A. Milne’s page.</li>
</ol>
<div id="bc9c986a" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(text_en.with_columns(n <span class="op">=</span> c.text.<span class="bu">str</span>.count_matches(<span class="st">"mw-parser-output"</span>)).select(c.n.<span class="bu">sum</span>()).item(), <span class="st">"matches in English text"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(text_fr.with_columns(n <span class="op">=</span> c.text.<span class="bu">str</span>.count_matches(<span class="st">"mw-parser-output"</span>)).select(c.n.<span class="bu">sum</span>()).item(), <span class="st">"matches in French text"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    text_en</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    .with_columns(n <span class="op">=</span> c.text.<span class="bu">str</span>.count_matches(<span class="st">"mw-parser-output"</span>))</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.n <span class="op">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    .select(c.doc_id, c.n)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    .sort(c.n, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>33 matches in English text
0 matches in French text</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (4, 2)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">doc_id</th>
<th data-quarto-table-cell-role="th">n</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"T. S. Eliot"</td>
<td>22</td>
</tr>
<tr class="even">
<td>"A. A. Milne"</td>
<td>8</td>
</tr>
<tr class="odd">
<td>"John Milton"</td>
<td>2</td>
</tr>
<tr class="even">
<td>"Thomas More"</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="7d3d7892" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>anno_en.<span class="bu">filter</span>(c.token <span class="op">==</span> <span class="st">"parser"</span>).select(c.doc_id, c.token, c.upos, c.is_alpha).unique()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="14">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (4, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">doc_id</th>
<th data-quarto-table-cell-role="th">token</th>
<th data-quarto-table-cell-role="th">upos</th>
<th data-quarto-table-cell-role="th">is_alpha</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>str</td>
<td>bool</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"A. A. Milne"</td>
<td>"parser"</td>
<td>"NOUN"</td>
<td>true</td>
</tr>
<tr class="even">
<td>"T. S. Eliot"</td>
<td>"parser"</td>
<td>"NOUN"</td>
<td>true</td>
</tr>
<tr class="odd">
<td>"John Milton"</td>
<td>"parser"</td>
<td>"NOUN"</td>
<td>true</td>
</tr>
<tr class="even">
<td>"Thomas More"</td>
<td>"parser"</td>
<td>"NOUN"</td>
<td>true</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="904f4779" class="cell" data-execution_count="17">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>idx <span class="op">=</span> docs_en.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> <span class="st">"A. A. Milne"</span>).item(<span class="dv">0</span>, <span class="st">"text"</span>).find(<span class="st">"parser"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>docs_en.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> <span class="st">"A. A. Milne"</span>).item(<span class="dv">0</span>, <span class="st">"text"</span>)[idx <span class="op">-</span> <span class="dv">120</span> : idx <span class="op">+</span> <span class="dv">120</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>'outh East England where the Pooh stories were set. Milne lived on the northern edge of the forest at Cotchford Farm .mw-parser-output .geo-default.mw-parser-output .geo-dms.mw-parser-output .geo-decdisplayinline.mw-parser-output .geo-nondef'</code></pre>
</div>
</div>
<p><code>"mw-parser-output"</code> is leaked CSS from a Wikipedia coordinate template, scraped straight into the article body along with the rest of the page text — 33 occurrences across four English pages, concentrated in Milne’s and Eliot’s, and zero anywhere in the French text. Printing the raw context around it confirms the source: a run of repeated <code>.mw-parser-output .geo-...</code> class names from a hidden geo-coordinate box, copy-pasted into the extracted text eight times in a single sentence on Milne’s page alone. spaCy tags the token <code>parser</code> itself as an ordinary alphabetic <code>NOUN</code>, exactly the way it would tag a real word, so nothing about <code>is_alpha</code> catches it the way notebook41’s backslash artifact was caught. It sails straight through <code>compute_tfidf</code> and inflates two authors’ top-term lists with a scraping artifact that has nothing to do with either of them.</p>
<ol start="7" type="1">
<li>Reproduce the chapter’s part-of-speech comparison — stack <code>anno_en</code> and <code>anno_fr</code> with a <code>lang</code> column, group by <code>lang</code> and <code>upos</code>, and compute the proportion of each part of speech within each language — but now on the matched 73-author subset both tables share. Report the determiner (<code>DET</code>) proportion for each language.</li>
</ol>
<div id="05a187b1" class="cell" data-execution_count="18">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    pl.concat([</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>        anno_en.with_columns(lang <span class="op">=</span> pl.lit(<span class="st">"en"</span>)),</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>        anno_fr.with_columns(lang <span class="op">=</span> pl.lit(<span class="st">"fr"</span>))</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    .group_by([c.lang, c.upos])</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    .agg(count <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    .with_columns(prop <span class="op">=</span> c.count <span class="op">/</span> c.count.<span class="bu">sum</span>().over(c.lang))</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.upos <span class="op">==</span> <span class="st">"DET"</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="16">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (2, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">lang</th>
<th data-quarto-table-cell-role="th">upos</th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">prop</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>u32</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"fr"</td>
<td>"DET"</td>
<td>24909</td>
<td>0.122232</td>
</tr>
<tr class="even">
<td>"en"</td>
<td>"DET"</td>
<td>36147</td>
<td>0.088871</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>8.9% of English tokens are determiners against 12.2% of French ones, the same gap the chapter describes, and this time it is not confounded by the population mismatch built into the chapter’s own version of this comparison: the chapter stacks all 75 English pages against only 73 French ones, quietly comparing two different populations, while <code>anno_en</code> and <code>anno_fr</code> here cover the identical 73 authors on both sides.</p>
<ol start="8" type="1">
<li>Compute the pairwise angle distance for each language separately with <code>DSText.compute_distances(..., min_df=0.01, max_df=0.5)</code>. For each language, stack the result with a copy of itself with the ID columns swapped, and find every author’s single nearest neighbor.</li>
</ol>
<div id="34d804cd" class="cell" data-execution_count="19">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>dist_en <span class="op">=</span> DSText.compute_distances(anno_en, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>dist_fr <span class="op">=</span> DSText.compute_distances(anno_fr, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>nn_en <span class="op">=</span> (</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    pl.concat([</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>        dist_en,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>        dist_en.select(doc_id<span class="op">=</span>c.doc_id2, doc_id2<span class="op">=</span>c.doc_id, distance<span class="op">=</span>c.distance)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    .sort(c.doc_id, c.distance)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    .group_by(c.doc_id, maintain_order<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">1</span>)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    .rename({<span class="st">"doc_id2"</span>: <span class="st">"nn_en"</span>})</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    .drop(<span class="st">"distance"</span>)</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>nn_fr <span class="op">=</span> (</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>    pl.concat([</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>        dist_fr,</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>        dist_fr.select(doc_id<span class="op">=</span>c.doc_id2, doc_id2<span class="op">=</span>c.doc_id, distance<span class="op">=</span>c.distance)</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>    .sort(c.doc_id, c.distance)</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>    .group_by(c.doc_id, maintain_order<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">1</span>)</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>    .rename({<span class="st">"doc_id2"</span>: <span class="st">"nn_fr"</span>})</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>    .drop(<span class="st">"distance"</span>)</span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a>nn_compare <span class="op">=</span> nn_en.join(nn_fr, on<span class="op">=</span><span class="st">"doc_id"</span>)</span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a>nn_compare</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="17">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (73, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">doc_id</th>
<th data-quarto-table-cell-role="th">nn_en</th>
<th data-quarto-table-cell-role="th">nn_fr</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"A. A. Milne"</td>
<td>"T. S. Eliot"</td>
<td>"George Orwell"</td>
</tr>
<tr class="even">
<td>"Alexander Pope"</td>
<td>"John Dryden"</td>
<td>"Jonathan Swift"</td>
</tr>
<tr class="odd">
<td>"Alfred, Lord Tennyson"</td>
<td>"Elizabeth Barrett Browning"</td>
<td>"Samuel Taylor Coleridge"</td>
</tr>
<tr class="even">
<td>"Ann Radcliffe"</td>
<td>"Jane Austen"</td>
<td>"Jane Austen"</td>
</tr>
<tr class="odd">
<td>"Beatrix Potter"</td>
<td>"C. S. Lewis"</td>
<td>"William Blake"</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"Walter Raleigh"</td>
<td>"Edmund Spenser"</td>
<td>"Philip Sidney"</td>
</tr>
<tr class="even">
<td>"William Blake"</td>
<td>"Cecil Day-Lewis"</td>
<td>"Samuel Beckett"</td>
</tr>
<tr class="odd">
<td>"William Langland"</td>
<td>"John Gower"</td>
<td>"Geoffrey Chaucer"</td>
</tr>
<tr class="even">
<td>"William Shakespeare"</td>
<td>"Ben Jonson"</td>
<td>"Samuel Beckett"</td>
</tr>
<tr class="odd">
<td>"William Wordsworth"</td>
<td>"Samuel Taylor Coleridge"</td>
<td>"Samuel Taylor Coleridge"</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ol start="9" type="1">
<li>What proportion of authors have the exact same nearest neighbor under both languages? Compare this to the chance rate of matching by accident among 72 other authors.</li>
</ol>
<div id="8099fa91" class="cell" data-execution_count="20">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>agree_rate <span class="op">=</span> nn_compare.select((c.nn_en <span class="op">==</span> c.nn_fr).mean()).item()</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(agree_rate, <span class="dv">3</span>), <span class="st">"agreement rate"</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(<span class="dv">1</span> <span class="op">/</span> <span class="dv">72</span>, <span class="dv">3</span>), <span class="st">"chance rate"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>0.479 agreement rate
0.014 chance rate</code></pre>
</div>
</div>
<p>Almost 48% of authors (35 of 73) have the identical nearest neighbor whether the distance is computed from their English page or their French one, over thirty times the roughly 1.4% we would expect from two independent random guesses among 72 other authors. The two languages are far from producing identical geometry, but the structure that TF-IDF and the angle distance recover is not arbitrary either: it survives translation for close to half the corpus.</p>
<ol start="10" type="1">
<li>Look at one agreement and one disagreement from <code>nn_compare</code> by eye. Ann Radcliffe’s nearest neighbor is Jane Austen in both languages; A. A. Milne’s is T. S. Eliot in English but George Orwell in French. In the first block, print the agreement pair’s top 5 TF-IDF terms in both languages for Ann Radcliffe and Jane Austen. In the second block, print the disagreement group’s top 5 terms for A. A. Milne, T. S. Eliot, and George Orwell. In the third block, check whether question 6’s <code>parser</code> artifact is actually what is pulling Milne toward Eliot by recomputing the English distance between them with <code>parser</code> removed from <code>anno_en</code>.</li>
</ol>
<div id="b8cc589d" class="cell" data-execution_count="21">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> author <span class="kw">in</span> [<span class="st">"Ann Radcliffe"</span>, <span class="st">"Jane Austen"</span>]:</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"EN"</span>, author, tfidf_en.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">5</span>).select(c.lemma).to_series().to_list())</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"FR"</span>, author, tfidf_fr.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">5</span>).select(c.lemma).to_series().to_list())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>EN Ann Radcliffe ['Radcliffe', 'Radcliffes', 'Ann', 'Udolpho', 'Gothic']
FR Ann Radcliffe ['Ann', 'radcliffe', 'Radcliffe', 'gothique', 'Oates']
EN Jane Austen ['Austen', 'Austens', 'Cassandra', 'Jane', 'Sensibility']
FR Jane Austen ['Austen', 'Jane', 'Cassandra', 'Henry', 'Abbey']</code></pre>
</div>
</div>
<div id="60c40211" class="cell" data-execution_count="22">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> author <span class="kw">in</span> [<span class="st">"A. A. Milne"</span>, <span class="st">"T. S. Eliot"</span>, <span class="st">"George Orwell"</span>]:</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"EN"</span>, author, tfidf_en.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">5</span>).select(c.lemma).to_series().to_list())</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"FR"</span>, author, tfidf_fr.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">5</span>).select(c.lemma).to_series().to_list())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>EN A. A. Milne ['Milne', 'Pooh', 'Winnie', 'Milnes', 'Robin']
FR A. A. Milne ['Milne', 'Honour', 'Hartfield', 'with', 'mondial']
EN T. S. Eliot ['Eliot', 'Eliots', 'Waste', 'parser', 'Land']
FR T. S. Eliot ['Eliot', 'Waste', 'Land', 'Harvard', 'deliot']
EN George Orwell ['Orwell', 'Orwells', 'Blair', 'Animal', 'Eighty']
FR George Orwell ['Orwell', 'orwell', 'Blair', 'Eric', 'dorwell']</code></pre>
</div>
</div>
<div id="ddaaa9b4" class="cell" data-execution_count="23">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>milne_eliot <span class="op">=</span> dist_en.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> <span class="st">"A. A. Milne"</span>, c.doc_id2 <span class="op">==</span> <span class="st">"T. S. Eliot"</span>).item(<span class="dv">0</span>, <span class="st">"distance"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>dist_en_no_parser <span class="op">=</span> DSText.compute_distances(anno_en.<span class="bu">filter</span>(c.lemma <span class="op">!=</span> <span class="st">"parser"</span>), min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>milne_eliot_no_parser <span class="op">=</span> dist_en_no_parser.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> <span class="st">"A. A. Milne"</span>, c.doc_id2 <span class="op">==</span> <span class="st">"T. S. Eliot"</span>).item(<span class="dv">0</span>, <span class="st">"distance"</span>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(milne_eliot, <span class="dv">3</span>), <span class="st">"with parser"</span>)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(milne_eliot_no_parser, <span class="dv">3</span>), <span class="st">"without parser"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>1.528 with parser
1.548 without parser</code></pre>
</div>
</div>
<p>Radcliffe and Austen both write Gothic-adjacent fiction, and Radcliffe’s own top terms (<code>Udolpho</code> in English, <code>gothique</code> in French) confirm the genre connection directly, so the agreement is easy to believe in both languages. Milne’s disagreement is harder to read off the term lists alone — neither Eliot’s nor Orwell’s top terms share anything obvious with Milne’s beyond ordinary biographical scaffolding. The <code>parser</code> artifact turns out not to be the explanation either: dropping it from <code>anno_en</code> entirely and recomputing barely moves the Milne–Eliot distance (1.528 to 1.548) and does not change who Milne’s nearest neighbor is. Whatever pulls Milne toward Eliot in English and toward Orwell in French runs through the geometry of the full term-weighted vector, not through any single term visible in a short printed list — a caution worth carrying forward: a top-5 or top-10 list is a convenient summary for a human reader, but it is not the same object the distance calculation actually compares.</p>
<ol start="11" type="1">
<li>Build a 2D UMAP projection for each language with <code>umap_text(..., min_df=0.01, max_df=0.5, random_state=42)</code>, join each author’s short name and <code>era</code> from <code>meta</code>, and plot both, colored by <code>era</code>. In the first block, do this for English (<code>anno_en</code>); in the second, for French (<code>anno_fr</code>). A plot is an impression, not a measurement, so in the third block also compute each projection’s own same-era nearest-neighbor rate directly from the <code>dr0</code>/<code>dr1</code> coordinates, the same check the last chapter’s notebook ran on <code>label</code>.</li>
</ol>
<div id="9b20170e" class="cell" data-execution_count="24">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>umap_en <span class="op">=</span> (</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>    anno_en</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    .pipe(umap_text, doc_id<span class="op">=</span>c.doc_id, term_id<span class="op">=</span>c.lemma, n_components<span class="op">=</span><span class="dv">2</span>, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">0.5</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    .predict(full<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    .join(meta.select(c.doc_id, c.short, c.era), on<span class="op">=</span><span class="st">"doc_id"</span>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>    umap_en</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(c.dr0, c.dr1))</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>    .geom_text(aes(label<span class="op">=</span>c.short, color<span class="op">=</span>c.era), size<span class="op">=</span><span class="dv">6</span>)</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/admin/gh/fds2/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
/Users/admin/gh/fds2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="22">
<div>
<figure class="figure">
<p><a href="notebook43_files/figure-html/cell-25-output-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="notebook43_files/figure-html/cell-25-output-2.png" width="672" height="480" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
<div id="0cc489dd" class="cell" data-execution_count="25">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>umap_fr <span class="op">=</span> (</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>    anno_fr</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    .pipe(umap_text, doc_id<span class="op">=</span>c.doc_id, term_id<span class="op">=</span>c.lemma, n_components<span class="op">=</span><span class="dv">2</span>, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">0.5</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    .predict(full<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    .join(meta.select(c.doc_id, c.short, c.era), on<span class="op">=</span><span class="st">"doc_id"</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>    umap_fr</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(c.dr0, c.dr1))</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>    .geom_text(aes(label<span class="op">=</span>c.short, color<span class="op">=</span>c.era), size<span class="op">=</span><span class="dv">6</span>)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/admin/gh/fds2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="23">
<div>
<figure class="figure">
<p><a href="notebook43_files/figure-html/cell-26-output-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="notebook43_files/figure-html/cell-26-output-2.png" width="672" height="480" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
<div id="0ea29196" class="cell" data-execution_count="26">
<details class="code-fold">
<summary>View code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> era_nn_rate(umap_df):</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>    coords <span class="op">=</span> umap_df.select(c.dr0, c.dr1).to_numpy()</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    dist_sq <span class="op">=</span> ((coords[:, <span class="va">None</span>, :] <span class="op">-</span> coords[<span class="va">None</span>, :, :]) <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    np.fill_diagonal(dist_sq, np.inf)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    nn_idx <span class="op">=</span> dist_sq.argmin(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    eras <span class="op">=</span> umap_df.select(c.era).to_series().to_numpy()</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (eras <span class="op">==</span> eras[nn_idx]).mean()</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(era_nn_rate(umap_en), <span class="dv">3</span>), <span class="st">"EN same-era nearest-neighbor rate"</span>)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(era_nn_rate(umap_fr), <span class="dv">3</span>), <span class="st">"FR same-era nearest-neighbor rate"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>0.205 EN same-era nearest-neighbor rate
0.26 FR same-era nearest-neighbor rate</code></pre>
</div>
</div>
<ol start="12" type="1">
<li>With seven <code>era</code> categories of uneven size, matching by chance alone runs around 17%. Both projections clear that bar but not by much — 20.5% for English and 26.0% for French — confirming what the plots suggest by eye: a weak, genuine pull toward grouping by era, not the tight separation notebook42’s own same-label check found for AG News’s four disjoint topic categories, and not nothing either. Looking back across this notebook: what carried over unchanged between English and French, and what genuinely differed?</li>
</ol>
<p>The machinery carried over without a single change: the same <code>DSText.process</code>, <code>compute_tfidf</code>, <code>compute_distances</code>, and <code>umap_text</code> calls ran on French tokens exactly as they did on English ones, because none of that code has any language-specific logic built in. What differed was the input each pipeline was handed and what came out the other end. Two authors have no French page at all, and coverage tracks obscurity rather than era. French pages run about half the length and half the vocabulary of their English counterparts on the very same subject. French uses determiners more often, a grammatical fact with nothing to do with editorial choice. And the two languages’ own document geometries agree on a given author’s closest match less than half the time, even though that rate is far above chance. None of this is a flaw in the pipeline; it is exactly the kind of genuine cross-lingual difference the chapter’s own closing paragraph says this machinery makes possible to study systematically rather than assert from a hunch.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script>
document.addEventListener('DOMContentLoaded', function() {
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details .sourceCode");
      for (let i = 0; i < detailsSrc.length; i++) {
        const details = detailsSrc[i].closest('details');
        if (details) {
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
      }
      return false;
    };
  }
  // Replace buttons to strip the broken listeners Quarto attached, then re-add fixed ones
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    const fresh = hideAllCode.cloneNode(true);
    hideAllCode.parentNode.replaceChild(fresh, hideAllCode);
    fresh.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    const fresh = showAllCode.cloneNode(true);
    showAllCode.parentNode.replaceChild(fresh, showAllCode);
    fresh.addEventListener("click", toggleCodeHandler(true));
  }
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb41" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Notebook43"</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="an">solutions-release-date:</span><span class="co"> "2026-10-21"</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="fu">### Setup</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>Run all of the following before starting the notebook.</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [noclear]</span></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a><span class="op">!</span> wget <span class="op">-</span>q <span class="op">-</span>nc https:<span class="op">//</span>raw.githubusercontent.com<span class="op">/</span>taylor<span class="op">-</span>arnold<span class="op">/</span>fds2<span class="op">/</span>refs<span class="op">/</span>heads<span class="op">/</span>main<span class="op">/</span>funs.py</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [noclear]</span></span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a><span class="op">!</span> pip install umap<span class="op">-</span>learn <span class="op">--</span>quiet</span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a><span class="op">!</span> python <span class="op">-</span>m spacy download en_core_web_sm</span>
<span id="cb41-25"><a href="#cb41-25" aria-hidden="true" tabindex="-1"></a><span class="op">!</span> python <span class="op">-</span>m spacy download fr_core_news_sm</span>
<span id="cb41-26"><a href="#cb41-26" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-27"><a href="#cb41-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-30"><a href="#cb41-30" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-31"><a href="#cb41-31" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [noclear]</span></span>
<span id="cb41-32"><a href="#cb41-32" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb41-33"><a href="#cb41-33" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotnine <span class="im">import</span> ggplot, aes</span>
<span id="cb41-34"><a href="#cb41-34" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> polars <span class="im">import</span> col <span class="im">as</span> c</span>
<span id="cb41-35"><a href="#cb41-35" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb41-36"><a href="#cb41-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-37"><a href="#cb41-37" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> funs</span>
<span id="cb41-38"><a href="#cb41-38" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> funs <span class="im">import</span> DSText, umap_text</span>
<span id="cb41-39"><a href="#cb41-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-40"><a href="#cb41-40" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> spacy</span>
<span id="cb41-41"><a href="#cb41-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-42"><a href="#cb41-42" aria-hidden="true" tabindex="-1"></a>ub <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/taylor-arnold/fds2/refs/heads/main/"</span></span>
<span id="cb41-43"><a href="#cb41-43" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-44"><a href="#cb41-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-47"><a href="#cb41-47" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-48"><a href="#cb41-48" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [remove]</span></span>
<span id="cb41-49"><a href="#cb41-49" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb41-50"><a href="#cb41-50" aria-hidden="true" tabindex="-1"></a>ub <span class="op">=</span> <span class="st">""</span></span>
<span id="cb41-51"><a href="#cb41-51" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-52"><a href="#cb41-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-55"><a href="#cb41-55" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-56"><a href="#cb41-56" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [noclear]</span></span>
<span id="cb41-57"><a href="#cb41-57" aria-hidden="true" tabindex="-1"></a>meta <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/wiki_uk_meta.csv.gz"</span>)</span>
<span id="cb41-58"><a href="#cb41-58" aria-hidden="true" tabindex="-1"></a>text_en <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/wiki_uk_authors_text.csv"</span>)</span>
<span id="cb41-59"><a href="#cb41-59" aria-hidden="true" tabindex="-1"></a>text_fr <span class="op">=</span> pl.read_csv(ub <span class="op">+</span> <span class="st">"data/wiki_uk_authors_text_fr.csv"</span>)</span>
<span id="cb41-60"><a href="#cb41-60" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-61"><a href="#cb41-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-64"><a href="#cb41-64" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-65"><a href="#cb41-65" aria-hidden="true" tabindex="-1"></a><span class="co">#| tags: [noclear]</span></span>
<span id="cb41-66"><a href="#cb41-66" aria-hidden="true" tabindex="-1"></a>nlp_en <span class="op">=</span> spacy.load(<span class="st">"en_core_web_sm"</span>)</span>
<span id="cb41-67"><a href="#cb41-67" aria-hidden="true" tabindex="-1"></a>nlp_fr <span class="op">=</span> spacy.load(<span class="st">"fr_core_news_sm"</span>)</span>
<span id="cb41-68"><a href="#cb41-68" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-69"><a href="#cb41-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-70"><a href="#cb41-70" aria-hidden="true" tabindex="-1"></a><span class="fu">### Questions</span></span>
<span id="cb41-71"><a href="#cb41-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-72"><a href="#cb41-72" aria-hidden="true" tabindex="-1"></a><span class="in">`meta`</span> holds one row per author, with a birth and death year, a literary</span>
<span id="cb41-73"><a href="#cb41-73" aria-hidden="true" tabindex="-1"></a><span class="in">`era`</span>, a <span class="in">`gender`</span>, and the <span class="in">`link`</span>/<span class="in">`short`</span> names used elsewhere in the corpus.</span>
<span id="cb41-74"><a href="#cb41-74" aria-hidden="true" tabindex="-1"></a><span class="in">`text_en`</span> has one row per author with the full text of their English</span>
<span id="cb41-75"><a href="#cb41-75" aria-hidden="true" tabindex="-1"></a>Wikipedia page; <span class="in">`text_fr`</span> is the same idea for the French edition. This is</span>
<span id="cb41-76"><a href="#cb41-76" aria-hidden="true" tabindex="-1"></a>the same 75-author corpus the chapter itself builds its cross-language</span>
<span id="cb41-77"><a href="#cb41-77" aria-hidden="true" tabindex="-1"></a>section on, because it is the only French-paired text in the whole</span>
<span id="cb41-78"><a href="#cb41-78" aria-hidden="true" tabindex="-1"></a>catalogue — there is no second bilingual corpus to swap in instead. The</span>
<span id="cb41-79"><a href="#cb41-79" aria-hidden="true" tabindex="-1"></a>first question below investigates a real narrowing this notebook has to</span>
<span id="cb41-80"><a href="#cb41-80" aria-hidden="true" tabindex="-1"></a>make before doing anything else: <span class="in">`text_fr`</span> does not have 75 rows. Print</span>
<span id="cb41-81"><a href="#cb41-81" aria-hidden="true" tabindex="-1"></a>results unless a question says otherwise.</span>
<span id="cb41-82"><a href="#cb41-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-83"><a href="#cb41-83" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>How many of the 75 authors in <span class="in">`text_en`</span> also have a row in <span class="in">`text_fr`</span>?</span>
<span id="cb41-84"><a href="#cb41-84" aria-hidden="true" tabindex="-1"></a>Anti-join to find the author(s) missing a French page, and join the result</span>
<span id="cb41-85"><a href="#cb41-85" aria-hidden="true" tabindex="-1"></a>to <span class="in">`meta`</span> for their era and gender.</span>
<span id="cb41-86"><a href="#cb41-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-89"><a href="#cb41-89" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-90"><a href="#cb41-90" aria-hidden="true" tabindex="-1"></a>n_common <span class="op">=</span> (</span>
<span id="cb41-91"><a href="#cb41-91" aria-hidden="true" tabindex="-1"></a>    text_en</span>
<span id="cb41-92"><a href="#cb41-92" aria-hidden="true" tabindex="-1"></a>    .join(text_fr.select(c.doc_id), on<span class="op">=</span><span class="st">"doc_id"</span>)</span>
<span id="cb41-93"><a href="#cb41-93" aria-hidden="true" tabindex="-1"></a>    .height</span>
<span id="cb41-94"><a href="#cb41-94" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-95"><a href="#cb41-95" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(n_common, <span class="st">"of"</span>, text_en.height, <span class="st">"authors have a French page"</span>)</span>
<span id="cb41-96"><a href="#cb41-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-97"><a href="#cb41-97" aria-hidden="true" tabindex="-1"></a>missing <span class="op">=</span> text_en.join(text_fr.select(c.doc_id), on<span class="op">=</span><span class="st">"doc_id"</span>, how<span class="op">=</span><span class="st">"anti"</span>)</span>
<span id="cb41-98"><a href="#cb41-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-99"><a href="#cb41-99" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb41-100"><a href="#cb41-100" aria-hidden="true" tabindex="-1"></a>    missing</span>
<span id="cb41-101"><a href="#cb41-101" aria-hidden="true" tabindex="-1"></a>    .join(meta, on<span class="op">=</span><span class="st">"doc_id"</span>)</span>
<span id="cb41-102"><a href="#cb41-102" aria-hidden="true" tabindex="-1"></a>    .select(c.doc_id, c.era, c.gender)</span>
<span id="cb41-103"><a href="#cb41-103" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-104"><a href="#cb41-104" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-105"><a href="#cb41-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-106"><a href="#cb41-106" aria-hidden="true" tabindex="-1"></a>Now rank all 75 authors by the character length of their English page, and</span>
<span id="cb41-107"><a href="#cb41-107" aria-hidden="true" tabindex="-1"></a>report where the two missing authors fall in that ranking.</span>
<span id="cb41-108"><a href="#cb41-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-111"><a href="#cb41-111" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-112"><a href="#cb41-112" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb41-113"><a href="#cb41-113" aria-hidden="true" tabindex="-1"></a>    text_en</span>
<span id="cb41-114"><a href="#cb41-114" aria-hidden="true" tabindex="-1"></a>    .with_columns(n_chars <span class="op">=</span> c.text.<span class="bu">str</span>.len_chars())</span>
<span id="cb41-115"><a href="#cb41-115" aria-hidden="true" tabindex="-1"></a>    .with_columns(rank <span class="op">=</span> c.n_chars.rank())</span>
<span id="cb41-116"><a href="#cb41-116" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.doc_id.is_in(missing.select(c.doc_id).to_series()))</span>
<span id="cb41-117"><a href="#cb41-117" aria-hidden="true" tabindex="-1"></a>    .select(c.doc_id, c.n_chars, c.rank)</span>
<span id="cb41-118"><a href="#cb41-118" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-119"><a href="#cb41-119" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-120"><a href="#cb41-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-121"><a href="#cb41-121" aria-hidden="true" tabindex="-1"></a>Only 73 of the 75 authors have a French Wikipedia page. Both authors missing</span>
<span id="cb41-122"><a href="#cb41-122" aria-hidden="true" tabindex="-1"></a>one, Rex Warner and Edward Upward, are Twentieth Century writers, but era</span>
<span id="cb41-123"><a href="#cb41-123" aria-hidden="true" tabindex="-1"></a>alone does not explain the gap: plenty of other Twentieth Century authors in</span>
<span id="cb41-124"><a href="#cb41-124" aria-hidden="true" tabindex="-1"></a>this corpus do have a French page. Page length does explain it. Rex Warner</span>
<span id="cb41-125"><a href="#cb41-125" aria-hidden="true" tabindex="-1"></a>has the single shortest English page in the entire 75-author corpus, and</span>
<span id="cb41-126"><a href="#cb41-126" aria-hidden="true" tabindex="-1"></a>Edward Upward has the third shortest. The two authors with no French</span>
<span id="cb41-127"><a href="#cb41-127" aria-hidden="true" tabindex="-1"></a>Wikipedia page at all are also, independently, two of the three</span>
<span id="cb41-128"><a href="#cb41-128" aria-hidden="true" tabindex="-1"></a>least-covered figures on the English side. Missing translation coverage</span>
<span id="cb41-129"><a href="#cb41-129" aria-hidden="true" tabindex="-1"></a>here tracks obscurity, not a random gap or a cutoff by time period.</span>
<span id="cb41-130"><a href="#cb41-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-131"><a href="#cb41-131" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>In the first block, restrict <span class="in">`text_en`</span> and <span class="in">`text_fr`</span> to the 73 shared</span>
<span id="cb41-132"><a href="#cb41-132" aria-hidden="true" tabindex="-1"></a>authors, sort both by <span class="in">`doc_id`</span>, and confirm the two tables now cover the</span>
<span id="cb41-133"><a href="#cb41-133" aria-hidden="true" tabindex="-1"></a>exact same set of authors. In the second block, run each language's text</span>
<span id="cb41-134"><a href="#cb41-134" aria-hidden="true" tabindex="-1"></a>through its own spaCy pipeline with <span class="in">`DSText.process`</span>, and print the</span>
<span id="cb41-135"><a href="#cb41-135" aria-hidden="true" tabindex="-1"></a>resulting shapes.</span>
<span id="cb41-136"><a href="#cb41-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-139"><a href="#cb41-139" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-140"><a href="#cb41-140" aria-hidden="true" tabindex="-1"></a>docs_en <span class="op">=</span> (</span>
<span id="cb41-141"><a href="#cb41-141" aria-hidden="true" tabindex="-1"></a>    text_en</span>
<span id="cb41-142"><a href="#cb41-142" aria-hidden="true" tabindex="-1"></a>    .join(text_fr.select(c.doc_id), on<span class="op">=</span><span class="st">"doc_id"</span>)</span>
<span id="cb41-143"><a href="#cb41-143" aria-hidden="true" tabindex="-1"></a>    .sort(c.doc_id)</span>
<span id="cb41-144"><a href="#cb41-144" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-145"><a href="#cb41-145" aria-hidden="true" tabindex="-1"></a>docs_fr <span class="op">=</span> text_fr.sort(c.doc_id)</span>
<span id="cb41-146"><a href="#cb41-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-147"><a href="#cb41-147" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(docs_en.select(c.doc_id).equals(docs_fr.select(c.doc_id)))</span>
<span id="cb41-148"><a href="#cb41-148" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-149"><a href="#cb41-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-152"><a href="#cb41-152" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-153"><a href="#cb41-153" aria-hidden="true" tabindex="-1"></a>anno_en <span class="op">=</span> DSText.process(docs_en, nlp_en)</span>
<span id="cb41-154"><a href="#cb41-154" aria-hidden="true" tabindex="-1"></a>anno_fr <span class="op">=</span> DSText.process(docs_fr, nlp_fr)</span>
<span id="cb41-155"><a href="#cb41-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-156"><a href="#cb41-156" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(anno_en.shape)</span>
<span id="cb41-157"><a href="#cb41-157" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(anno_fr.shape)</span>
<span id="cb41-158"><a href="#cb41-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-159"><a href="#cb41-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-160"><a href="#cb41-160" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>For each language, compute the average number of alphabetic tokens per</span>
<span id="cb41-161"><a href="#cb41-161" aria-hidden="true" tabindex="-1"></a>document and the average number of distinct lemmas per document. In the</span>
<span id="cb41-162"><a href="#cb41-162" aria-hidden="true" tabindex="-1"></a>first block, do this for English (<span class="in">`anno_en`</span>); in the second, for French</span>
<span id="cb41-163"><a href="#cb41-163" aria-hidden="true" tabindex="-1"></a>(<span class="in">`anno_fr`</span>).</span>
<span id="cb41-164"><a href="#cb41-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-167"><a href="#cb41-167" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-168"><a href="#cb41-168" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb41-169"><a href="#cb41-169" aria-hidden="true" tabindex="-1"></a>    anno_en</span>
<span id="cb41-170"><a href="#cb41-170" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.is_alpha)</span>
<span id="cb41-171"><a href="#cb41-171" aria-hidden="true" tabindex="-1"></a>    .group_by(c.doc_id)</span>
<span id="cb41-172"><a href="#cb41-172" aria-hidden="true" tabindex="-1"></a>    .agg(n_tokens <span class="op">=</span> pl.<span class="bu">len</span>(), n_lemmas <span class="op">=</span> c.lemma.n_unique())</span>
<span id="cb41-173"><a href="#cb41-173" aria-hidden="true" tabindex="-1"></a>    .select(c.n_tokens.mean(), c.n_lemmas.mean())</span>
<span id="cb41-174"><a href="#cb41-174" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-175"><a href="#cb41-175" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-176"><a href="#cb41-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-179"><a href="#cb41-179" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-180"><a href="#cb41-180" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb41-181"><a href="#cb41-181" aria-hidden="true" tabindex="-1"></a>    anno_fr</span>
<span id="cb41-182"><a href="#cb41-182" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.is_alpha)</span>
<span id="cb41-183"><a href="#cb41-183" aria-hidden="true" tabindex="-1"></a>    .group_by(c.doc_id)</span>
<span id="cb41-184"><a href="#cb41-184" aria-hidden="true" tabindex="-1"></a>    .agg(n_tokens <span class="op">=</span> pl.<span class="bu">len</span>(), n_lemmas <span class="op">=</span> c.lemma.n_unique())</span>
<span id="cb41-185"><a href="#cb41-185" aria-hidden="true" tabindex="-1"></a>    .select(c.n_tokens.mean(), c.n_lemmas.mean())</span>
<span id="cb41-186"><a href="#cb41-186" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-187"><a href="#cb41-187" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-188"><a href="#cb41-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-189"><a href="#cb41-189" aria-hidden="true" tabindex="-1"></a>An English page runs about 5,184 alphabetic tokens on average, drawn from</span>
<span id="cb41-190"><a href="#cb41-190" aria-hidden="true" tabindex="-1"></a>about 1,446 distinct lemmas; a French page for the very same author runs</span>
<span id="cb41-191"><a href="#cb41-191" aria-hidden="true" tabindex="-1"></a>about 2,579 tokens from about 822 distinct lemmas. Both halve at roughly the</span>
<span id="cb41-192"><a href="#cb41-192" aria-hidden="true" tabindex="-1"></a>same rate, which matches the character-length gap between the two text</span>
<span id="cb41-193"><a href="#cb41-193" aria-hidden="true" tabindex="-1"></a>columns: French Wikipedia's coverage of these authors is real, but</span>
<span id="cb41-194"><a href="#cb41-194" aria-hidden="true" tabindex="-1"></a>consistently shorter than English Wikipedia's.</span>
<span id="cb41-195"><a href="#cb41-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-196"><a href="#cb41-196" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Compute the TF-IDF table for each language with `DSText.compute_tfidf(...,</span>
<span id="cb41-197"><a href="#cb41-197" aria-hidden="true" tabindex="-1"></a>min_df=0.01, max_df=1.0)`, the exact call the chapter itself uses for</span>
<span id="cb41-198"><a href="#cb41-198" aria-hidden="true" tabindex="-1"></a><span class="in">`anno_fr`</span>. Print the top 10 terms for <span class="in">`"Jane Austen"`</span> in both languages. Do</span>
<span id="cb41-199"><a href="#cb41-199" aria-hidden="true" tabindex="-1"></a>these lists match the chapter's own description of what a top-TF-IDF list</span>
<span id="cb41-200"><a href="#cb41-200" aria-hidden="true" tabindex="-1"></a>should look like?</span>
<span id="cb41-201"><a href="#cb41-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-204"><a href="#cb41-204" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-205"><a href="#cb41-205" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> author <span class="kw">in</span> [<span class="st">"Jane Austen"</span>]:</span>
<span id="cb41-206"><a href="#cb41-206" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"EN"</span>, author, DSText.compute_tfidf(anno_en, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">1.0</span>).<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">10</span>).select(c.lemma).to_series().to_list())</span>
<span id="cb41-207"><a href="#cb41-207" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"FR"</span>, author, DSText.compute_tfidf(anno_fr, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">1.0</span>).<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">10</span>).select(c.lemma).to_series().to_list())</span>
<span id="cb41-208"><a href="#cb41-208" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-209"><a href="#cb41-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-210"><a href="#cb41-210" aria-hidden="true" tabindex="-1"></a>No. The chapter's own text claims that TF-IDF "downweights generic terms...</span>
<span id="cb41-211"><a href="#cb41-211" aria-hidden="true" tabindex="-1"></a>and what remains are the names, places, and titles that actually identify</span>
<span id="cb41-212"><a href="#cb41-212" aria-hidden="true" tabindex="-1"></a>each author," but with <span class="in">`max_df=1.0`</span> nothing actually gets downweighted</span>
<span id="cb41-213"><a href="#cb41-213" aria-hidden="true" tabindex="-1"></a>enough to matter: <span class="in">`the`</span>, <span class="in">`of`</span>, <span class="in">`and`</span>, <span class="in">`in`</span>, <span class="in">`to`</span>, and <span class="in">`her`</span> fill six of</span>
<span id="cb41-214"><a href="#cb41-214" aria-hidden="true" tabindex="-1"></a>Austen's ten English slots, and <span class="in">`de`</span>, <span class="in">`le`</span>, <span class="in">`à`</span>, <span class="in">`et`</span>, <span class="in">`un`</span>, <span class="in">`être`</span>, and <span class="in">`en`</span></span>
<span id="cb41-215"><a href="#cb41-215" aria-hidden="true" tabindex="-1"></a>fill seven of her ten French ones. This is not an artifact of the 73-author</span>
<span id="cb41-216"><a href="#cb41-216" aria-hidden="true" tabindex="-1"></a>subset — the book's own rendered table for the full 75-author English corpus</span>
<span id="cb41-217"><a href="#cb41-217" aria-hidden="true" tabindex="-1"></a>shows exactly the same pattern (`"Louis MacNeice" → "MacNeice; the; and; in;</span>
<span id="cb41-218"><a href="#cb41-218" aria-hidden="true" tabindex="-1"></a>be; of…"<span class="in">`, `</span>"George Bernard Shaw" → "the; Shaw; in; and; of; be; a;…"`), so</span>
<span id="cb41-219"><a href="#cb41-219" aria-hidden="true" tabindex="-1"></a>this is the chapter's own documented behavior, not something this notebook</span>
<span id="cb41-220"><a href="#cb41-220" aria-hidden="true" tabindex="-1"></a>introduced. Without a <span class="in">`max_df`</span> cutoff, a word appearing in every single</span>
<span id="cb41-221"><a href="#cb41-221" aria-hidden="true" tabindex="-1"></a>document (<span class="in">`the`</span> sits at <span class="in">`df_docs = 73`</span> here) still keeps an <span class="in">`idf`</span> of</span>
<span id="cb41-222"><a href="#cb41-222" aria-hidden="true" tabindex="-1"></a>exactly 1, and a common English or French function word's raw in-document</span>
<span id="cb41-223"><a href="#cb41-223" aria-hidden="true" tabindex="-1"></a>count is large enough that it still outranks a genuinely rare, document-</span>
<span id="cb41-224"><a href="#cb41-224" aria-hidden="true" tabindex="-1"></a>specific proper noun.</span>
<span id="cb41-225"><a href="#cb41-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-226"><a href="#cb41-226" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Recompute the TF-IDF tables with the stricter <span class="in">`max_df=0.5`</span> the chapter's</span>
<span id="cb41-227"><a href="#cb41-227" aria-hidden="true" tabindex="-1"></a>own UMAP and distance sections use elsewhere in this same chapter, for both</span>
<span id="cb41-228"><a href="#cb41-228" aria-hidden="true" tabindex="-1"></a>languages, and re-check <span class="in">`"Jane Austen"`</span>, <span class="in">`"A. A. Milne"`</span>, and `"T. S.</span>
<span id="cb41-229"><a href="#cb41-229" aria-hidden="true" tabindex="-1"></a>Eliot"`. Does this cutoff produce the clean lists the chapter's prose</span>
<span id="cb41-230"><a href="#cb41-230" aria-hidden="true" tabindex="-1"></a>described? Does anything still look out of place?</span>
<span id="cb41-231"><a href="#cb41-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-234"><a href="#cb41-234" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-235"><a href="#cb41-235" aria-hidden="true" tabindex="-1"></a>tfidf_en <span class="op">=</span> DSText.compute_tfidf(anno_en, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb41-236"><a href="#cb41-236" aria-hidden="true" tabindex="-1"></a>tfidf_fr <span class="op">=</span> DSText.compute_tfidf(anno_fr, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb41-237"><a href="#cb41-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-238"><a href="#cb41-238" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> author <span class="kw">in</span> [<span class="st">"Jane Austen"</span>, <span class="st">"A. A. Milne"</span>, <span class="st">"T. S. Eliot"</span>]:</span>
<span id="cb41-239"><a href="#cb41-239" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"EN"</span>, author, tfidf_en.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">10</span>).select(c.lemma).to_series().to_list())</span>
<span id="cb41-240"><a href="#cb41-240" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"FR"</span>, author, tfidf_fr.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">10</span>).select(c.lemma).to_series().to_list())</span>
<span id="cb41-241"><a href="#cb41-241" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-242"><a href="#cb41-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-243"><a href="#cb41-243" aria-hidden="true" tabindex="-1"></a>Mostly yes. Dropping every lemma that appears in more than half the corpus</span>
<span id="cb41-244"><a href="#cb41-244" aria-hidden="true" tabindex="-1"></a>clears out the function words from all three lists, and what is left for</span>
<span id="cb41-245"><a href="#cb41-245" aria-hidden="true" tabindex="-1"></a>Austen is her own name, her sister Cassandra, and her novels — the clean</span>
<span id="cb41-246"><a href="#cb41-246" aria-hidden="true" tabindex="-1"></a>result question 4 promised but did not deliver. Milne's and Eliot's English</span>
<span id="cb41-247"><a href="#cb41-247" aria-hidden="true" tabindex="-1"></a>lists are almost as clean, but both still contain <span class="in">`"parser"`</span>, a word with no</span>
<span id="cb41-248"><a href="#cb41-248" aria-hidden="true" tabindex="-1"></a>obvious connection to either a children's author or a modernist poet.</span>
<span id="cb41-249"><a href="#cb41-249" aria-hidden="true" tabindex="-1"></a>Neither French list has anything like it. The next question tracks that</span>
<span id="cb41-250"><a href="#cb41-250" aria-hidden="true" tabindex="-1"></a>down.</span>
<span id="cb41-251"><a href="#cb41-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-252"><a href="#cb41-252" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>In the first block, search both raw text columns for the substring</span>
<span id="cb41-253"><a href="#cb41-253" aria-hidden="true" tabindex="-1"></a><span class="in">`"mw-parser-output"`</span>, count how many characters match it per document,</span>
<span id="cb41-254"><a href="#cb41-254" aria-hidden="true" tabindex="-1"></a>compare the two languages, and list the documents with any matches sorted by</span>
<span id="cb41-255"><a href="#cb41-255" aria-hidden="true" tabindex="-1"></a>count. In the second block, filter <span class="in">`anno_en`</span> to the token <span class="in">`"parser"`</span> and</span>
<span id="cb41-256"><a href="#cb41-256" aria-hidden="true" tabindex="-1"></a>check its <span class="in">`upos`</span> tag and <span class="in">`is_alpha`</span> flag. In the third block, print the raw</span>
<span id="cb41-257"><a href="#cb41-257" aria-hidden="true" tabindex="-1"></a>text around the first occurrence of <span class="in">`"parser"`</span> on A. A. Milne's page.</span>
<span id="cb41-258"><a href="#cb41-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-261"><a href="#cb41-261" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-262"><a href="#cb41-262" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(text_en.with_columns(n <span class="op">=</span> c.text.<span class="bu">str</span>.count_matches(<span class="st">"mw-parser-output"</span>)).select(c.n.<span class="bu">sum</span>()).item(), <span class="st">"matches in English text"</span>)</span>
<span id="cb41-263"><a href="#cb41-263" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(text_fr.with_columns(n <span class="op">=</span> c.text.<span class="bu">str</span>.count_matches(<span class="st">"mw-parser-output"</span>)).select(c.n.<span class="bu">sum</span>()).item(), <span class="st">"matches in French text"</span>)</span>
<span id="cb41-264"><a href="#cb41-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-265"><a href="#cb41-265" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb41-266"><a href="#cb41-266" aria-hidden="true" tabindex="-1"></a>    text_en</span>
<span id="cb41-267"><a href="#cb41-267" aria-hidden="true" tabindex="-1"></a>    .with_columns(n <span class="op">=</span> c.text.<span class="bu">str</span>.count_matches(<span class="st">"mw-parser-output"</span>))</span>
<span id="cb41-268"><a href="#cb41-268" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.n <span class="op">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb41-269"><a href="#cb41-269" aria-hidden="true" tabindex="-1"></a>    .select(c.doc_id, c.n)</span>
<span id="cb41-270"><a href="#cb41-270" aria-hidden="true" tabindex="-1"></a>    .sort(c.n, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb41-271"><a href="#cb41-271" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-272"><a href="#cb41-272" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-273"><a href="#cb41-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-276"><a href="#cb41-276" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-277"><a href="#cb41-277" aria-hidden="true" tabindex="-1"></a>anno_en.<span class="bu">filter</span>(c.token <span class="op">==</span> <span class="st">"parser"</span>).select(c.doc_id, c.token, c.upos, c.is_alpha).unique()</span>
<span id="cb41-278"><a href="#cb41-278" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-279"><a href="#cb41-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-282"><a href="#cb41-282" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-283"><a href="#cb41-283" aria-hidden="true" tabindex="-1"></a>idx <span class="op">=</span> docs_en.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> <span class="st">"A. A. Milne"</span>).item(<span class="dv">0</span>, <span class="st">"text"</span>).find(<span class="st">"parser"</span>)</span>
<span id="cb41-284"><a href="#cb41-284" aria-hidden="true" tabindex="-1"></a>docs_en.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> <span class="st">"A. A. Milne"</span>).item(<span class="dv">0</span>, <span class="st">"text"</span>)[idx <span class="op">-</span> <span class="dv">120</span> : idx <span class="op">+</span> <span class="dv">120</span>]</span>
<span id="cb41-285"><a href="#cb41-285" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-286"><a href="#cb41-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-287"><a href="#cb41-287" aria-hidden="true" tabindex="-1"></a><span class="in">`"mw-parser-output"`</span> is leaked CSS from a Wikipedia coordinate template,</span>
<span id="cb41-288"><a href="#cb41-288" aria-hidden="true" tabindex="-1"></a>scraped straight into the article body along with the rest of the page text</span>
<span id="cb41-289"><a href="#cb41-289" aria-hidden="true" tabindex="-1"></a>— 33 occurrences across four English pages, concentrated in Milne's and</span>
<span id="cb41-290"><a href="#cb41-290" aria-hidden="true" tabindex="-1"></a>Eliot's, and zero anywhere in the French text. Printing the raw context</span>
<span id="cb41-291"><a href="#cb41-291" aria-hidden="true" tabindex="-1"></a>around it confirms the source: a run of repeated `.mw-parser-output</span>
<span id="cb41-292"><a href="#cb41-292" aria-hidden="true" tabindex="-1"></a>.geo-...` class names from a hidden geo-coordinate box, copy-pasted into the</span>
<span id="cb41-293"><a href="#cb41-293" aria-hidden="true" tabindex="-1"></a>extracted text eight times in a single sentence on Milne's page alone. spaCy</span>
<span id="cb41-294"><a href="#cb41-294" aria-hidden="true" tabindex="-1"></a>tags the token <span class="in">`parser`</span> itself as an ordinary alphabetic <span class="in">`NOUN`</span>, exactly the</span>
<span id="cb41-295"><a href="#cb41-295" aria-hidden="true" tabindex="-1"></a>way it would tag a real word, so nothing about <span class="in">`is_alpha`</span> catches it the way</span>
<span id="cb41-296"><a href="#cb41-296" aria-hidden="true" tabindex="-1"></a>notebook41's backslash artifact was caught. It sails straight through</span>
<span id="cb41-297"><a href="#cb41-297" aria-hidden="true" tabindex="-1"></a><span class="in">`compute_tfidf`</span> and inflates two authors' top-term lists with a scraping</span>
<span id="cb41-298"><a href="#cb41-298" aria-hidden="true" tabindex="-1"></a>artifact that has nothing to do with either of them.</span>
<span id="cb41-299"><a href="#cb41-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-300"><a href="#cb41-300" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>Reproduce the chapter's part-of-speech comparison — stack <span class="in">`anno_en`</span> and</span>
<span id="cb41-301"><a href="#cb41-301" aria-hidden="true" tabindex="-1"></a><span class="in">`anno_fr`</span> with a <span class="in">`lang`</span> column, group by <span class="in">`lang`</span> and <span class="in">`upos`</span>, and compute the</span>
<span id="cb41-302"><a href="#cb41-302" aria-hidden="true" tabindex="-1"></a>proportion of each part of speech within each language — but now on the</span>
<span id="cb41-303"><a href="#cb41-303" aria-hidden="true" tabindex="-1"></a>matched 73-author subset both tables share. Report the determiner (<span class="in">`DET`</span>)</span>
<span id="cb41-304"><a href="#cb41-304" aria-hidden="true" tabindex="-1"></a>proportion for each language.</span>
<span id="cb41-305"><a href="#cb41-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-308"><a href="#cb41-308" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-309"><a href="#cb41-309" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb41-310"><a href="#cb41-310" aria-hidden="true" tabindex="-1"></a>    pl.concat([</span>
<span id="cb41-311"><a href="#cb41-311" aria-hidden="true" tabindex="-1"></a>        anno_en.with_columns(lang <span class="op">=</span> pl.lit(<span class="st">"en"</span>)),</span>
<span id="cb41-312"><a href="#cb41-312" aria-hidden="true" tabindex="-1"></a>        anno_fr.with_columns(lang <span class="op">=</span> pl.lit(<span class="st">"fr"</span>))</span>
<span id="cb41-313"><a href="#cb41-313" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb41-314"><a href="#cb41-314" aria-hidden="true" tabindex="-1"></a>    .group_by([c.lang, c.upos])</span>
<span id="cb41-315"><a href="#cb41-315" aria-hidden="true" tabindex="-1"></a>    .agg(count <span class="op">=</span> pl.<span class="bu">len</span>())</span>
<span id="cb41-316"><a href="#cb41-316" aria-hidden="true" tabindex="-1"></a>    .with_columns(prop <span class="op">=</span> c.count <span class="op">/</span> c.count.<span class="bu">sum</span>().over(c.lang))</span>
<span id="cb41-317"><a href="#cb41-317" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.upos <span class="op">==</span> <span class="st">"DET"</span>)</span>
<span id="cb41-318"><a href="#cb41-318" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-319"><a href="#cb41-319" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-320"><a href="#cb41-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-321"><a href="#cb41-321" aria-hidden="true" tabindex="-1"></a>8.9% of English tokens are determiners against 12.2% of French ones, the</span>
<span id="cb41-322"><a href="#cb41-322" aria-hidden="true" tabindex="-1"></a>same gap the chapter describes, and this time it is not confounded by the</span>
<span id="cb41-323"><a href="#cb41-323" aria-hidden="true" tabindex="-1"></a>population mismatch built into the chapter's own version of this</span>
<span id="cb41-324"><a href="#cb41-324" aria-hidden="true" tabindex="-1"></a>comparison: the chapter stacks all 75 English pages against only 73 French</span>
<span id="cb41-325"><a href="#cb41-325" aria-hidden="true" tabindex="-1"></a>ones, quietly comparing two different populations, while <span class="in">`anno_en`</span> and</span>
<span id="cb41-326"><a href="#cb41-326" aria-hidden="true" tabindex="-1"></a><span class="in">`anno_fr`</span> here cover the identical 73 authors on both sides.</span>
<span id="cb41-327"><a href="#cb41-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-328"><a href="#cb41-328" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>Compute the pairwise angle distance for each language separately with</span>
<span id="cb41-329"><a href="#cb41-329" aria-hidden="true" tabindex="-1"></a><span class="in">`DSText.compute_distances(..., min_df=0.01, max_df=0.5)`</span>. For each language,</span>
<span id="cb41-330"><a href="#cb41-330" aria-hidden="true" tabindex="-1"></a>stack the result with a copy of itself with the ID columns swapped, and find</span>
<span id="cb41-331"><a href="#cb41-331" aria-hidden="true" tabindex="-1"></a>every author's single nearest neighbor.</span>
<span id="cb41-332"><a href="#cb41-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-335"><a href="#cb41-335" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-336"><a href="#cb41-336" aria-hidden="true" tabindex="-1"></a>dist_en <span class="op">=</span> DSText.compute_distances(anno_en, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb41-337"><a href="#cb41-337" aria-hidden="true" tabindex="-1"></a>dist_fr <span class="op">=</span> DSText.compute_distances(anno_fr, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb41-338"><a href="#cb41-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-339"><a href="#cb41-339" aria-hidden="true" tabindex="-1"></a>nn_en <span class="op">=</span> (</span>
<span id="cb41-340"><a href="#cb41-340" aria-hidden="true" tabindex="-1"></a>    pl.concat([</span>
<span id="cb41-341"><a href="#cb41-341" aria-hidden="true" tabindex="-1"></a>        dist_en,</span>
<span id="cb41-342"><a href="#cb41-342" aria-hidden="true" tabindex="-1"></a>        dist_en.select(doc_id<span class="op">=</span>c.doc_id2, doc_id2<span class="op">=</span>c.doc_id, distance<span class="op">=</span>c.distance)</span>
<span id="cb41-343"><a href="#cb41-343" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb41-344"><a href="#cb41-344" aria-hidden="true" tabindex="-1"></a>    .sort(c.doc_id, c.distance)</span>
<span id="cb41-345"><a href="#cb41-345" aria-hidden="true" tabindex="-1"></a>    .group_by(c.doc_id, maintain_order<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb41-346"><a href="#cb41-346" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">1</span>)</span>
<span id="cb41-347"><a href="#cb41-347" aria-hidden="true" tabindex="-1"></a>    .rename({<span class="st">"doc_id2"</span>: <span class="st">"nn_en"</span>})</span>
<span id="cb41-348"><a href="#cb41-348" aria-hidden="true" tabindex="-1"></a>    .drop(<span class="st">"distance"</span>)</span>
<span id="cb41-349"><a href="#cb41-349" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-350"><a href="#cb41-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-351"><a href="#cb41-351" aria-hidden="true" tabindex="-1"></a>nn_fr <span class="op">=</span> (</span>
<span id="cb41-352"><a href="#cb41-352" aria-hidden="true" tabindex="-1"></a>    pl.concat([</span>
<span id="cb41-353"><a href="#cb41-353" aria-hidden="true" tabindex="-1"></a>        dist_fr,</span>
<span id="cb41-354"><a href="#cb41-354" aria-hidden="true" tabindex="-1"></a>        dist_fr.select(doc_id<span class="op">=</span>c.doc_id2, doc_id2<span class="op">=</span>c.doc_id, distance<span class="op">=</span>c.distance)</span>
<span id="cb41-355"><a href="#cb41-355" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb41-356"><a href="#cb41-356" aria-hidden="true" tabindex="-1"></a>    .sort(c.doc_id, c.distance)</span>
<span id="cb41-357"><a href="#cb41-357" aria-hidden="true" tabindex="-1"></a>    .group_by(c.doc_id, maintain_order<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb41-358"><a href="#cb41-358" aria-hidden="true" tabindex="-1"></a>    .head(<span class="dv">1</span>)</span>
<span id="cb41-359"><a href="#cb41-359" aria-hidden="true" tabindex="-1"></a>    .rename({<span class="st">"doc_id2"</span>: <span class="st">"nn_fr"</span>})</span>
<span id="cb41-360"><a href="#cb41-360" aria-hidden="true" tabindex="-1"></a>    .drop(<span class="st">"distance"</span>)</span>
<span id="cb41-361"><a href="#cb41-361" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-362"><a href="#cb41-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-363"><a href="#cb41-363" aria-hidden="true" tabindex="-1"></a>nn_compare <span class="op">=</span> nn_en.join(nn_fr, on<span class="op">=</span><span class="st">"doc_id"</span>)</span>
<span id="cb41-364"><a href="#cb41-364" aria-hidden="true" tabindex="-1"></a>nn_compare</span>
<span id="cb41-365"><a href="#cb41-365" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-366"><a href="#cb41-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-367"><a href="#cb41-367" aria-hidden="true" tabindex="-1"></a><span class="ss">9. </span>What proportion of authors have the exact same nearest neighbor under</span>
<span id="cb41-368"><a href="#cb41-368" aria-hidden="true" tabindex="-1"></a>both languages? Compare this to the chance rate of matching by accident</span>
<span id="cb41-369"><a href="#cb41-369" aria-hidden="true" tabindex="-1"></a>among 72 other authors.</span>
<span id="cb41-370"><a href="#cb41-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-373"><a href="#cb41-373" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-374"><a href="#cb41-374" aria-hidden="true" tabindex="-1"></a>agree_rate <span class="op">=</span> nn_compare.select((c.nn_en <span class="op">==</span> c.nn_fr).mean()).item()</span>
<span id="cb41-375"><a href="#cb41-375" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(agree_rate, <span class="dv">3</span>), <span class="st">"agreement rate"</span>)</span>
<span id="cb41-376"><a href="#cb41-376" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(<span class="dv">1</span> <span class="op">/</span> <span class="dv">72</span>, <span class="dv">3</span>), <span class="st">"chance rate"</span>)</span>
<span id="cb41-377"><a href="#cb41-377" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-378"><a href="#cb41-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-379"><a href="#cb41-379" aria-hidden="true" tabindex="-1"></a>Almost 48% of authors (35 of 73) have the identical nearest neighbor whether</span>
<span id="cb41-380"><a href="#cb41-380" aria-hidden="true" tabindex="-1"></a>the distance is computed from their English page or their French one, over</span>
<span id="cb41-381"><a href="#cb41-381" aria-hidden="true" tabindex="-1"></a>thirty times the roughly 1.4% we would expect from two independent random</span>
<span id="cb41-382"><a href="#cb41-382" aria-hidden="true" tabindex="-1"></a>guesses among 72 other authors. The two languages are far from producing</span>
<span id="cb41-383"><a href="#cb41-383" aria-hidden="true" tabindex="-1"></a>identical geometry, but the structure that TF-IDF and the angle distance</span>
<span id="cb41-384"><a href="#cb41-384" aria-hidden="true" tabindex="-1"></a>recover is not arbitrary either: it survives translation for close to half</span>
<span id="cb41-385"><a href="#cb41-385" aria-hidden="true" tabindex="-1"></a>the corpus.</span>
<span id="cb41-386"><a href="#cb41-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-387"><a href="#cb41-387" aria-hidden="true" tabindex="-1"></a><span class="ss">10. </span>Look at one agreement and one disagreement from <span class="in">`nn_compare`</span> by eye. Ann</span>
<span id="cb41-388"><a href="#cb41-388" aria-hidden="true" tabindex="-1"></a>Radcliffe's nearest neighbor is Jane Austen in both languages; A. A. Milne's</span>
<span id="cb41-389"><a href="#cb41-389" aria-hidden="true" tabindex="-1"></a>is T. S. Eliot in English but George Orwell in French. In the first block,</span>
<span id="cb41-390"><a href="#cb41-390" aria-hidden="true" tabindex="-1"></a>print the agreement pair's top 5 TF-IDF terms in both languages for Ann</span>
<span id="cb41-391"><a href="#cb41-391" aria-hidden="true" tabindex="-1"></a>Radcliffe and Jane Austen. In the second block, print the disagreement</span>
<span id="cb41-392"><a href="#cb41-392" aria-hidden="true" tabindex="-1"></a>group's top 5 terms for A. A. Milne, T. S. Eliot, and George Orwell. In the</span>
<span id="cb41-393"><a href="#cb41-393" aria-hidden="true" tabindex="-1"></a>third block, check whether question 6's <span class="in">`parser`</span> artifact is actually what is</span>
<span id="cb41-394"><a href="#cb41-394" aria-hidden="true" tabindex="-1"></a>pulling Milne toward Eliot by recomputing the English distance between them</span>
<span id="cb41-395"><a href="#cb41-395" aria-hidden="true" tabindex="-1"></a>with <span class="in">`parser`</span> removed from <span class="in">`anno_en`</span>.</span>
<span id="cb41-396"><a href="#cb41-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-399"><a href="#cb41-399" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-400"><a href="#cb41-400" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> author <span class="kw">in</span> [<span class="st">"Ann Radcliffe"</span>, <span class="st">"Jane Austen"</span>]:</span>
<span id="cb41-401"><a href="#cb41-401" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"EN"</span>, author, tfidf_en.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">5</span>).select(c.lemma).to_series().to_list())</span>
<span id="cb41-402"><a href="#cb41-402" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"FR"</span>, author, tfidf_fr.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">5</span>).select(c.lemma).to_series().to_list())</span>
<span id="cb41-403"><a href="#cb41-403" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-404"><a href="#cb41-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-407"><a href="#cb41-407" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-408"><a href="#cb41-408" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> author <span class="kw">in</span> [<span class="st">"A. A. Milne"</span>, <span class="st">"T. S. Eliot"</span>, <span class="st">"George Orwell"</span>]:</span>
<span id="cb41-409"><a href="#cb41-409" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"EN"</span>, author, tfidf_en.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">5</span>).select(c.lemma).to_series().to_list())</span>
<span id="cb41-410"><a href="#cb41-410" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"FR"</span>, author, tfidf_fr.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> author).sort(c.tfidf, descending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">5</span>).select(c.lemma).to_series().to_list())</span>
<span id="cb41-411"><a href="#cb41-411" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-412"><a href="#cb41-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-415"><a href="#cb41-415" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-416"><a href="#cb41-416" aria-hidden="true" tabindex="-1"></a>milne_eliot <span class="op">=</span> dist_en.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> <span class="st">"A. A. Milne"</span>, c.doc_id2 <span class="op">==</span> <span class="st">"T. S. Eliot"</span>).item(<span class="dv">0</span>, <span class="st">"distance"</span>)</span>
<span id="cb41-417"><a href="#cb41-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-418"><a href="#cb41-418" aria-hidden="true" tabindex="-1"></a>dist_en_no_parser <span class="op">=</span> DSText.compute_distances(anno_en.<span class="bu">filter</span>(c.lemma <span class="op">!=</span> <span class="st">"parser"</span>), min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb41-419"><a href="#cb41-419" aria-hidden="true" tabindex="-1"></a>milne_eliot_no_parser <span class="op">=</span> dist_en_no_parser.<span class="bu">filter</span>(c.doc_id <span class="op">==</span> <span class="st">"A. A. Milne"</span>, c.doc_id2 <span class="op">==</span> <span class="st">"T. S. Eliot"</span>).item(<span class="dv">0</span>, <span class="st">"distance"</span>)</span>
<span id="cb41-420"><a href="#cb41-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-421"><a href="#cb41-421" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(milne_eliot, <span class="dv">3</span>), <span class="st">"with parser"</span>)</span>
<span id="cb41-422"><a href="#cb41-422" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(milne_eliot_no_parser, <span class="dv">3</span>), <span class="st">"without parser"</span>)</span>
<span id="cb41-423"><a href="#cb41-423" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-424"><a href="#cb41-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-425"><a href="#cb41-425" aria-hidden="true" tabindex="-1"></a>Radcliffe and Austen both write Gothic-adjacent fiction, and Radcliffe's own</span>
<span id="cb41-426"><a href="#cb41-426" aria-hidden="true" tabindex="-1"></a>top terms (<span class="in">`Udolpho`</span> in English, <span class="in">`gothique`</span> in French) confirm the genre</span>
<span id="cb41-427"><a href="#cb41-427" aria-hidden="true" tabindex="-1"></a>connection directly, so the agreement is easy to believe in both languages.</span>
<span id="cb41-428"><a href="#cb41-428" aria-hidden="true" tabindex="-1"></a>Milne's disagreement is harder to read off the term lists alone — neither</span>
<span id="cb41-429"><a href="#cb41-429" aria-hidden="true" tabindex="-1"></a>Eliot's nor Orwell's top terms share anything obvious with Milne's beyond</span>
<span id="cb41-430"><a href="#cb41-430" aria-hidden="true" tabindex="-1"></a>ordinary biographical scaffolding. The <span class="in">`parser`</span> artifact turns out not to be</span>
<span id="cb41-431"><a href="#cb41-431" aria-hidden="true" tabindex="-1"></a>the explanation either: dropping it from <span class="in">`anno_en`</span> entirely and</span>
<span id="cb41-432"><a href="#cb41-432" aria-hidden="true" tabindex="-1"></a>recomputing barely moves the Milne–Eliot distance (1.528 to 1.548) and does</span>
<span id="cb41-433"><a href="#cb41-433" aria-hidden="true" tabindex="-1"></a>not change who Milne's nearest neighbor is. Whatever pulls Milne toward</span>
<span id="cb41-434"><a href="#cb41-434" aria-hidden="true" tabindex="-1"></a>Eliot in English and toward Orwell in French</span>
<span id="cb41-435"><a href="#cb41-435" aria-hidden="true" tabindex="-1"></a>runs through the geometry of the full term-weighted vector, not through any</span>
<span id="cb41-436"><a href="#cb41-436" aria-hidden="true" tabindex="-1"></a>single term visible in a short printed list — a caution worth carrying</span>
<span id="cb41-437"><a href="#cb41-437" aria-hidden="true" tabindex="-1"></a>forward: a top-5 or top-10 list is a convenient summary for a human reader,</span>
<span id="cb41-438"><a href="#cb41-438" aria-hidden="true" tabindex="-1"></a>but it is not the same object the distance calculation actually compares.</span>
<span id="cb41-439"><a href="#cb41-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-440"><a href="#cb41-440" aria-hidden="true" tabindex="-1"></a><span class="ss">11. </span>Build a 2D UMAP projection for each language with `umap_text(...,</span>
<span id="cb41-441"><a href="#cb41-441" aria-hidden="true" tabindex="-1"></a>min_df=0.01, max_df=0.5, random_state=42)`, join each author's short name</span>
<span id="cb41-442"><a href="#cb41-442" aria-hidden="true" tabindex="-1"></a>and <span class="in">`era`</span> from <span class="in">`meta`</span>, and plot both, colored by <span class="in">`era`</span>. In the first block,</span>
<span id="cb41-443"><a href="#cb41-443" aria-hidden="true" tabindex="-1"></a>do this for English (<span class="in">`anno_en`</span>); in the second, for French (<span class="in">`anno_fr`</span>). A</span>
<span id="cb41-444"><a href="#cb41-444" aria-hidden="true" tabindex="-1"></a>plot is an impression, not a measurement, so in the third block also compute</span>
<span id="cb41-445"><a href="#cb41-445" aria-hidden="true" tabindex="-1"></a>each projection's own same-era nearest-neighbor rate directly from the</span>
<span id="cb41-446"><a href="#cb41-446" aria-hidden="true" tabindex="-1"></a><span class="in">`dr0`</span>/<span class="in">`dr1`</span> coordinates, the same check the last chapter's notebook ran on</span>
<span id="cb41-447"><a href="#cb41-447" aria-hidden="true" tabindex="-1"></a><span class="in">`label`</span>.</span>
<span id="cb41-448"><a href="#cb41-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-451"><a href="#cb41-451" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-452"><a href="#cb41-452" aria-hidden="true" tabindex="-1"></a>umap_en <span class="op">=</span> (</span>
<span id="cb41-453"><a href="#cb41-453" aria-hidden="true" tabindex="-1"></a>    anno_en</span>
<span id="cb41-454"><a href="#cb41-454" aria-hidden="true" tabindex="-1"></a>    .pipe(umap_text, doc_id<span class="op">=</span>c.doc_id, term_id<span class="op">=</span>c.lemma, n_components<span class="op">=</span><span class="dv">2</span>, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">0.5</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb41-455"><a href="#cb41-455" aria-hidden="true" tabindex="-1"></a>    .predict(full<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb41-456"><a href="#cb41-456" aria-hidden="true" tabindex="-1"></a>    .join(meta.select(c.doc_id, c.short, c.era), on<span class="op">=</span><span class="st">"doc_id"</span>)</span>
<span id="cb41-457"><a href="#cb41-457" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-458"><a href="#cb41-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-459"><a href="#cb41-459" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb41-460"><a href="#cb41-460" aria-hidden="true" tabindex="-1"></a>    umap_en</span>
<span id="cb41-461"><a href="#cb41-461" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(c.dr0, c.dr1))</span>
<span id="cb41-462"><a href="#cb41-462" aria-hidden="true" tabindex="-1"></a>    .geom_text(aes(label<span class="op">=</span>c.short, color<span class="op">=</span>c.era), size<span class="op">=</span><span class="dv">6</span>)</span>
<span id="cb41-463"><a href="#cb41-463" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-464"><a href="#cb41-464" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-465"><a href="#cb41-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-468"><a href="#cb41-468" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-469"><a href="#cb41-469" aria-hidden="true" tabindex="-1"></a>umap_fr <span class="op">=</span> (</span>
<span id="cb41-470"><a href="#cb41-470" aria-hidden="true" tabindex="-1"></a>    anno_fr</span>
<span id="cb41-471"><a href="#cb41-471" aria-hidden="true" tabindex="-1"></a>    .pipe(umap_text, doc_id<span class="op">=</span>c.doc_id, term_id<span class="op">=</span>c.lemma, n_components<span class="op">=</span><span class="dv">2</span>, min_df<span class="op">=</span><span class="fl">0.01</span>, max_df<span class="op">=</span><span class="fl">0.5</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb41-472"><a href="#cb41-472" aria-hidden="true" tabindex="-1"></a>    .predict(full<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb41-473"><a href="#cb41-473" aria-hidden="true" tabindex="-1"></a>    .join(meta.select(c.doc_id, c.short, c.era), on<span class="op">=</span><span class="st">"doc_id"</span>)</span>
<span id="cb41-474"><a href="#cb41-474" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-475"><a href="#cb41-475" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-476"><a href="#cb41-476" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb41-477"><a href="#cb41-477" aria-hidden="true" tabindex="-1"></a>    umap_fr</span>
<span id="cb41-478"><a href="#cb41-478" aria-hidden="true" tabindex="-1"></a>    .pipe(ggplot, aes(c.dr0, c.dr1))</span>
<span id="cb41-479"><a href="#cb41-479" aria-hidden="true" tabindex="-1"></a>    .geom_text(aes(label<span class="op">=</span>c.short, color<span class="op">=</span>c.era), size<span class="op">=</span><span class="dv">6</span>)</span>
<span id="cb41-480"><a href="#cb41-480" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-481"><a href="#cb41-481" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-482"><a href="#cb41-482" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-485"><a href="#cb41-485" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-486"><a href="#cb41-486" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> era_nn_rate(umap_df):</span>
<span id="cb41-487"><a href="#cb41-487" aria-hidden="true" tabindex="-1"></a>    coords <span class="op">=</span> umap_df.select(c.dr0, c.dr1).to_numpy()</span>
<span id="cb41-488"><a href="#cb41-488" aria-hidden="true" tabindex="-1"></a>    dist_sq <span class="op">=</span> ((coords[:, <span class="va">None</span>, :] <span class="op">-</span> coords[<span class="va">None</span>, :, :]) <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb41-489"><a href="#cb41-489" aria-hidden="true" tabindex="-1"></a>    np.fill_diagonal(dist_sq, np.inf)</span>
<span id="cb41-490"><a href="#cb41-490" aria-hidden="true" tabindex="-1"></a>    nn_idx <span class="op">=</span> dist_sq.argmin(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb41-491"><a href="#cb41-491" aria-hidden="true" tabindex="-1"></a>    eras <span class="op">=</span> umap_df.select(c.era).to_series().to_numpy()</span>
<span id="cb41-492"><a href="#cb41-492" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (eras <span class="op">==</span> eras[nn_idx]).mean()</span>
<span id="cb41-493"><a href="#cb41-493" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-494"><a href="#cb41-494" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(era_nn_rate(umap_en), <span class="dv">3</span>), <span class="st">"EN same-era nearest-neighbor rate"</span>)</span>
<span id="cb41-495"><a href="#cb41-495" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(era_nn_rate(umap_fr), <span class="dv">3</span>), <span class="st">"FR same-era nearest-neighbor rate"</span>)</span>
<span id="cb41-496"><a href="#cb41-496" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-497"><a href="#cb41-497" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-498"><a href="#cb41-498" aria-hidden="true" tabindex="-1"></a><span class="ss">12. </span>With seven <span class="in">`era`</span> categories of uneven size, matching by chance alone</span>
<span id="cb41-499"><a href="#cb41-499" aria-hidden="true" tabindex="-1"></a>runs around 17%. Both projections clear that bar but not by much — 20.5% for</span>
<span id="cb41-500"><a href="#cb41-500" aria-hidden="true" tabindex="-1"></a>English and 26.0% for French — confirming what the plots suggest by eye: a</span>
<span id="cb41-501"><a href="#cb41-501" aria-hidden="true" tabindex="-1"></a>weak, genuine pull toward grouping by era, not the tight separation</span>
<span id="cb41-502"><a href="#cb41-502" aria-hidden="true" tabindex="-1"></a>notebook42's own same-label check found for AG News's four disjoint topic</span>
<span id="cb41-503"><a href="#cb41-503" aria-hidden="true" tabindex="-1"></a>categories, and not nothing either. Looking back across this notebook: what</span>
<span id="cb41-504"><a href="#cb41-504" aria-hidden="true" tabindex="-1"></a>carried over unchanged between English and French, and what genuinely</span>
<span id="cb41-505"><a href="#cb41-505" aria-hidden="true" tabindex="-1"></a>differed?</span>
<span id="cb41-506"><a href="#cb41-506" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-507"><a href="#cb41-507" aria-hidden="true" tabindex="-1"></a>The machinery carried over without a single change: the same</span>
<span id="cb41-508"><a href="#cb41-508" aria-hidden="true" tabindex="-1"></a><span class="in">`DSText.process`</span>, <span class="in">`compute_tfidf`</span>, <span class="in">`compute_distances`</span>, and <span class="in">`umap_text`</span></span>
<span id="cb41-509"><a href="#cb41-509" aria-hidden="true" tabindex="-1"></a>calls ran on French tokens exactly as they did on English ones, because none</span>
<span id="cb41-510"><a href="#cb41-510" aria-hidden="true" tabindex="-1"></a>of that code has any language-specific logic built in. What differed was</span>
<span id="cb41-511"><a href="#cb41-511" aria-hidden="true" tabindex="-1"></a>the input each pipeline was handed and what came out the other end. Two</span>
<span id="cb41-512"><a href="#cb41-512" aria-hidden="true" tabindex="-1"></a>authors have no French page at all, and coverage tracks obscurity rather</span>
<span id="cb41-513"><a href="#cb41-513" aria-hidden="true" tabindex="-1"></a>than era. French pages run about half the length and half the vocabulary of</span>
<span id="cb41-514"><a href="#cb41-514" aria-hidden="true" tabindex="-1"></a>their English counterparts on the very same subject. French uses</span>
<span id="cb41-515"><a href="#cb41-515" aria-hidden="true" tabindex="-1"></a>determiners more often, a grammatical fact with nothing to do with editorial</span>
<span id="cb41-516"><a href="#cb41-516" aria-hidden="true" tabindex="-1"></a>choice. And the two languages' own document geometries agree on a given</span>
<span id="cb41-517"><a href="#cb41-517" aria-hidden="true" tabindex="-1"></a>author's closest match less than half the time, even though that rate is</span>
<span id="cb41-518"><a href="#cb41-518" aria-hidden="true" tabindex="-1"></a>far above chance. None of this is a flaw in the pipeline; it is exactly the</span>
<span id="cb41-519"><a href="#cb41-519" aria-hidden="true" tabindex="-1"></a>kind of genuine cross-lingual difference the chapter's own closing paragraph</span>
<span id="cb41-520"><a href="#cb41-520" aria-hidden="true" tabindex="-1"></a>says this machinery makes possible to study systematically rather than</span>
<span id="cb41-521"><a href="#cb41-521" aria-hidden="true" tabindex="-1"></a>assert from a hunch.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>