project:
  type: website
  output-dir: ../docs/nb289
  render:
    - "notebook01.qmd"
    - "notebook02.qmd"
    - "notebook03.qmd"
    - "notebook04.qmd"
    - "notebook05.qmd"
    - "notebook06.qmd"
    - "notebook07.qmd"
    - "notebook08.qmd"
    - "notebook09.qmd"
    - "notebook10.qmd"
    - "notebook11.qmd"
    - "notebook12.qmd"
    - "notebook13.qmd"
    - "notebook14.qmd"
    - "notebook15.qmd"
    - "notebook17.qmd"
    - "notebook18.qmd"
    - "notebook19.qmd"
    - "notebook20.qmd"
website:
  title: "Foundations of Data Science: Notebooks"
  sidebar:
    style: docked
    search: true
    contents:
      - file: notebook01.qmd
        text: "Notebook01"
      - file: notebook02.qmd
        text: "Notebook02"
      - file: notebook03.qmd
        text: "Notebook03"
      - file: notebook04.qmd
        text: "Notebook04"
      - file: notebook05.qmd
        text: "Notebook05"
      - file: notebook06.qmd
        text: "Notebook06"
      - file: notebook07.qmd
        text: "Notebook07"
      - file: notebook08.qmd
        text: "Notebook08"
      - file: notebook09.qmd
        text: "Notebook09"
      - file: notebook10.qmd
        text: "Notebook10"
      - file: notebook11.qmd
        text: "Notebook11"
      - file: notebook12.qmd
        text: "Notebook12"
      - file: notebook13.qmd
        text: "Notebook13"
      - file: notebook14.qmd
        text: "Notebook14"
      - file: notebook15.qmd
        text: "Notebook15"
      - file: notebook17.qmd
        text: "Notebook17"
      - file: notebook18.qmd
        text: "Notebook18"
      - file: notebook19.qmd
        text: "Notebook19"
      - file: notebook20.qmd
        text: "Notebook20"
format:
  html:
    code-fold: true
    code-summary: "View code"
    code-tools: true
    include-after-body: fix-code-toggle.html
    theme:
      - cosmo
      - custom.scss
    lightbox: true

execute:
  echo: true
  eval: true