project:
  type: website
  output-dir: ../docs/nb289
  render:
    - "notebook30.qmd"
website:
  title: "Foundations of Data Science: Notebooks"
  sidebar:
    style: docked
    search: true
    contents:
      - file: notebook30.qmd
        text: "Notebook30"
format:
  html:
    code-fold: true
    code-summary: "View code"
    code-tools: true
    include-after-body: fix-code-toggle.html
    theme:
      - cosmo
      - custom.scss
    lightbox: true

execute:
  echo: true
  eval: true