project:
  type: website
  output-dir: ../docs/nb289
  render:
    - "notebook30.qmd"
    - "notebook31.qmd"
    - "notebook32.qmd"
    - "notebook33.qmd"
    - "notebook34.qmd"
    - "notebook35.qmd"
    - "notebook36.qmd"
    - "notebook37.qmd"
    - "notebook38.qmd"
    - "notebook39.qmd"
    - "notebook40.qmd"
    - "notebook41.qmd"
    - "notebook42.qmd"
    - "notebook43.qmd"
    - "notebook45.qmd"
    - "notebook46.qmd"
    - "notebook47.qmd"
    - "notebook48.qmd"
website:
  title: "Foundations of Data Science: Notebooks"
  sidebar:
    style: docked
    search: true
    contents:
      - file: notebook30.qmd
        text: "Notebook30"
      - file: notebook31.qmd
        text: "Notebook31"
      - file: notebook32.qmd
        text: "Notebook32"
      - file: notebook33.qmd
        text: "Notebook33"
      - file: notebook34.qmd
        text: "Notebook34"
      - file: notebook35.qmd
        text: "Notebook35"
      - file: notebook36.qmd
        text: "Notebook36"
      - file: notebook37.qmd
        text: "Notebook37"
      - file: notebook38.qmd
        text: "Notebook38"
      - file: notebook39.qmd
        text: "Notebook39"
      - file: notebook40.qmd
        text: "Notebook40"
      - file: notebook41.qmd
        text: "Notebook41"
      - file: notebook42.qmd
        text: "Notebook42"
      - file: notebook43.qmd
        text: "Notebook43"
      - file: notebook45.qmd
        text: "Notebook45"
      - file: notebook46.qmd
        text: "Notebook46"
      - file: notebook47.qmd
        text: "Notebook47"
      - file: notebook48.qmd
        text: "Notebook48"
format:
  html:
    code-fold: true
    code-summary: "View code"
    code-tools: true
    include-after-body: fix-code-toggle.html
    theme:
      - cosmo
      - custom.scss
    lightbox: true

execute:
  echo: true
  eval: true