<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Taylor Arnold">

<title>8&nbsp; Combining Tables – Foundations of Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09_restructure.html" rel="next">
<link href="./07_graphics_ii.html" rel="prev">
<link href="./img/owl_explore.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ee6335475bc6b9f2146ef75da7f65f4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01_intro.html">Part I: Core</a></li><li class="breadcrumb-item"><a href="./08_combine.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Combining Tables</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Foundations of Data Science</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I: Core</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_organize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Organizing Data I</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_types.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Types</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_graphics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Visualizing Data I</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_group.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Grouping and Aggregation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_window.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Window Functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_graphics_ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Visualizing Data II</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_combine.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Combining Tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_restructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Restructuring Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_collect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Collecting Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Part II: Applications</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_spatial_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Spatial Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_apis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Data APIs and Corpora</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_temporal_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Temporal Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14_text_annotations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Textual Data: Annotations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15_text_vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Textual Data: Vectors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16_network_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Network Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17_image_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Image Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup"><span class="header-section-number">8.1</span> Setup</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">8.2</span> Introduction</a></li>
  <li><a href="#primary-and-foreign-keys" id="toc-primary-and-foreign-keys" class="nav-link" data-scroll-target="#primary-and-foreign-keys"><span class="header-section-number">8.3</span> Primary and Foreign Keys</a></li>
  <li><a href="#joining-by-relation" id="toc-joining-by-relation" class="nav-link" data-scroll-target="#joining-by-relation"><span class="header-section-number">8.4</span> Joining by Relation</a></li>
  <li><a href="#join-examples" id="toc-join-examples" class="nav-link" data-scroll-target="#join-examples"><span class="header-section-number">8.5</span> Join Examples</a></li>
  <li><a href="#filtering-joins-semi-and-anti" id="toc-filtering-joins-semi-and-anti" class="nav-link" data-scroll-target="#filtering-joins-semi-and-anti"><span class="header-section-number">8.6</span> Filtering Joins: Semi and Anti</a></li>
  <li><a href="#sec-diagnosing-joins" id="toc-sec-diagnosing-joins" class="nav-link" data-scroll-target="#sec-diagnosing-joins"><span class="header-section-number">8.7</span> Diagnosing Bad Joins</a></li>
  <li><a href="#conditional-joins" id="toc-conditional-joins" class="nav-link" data-scroll-target="#conditional-joins"><span class="header-section-number">8.8</span> Conditional Joins</a></li>
  <li><a href="#attaching-a-group-summary" id="toc-attaching-a-group-summary" class="nav-link" data-scroll-target="#attaching-a-group-summary"><span class="header-section-number">8.9</span> Attaching a Group Summary</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01_intro.html">Part I: Core</a></li><li class="breadcrumb-item"><a href="./08_combine.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Combining Tables</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-combine" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Combining Tables</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="setup" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="setup"><span class="header-section-number">8.1</span> Setup</h2>
<p>Load all of the modules and datasets needed for the chapter.</p>
<div id="22dbbcac" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotnine <span class="im">import</span> ggplot, aes</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> polars <span class="im">import</span> col <span class="im">as</span> c</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> funs</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>country <span class="op">=</span> pl.read_csv(<span class="st">"data/countries.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="introduction" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="introduction"><span class="header-section-number">8.2</span> Introduction</h2>
<p>In <a href="02_organize.html" class="quarto-xref"><span>Chapter 2</span></a>, we used data operations to modify a single dataset in Python: filtering rows, selecting columns, adding new columns, and sorting. <a href="05_group.html" class="quarto-xref"><span>Chapter 5</span></a> added grouping-and-summarizing to that list. All of that worked with one table at a time. Real projects rarely stop there. A dataset about customers usually needs to be linked to a dataset about products; a dataset about countries needs to be linked to a dataset about their borders. This chapter is about combining tables of data using joins, the primary tool for connecting information stored in separate places.</p>
</section>
<section id="primary-and-foreign-keys" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="primary-and-foreign-keys"><span class="header-section-number">8.3</span> Primary and Foreign Keys</h2>
<p>Primary keys are a core concept we need to understand to combine two datasets in Python. A <em>primary key</em> consists of one or more columns that can uniquely and minimally identify a row of data. For example, in our <code>country</code> dataset the column <code>iso</code> is a primary key. The column <code>full_name</code> is also a primary key. In database theory a distinction is made between <em>candidate keys</em> (any set of one or more columns that could serve as a primary key) and the specific primary key chosen for a table. This distinction is less applicable to data science work, where we will use the term primary key to refer to any possible way of identifying a row in our dataset.</p>
<p>A <em>foreign key</em> is a primary key from one table that appears in another table. For example, we might have a dataset of customers, with one column indicating the <code>iso</code> of the country in which they live. We join multiple tables by associating the primary key in one table with the matching foreign key in another. Notice that the difference between primary and foreign is the table in which the key appears, not the information itself. The value <code>iso</code> is both a primary key in the countries dataset and a foreign key in the customers dataset. The connection between these two tables is called a <em>relation</em>. This is where the term <em>relational database</em> comes from.</p>
</section>
<section id="joining-by-relation" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="joining-by-relation"><span class="header-section-number">8.4</span> Joining by Relation</h2>
<p>We will start with an abstract example before turning to a specific example using actual DataFrames in Python. Assume we have two tables, <code>table_one</code> and <code>table_two</code>. The column <code>key_col</code> appears in both tables: it is a primary key in <code>table_two</code> and a foreign key in <code>table_one</code>. This means it has a single unique row associated with it in <code>table_two</code> but possibly many instances in <code>table_one</code>.</p>
<p>To join the information in these two tables, we use the <code>.join()</code> method of the table containing the foreign key. The arguments include the second dataset and the name of the key used to combine the tables.</p>
<div id="48517e0d" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    table_one</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    .join(table_two, on<span class="op">=</span>c.key_col)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Assuming our data are correctly organized, the output will be a dataset with the same number of rows as <code>table_one</code>, where the first set of columns will also match <code>table_one</code>. After the original columns, there will be a version of all the columns from <code>table_two</code> that correspond to the matching values of our key.</p>
<p>Often some of the values in <code>table_one</code> will not have a matching value in <code>table_two</code>. In that case, the default behavior is to remove rows without matches; this is called an <em>inner join</em>. Alternatively, you can fill missing columns with <code>null</code> values, which results in a <em>left join</em>. We can indicate this to Python as follows:</p>
<div id="abcbe018" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    table_one</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    .join(table_two, on<span class="op">=</span>c.key_col, how<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Left and right tables
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The terminology of “left” and “right” tables comes from thinking about how the join would look when written on a single line. Consider the code <code>table_one.join(table_two)</code>; the first table is to the left of the join function and the second table is to the right of the join function. As a rule of thumb, we try to place the table with the foreign key on the left and the table with the primary key on the right. The reason for this is that the output should match the number of observations in the table with the foreign key, so it typically makes it easier to reason about treating it as a method of the foreign-key table. Note that usually the table with the foreign key will be much larger than the table with the primary key.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Equi-joins: inner, left, right, full, semi, anti, cross
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>There are six different options that we can assign to the <code>how</code> parameter in the table join method. The default, <code>inner</code>, returns only rows that match in both tables. <code>Left</code> joins return all rows from the left DataFrame; <code>right</code> joins return all rows from the right DataFrame. <code>Full</code> joins (rarely used) return all rows from both tables. A <code>semi</code> join returns only rows from the left table that have a match in the right table; no additional columns are added. An <code>anti</code> join returns only rows in the left table that do not match any rows in the right table. These six options are called equi-joins because they work by finding where the key(s) in one table are equal to the key(s) in another table. We’ll come back to semi- and anti-joins below, since they are useful enough to deserve their own worked example.</p>
<p>A cross join returns all combinations of rows from the two tables, with no key required. It has several interesting applications, which we will see in later chapters.</p>
</div>
</div>
</div>
<p>There are several other modifications that we can apply to the basic syntax. For example, if our key has multiple columns, we can pass a list to <code>on</code> instead of a single value. Here is the code to join on two matching columns from the two DataFrames.</p>
<div id="4716086e" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    table_one</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    .join(table_two, on<span class="op">=</span>[c.key_col1, c.key_col2])</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Or, if the key has different names in the two tables, we can describe them with <code>left_on</code> (the first table) and <code>right_on</code> (the second table). These can be individual values or lists, where each element in one list corresponds to the element in the other.</p>
<div id="8034f3d3" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    table_one</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    .join(table_two, left_on<span class="op">=</span>c.key_col1, right_on<span class="op">=</span>c.key_col1)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note that Python will let you join on any set of columns that match between the two tables, whether or not either column is actually a primary key. When the join column is not unique in the right-hand table, the result can be surprising, and possibly very large. We’ll see exactly what that looks like, and how to catch it before it happens, in <a href="#sec-diagnosing-joins" class="quarto-xref"><span>Section 8.7</span></a> below. Avoid joins that do not follow the pattern here (foreign key in the left table and a primary key in the right table).</p>
</section>
<section id="join-examples" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="join-examples"><span class="header-section-number">8.5</span> Join Examples</h2>
<p>The code outline in the previous section should make more sense once we see examples using actual datasets. To do this, we need multiple datasets that we can join together. We will create a smaller version of the <code>country</code> dataset that contains only two columns, which makes it easier to view the results without scrolling. We also load a dataset of country borders, where each row shows the relationship between a country and one of its neighbors.</p>
<div id="076eeae8" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>c_sml <span class="op">=</span> country.select(c.iso, c.gini)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>border <span class="op">=</span> pl.read_csv(<span class="st">"data/countries_borders.csv"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>border</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (829, 2)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">iso_neighbor</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"AFG"</td>
<td>"IRN"</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"PAK"</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"CHN"</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"TJK"</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"TKM"</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"ZMB"</td>
<td>"ZWE"</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"BWA"</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"MOZ"</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"ZAF"</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"ZMB"</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>We can use a relational join to add the Gini coefficient for the country referenced in the border data. Note that <code>iso</code> is present in both tables; it’s a primary key in <code>c_sml</code> and a foreign key in <code>border</code>. We can join them using the code below.</p>
<div id="06a31f78" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    border</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    .join(c_sml, on<span class="op">=</span>c.iso)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (641, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">iso_neighbor</th>
<th data-quarto-table-cell-role="th">gini</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"AFG"</td>
<td>"IRN"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"PAK"</td>
<td>27.8</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"CHN"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"TJK"</td>
<td>27.8</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"TKM"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"ZMB"</td>
<td>"ZWE"</td>
<td>57.1</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"BWA"</td>
<td>50.3</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"MOZ"</td>
<td>50.3</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"ZAF"</td>
<td>50.3</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"ZMB"</td>
<td>50.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Notice that the Gini coefficient of the base country has been added to the data. The first five rows all correspond to borders with Afghanistan and therefore the same value of the Gini coefficient (27.8) is duplicated for each of the rows. Similarly, the last four rows correspond to Zimbabwe and repeat the Gini coefficient value of 50.3 in each. As with other data methods we use, the <code>.join()</code> method returns a new dataset without modifying the original data. We would need to save the output if we wanted to work further with the results.</p>
<p>The DataFrame after the join has only 641 observations compared to the 829 observations in the original. The reason is that our <code>country</code> data only contains those countries for which we have full economic data. This means that some of the countries in <code>border</code> do not have an entry in <code>c_sml</code>. The default relational join is an inner join, so these missing corresponding rows are removed from the result. Changing to a left join restores the DataFrame to the same number of observations as the original <code>border</code> data.</p>
<div id="2c89b956" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    border</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    .join(c_sml, on<span class="op">=</span>c.iso, how<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (829, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">iso_neighbor</th>
<th data-quarto-table-cell-role="th">gini</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"AFG"</td>
<td>"IRN"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"PAK"</td>
<td>27.8</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"CHN"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"TJK"</td>
<td>27.8</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"TKM"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"ZMB"</td>
<td>"ZWE"</td>
<td>57.1</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"BWA"</td>
<td>50.3</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"MOZ"</td>
<td>50.3</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"ZAF"</td>
<td>50.3</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"ZMB"</td>
<td>50.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>So far, we have added the Gini coefficient of the base country. We could also add the coefficient of the bordering country by associating the column <code>iso_neighbor</code> with the column <code>iso</code> in our countries DataFrame. Here is the code to add the neighboring Gini coefficient.</p>
<div id="23c2fe1a" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    border</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    .join(c_sml, left_on<span class="op">=</span>c.iso_neighbor, right_on<span class="op">=</span>c.iso)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (667, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">iso_neighbor</th>
<th data-quarto-table-cell-role="th">gini</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"AFG"</td>
<td>"IRN"</td>
<td>40.9</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"PAK"</td>
<td>29.6</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"CHN"</td>
<td>38.2</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"TJK"</td>
<td>34.0</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"UZB"</td>
<td>35.3</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"ZMB"</td>
<td>"ZWE"</td>
<td>50.3</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"BWA"</td>
<td>53.3</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"MOZ"</td>
<td>54.0</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"ZAF"</td>
<td>63.1</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"ZMB"</td>
<td>57.1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>What if we wanted to add the Gini coefficient to both countries in each row? This requires doing two separate joins, one after the other. In the second join, we add the suffix <code>_neighbor</code> to the Gini coefficient to distinguish the two scores in the output.</p>
<div id="e45fcb37" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    border</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    .join(c_sml, on<span class="op">=</span>c.iso)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    .join(c_sml, left_on<span class="op">=</span>c.iso_neighbor, right_on<span class="op">=</span>c.iso, suffix<span class="op">=</span><span class="st">"_neighbor"</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (523, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">iso_neighbor</th>
<th data-quarto-table-cell-role="th">gini</th>
<th data-quarto-table-cell-role="th">gini_neighbor</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>f64</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"AFG"</td>
<td>"IRN"</td>
<td>27.8</td>
<td>40.9</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"PAK"</td>
<td>27.8</td>
<td>29.6</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"CHN"</td>
<td>27.8</td>
<td>38.2</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"TJK"</td>
<td>27.8</td>
<td>34.0</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"UZB"</td>
<td>27.8</td>
<td>35.3</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"ZMB"</td>
<td>"ZWE"</td>
<td>57.1</td>
<td>50.3</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"BWA"</td>
<td>50.3</td>
<td>53.3</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"MOZ"</td>
<td>50.3</td>
<td>54.0</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"ZAF"</td>
<td>50.3</td>
<td>63.1</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"ZMB"</td>
<td>50.3</td>
<td>57.1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>As noted above, we can add the option <code>how=</code> with the values <code>inner</code> (default), <code>left</code>, <code>right</code>, or <code>full</code> to indicate what should happen when keys appear only in one table. Left joins retain all keys from the first (left) table, right joins retain all keys from the second (right) table, and full joins retain all keys from both tables. When there is no matching value in the other table, <code>null</code> values are filled in. The default, <code>inner</code>, is often a good choice to avoid missing values.</p>
</section>
<section id="filtering-joins-semi-and-anti" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="filtering-joins-semi-and-anti"><span class="header-section-number">8.6</span> Filtering Joins: Semi and Anti</h2>
<p>Not every join is meant to add columns. Sometimes we just want to know which rows in one table have a match in another table, or which ones do not, without pulling in any of the second table’s columns. These are called filtering joins, because they act like the <code>.filter()</code> method: they select a subset of rows rather than adding new information. There are two variants. A <em>semi-join</em> keeps only the rows in the left table that have a match in the right table. An <em>anti-join</em> keeps only the rows in the left table that do <em>not</em> have a match. When there is a single key column, semi- and anti-joins can be replaced by a call to <code>.is_in()</code>; their real value shows up once there are multiple key columns and we want to know whether a specific combination matches, which <code>.is_in()</code> cannot express.</p>
<p>Filtering joins are also a quick way to check data quality. Above, we saw that joining <code>border</code> to <code>c_sml</code> on <code>iso</code> dropped the DataFrame from 829 rows down to 641, because <code>c_sml</code> only contains countries with full economic data. But is that the <em>whole</em> explanation? We can check by comparing <code>border</code> against the full <code>country</code> table (not the trimmed-down <code>c_sml</code>) using an anti-join, which will show us every row in <code>border</code> whose <code>iso</code> value has no match in <code>country</code> at all.</p>
<div id="bcef1165" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    border</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    .join(country, on<span class="op">=</span>c.iso, how<span class="op">=</span><span class="st">"anti"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (188, 2)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">iso_neighbor</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"AGO"</td>
<td>"COD"</td>
</tr>
<tr class="even">
<td>"AGO"</td>
<td>"GAB"</td>
</tr>
<tr class="odd">
<td>"AGO"</td>
<td>"NAM"</td>
</tr>
<tr class="even">
<td>"AGO"</td>
<td>"COG"</td>
</tr>
<tr class="odd">
<td>"AGO"</td>
<td>"ZMB"</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"VIR"</td>
<td>"VGB"</td>
</tr>
<tr class="even">
<td>"VIR"</td>
<td>"PRI"</td>
</tr>
<tr class="odd">
<td>"VUT"</td>
<td>"AUS"</td>
</tr>
<tr class="even">
<td>"VUT"</td>
<td>"SLB"</td>
</tr>
<tr class="odd">
<td>"WSM"</td>
<td>"USA"</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Any rows that show up here are not explained by missing economic data. They are <code>iso</code> codes in the border dataset that don’t correspond to any row in the country table at all. In a real project, this is exactly the kind of thing you’d want to chase down: is <code>border</code> including dependent territories or disputed regions that <code>country</code> deliberately excludes, or is there a typo in one of the codes? A semi-join answers the mirror-image question. <code>border.join(country, on=c.iso, how="semi")</code> would keep only the rows of <code>border</code> whose <code>iso</code> value <em>does</em> have a match, without adding any of <code>country</code>’s columns. That is useful when you want to filter one table down to “things that exist elsewhere” and nothing more.</p>
</section>
<section id="sec-diagnosing-joins" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="sec-diagnosing-joins"><span class="header-section-number">8.7</span> Diagnosing Bad Joins</h2>
<p>We said above that joining on a column that isn’t a primary key in the right table can produce surprising, and possibly very large, results. Let’s see exactly what that looks like, because this is the single join bug you are most likely to write yourself.</p>
<p>Suppose <code>c_sml</code> had gotten corrupted somewhere upstream, perhaps because two data sources were merged carelessly, and ended up with two rows for Afghanistan instead of one. We can simulate that here by adding a duplicate row.</p>
<div id="020e828e" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>bad_c_sml <span class="op">=</span> pl.concat([c_sml, c_sml.<span class="bu">filter</span>(c.iso <span class="op">==</span> <span class="st">"AFG"</span>)])</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>bad_c_sml.<span class="bu">filter</span>(c.iso <span class="op">==</span> <span class="st">"AFG"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (2, 2)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">gini</th>
</tr>
<tr class="even">
<td>str</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"AFG"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>27.8</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Now watch what happens when we join <code>border</code> to this corrupted table instead of the original.</p>
<div id="0554083d" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    border</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    .join(bad_c_sml, on<span class="op">=</span>c.iso)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (647, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">iso_neighbor</th>
<th data-quarto-table-cell-role="th">gini</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"AFG"</td>
<td>"IRN"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"IRN"</td>
<td>27.8</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"PAK"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"PAK"</td>
<td>27.8</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"CHN"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"ZMB"</td>
<td>"ZWE"</td>
<td>57.1</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"BWA"</td>
<td>50.3</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"MOZ"</td>
<td>50.3</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"ZAF"</td>
<td>50.3</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"ZMB"</td>
<td>50.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Recall that the first five rows of <code>border</code> all correspond to Afghanistan. Each one of those rows now matches <em>two</em> rows in <code>bad_c_sml</code> instead of one, so the join produces five extra rows, 646 instead of 641, all of them duplicate copies of Afghanistan’s borders. Nothing in the code raised an error. Polars did exactly what we asked: it matched every row in the left table against every matching row in the right table, however many there were. If this had been a real dataset and we hadn’t been watching the row count carefully, we might not have noticed the duplication at all, especially in a larger table where the extra rows blend in.</p>
<p>This is why it pays to check the key column <em>before</em> joining, rather than after. Back in <a href="05_group.html" class="quarto-xref"><span>Chapter 5</span></a> we used <code>n_unique()</code> alongside <code>len()</code> to check whether a column had repeated values; the same check tells us immediately whether a table is safe to use as the right-hand side of a join.</p>
<div id="603143d2" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>c_sml.select(c.iso).n_unique() <span class="op">==</span> <span class="bu">len</span>(c_sml)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>True</code></pre>
</div>
</div>
<div id="78bee37a" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>bad_c_sml.select(c.iso).n_unique() <span class="op">==</span> <span class="bu">len</span>(bad_c_sml)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>False</code></pre>
</div>
</div>
<p>The first check passes: <code>iso</code> is a genuine primary key in <code>c_sml</code>, one row per country. The second fails, which tells us, before we’ve joined anything, that <code>bad_c_sml</code> will multiply rows if we use it as the right table. Get in the habit of running this check on the right-hand table any time you’re not certain the join key is unique. It takes one line and it catches the bug at its source instead of downstream, where a silently inflated row count can quietly throw off every summary statistic you compute afterward.</p>
</section>
<section id="conditional-joins" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="conditional-joins"><span class="header-section-number">8.8</span> Conditional Joins</h2>
<p>In this section, we introduce two additional kinds of joins that are helpful when working with certain types of complex data. Both of these allow us to join by relationships between keys that do not require values to be exactly equal. To start, let’s create two subsets of our <code>countries</code> data, separating out countries in Africa and in Asia, and sorting by the Gini coefficient. We remove any missing values from the output.</p>
<div id="53a89c6a" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>africa <span class="op">=</span> (</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    country</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.region <span class="op">==</span> <span class="st">"Africa"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    .select(c.full_name, c.gini)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    .sort(c.gini)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    .drop_nulls()</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>asia <span class="op">=</span> (</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    country</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.region <span class="op">==</span> <span class="st">"Asia"</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    .select(c.full_name, c.gini)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    .sort(c.gini)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    .drop_nulls()</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The function <code>.join_asof</code> combines two datasets by matching each row in the first (left) dataset to the nearest value in the second (right) dataset based on numeric values in a specified pair of columns. It always returns a dataset with the same number of rows as the first (left) dataset. The function is optimized to do this quickly even for large datasets; to achieve this, it requires that both datasets be sorted by the join key before being called. Below is an example where we associate each African country with the nearest Asian country in terms of their Gini coefficient. We set <code>coalesce=False</code> to ensure the matching country’s Gini coefficient is retained in the output.</p>
<div id="25573b9d" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    africa</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    .join_asof(asia, on<span class="op">=</span>c.gini, strategy<span class="op">=</span><span class="st">"nearest"</span>, coalesce<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (35, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">full_name</th>
<th data-quarto-table-cell-role="th">gini</th>
<th data-quarto-table-cell-role="th">full_name_right</th>
<th data-quarto-table-cell-role="th">gini_right</th>
</tr>
<tr class="even">
<td>str</td>
<td>f64</td>
<td>str</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Guinea"</td>
<td>29.6</td>
<td>"Pakistan"</td>
<td>29.6</td>
</tr>
<tr class="even">
<td>"Egypt"</td>
<td>31.5</td>
<td>"Korea, Republic of"</td>
<td>31.4</td>
</tr>
<tr class="odd">
<td>"Mauritania"</td>
<td>32.6</td>
<td>"Mongolia"</td>
<td>32.7</td>
</tr>
<tr class="even">
<td>"Ethiopia"</td>
<td>35.0</td>
<td>"Thailand"</td>
<td>35.0</td>
</tr>
<tr class="odd">
<td>"Nigeria"</td>
<td>35.1</td>
<td>"Thailand"</td>
<td>35.0</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"Botswana"</td>
<td>53.3</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
<tr class="even">
<td>"Mozambique"</td>
<td>54.0</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
<tr class="odd">
<td>"Zambia"</td>
<td>57.1</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
<tr class="even">
<td>"Namibia"</td>
<td>59.1</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
<tr class="odd">
<td>"South Africa"</td>
<td>63.1</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The original motivation for the <code>.join_asof</code> method was to join two time-series datasets. The idea is that we might want the current (most recent) value from one table relative to another. Hence the function’s name and the fact that it uses the <code>backward</code> strategy by default to find the nearest value in the second dataset that is less than (i.e., earlier than) the value in the first. You can set the strategy to <code>forward</code> to look in the other direction, or to <code>nearest</code> to find the closest value. You can also add additional keys with the <code>by</code>, <code>by_left</code>, or <code>by_right</code> options; these keys must match exactly before performing the nearest search. The tables must be pre-sorted by the join key(s) for the function to work.</p>
<p>If we need to do more exotic joins between two tables, we can use the <code>.join_where</code> method. It takes one or more expressions in the same format used by the <code>.filter</code> method to specify exactly which pairs of rows to keep in the joined dataset. To refer to columns that share the same name in both datasets, use the <code>_right</code> suffix to indicate the second dataset. Below is an example that finds all pairs of countries in Africa and Asia where the difference in the Gini coefficient is less than 5.</p>
<div id="75115bba" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    africa</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    .join_where(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>        asia,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>        (c.gini <span class="op">-</span> c.gini_right).<span class="bu">abs</span>() <span class="op">&lt;</span> <span class="dv">5</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (414, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">full_name</th>
<th data-quarto-table-cell-role="th">gini</th>
<th data-quarto-table-cell-role="th">full_name_right</th>
<th data-quarto-table-cell-role="th">gini_right</th>
</tr>
<tr class="even">
<td>str</td>
<td>f64</td>
<td>str</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Guinea"</td>
<td>29.6</td>
<td>"Armenia"</td>
<td>25.2</td>
</tr>
<tr class="even">
<td>"Guinea"</td>
<td>29.6</td>
<td>"United Arab Emirates"</td>
<td>26.0</td>
</tr>
<tr class="odd">
<td>"Guinea"</td>
<td>29.6</td>
<td>"Azerbaijan"</td>
<td>26.6</td>
</tr>
<tr class="even">
<td>"Guinea"</td>
<td>29.6</td>
<td>"Afghanistan"</td>
<td>27.8</td>
</tr>
<tr class="odd">
<td>"Guinea"</td>
<td>29.6</td>
<td>"Kazakhstan"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"Cameroon"</td>
<td>46.6</td>
<td>"Philippines"</td>
<td>42.3</td>
</tr>
<tr class="even">
<td>"Cameroon"</td>
<td>46.6</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
<tr class="odd">
<td>"Burkina Faso"</td>
<td>47.3</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
<tr class="even">
<td>"Congo"</td>
<td>48.9</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
<tr class="odd">
<td>"Zimbabwe"</td>
<td>50.3</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>This method can be slow because it needs to manually check every combination of rows in the two datasets. However, it is very powerful and useful when combining two reasonably sized datasets in a complex way. Notice that we could obtain the same result by starting with a cross join (which returns every combination of rows) and then applying a filter. The benefit of the <code>.join_where</code> is that it avoids having to store in memory all combinations of non-matching rows by effectively combining the cross join and filtering into a single step.</p>
</section>
<section id="attaching-a-group-summary" class="level2" data-number="8.9">
<h2 data-number="8.9" class="anchored" data-anchor-id="attaching-a-group-summary"><span class="header-section-number">8.9</span> Attaching a Group Summary</h2>
<p>In <a href="05_group.html" class="quarto-xref"><span>Chapter 5</span></a> we saw how <code>.group_by()</code> and <code>.agg()</code> collapse a dataset down to one row per group, and how <code>.over()</code> computes a group-level statistic while keeping every original row. Joins give us a second way to reach the same result as <code>.agg()</code> followed by a join, so it’s worth comparing them directly.</p>
<p>Suppose we want to attach each country’s regional average Gini coefficient to every row of <code>country</code>, without collapsing the table. The <code>.over()</code> approach does this in a single step.</p>
<div id="2194c8fa" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    country</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    .with_columns(</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>        region_avg_gini <span class="op">=</span> c.gini.mean().over(c.region)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (135, 16)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">full_name</th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">subregion</th>
<th data-quarto-table-cell-role="th">pop</th>
<th data-quarto-table-cell-role="th">lexp</th>
<th data-quarto-table-cell-role="th">lat</th>
<th data-quarto-table-cell-role="th">lon</th>
<th data-quarto-table-cell-role="th">hdi</th>
<th data-quarto-table-cell-role="th">gdp</th>
<th data-quarto-table-cell-role="th">gini</th>
<th data-quarto-table-cell-role="th">happy</th>
<th data-quarto-table-cell-role="th">cellphone</th>
<th data-quarto-table-cell-role="th">water_access</th>
<th data-quarto-table-cell-role="th">lang</th>
<th data-quarto-table-cell-role="th">region_avg_gini</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>str</td>
<td>str</td>
<td>f64</td>
<td>f64</td>
<td>f64</td>
<td>f64</td>
<td>f64</td>
<td>i64</td>
<td>f64</td>
<td>f64</td>
<td>f64</td>
<td>f64</td>
<td>str</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"SEN"</td>
<td>"Senegal"</td>
<td>"Africa"</td>
<td>"Western Africa"</td>
<td>18.932</td>
<td>70.43</td>
<td>14.366667</td>
<td>-14.283333</td>
<td>0.53</td>
<td>4871</td>
<td>38.1</td>
<td>50.93</td>
<td>66.0</td>
<td>54.93987</td>
<td>"pbp|fra|wol"</td>
<td>41.922857</td>
</tr>
<tr class="even">
<td>"VEN"</td>
<td>"Venezuela, Bolivarian Republic…</td>
<td>"Americas"</td>
<td>"South America"</td>
<td>28.517</td>
<td>76.18</td>
<td>8.0</td>
<td>-67.0</td>
<td>0.709</td>
<td>8899</td>
<td>44.8</td>
<td>57.65</td>
<td>96.8</td>
<td>95.66913</td>
<td>"spa|vsl"</td>
<td>45.121053</td>
</tr>
<tr class="odd">
<td>"FIN"</td>
<td>"Finland"</td>
<td>"Europe"</td>
<td>"Northern Europe"</td>
<td>5.623</td>
<td>82.84</td>
<td>65.0</td>
<td>27.0</td>
<td>0.948</td>
<td>57574</td>
<td>27.7</td>
<td>76.99</td>
<td>156.4</td>
<td>99.44798</td>
<td>"fin|swe"</td>
<td>30.85</td>
</tr>
<tr class="even">
<td>"USA"</td>
<td>"United States of America"</td>
<td>"Americas"</td>
<td>"Northern America"</td>
<td>347.276</td>
<td>79.83</td>
<td>39.828175</td>
<td>-98.5795</td>
<td>0.938</td>
<td>78389</td>
<td>47.7</td>
<td>65.21</td>
<td>91.7</td>
<td>99.72235</td>
<td>"eng"</td>
<td>45.121053</td>
</tr>
<tr class="odd">
<td>"LKA"</td>
<td>"Sri Lanka"</td>
<td>"Asia"</td>
<td>"Southern Asia"</td>
<td>23.229</td>
<td>78.51</td>
<td>7.0</td>
<td>81.0</td>
<td>0.776</td>
<td>14380</td>
<td>39.3</td>
<td>36.02</td>
<td>83.1</td>
<td>90.77437</td>
<td>"sin|sin|tam|tam"</td>
<td>33.978788</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"ALB"</td>
<td>"Albania"</td>
<td>"Europe"</td>
<td>"Southern Europe"</td>
<td>2.772</td>
<td>79.67</td>
<td>41.0</td>
<td>20.0</td>
<td>0.81</td>
<td>20362</td>
<td>30.8</td>
<td>54.45</td>
<td>91.9</td>
<td>98.5473</td>
<td>"sqi"</td>
<td>30.85</td>
</tr>
<tr class="even">
<td>"MYS"</td>
<td>"Malaysia"</td>
<td>"Asia"</td>
<td>"South-eastern Asia"</td>
<td>35.978</td>
<td>76.03</td>
<td>3.7805111</td>
<td>102.314362</td>
<td>0.819</td>
<td>35990</td>
<td>46.2</td>
<td>58.68</td>
<td>118.2</td>
<td>95.69194</td>
<td>"msa"</td>
<td>33.978788</td>
</tr>
<tr class="odd">
<td>"SLV"</td>
<td>"El Salvador"</td>
<td>"Americas"</td>
<td>"Central America"</td>
<td>6.366</td>
<td>76.98</td>
<td>13.668889</td>
<td>-88.866111</td>
<td>0.678</td>
<td>12221</td>
<td>38.3</td>
<td>64.82</td>
<td>126.9</td>
<td>86.19786</td>
<td>"spa"</td>
<td>45.121053</td>
</tr>
<tr class="even">
<td>"CYP"</td>
<td>"Cyprus"</td>
<td>"Asia"</td>
<td>"Western Asia"</td>
<td>1.371</td>
<td>81.77</td>
<td>35.0</td>
<td>33.0</td>
<td>0.913</td>
<td>55720</td>
<td>31.2</td>
<td>60.71</td>
<td>123.1</td>
<td>99.41781</td>
<td>"ell|tur"</td>
<td>33.978788</td>
</tr>
<tr class="odd">
<td>"PAK"</td>
<td>"Pakistan"</td>
<td>"Asia"</td>
<td>"Southern Asia"</td>
<td>255.22</td>
<td>66.71</td>
<td>30.0</td>
<td>71.0</td>
<td>0.544</td>
<td>5717</td>
<td>29.6</td>
<td>45.49</td>
<td>49.8</td>
<td>61.92651</td>
<td>"eng|urd"</td>
<td>33.978788</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The agg-then-join approach reaches the same place in two steps: first collapse to one row per region, then join that summary back onto the original table using the shared <code>region</code> column as the key.</p>
<div id="9e443203" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>region_avg <span class="op">=</span> (</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    country</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    .group_by(c.region)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    .agg(region_avg_gini <span class="op">=</span> c.gini.mean())</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    country</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    .join(region_avg, on<span class="op">=</span>c.region)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (135, 16)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">full_name</th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">subregion</th>
<th data-quarto-table-cell-role="th">pop</th>
<th data-quarto-table-cell-role="th">lexp</th>
<th data-quarto-table-cell-role="th">lat</th>
<th data-quarto-table-cell-role="th">lon</th>
<th data-quarto-table-cell-role="th">hdi</th>
<th data-quarto-table-cell-role="th">gdp</th>
<th data-quarto-table-cell-role="th">gini</th>
<th data-quarto-table-cell-role="th">happy</th>
<th data-quarto-table-cell-role="th">cellphone</th>
<th data-quarto-table-cell-role="th">water_access</th>
<th data-quarto-table-cell-role="th">lang</th>
<th data-quarto-table-cell-role="th">region_avg_gini</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>str</td>
<td>str</td>
<td>f64</td>
<td>f64</td>
<td>f64</td>
<td>f64</td>
<td>f64</td>
<td>i64</td>
<td>f64</td>
<td>f64</td>
<td>f64</td>
<td>f64</td>
<td>str</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"SEN"</td>
<td>"Senegal"</td>
<td>"Africa"</td>
<td>"Western Africa"</td>
<td>18.932</td>
<td>70.43</td>
<td>14.366667</td>
<td>-14.283333</td>
<td>0.53</td>
<td>4871</td>
<td>38.1</td>
<td>50.93</td>
<td>66.0</td>
<td>54.93987</td>
<td>"pbp|fra|wol"</td>
<td>41.922857</td>
</tr>
<tr class="even">
<td>"VEN"</td>
<td>"Venezuela, Bolivarian Republic…</td>
<td>"Americas"</td>
<td>"South America"</td>
<td>28.517</td>
<td>76.18</td>
<td>8.0</td>
<td>-67.0</td>
<td>0.709</td>
<td>8899</td>
<td>44.8</td>
<td>57.65</td>
<td>96.8</td>
<td>95.66913</td>
<td>"spa|vsl"</td>
<td>45.121053</td>
</tr>
<tr class="odd">
<td>"FIN"</td>
<td>"Finland"</td>
<td>"Europe"</td>
<td>"Northern Europe"</td>
<td>5.623</td>
<td>82.84</td>
<td>65.0</td>
<td>27.0</td>
<td>0.948</td>
<td>57574</td>
<td>27.7</td>
<td>76.99</td>
<td>156.4</td>
<td>99.44798</td>
<td>"fin|swe"</td>
<td>30.85</td>
</tr>
<tr class="even">
<td>"USA"</td>
<td>"United States of America"</td>
<td>"Americas"</td>
<td>"Northern America"</td>
<td>347.276</td>
<td>79.83</td>
<td>39.828175</td>
<td>-98.5795</td>
<td>0.938</td>
<td>78389</td>
<td>47.7</td>
<td>65.21</td>
<td>91.7</td>
<td>99.72235</td>
<td>"eng"</td>
<td>45.121053</td>
</tr>
<tr class="odd">
<td>"LKA"</td>
<td>"Sri Lanka"</td>
<td>"Asia"</td>
<td>"Southern Asia"</td>
<td>23.229</td>
<td>78.51</td>
<td>7.0</td>
<td>81.0</td>
<td>0.776</td>
<td>14380</td>
<td>39.3</td>
<td>36.02</td>
<td>83.1</td>
<td>90.77437</td>
<td>"sin|sin|tam|tam"</td>
<td>33.978788</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"ALB"</td>
<td>"Albania"</td>
<td>"Europe"</td>
<td>"Southern Europe"</td>
<td>2.772</td>
<td>79.67</td>
<td>41.0</td>
<td>20.0</td>
<td>0.81</td>
<td>20362</td>
<td>30.8</td>
<td>54.45</td>
<td>91.9</td>
<td>98.5473</td>
<td>"sqi"</td>
<td>30.85</td>
</tr>
<tr class="even">
<td>"MYS"</td>
<td>"Malaysia"</td>
<td>"Asia"</td>
<td>"South-eastern Asia"</td>
<td>35.978</td>
<td>76.03</td>
<td>3.7805111</td>
<td>102.314362</td>
<td>0.819</td>
<td>35990</td>
<td>46.2</td>
<td>58.68</td>
<td>118.2</td>
<td>95.69194</td>
<td>"msa"</td>
<td>33.978788</td>
</tr>
<tr class="odd">
<td>"SLV"</td>
<td>"El Salvador"</td>
<td>"Americas"</td>
<td>"Central America"</td>
<td>6.366</td>
<td>76.98</td>
<td>13.668889</td>
<td>-88.866111</td>
<td>0.678</td>
<td>12221</td>
<td>38.3</td>
<td>64.82</td>
<td>126.9</td>
<td>86.19786</td>
<td>"spa"</td>
<td>45.121053</td>
</tr>
<tr class="even">
<td>"CYP"</td>
<td>"Cyprus"</td>
<td>"Asia"</td>
<td>"Western Asia"</td>
<td>1.371</td>
<td>81.77</td>
<td>35.0</td>
<td>33.0</td>
<td>0.913</td>
<td>55720</td>
<td>31.2</td>
<td>60.71</td>
<td>123.1</td>
<td>99.41781</td>
<td>"ell|tur"</td>
<td>33.978788</td>
</tr>
<tr class="odd">
<td>"PAK"</td>
<td>"Pakistan"</td>
<td>"Asia"</td>
<td>"Southern Asia"</td>
<td>255.22</td>
<td>66.71</td>
<td>30.0</td>
<td>71.0</td>
<td>0.544</td>
<td>5717</td>
<td>29.6</td>
<td>45.49</td>
<td>49.8</td>
<td>61.92651</td>
<td>"eng|urd"</td>
<td>33.978788</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Both produce the same output column. <code>.over()</code> is more concise and is the natural choice when the summary is the only thing you need. The agg-then-join version is worth reaching for when you need the intermediate summary table for its own sake (to inspect it, plot it, or join it against something else), since <code>.group_by().agg()</code> gives you that table directly, while <code>.over()</code> never materializes it at all.</p>
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./07_graphics_ii.html" class="pagination-link" aria-label="Visualizing Data II">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Visualizing Data II</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09_restructure.html" class="pagination-link" aria-label="Restructuring Data">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Restructuring Data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Taylor Arnold</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>A <a href="https://distantviewing.org/">Distant Viewing Lab</a> project</p>
</div>
  </div>
</footer>




</body></html>